Repository vaadin/flow, pull requests merged in 2019-05, with the labels that each got.

#5598 Load a theme with npm if root not found.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeExecutorTest.java
Labels: npm

#5613 find tools in common unix paths when IDE launched from desktop icon
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
Labels: npm

#5621 Refactor drag and drop to a separate module
  .gitignore
  flow-dnd/pom.xml
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragEndEvent.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragStartEvent.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropEffect.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropEvent.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/EffectAllowed.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/DragSourceTest.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/DropTargetTest.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/MockUI.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-tests/pom.xml
  pom.xml
Labels: 2.0-RC

#5594 Allow customizing scroll position restoration
  flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtRouterLinkHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/scroll/CustomScrollCallbacksView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/CustomScrollCallbacksIT.java
Labels: 2.0-RC

#5626 Issues/5342 gather exporter dependencies and theme
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
Labels: 2.0-RC, embedding flow

#5656 Update webpack with latest maven configuration changes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/webpack.config.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: npm

#5661 simpler code by making node_modules a static
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeValidateMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
Labels: npm

#5664 Fix loading of classes when class-loader does not match the set of cl…
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ClassFinderTest.java
Labels: npm

#5665 Allow custom `frontend` and `target/frontend` locations.
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeValidateMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeValidateMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: npm

#5681 Improve version resolution
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeValidateMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: npm

#5704 `converHtml` was not fully removed, removing it from imports updater
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/NodeBuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendDependenciesTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Labels: npm

#5705 fix 3rd party imports. Fixes #5684
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestComponents.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
Labels: npm

#5695 propagate mode in validate mode to other modules
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CopyProductionFilesMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PackageForProductionMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-tests/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-frontend-production-custom-context/pom.xml
  flow-tests/test-mixed/frontend/my-component.js
  flow-tests/test-mixed/pom-bower-devmode.xml
  flow-tests/test-mixed/pom-bower-production.xml
  flow-tests/test-mixed/pom-npm-devmode.xml
  flow-tests/test-mixed/pom-npm-production.xml
  flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/IdTestView.java
  flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
  flow-tests/test-mixed/src/main/webapp/frontend/my-component.html
  flow-tests/test-mixed/src/test/java/com/vaadin/flow/mixedtest/ui/IdTestIT.java
  flow-tests/test-npm-web-components/src/main/java/com/vaadin/flow/webcomponent/PlainServlet.java
  flow-tests/test-npm-web-components/src/main/java/com/vaadin/flow/webcomponent/PushWebComponentServlet.java
  flow-tests/test-npm-web-components/src/main/java/com/vaadin/flow/webcomponent/WebComponentVaadinServlet.java
  flow-tests/test-npm-web-components/src/test/java/com/vaadin/flow/webcomponent/NpmUpdateServerSideWebComponentIT.java
  flow-tests/test-npm/pom.xml
  flow-tests/test-npm/src/main/java/com/vaadin/flow/npmtest/NpmEnabledVaadinServlet.java
  flow-tests/test-root-context/pom.xml
  flow-tests/test-web-components-production/pom.xml
Labels: npm

#5746 Remove obsolete checks after using the flow-build-info.json
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: npm
