Repository vaadin/flow, pull requests merged in 2019-08, with the labels that each got.

#6127 CCDM: Adding a JsInit Handler for JS bootstrapper
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/ServletHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: CCDM Review Needed, ccdm

#6140 CCDM: Adding a npm package for flow JS client API
  .gitignore
  flow-client/.eslintrc.js
  flow-client/README.md
  flow-client/intern.json
  flow-client/package.json
  flow-client/pom.xml
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/flow-bootstrap.js
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/tsconfig.json
  flow-client/tsconfig.json
  flow-client/tslint.json
  flow-client/webpack.tests.config.js
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
Labels: ccdm

#6194 CCDM: implement Flow.start() API
  .gitignore
  flow-client/intern.json
  flow-client/package.json
  flow-client/pom.xml
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/FlowBootstrap.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/FlowBootstrap.js
  flow-client/src/main/resources/META-INF/resources/frontend/FlowClient.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/flow-bootstrap.js
  flow-client/src/test/frontend/FlowTests.ts
Labels: ccdm

#6167 CCDM: index html request handler
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/ClientIndexHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/ClientIndexHandlerTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  flow-server/src/test/resources/META-INF/VAADIN/index.html
  flow-tests/pom.xml
  flow-tests/test-ccdm/.gitignore
  flow-tests/test-ccdm/frontend/another-bundle.js
  flow-tests/test-ccdm/frontend/index.html
  flow-tests/test-ccdm/frontend/index.js
  flow-tests/test-ccdm/package.json
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/EmptyUI.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/ClientIndexHandlerIT.java
  flow-tests/test-ccdm/webpack.config.js
Labels: CCDM Review Needed, ccdm

#6210 CCDM: connect client and server UIs from javascript
  flow-client/.eslintrc.js
  flow-client/package.json
  flow-client/src/main/java/com/vaadin/client/communication/XhrConnection.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/dom/BasicElementStateProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ShadowRootTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/TestNodeVisitor.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
Labels: ccdm

#6215 CCDM: Add ITs for Flow client API
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-ccdm/frontend/index.html
  flow-tests/test-ccdm/frontend/index.js
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/ClientIndexHandlerIT.java
  flow-tests/test-ccdm/tsconfig.json
Labels: ccdm

#6234 merge master to ccdm
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/migration/CopyResourcesStepTest.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/MyUIInitListener.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteComponent.java
  flow-tests/pom.xml
  flow-tests/test-mixed/pom-bower-devmode.xml
  flow-tests/test-mixed/pom-bower-production.xml
  flow-tests/test-npm-only-features/test-npm-general/frontend/init-listener-component.js
  flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerView.java
  flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/TestingServiceInitListener.java
  flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/TestingUiUnitListener.java
  flow-tests/test-npm-only-features/test-npm-general/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-npm-only-features/test-npm-general/src/test/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: ccdm

#6232 CCDM: Flow.navigate must be executed in the flow ctx
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
Labels: ccdm

#6246 CCDM: Consider folders in the classpath when copying resources
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TestUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/resources/dir-with-frontend-resources/META-INF/resources/frontend/resourceInFolder.js
Labels: CCDM Review Needed, ccdm

#6283 CCDM: reuse client wrapper element for the Flow UI
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
Labels: ccdm

#6292 Setup the template of the renderer earlier (#6144)
  flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentDataGenerator.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestLabel.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java
Labels: to be cherry picked

#6316 Update BeforeLeaveObserver.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveObserver.java
Labels: to be cherry picked
