Repository vaadin/flow, pull requests merged in 2019-11, with the labels that each got.

#6830 Enable fat-/uber-jar production mode #6685
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, cherry pick

#6814 CCDM: package connect-client in flow-client.jar
  flow-client/intern.json
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/utils.js
  flow-client/webpack.tests.config.js
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/resources/connect-client.default.ts.template
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-custom.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-default.ts
Labels: +0.0.1, ccdm

#6786 include flow-server-production-mode into flow-bom
  flow-bom/pom.xml
Labels: +0.0.1

#6820 Implement VaadinConfig
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinConfigurationException.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinContext.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletConfigTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletContextTest.java
Labels: +1.0.0

#6815 Clarify executeJs JavaDocs for return values
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
Labels: +0.0.1

#6811 Add two new setRoute() variants to RouterLink as per #6540.
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
Labels: +0.1.0, to be cherry picked

#6835 CCDM: protect against CSRF
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, ccdm

#6823 Replaced method reference with anonymous class in addDataProviderListener
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +1.0.0

#6836 All modules should stay sorted
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
Labels: +1.0.0, to be cherry picked

#6833 Handle client-initiated resync request
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.1.0

#6827 Remove removed binding from changedBinding field
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#6843 All modules should stay sorted (#6836)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
Labels: +0.0.1, 2.1, cherry pick

#6845 Replaced method reference with anonymous class in addDataProviderListener
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +0.0.1, cherry pick

#6844 Replaced method reference with anonymous class in addDataProviderListener
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +0.0.1, cherry pick

#6839 CCDM: check user roles when accessing to services
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
Labels: +0.0.1, ccdm

#6847 Handle client-initiated resync request (#6833)
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.1.0, cherry pick

#6837 CCDM: generate undefined instead of null
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/AbstractServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/nullable/NullableService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/nullable/NullableServiceTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/collectionservice/expected-CollectionService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/collectionservice/expected-model-collectionservice.CollectionService.Collection.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/datetime/expected-DateTimeService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-InheritedModelService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-core.Version.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-inheritedmodel.InheritedModelService.ChildModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-inheritedmodel.InheritedModelService.ParentModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.ArraySchema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Discriminator.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Schema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.XML.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-models.ExternalDocumentation.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-JsonTestService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-core.Version.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.Role.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.Status.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.User.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-openapi-custom-application-properties.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ComplexReturnTypeService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ComplexTypeParamsService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ModelService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Group.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-subpackage.ModelFromDifferentPackage.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-ModelPackageService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-SubModelPackageService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-model-modelpackage.ModelPackageService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-model-subpackage.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/notnull/expected-NotNullService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/notnull/expected-model-notnull.NotNullService.NonNullModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-NullableService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.NullableModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.ParameterType.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.ReturnType.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-SameClassNameService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-sameclassname.SameClassNameService.SameClassNameModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SameClassNameModel.SubProperty.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SameClassNameModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SubProperty.ts
  flow-tests/test-ccdm-connect/frontend/src/test-component.js
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/ConnectServices.java
  flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
Labels: +1.0.0, ccdm

#6858 Fix uber jar build file finding.
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, to be cherry picked

#6864 Add HasErrorParameter classes to the endpoints
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/ErrorComponent.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
Labels: +0.1.0

#6865 Clarify isCloseIdleSession method javadocs
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
Labels: +0.0.1, to be cherry picked

#6805 CCDM: Disallow implicit null types
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/SchemaResolverTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/AbstractServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/nullable/NullableService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/nullable/NullableServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionIT.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/collectionservice/expected-CollectionService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/collectionservice/expected-model-collectionservice.CollectionService.Collection.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/datetime/expected-DateTimeService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-InheritedModelService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-core.Version.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-inheritedmodel.InheritedModelService.ChildModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-inheritedmodel.InheritedModelService.ParentModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.ArraySchema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Discriminator.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Schema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.XML.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-models.ExternalDocumentation.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-JsonTestService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-core.Version.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.Role.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.Status.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.User.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-openapi-custom-application-properties.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ComplexReturnTypeService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ComplexTypeParamsService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ModelService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Group.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-subpackage.ModelFromDifferentPackage.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-ModelPackageService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-SubModelPackageService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-model-modelpackage.ModelPackageService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-model-subpackage.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/notnull/expected-NotNullService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/notnull/expected-model-notnull.NotNullService.NonNullModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-NullableService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.NullableModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.ParameterType.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.ReturnType.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-SameClassNameService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-sameclassname.SameClassNameService.SameClassNameModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SameClassNameModel.SubProperty.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SameClassNameModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SubProperty.ts
  flow-tests/test-ccdm-connect/frontend/src/test-component.js
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/ConnectServices.java
  flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
Labels: +1.0.0, ccdm

#6871 Add HasErrorParameter classes to the endpoints (#6864)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/ErrorComponent.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
Labels: +0.1.0, cherry pick

#6875 Clarify isCloseIdleSession method javadocs (#6865)
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
Labels: +0.0.1, cherry pick

#6876 Clarify isCloseIdleSession method javadocs (#6865)
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
Labels: +0.1.0, cherry pick

#6869 Fix uber jar build file finding. (#6858)
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, cherry pick

#6870 Fix uber jar build file finding. (#6858)
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, cherry pick

#6860 Prevent npm --version from querying the internets for updates
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, to be cherry picked

#6885 Don't use NoTheme for built-in classes.
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
Labels: +0.1.0, cherry pick

#6886 Prevent npm --version from querying the internets for updates (#6860)
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, cherry pick

#6887 Prevent npm --version from querying the internets for updates (#6860)
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, cherry pick

#6872 Add HasErrorParameter classes to the endpoints (#6864)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/ErrorComponent.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
Labels: +0.1.0, cherry pick

#6889 Avoid shadow root access in TemplateInitializer
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +0.1.0

#6862 CCDM: remove unsupported connect client API
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/utils.js
Labels: +0.0.1, ccdm

#6900 Fix cherry-picked API
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
Labels: +0.0.1

#6904 Remove plural from add(String) javadoc
  flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
Labels: +0.0.1

#6905 Add "not null" javadocs to a chain of text node methods
  flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
  flow-server/src/main/java/com/vaadin/flow/component/Text.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/TextNodeMap.java
Labels: +0.0.1

#6868 Make Page.open(..., ...) public
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
Labels: +0.1.0

#6895 CCDM: respect nullable return type
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/nullable/NullableService.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-NullableService.ts
Labels: +1.0.0, ccdm

#6903 Fix embedding: allow removing virtual children
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentWrapper.java
  flow-server/src/main/java/com/vaadin/flow/dom/Node.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenList.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentWrapperTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenListTest.java
Labels: +0.1.0

#6891 CCDM: check for null in returned Java Bean from Connect service methods
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Labels: +0.0.1, ccdm

#6921 CCDM: check for null in returned Map values from Connect service methods
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Labels: +0.0.1, ccdm

#6925 Fix IT in snapshot
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
Labels: +0.0.1

#6919 Optimize stats contents
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.1.0

#6915 CP: Fix embedding: removing virtual child (#6903)
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentWrapper.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenList.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentWrapperTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenListTest.java
Labels: +0.1.0, cherry pick

#6916 CP: Fix embedding: removing virtual child (#6903)
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentWrapper.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenList.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentWrapperTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/VirtualChildrenListTest.java
Labels: +0.1.0, cherry pick

#6927 CCDM: remove reading request.body key which errors in Safari
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +0.0.1, ccdm

#6913 CCDM: Add security tests for ITs
  flow-tests/test-ccdm-connect/.gitignore
  flow-tests/test-ccdm-connect/frontend/src/test-component.js
  flow-tests/test-ccdm-connect/pom.xml
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/ConnectServices.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/SecurityConfiguration.java
  flow-tests/test-ccdm-connect/src/main/resources/application.properties
  flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
Labels: +0.0.1, ccdm

#6928 Enable using external stats.json
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +1.0.0

#6943 Enable push unit tests for Java 10
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
Labels: +1.0.0

#6798 Send sessionExpired as early as possible.
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/MetadataWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/CommunicationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/MetadataWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushAtmosphereHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterTestServlet.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutIT.java
Labels: +1.0.0, BFP, bug

#6957 Disable dev mode for GWT unit tests to speed up them
  flow-client/pom.xml
Labels: +1.0.0

#6963 Upgrade webpack-babel-multi-target-plugin dependency
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#6956 Make DevModeHandler non serializable
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#6950 CCDM: set commons-lang3 version when running generators in maven goals
  flow-maven-plugin/pom.xml
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskConnectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGeneratorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/openapi/OpenApiSpecBasedTests.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/AbstractServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/json/JsonTestServiceGeneratedTest.java
Labels: +1.0.0

#6962 Filters out meta and style tags from head element
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Labels: +0.0.1

#6958 CCDM: add webpack progress to improve DX
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1, ccdm

#6909 Parse Polymer 2 template insertion style
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/JsoupUtils.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/no-html-template.json
Labels: +1.0.0

#6968 CCDM: fix(generator): remove extra TS imports for bean grandparents
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/complexhierarchymodel/GrandParentModel.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/complexhierarchymodel/Model.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/complexhierarchymodel/ParentModel.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/ComplexHierarchyService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/ComplexHierarchyServiceTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-ComplexHierarchyService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-model-complexhierarchymodel.GrandParentModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-model-complexhierarchymodel.Model.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-model-complexhierarchymodel.ParentModel.ts
Labels: +0.0.1, ccdm

#6952 Remove all extra info from json file and make it easy to write for tests
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/babel_stats.json
  flow-server/src/test/resources/META-INF/VAADIN/config/stats-beverage.json
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/src/test/resources/META-INF/VAADIN/config/template-in-template-stats.json
Labels: +0.0.1

#6964 CCDM: show webpack errors in `index.html`
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.1.0, ccdm

#6970 CCDM: add generated comment with file path
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/ModelTemplate.mustache
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/AbstractServiceGenerationTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-default-class-no-tag.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-first-class-multiple-tags.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-multiple-lines-description.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-no-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-second-class-multiple-tags.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/collectionservice/expected-CollectionService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/collectionservice/expected-model-collectionservice.CollectionService.Collection.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-ComplexHierarchyService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-model-complexhierarchymodel.GrandParentModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-model-complexhierarchymodel.Model.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/complexhierarchyservice/expected-model-complexhierarchymodel.ParentModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/datetime/expected-DateTimeService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/denyall/expected-DenyAllService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-InheritedModelService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-core.Version.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-inheritedmodel.InheritedModelService.ChildModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-inheritedmodel.InheritedModelService.ParentModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.ArraySchema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Discriminator.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Schema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.XML.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-models.ExternalDocumentation.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-GeneratorAnonymousAllowedTestClass.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-JsonTestService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-core.Version.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.Role.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.Status.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-model-json.JsonTestService.User.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-openapi-custom-application-properties.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/json/expected-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ComplexReturnTypeService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ComplexTypeParamsService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-ModelService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Group.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-subpackage.ModelFromDifferentPackage.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-ModelPackageService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-SubModelPackageService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-model-modelpackage.ModelPackageService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/modelpackage/expected-model-subpackage.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-NullableService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.NullableModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.ParameterType.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/nullable/expected-model-nullable.NullableService.ReturnType.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-SameClassNameService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-sameclassname.SameClassNameService.SameClassNameModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SameClassNameModel.SubProperty.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SameClassNameModel.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/sameclassname/expected-model-subpackage.SubProperty.ts
Labels: +0.1.0, ccdm

#6974 CCDM: add auto-generated comments index files
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.js
Labels: +0.0.1, ccdm

#6982 Don't use scroll position handler in embedded web components app
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java
Labels: +0.0.1, to be cherry picked

#6977 move `flow-frontend` from `node_modules` to `target` folder.
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
Labels: +1.0.0, ccdm

#6979 Deprecate isIPad due to changes in detection.
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.1.0

#6981 Add deprecation messages for isIPad
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.1.0, to be cherry picked

#6985 Change external stats default config
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.1.0

#6983 Add isIPad to extendedClientDetails
  flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js
  flow-server/src/test/java/com/vaadin/flow/component/page/ExtendedClientDetailsTest.java
Labels: +0.1.0

#6988 Add deprecation messages for isIPad (#6981)
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.1.0, cherry pick

#6987 Add deprecation messages for isIPad (#6981)
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.1.0, cherry pick

#6931 Block directory traversal urls in StaticFileServer
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Labels: +0.0.1

#6991 CCDM: do not remove `flow-frontend/package.json` on clean
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
Labels: +0.0.1, bug, ccdm

#6986 Pin @vaadin/vaadin-element-mixin to 2.1.5
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesTest.java
Labels: +0.1.0

#6992 Cherry-pick (#6931)
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Labels: +0.0.1

#6993 Cherry-pick (#6931)
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Labels: +0.0.1

#6997 CCDM: remove main key from `frontend/package.json` to avoid duplicates
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, BFP, ccdm

#6998 CCDM: fix bug with escaped content when using eagerServerLoad
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, ccdm

#6944 Handle the error if the icon is not loadable (#6344).
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
  flow-tests/test-misc/src/main/webapp/icons/icon.png
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/MiscelaneousIT.java
Labels: +1.0.0

#7006 Send sessionExpired as early as possible. (#6798)
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/MetadataWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/CommunicationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/MetadataWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushAtmosphereHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterTestServlet.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutIT.java
Labels: +0.1.0

#7004 Improve InitialPageSettings::addInlineWithContents Javadoc
  flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
Labels: +0.0.1

#7011 Prevent VaadinSession.setErrorHandler from accepting null
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
Labels: +0.0.1

#6995 Add test module readme
  flow-tests/README.md
  flow-tests/test-dev-mode/pom.xml
Labels: +0.0.1

#7015 make the comments in the auto-generated webpack.config.js ready to use
  flow-server/src/main/resources/webpack.config.js
Labels: +1.0.0

#7023 Improve InitialPageSettings::addInlineWithContents Javadoc (#7004)
  flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
Labels: +0.0.1

#7013 Do not add defer attribute to JS module element
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#7024 CCDM: prevent infinite-loop when controller mapping is registered
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
Labels: +0.0.1, bug, ccdm

#7010 CCDM: Remove misleading lines from webpack.config.js template
  flow-server/src/main/resources/webpack.config.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: +0.0.1, ccdm

#7025 update to latest testbench
  pom.xml
Labels: +0.0.1

#7007 Send sessionExpired as early as possible. (#6798)
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/MetadataWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/CommunicationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/MetadataWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushAtmosphereHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterTestServlet.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutIT.java
Labels: +0.1.0

#7022 Don't flush if flush underway.
  flow-client/src/main/java/com/vaadin/client/flow/reactive/Reactive.java
  flow-client/src/test/java/com/vaadin/client/flow/reactive/ReactiveTest.java
  flow-tests/test-root-context/frontend/template-scalability-panel.js
  flow-tests/test-root-context/frontend/template-scalability-view.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityView.java
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-panel.html
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-view.html
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
Labels: +0.0.1

#7014 Improve logging
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#7028 fix: use the latest Spring version
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-tests/test-ccdm-connect/pom.xml
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/SecurityConfiguration.java
Labels: +0.0.1, ccdm

#7036 Re-enable embedding ITs
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
Labels: +0.0.1

#7037 Don't flush if flush underway. (#7022)
  flow-client/src/main/java/com/vaadin/client/flow/reactive/Reactive.java
  flow-client/src/test/java/com/vaadin/client/flow/reactive/ReactiveTest.java
  flow-tests/test-root-context/frontend/template-scalability-panel.js
  flow-tests/test-root-context/frontend/template-scalability-view.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityView.java
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-panel.html
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-view.html
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
Labels: +0.0.1, cherry pick

#7038 Don't flush if flush underway. (#7022)
  flow-client/src/main/java/com/vaadin/client/flow/reactive/Reactive.java
  flow-client/src/test/java/com/vaadin/client/flow/reactive/ReactiveTest.java
  flow-tests/test-root-context/frontend/template-scalability-panel.js
  flow-tests/test-root-context/frontend/template-scalability-view.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityView.java
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-panel.html
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/template-scalability-view.html
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
Labels: +0.0.1, cherry pick

#7034 Error message if dev-server not responding
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/WebpackConnectionException.java
Labels: +0.1.0

#7045 Remove unnecessary part from LICENSE
  LICENSE
Labels: +1.0.0

#7053 Simplify JavaDoc for @Route.absolute
  flow-server/src/main/java/com/vaadin/flow/router/Route.java
Labels: +0.0.1, to be cherry picked

#7048 Use latest leaf bean instance from data provider
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +1.0.0, to be cherry picked

#7051 Add a command to locate pnpm executable
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.1.0

#7054 Fix bug in Element::removeFromTree not removing virtual child nodes from their parent
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +0.0.1, to be cherry picked

#7049 Ignore PWA registry in embedded bootstrapper and add tests
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/resources/META-INF/resources/VAADIN/static/client/compile.properties
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/ClientSelectExporter.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddedWebComponentIT.java
Labels: +0.0.1

#7062 Update reference to ticket with details
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
Labels: +0.0.1

#7050 CCDM: allow page configuration in client mode
  flow-server/src/main/java/com/vaadin/flow/component/page/VaadinAppShell.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractAnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java
  flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java
  flow-tests/test-ccdm/package.json
Labels: +0.1.0, ccdm

#7065 CCDM: adding a IT for AppShell -> @Meta
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +0.0.1, ccdm
