Repository vaadin/flow, pull requests merged in 2019-10, with the labels that each got.

#6569 Add empty since tags
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ThemeWrapper.java
Labels: +0.0.1

#6561 CCDM: add initial Flow UIDL to index.html
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapInitialPredicate.java
  flow-server/src/main/java/com/vaadin/flow/server/ClientIndexBootstrapPage.java
  flow-server/src/main/java/com/vaadin/flow/server/ClientIndexHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/ClientIndexHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
Labels: +1.0.0, ccdm

#6581 Make fallback chunk info available via VaadinContext
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FallbackChunk.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/ByteCodeScanningView.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/test/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/ByteCodeScanningIT.java
Labels: +0.1.0

#6588 CCDM: ensure flow.start works with testbench
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, ccdm

#6557 CCDM: set clientSideMode as the default mode
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-tests/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
Labels: +0.0.1, ccdm

#6589 Fix javadocs for fallback chunk and add extra CTOR
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FallbackChunk.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
Labels: +0.1.0

#6573 Performance regression test for large project
  flow-tests/test-npm-only-features/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/main/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformance.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#6595 CCDM: prevent navigation loop
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.0.1, ccdm

#6594 CCDM: rename flow.route to flow.serverSideRoutes
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-tests/test-ccdm/frontend/client-router.js
  flow-tests/test-ccdm/frontend/index.js
Labels: +0.0.1, ccdm

#6592 package.json updates force npm i
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.1.0

#6613 Correct Javadoc lines
  flow-data/src/main/java/com/vaadin/flow/data/converter/Converter.java
Labels: +0.0.1

#6615 CCDM: use current url for flow.start initialization
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, ccdm

#6602 Allow to add a dependency dynamically via JS expression
  flow-client/eclipse/GWT tests.launch
  flow-client/src/main/java/com/vaadin/client/DependencyLoader.java
  flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/shared/ui/Dependency.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/PageTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/ui/DependencyTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyIT.java
Labels: +1.0.0

#6611 CCDM: generate a TS definition file for generated-flow-imports.js
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Labels: +0.1.0, ccdm

#6618 Avoid state mutation in a public method, add a warning
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
Labels: +0.0.1

#6612 Additions to generic DnD support
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragEndEvent.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/DropTargetTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDCustomComponentView.java
Labels: +0.0.1

#6614 add StringToUuidConverter (#4400)
  flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
Labels: +1.0.0

#6639 Fix JsonValues for Embedding
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentBinding.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentBindingTest.java
Labels: +0.0.1, to be cherry picked

#6640 Fallback import is excluded by name
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#6647 Lumo theme as default for exporters
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Labels: +0.0.1

#6638 CCDM: consider servlet context when server navigation
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +1.0.0, ccdm

#6649 Fix wrong path to service file in javadocs
  flow-server/src/main/java/com/vaadin/flow/server/startup/NavigationTargetFilter.java
Labels: +0.0.1

#6591 fix(material): LoadingIndicator's primary color
  flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java
Labels: +0.0.1

#6636 Do not load jar build-info
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.0.1

#6648 For bootstrap only read until assetsByChunkName
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/resources/InvalidStats.json
  flow-server/src/test/resources/MissFormatStats.json
  flow-server/src/test/resources/ValidStats.json
Labels: +0.1.0

#6658 Improved exception readability in FullDependenciesScanner
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
Labels: +0.0.1

#6660 Use compatibility mode for Frontend servlet.
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Labels: +0.0.1

#6664 Avoid asking classloader on servlet context.
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.0.1

#6654 Reactivate drop target after detach/attach
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDAttachDetachView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDAttachDetachIT.java
Labels: +0.0.1

#6633 Generic DnD: load connector in bundle, add stats
  flow-dnd/pom.xml
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector-es6.js
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/DragSourceTest.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/DropTargetTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDIT.java
Labels: +0.0.1

#6668 Remove duplicate import entries from generated-flow-imports.js
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Labels: +1.0.0

#6675 update bytebuddy version from 1.9.13 to 1.10.1
  flow-server/pom.xml
Labels: +0.0.1

#6674 Extracted interface ExportsWebComponent from WebComponentExporter
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FlowPluginFrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/ExportsWebComponent.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentExporterTagExtractor.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
Labels: +1.0.0

#6681 Pin byte buddy version
  flow-server/pom.xml
  flow-tests/servlet-containers/felix-jetty/pom.xml
  pom.xml
Labels: +0.0.1

#6676 Use setStatus for non error response code
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#6600 added note about error messages to AbstractCompositeField JavaDoc
  flow-server/src/main/java/com/vaadin/flow/component/AbstractCompositeField.java
Labels: +0.0.1

#6686 Visit method references in byte code traversal
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteComponentWithMethodReference.java
Labels: +0.0.1, to be cherry picked

#6693 Windows uses \ not /
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FlowPluginFrontendUtils.java
Labels: +1.0.0

#6695 Cherry-pick: Use setStatus for non error response code (#6676)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#6694 Cherry-pick: Visit method references in byte code traversal (#6686)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteComponentWithMethodReference.java
Labels: +0.0.1

#6702 Use application id to call client side app context methods
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/FrontendProtocolIT.java
Labels: +0.0.1

#6710 List supported types in @EventData javadocs
  flow-server/src/main/java/com/vaadin/flow/component/EventData.java
Labels: +0.0.1

#6704 CCDM: mark spring dependencies as provided
  flow-server/pom.xml
Labels: +0.0.1, ccdm

#6713 Cherry-pick: Visit implemented interfaces when preparing frontend. (#6684)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/JsModuleComponent.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterface.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/samples/RouteInterfaceComponent.java
Labels: +0.0.1

#6705 Enhancing DEBUG mode startup warning message
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
Labels: +1.0.0

#6692 ExportsWebComponent: IT + fix for compatibility/prod mode
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/WebComponentModulesGenerator.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/WebComponentModulesGeneratorTest.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/InterfaceBasedExporter.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/InterfaceBasedIT.java
  flow-tests/test-embedding/webapp/compatibility-dev/interfaceBased.html
  flow-tests/test-embedding/webapp/compatibility-prod/interfaceBased.html
  flow-tests/test-embedding/webapp/npm/interfaceBased.html
Labels: +1.0.0, portlet

#6711 CCDM: use default serviceUrl from flow-client
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +0.0.1, ccdm

#6706 Report usage statistics as expected by the P3 collector
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Labels: +0.0.1, 2.0, to be cherry picked

#6690 CCDM: add OpenAPI spec generator
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-migration/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskConnectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApi.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/AbstractServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/collectionservice/CollectionService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/collectionservice/CollectionServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/datetime/DateTimeService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/datetime/DateTimeServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/denyall/DenyAllService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/denyall/DenyAllServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/inheritedmodel/InheritedModelService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/inheritedmodel/InheritedModelServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/model/ComplexReturnTypeService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/model/ComplexTypeParamsService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/model/ModelService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/model/ModelServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/model/ShouldNotBeGenerated.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/model/subpackage/ModelFromDifferentPackage.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/modelpackage/ModelPackageService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/modelpackage/ModelPackageTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/modelpackage/SubModelPackageService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/modelpackage/subpackage/Account.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/notnull/NotNullService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/notnull/NotNullServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/reservedwordclass/ReservedWordClassServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/reservedwordclass/await.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/reservedwordmethod/ReservedWordMethodService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/reservedwordmethod/ReservedWordMethodServiceGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/sameclassname/SameClassNameService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/sameclassname/SameClassNameTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/sameclassname/subpackage/SameClassNameModel.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/sameclassname/subpackage/SubProperty.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java
Labels: +0.1.0, ccdm

#6718 Cherry-pick: Remove duplicate import entries from generated-flow-imports.js #6668
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Labels: +0.0.1

#6727 Correction 2.1.portal-SNAPSHOT to 2.2-SNAPSHOT in two tests
  flow-tests/test-no-root-context/pom.xml
  flow-tests/test-no-theme/pom.xml
Labels: +1.0.0

#6726 Set internal server error status on stream resource exception
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
Labels: +0.0.1

#6728 Fix app id in UI.
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
Labels: +0.0.1

#6719 CCDM: throw when using VaadinService in non Spring projects
  flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectServicesValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectServicesValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
Labels: +1.0.0, ccdm

#6708 CCDM: Test ui.navigate updates URL when using client-side routing
  flow-tests/test-ccdm/frontend/client-router.js
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ViewWithServerViewButton.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +0.0.1, ccdm

#6685 Enable fat-/uber-jar production mode
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1

#6697 Generic DnD: enable dnd polyfill for iOS
  flow-dnd/pom.xml
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
Labels: +0.0.1

#6735 Enable fat-/uber-jar production mode (#6685)
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1

#6731 Remove redundancy from CssImport javadocs
  flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java
Labels: +0.0.1

#6741 Exclude DnDConnectorResource from SerializableTest
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.0.1, cherry picked

#6729 Remove spam from watchdog
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#6734 CCDM: generate OpenAPI in DevMode
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +1.0.0, ccdm

#6747 CCDM: skip spring check when in a CDI environment
  flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectServicesValidator.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectServicesValidatorTest.java
Labels: +0.0.1, bug, ccdm

#6745 Fail if npm of known faulty version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.1.0

#6744 CCDM: ensure generated index js is valid for Windows
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexJs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexJsTest.java
Labels: +0.1.0, ccdm

#6738 CCDM: Add ConnnectClient and ConnectTs generators
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/exception/VaadinConnectException.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/exception/VaadinConnectValidationException.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskConnectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexJs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApi.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/ModelTemplate.mustache
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/main/resources/connect-client.default.ts.template
  flow-server/src/test/java/com/vaadin/flow/component/CompositeTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/SchemaResolverTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGeneratorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/openapi/OpenApiSpecBasedTests.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/application.properties.for.testing
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-custom.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-default.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/esmodule-generator-OneServiceOneMethod.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/esmodule-generator-TwoServicesThreeMethods.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-default-class-no-tag.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-first-class-multiple-tags.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-multiple-lines-description.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-no-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-second-class-multiple-tags.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/get-operation-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/invalid-schema-type-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/multiple-tags-operation.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/multiplelines-description.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/no-description-response-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/no-tag-operation.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/no-tsdoc-operation.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/parameters-and-return-tsdoc.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/wrong-input-path-openapi.json
  flow-server/src/test/resources/java/MyVaadinServices.java
  flow-tests/test-ccdm-connect/frontend/src/test-component.js
Labels: +1.0.0, ccdm

#6750 Fail if npm of known faulty version (#6745)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.1.0, 2.1, cherry pick

#6755 CCDM: run TS generators in dev-mode
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/openapi/OpenApiSpecBasedTests.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.1.0, ccdm

#6757 Give hint about missing null representation in error message
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.1.0

#6758 CCDM: move connect goals from prepare to build goal
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +0.0.1, ccdm

#6761 Update browser version to 78 from 77
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.1.0

#6725 Add Java API for pre element (#5010)
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/PreElement.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Pre.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/PreTest.java
Labels: +0.1.0

#6765 Update browser version to 78 from 77 (#6761)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#6766 Update browser version to 78 from 77 (#6761)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#6751 Fail if npm of known faulty version (#6745)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.1.0, 2.0, cherry pick

#6767 Add Java API for pre element (#5010) (#6725)
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/PreElement.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Pre.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/PreTest.java
Labels: +0.1.0

#6769 Maven plugin: include javax.servlet-api as well if in provided dependencies for bytecode scanner
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FlowPluginFrontendUtils.java
Labels: +0.0.1

#6774 CCDM: remove stale module
  flow-components-parent/flow-code-generator-api/pom.xml
  flow-components-parent/flow-code-generator/pom.xml
  flow-components-parent/flow-generated-components/pom.xml
  flow-components-parent/flow-webcomponent-api-analyzer/pom.xml
  flow-components-parent/pom.xml
  pom.xml
Labels: +0.0.1

#6775 Pass response object to WebComponentBootstrapHandler::getServiceUrl and WebComponentProvider::generateNPMResponse
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
Labels: +1.0.0

#6780 Remove from release profile removed module
  pom.xml
Labels: +0.0.1

#6597 Support @ClientCallable return values
  flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
  flow-client/src/main/java/com/vaadin/client/communication/ServerConnector.java
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventHandlerBinder.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/test-gwt/java/com/vaadin/client/ClientEngineTestBase.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtMultipleBindingTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateTreeTest.java
  flow-server/src/main/java/com/vaadin/flow/component/ClientCallable.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractServerHandlers.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ClientCallableHandlers.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/FocusableTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonCodecTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockUI.java
  flow-tests/test-root-context/frontend/EventHandler.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/EventHandlerView.java
  flow-tests/test-root-context/src/main/webapp/frontend/com/vaadin/flow/uitest/ui/template/EventHandler.html
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EventHandlerIT.java
Labels: +0.1.0

#6782 CCDM: check userPrincipal for non-anonymous methods
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-tests/test-ccdm-connect/frontend/src/test-component.js
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/ConnectServices.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/VaadinView.java
  flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
Labels: +1.0.0, ccdm

#6783 Add tryCatchWrapper
  flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js
Labels: +0.0.1

#6778 Show error in console when dynamic import fails
  flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyIT.java
Labels: +0.0.1

#6794 CCDM: use default relative connect endpoint
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-default.ts
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/VaadinView.java
  flow-tests/test-ccdm-connect/src/main/resources/application.properties
  flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
  flow-tests/test-ccdm-connect/tsconfig.json
Labels: +0.0.1, ccdm

#6800 Add tryCatchWrapper (#6783)
  flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js
Labels: +0.0.1, cherry pick

#6799 Add tryCatchWrapper (#6783)
  flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js
Labels: +0.0.1, cherry pick
