Repository vaadin/flow, pull requests merged in 2019-12, with the labels that each got.

#7057 Fix bug in Element::removeFromTree not removing virtual child nodes from their parent (#7054)
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentWrapper.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +0.1.0, cherry pick

#7069 Wait for custom elements to load before adding demo contents
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/SourceContent.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/WhenDefinedManager.java
Labels: +0.0.1

#7066 Accept a build-info
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, to be cherry picked

#7072 Accept a build-info #7066
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, 2.1, cherry pick

#7076 Load dependencies for components pending attach
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/WhenDefinedManager.java
Labels: +0.0.1

#7056 Remove target/frontend/package
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +1.0.0

#7047 Error message if dev-server not responding 2.1 (#7034)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/WebpackConnectionException.java
Labels: +0.1.0, cherry pick

#7080 CCDM: remove tests depending on vaadin-spring
  flow-tests/pom.xml
  flow-tests/test-ccdm-connect/.gitignore
  flow-tests/test-ccdm-connect/frontend/src/test-component.js
  flow-tests/test-ccdm-connect/pom.xml
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/AppShell.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/Application.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/ConnectServices.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/SecurityConfiguration.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/TestComponent.java
  flow-tests/test-ccdm-connect/src/main/java/com/vaadin/flow/connect/VaadinView.java
  flow-tests/test-ccdm-connect/src/main/resources/application.properties
  flow-tests/test-ccdm-connect/src/test/java/com/vaadin/flow/connect/VaadinViewIT.java
  flow-tests/test-ccdm-connect/tsconfig.json
Labels: +0.0.1, ccdm

#7008 Update exception message
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
Labels: +1.0.0

#7084 Fix nullRepresentation argument not used
  flow-data/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java
Labels: +0.0.1, to be cherry picked

#7096 Fix tests now that pnpm is in use.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +0.1.0

#7095 Avoid clean up if PNPM is used
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.1.0

#7103 Iterate over a copy for UI internals listeners
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.1.0, to be cherry picked

#7102 Fix Java 11 build
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationRegistryTest.java
Labels: +0.1.0

#7100 Fix command expectations to expect a local install
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
Labels: +0.1.0

#7104 CCDM: implement proper getChildren in JavaScriptBootstrapUI
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.1.0, ccdm

#7110 Fix drop target highlighting issues with child elements
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
Labels: +0.0.1

#6933 Allow adding a local js module through Page.addJsModule
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
Labels: +0.1.0

#7117 Remove old "flow-deps" dependency/package-lock if PNPM is used
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1

#7115 Fix using host value from the request
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1

#7125 Exclude pnpm from managing itself
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#7119 CCDM: remove `Flow.start()` API
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.js
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/test-ccdm/frontend/index.js
Labels: +1.0.0, ccdm

#7138 Use recommended API to get chrome capabilities
  flow-tests/test-memory-leaks/src/test/java/com/vaadin/flow/memoryleaks/ui/RedeployLeakIT.java
Labels: +0.0.1

#7124 Add explicit "crossorigin" attribute to bundle script tag in bootstrap
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#7131 Use Element API for traversing children to call the onEnabledStateChanged method
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1

#7139 Deprecate isIOS method and make it in ExtendedClientDetails
  flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-server/src/test/java/com/vaadin/flow/component/page/ExtendedClientDetailsTest.java
Labels: +0.1.0

#7099 Added missing constructor with scanNestedDefinitions option
  flow-data/src/main/java/com/vaadin/flow/data/binder/BeanValidationBinder.java
Labels: +0.1.0

#7122 Upgrade webpack plugins to fix npm audit warnings
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#7141 Update compression plugin
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#7142 Upgrade webpack plugins to fix npm audit warnings
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#7145 CCDM: cherry pick changes in BootstrapHandler.js to FlowBootstrap.js
  flow-client/src/main/resources/META-INF/resources/frontend/FlowBootstrap.js
Labels: +0.0.1, ccdm

#7140 fix navigation loops
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.0.1, ccdm

#7157 Revert "Added missing constructor with scanNestedDefinitions option (…
  flow-data/src/main/java/com/vaadin/flow/data/binder/BeanValidationBinder.java
Labels: +1.0.0

#7159 Handle possible array
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#7153 CCDM: prevent connector failures when they expect connected component
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, ccdm

#7154 Only sending to server should be postponed
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java
Labels: +1.0.0

#7161 Handle possible array 2.1 (#7159)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1, 2.1, cherry pick

#7165 Workarounds for Safari 10 <script nomodule> and scope bugs
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/resources/com/vaadin/flow/server/safari-10-1-script-nomodule.js
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#7061 Unregister listener when disconnecting web component
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentWrapper.java
Labels: +0.0.1

#7155 Make links focusable
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
Labels: +0.1.0

#7163 Fix broken mobile dnd polyfill for ipad on iOS13
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/internal/DnDUtilHelper.java
Labels: +0.0.1, to be cherry picked

#7175 Copy when jar
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +0.0.1, to be cherry picked

#7180 Copy when jar 2.1 (#7175)
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +0.0.1, cherry pick

#7168 Dp/ccdm/support inline bodysize viewport annotations
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +0.1.0, ccdm

#7169 Allow server->server when calling navigation in the same round-trip
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.0.1, ccdm

#7185 Fix running pnpm for a local installation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1

#7179 Dp/ccdm/bodysize annotation
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/TestApplicationServiceInitListener.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +0.1.0, ccdm

#7192 fixes #7190
  flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicTextElementStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/ShadowRootStateProvider.java
  flow-server/src/test/java/com/vaadin/flow/dom/impl/ElementStateProviderDeserializationTest.java
Labels: +0.1.0

#7191 Pin pnpm verion to 4.5 and remove workaround for 4.3.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#7189 Pass query parameters to the new location
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.0.1

#7193 CCDM: inform TestBench that Flow client navigation is in progress
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/FlowBootstrap.js
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.1.0, ccdm

#7181 Update chromedriver to v79
  drivers.xml
Labels: +0.0.1

#7201 Assert chrome version 79
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#7195 CCDM: fix NPE when in prod there is no VaadinAppShell
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +0.0.1, ccdm

#7207 Update chromedriver and test for version 79
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, ccdm

#7203 CCDM: bump router version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, ccdm

#7209 fix: @Transactional works in @VaadinService classes
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, ccdm

#7212 Only clear all if value changes.
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ElementInnerHtmlView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ElementInnerHtmlIT.java
Labels: +0.0.1

#7213 chore: remove unused method parameter
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
Labels: +0.0.1, ccdm

#7215 Don't add abstract error targets
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryTestBase.java
Labels: +0.0.1, to be cherry picked

#7217 Add onclick to error window
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Labels: +0.0.1

#7208 Dp/ccdm/inline annotaion
  flow-server/src/main/java/com/vaadin/flow/server/InlineTargets.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +1.0.0, ccdm

#7216 Error message for failing imports should be tool dependent
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Labels: +0.0.1

#7220 Combine all constructors together
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1

#7221 log: debug the list of dependencies and imports found in classes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
Labels: +0.0.1

#7214 Remove self imports from generated TS files
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/selfreference/SelfReference.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/selfreference/SelfReferenceService.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/services/selfreference/SelfReferenceTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/inheritedmodel/expected-model-media.Schema.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/model/expected-model-model.ModelService.Account.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/selfreference/expected-SelfReferenceService.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/services/selfreference/expected-model-selfreference.SelfReference.ts
Labels: +1.0.0, ccdm

#7222 Remove test-jar artifact from flow-server
  flow-server/pom.xml
Labels: +0.0.1

#7223 add UI getter into IndexHtmlRequestListener
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlResponse.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-ccdm/pnpm-lock.yaml
Labels: +0.1.0, ccdm

#7229 Drop all es5 mentions and support
  flow-client/src/main/java/com/vaadin/client/BrowserInfo.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-server/src/main/java/com/vaadin/flow/component/dependency/HtmlImport.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/HtmlDependencyParser.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DependencyFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/ServiceContextUriResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/BundleDependencyFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/BundleFilterFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/FakeBrowser.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-server/src/main/java/com/vaadin/flow/shared/VaadinUriResolver.java
  flow-server/src/main/resources/com/vaadin/flow/server/babel-helpers.min.js
  flow-server/src/main/resources/com/vaadin/flow/server/es6-collections.js
  flow-server/src/main/resources/com/vaadin/flow/server/safari-10-1-script-nomodule.js
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/BundleDependencyFilterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/BundleFilterFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/VaadinUriResolverTest.java
  flow-server/src/test/resources/InvalidStats.json
  flow-server/src/test/resources/META-INF/VAADIN/config/babel_stats.json
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/src/test/resources/MissFormatStats.json
  flow-server/src/test/resources/ValidStats.json
Labels: +1.0.0

#7236 CCDM: serve all assets from webpack dev server
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +1.0.0, ccdm

#7237 Remove unused method from PageTest
  flow-server/src/test/java/com/vaadin/flow/component/internal/PageTest.java
Labels: +0.0.1

#7241 fix: warn about PageConfigurator also in Spring apps
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
Labels: +1.0.0

#7233 If globally installed pnpm is too old, install newer version locally
  flow-migration/src/main/java/com/vaadin/flow/migration/Migration.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0

#7235 CCDM: add method to VaadinAppShell for configuring the page
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
  flow-server/src/main/java/com/vaadin/flow/component/page/VaadinAppShell.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/PageConfigurator.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractAnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
Labels: +1.0.0, ccdm

#7253 Add skipLibCheck to tsconfig.json
  flow-client/tsconfig.json
Labels: +1.0.0
