Repository vaadin/flow, pull requests merged in 2020-11, with the labels that each got.

#9271 chore: do not depend on commons.lang3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
Labels: +0.0.1

#9272 chore: fix typo
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.0.1

#9275 fix: Sync HierarchicalDataCommunicator's expand state with client side
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
Labels: +0.1.0

#9289 refactoring: review fixes
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletContext.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
  flow-tests/test-root-context/pom-npm.xml
Labels: +1.0.0

#9285 test: service-worker aware live reload IT
  flow-tests/test-live-reload/frontend/code.js
  flow-tests/test-live-reload/frontend/custom-component.ts
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/JavaLiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
Labels: +1.0.0, fusion

#9296 fix: enable workbox Webpack plugin only for PWAs
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: +1.0.0, fusion

#9307 refactoring: get rid of cmpn osgi dependency
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
Labels: +1.0.0, OSGi

#9278 refactoring: App classpath resources should be access via ResourceProvider
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
Labels: +1.0.0, OSGi

#9304 deferred call submission status API refactor
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Offline.ts
  flow-client/src/main/resources/META-INF/resources/frontend/index.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/OfflineTests.ts
  flow-client/webpack.tests.config.js
Labels: +1.0.0, fusion

#9298 refactor: make web browser immutable
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
Labels: +1.0.0

#9317 Cherry Picks to 5.0
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
Labels: +0.1.0, cherry pick

#9295 feat: Create Flow plugins for webpack
  flow-server/README.md
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
  flow-server/src/main/resources/plugins/stats-plugin/package.json
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
  flow-server/src/main/resources/plugins/webpack-plugins.json
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0, webpack

#9335 fix: do not attempt to call `$server.leaveNavigation` in offline case
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
Labels: +1.0.0, fusion

#9325 chore: consolidated offline navigation tests to single class
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/OfflineServerViewIT.java
Labels: +1.0.0, fusion

#9332 fix: AppShellConfigurator is now considered for theme endpoint
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
Labels: +0.1.0, target/5.0

#9336 fix: TreeGrid updating wrong expanded items state after setDataProvider
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
Labels: +0.0.1

#9342 Cherry Picks to 5.0
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
Labels: +0.0.1, cherry pick

#9277 refactoring: get rid of OSGiClientStaticResource
  flow-client/bnd.bnd
  flow-client/pom.xml
  flow-client/src/main/java/com/vaadin/flow/client/osgi/OSGiClientStaticResource.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
Labels: +1.0.0, OSGi

#9313 feat: Theme annotation should be only on AppShellConfigurator
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java
  flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +0.1.0, target/5.0

#9329 test(TypeScript): ensure CSRF token is updated when session is invalidated
  flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/SessionView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/SessionViewIT.java
Labels: +0.1.0, fusion

#9309 generate sw.ts to frontend folder when pwa enabled
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateServiceWorker.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateServicWorkerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0, fusion

#9361 [OSGi] - Cleanup BudleActivator and Service registration, Update bnd and osgi deps
  flow-client/pom.xml
  flow-data/pom.xml
  flow-dnd/pom.xml
  flow-lit-template/pom.xml
  flow-polymer-template/pom.xml
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/OSGiPolymerPublishedEventHandlerRegistration.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/PolymerPublishedEventRpcHandler.java
  flow-push/pom.xml
  flow-server/bnd.bnd
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiResourceProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
  flow-tests/pom.xml
  flow-tests/test-root-context/pom.xml
  pom.xml
Labels: +1.0.0

#9381 fix: increase threshold for performance test
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#9380 fix: hide loading indicator when endpoint call fails
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +0.0.1, fusion

#9315 fix!: Store in-memory filtering and sorting in component
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
Labels: +1.0.0, target/5.0, to be cherry picked

#9368 fix: support Range requests with either start or end byte index omitted
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
Labels: +0.0.1, target/2.4, target/2.5, target/4.0, target/5.0

#9390 refactor: revert 'Use data view filter and sorting in component'
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
Labels: +1.0.0

#9394 chore: remove test module test-subcontext
  flow-tests/README.md
  flow-tests/pom.xml
  flow-tests/test-subcontext/eclipse/UI Test Development Server (subcontext).launch
  flow-tests/test-subcontext/pom.xml
  flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/DependencyUI.java
  flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/NoRouterServlet.java
  flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/RootContextUI.java
  flow-tests/test-subcontext/src/main/java/com/vaadin/flow/contexttest/ui/SubContextUI.java
  flow-tests/test-subcontext/src/test/java/com/vaadin/flow/contexttest/ui/AbstractContextIT.java
  flow-tests/test-subcontext/src/test/java/com/vaadin/flow/contexttest/ui/RootContextIT.java
  flow-tests/test-subcontext/src/test/java/com/vaadin/flow/contexttest/ui/SubContextIT.java
  flow-tests/test-subcontext/src/test/java/com/vaadin/flow/contexttest/ui/SubContextNoEndingSlashIT.java
  flow-tests/test-subcontext/src/test/java/com/vaadin/flow/contexttest/ui/SubContextSubPathIT.java
Labels: +0.0.1, target/4.0, target/5.0, to be cherry picked

#9382 refactor: update readme with discord link
  README.md
Labels: +0.0.1, target/2.5, to be cherry picked

#9395 test: remove Theme annotation from demo helpers module
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java
Labels: +0.0.1

#9389 feat: Do not allow themeClass and themeName in same annotation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-tests/README.md
  flow-tests/test-misc/frontend/legacyTheme/my-theme/client-side-component.js
  flow-tests/test-misc/frontend/legacyTheme/my-theme/npm-themed-component.js
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/NpmThemedComponentView.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/NpmThemedComponentIT.java
  flow-tests/test-themes/frontend/src/client-side-component.js
  flow-tests/test-themes/frontend/src/npm-themed-component.js
  flow-tests/test-themes/pom.xml
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9391 fix!: Store in-memory filtering and sorting in component
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataViewUtils.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
Labels: +1.0.0

#9406 feat: Only handle annotated theme
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-themes/frontend/theme/no-copy/no-copy.txt
  flow-tests/test-themes/pom.xml
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +1.0.0

#9377 feat: application connection state store
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/ConnectionState.java
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/LoadingIndicatorConfigurator.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/LoadingIndicator.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Offline.ts
  flow-client/src/test-gwt/java/com/vaadin/client/GwtApplicationConnectionTest.java
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/OfflineTests.ts
  flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
  flow-client/src/test/java/com/vaadin/client/communication/LoadingIndicatorConfiguratorTest.java
  flow-client/webpack.tests.config.js
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
Labels: +1.0.0, fusion, offline

#9431 fix: revert not working deployment of test-root-context ui classifier
  flow-tests/pom.xml
  flow-tests/test-root-context/pom.xml
Labels: +0.0.1

#9392 fix: check if Url path is encoded twice in Dev Mode
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
Labels: +0.1.0

#9421 fix: preserve filter for not losing it between page requests
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0, target/5.0, to be cherry picked

#9426 Update issue template with discord link
  .github/ISSUE_TEMPLATE.md
Labels: +0.0.1

#9445 chore: update chrome expectation to 87
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, target/2.4, target/4.0, target/5.0, to be cherry picked

#9447 chore: update chrome expectation to 87 (#9445)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#9448 chore: update chrome expectation to 87 (#9445)
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#9449 chore: update chrome expectation to 87 (#9445)
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#9432 fix: revert changes which broke route registration
  flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
Labels: +1.0.0

#9453 chore: fix outdated AppShell javadoc
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
Labels: +1.0.0, target/4.0, target/5.0

#9436 test: add test for setting global font
  flow-tests/test-themes/frontend/theme/app-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-themes/frontend/theme/app-theme/global.css
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9416 fix race-condition in IT-Tests
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1

#9452 feat: transition to RECONNECTING when receiving browser online event
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/ConnectionState.java
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
  flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtDefaultConnectionStateHandlerTest.java
Labels: +1.0.0, fusion, offline

#9465 Fix push osgi
  flow-server/bnd.bnd
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
Labels: +0.0.1

#9442 fix: made VaadinRequest available in endpoint
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, fusion, target/4.0, target/5.0, to be cherry picked

#9396 feat(offline): add connection indicator element
  flow-client/src/main/java/com/vaadin/client/communication/LoadingIndicatorConfigurator.java
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/LoadingIndicator.ts
  flow-client/src/main/resources/META-INF/resources/frontend/index.ts
  flow-client/src/test/frontend/ConnectionIndicatorTests.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/webpack.tests.config.js
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
Labels: +1.0.0, fusion

#9151 chore: remove mentions of “Connect”
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-maven-plugin/README.md
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-polymer-template/pom.xml
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/EndpointNameChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinEndpointProperties.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/AnonymousAllowed.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/exception/EndpointException.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskConnectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApi.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectEndpointsValidator.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/application.properties.for.testing
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/esmodule-generator-OneEndpointOneMethod.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/esmodule-generator-TwoEndpointsThreeMethods.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/get-operation-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/invalid-schema-type-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/multiple-tags-operation.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/multiplelines-description.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/no-description-response-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/no-tsdoc-operation.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/parameters-and-return-tsdoc.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/wrong-input-path-openapi.json
Labels: +0.0.1, fusion

#9451 feat: Serve theme static files from VAADIN/static
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/theme-loader/package.json
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
  flow-server/src/main/resources/plugins/webpack-plugins.json
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
  flow-tests/test-themes/frontend/theme/app-theme/global.css
  flow-tests/test-themes/frontend/theme/app-theme/icons/archive.png
  flow-tests/test-themes/frontend/theme/app-theme/sub-css/sub.css
  flow-tests/test-themes/pom.xml
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1, theming

#9472 refactor: Remove OSGi code from flow-server
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiResourceProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/ServletContainerInitializerExtender.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/OSGiWebComponentConfigurationRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/OSGiVaadinServletTest.java
  flow-server/src/test/java/com/vaadin/flow/server/osgi/OSGiAccessTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/OSGiApplicationRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/OSGiInitApplicationRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/OSGiWebComponentConfigurationRegistryTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +1.0.0

#9469 chore: update Flow versions description in README.md
  README.md
Labels: +0.0.1

#9486 fix: check whether class implements an interface first directly
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Labels: +0.0.1

#9427 feat: TypeScript API for connection indicator configuration
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-tests/test-ccdm-flow-navigation/frontend/index.ts
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +1.0.0, fusion, offline

#9475 fix: remove instance field from singleton IndexHtmlRequestHandler
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +1.0.0, fusion

#9476 Stop logging error when updating dev dependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, target/2.4, target/2.5, target/4.0, to be cherry picked

#9484 fix: optimize handling of requests containing Range header
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
Labels: +0.1.0

#9481 Remove reconnect dialog
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/DefaultReconnectDialog.java
  flow-client/src/main/java/com/vaadin/client/communication/ReconnectDialog.java
  flow-client/src/main/resources/com/vaadin/ClientEngineXSI.gwt.xml
  flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
  flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtDefaultReconnectDialogTest.java
  flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
Labels: +1.0.0, fusion

#9496 fix: Correct regexp to only match when digit first
  flow-server/src/main/java/com/vaadin/flow/internal/CustomElementNameValidator.java
  flow-server/src/test/java/com/vaadin/flow/internal/CustomElementNameValidatorTest.java
Labels: +0.0.1

#9482 test: add test that external urls are not touched
  flow-tests/test-themes/frontend/theme/app-theme/global.css
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/servlets/WorkaroundServlet.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/main/webapp/octopuss.jpg
  flow-tests/test-themes/src/main/webapp/path/test/path/monarch-butterfly.jpg
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9489 fix: Add polyfill for constructable stylesheets
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1

#9500 fix: Initialize VaadinServlet after Lookup is available
  flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
Labels: +0.1.0

#9495 feat: Enable adding assets from node_modules
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-tests/test-themes/frontend/theme/app-theme/theme.json
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9507 test: add unit test for clear all in the servlet init method
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
Labels: +0.0.1

#9502 fix: reconnect dialog settings to vaadin-connection-indicator
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/ConnectionIndicator.java
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/LoadingIndicatorConfigurator.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-client/src/main/java/com/vaadin/client/communication/ReconnectConfiguration.java
  flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
  flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtDefaultConnectionStateHandlerTest.java
  flow-client/src/test/frontend/ConnectionIndicatorTests.ts
  flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
  flow-client/src/test/java/com/vaadin/client/communication/ReconnectConfigurationTest.java
  flow-server/src/main/java/com/vaadin/flow/component/ReconnectDialogConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReconnectDialogConfigurationMap.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ReconnectDialogConfigurationMapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/ConnectionIndicatorView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
Labels: +1.0.0, fusion

#9505 Fix: fix file system traversal of theme-loader to stop at root
  flow-server/src/main/resources/plugins/theme-loader/package.json
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
Labels: +0.0.1

#9520 fix: enable PlainScriptViaJavaScriptIT in OSGi
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptIT.java
Labels: +0.0.1

#9519 chore: fix flaky offline ITs
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
Labels: +1.0.0, fusion, offline

#9510 fix: add vaadin-connection-indicator in Connect ctor
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +1.0.0, fusion, offline

#9511 chore: remove defunct dialogGracePeriod and dialogModal
  flow-server/src/main/java/com/vaadin/flow/component/ReconnectDialogConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReconnectDialogConfigurationMap.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/ClientServerCounterUI.java
Labels: +1.0.0, fusion, offline

#9518 fix: enable PushRouteWildcardParameterIT in OSGi
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterIT.java
Labels: +0.0.1

#9515 fix: enable BaseHref IT for OSGi back
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java
Labels: +0.0.1

#9513 feat(offline): retry server navigation when back online
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +1.0.0, fusion

#9527 chore: Add information on logging in webpack
  flow-server/README.md
Labels: +0.0.1

#9528 test: fix test class and register view servlet with a context in OSGi
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1, OSGi
