Repository vaadin/flow, pull requests merged in 2020-09, with the labels that each got.

#8922 Add HasHelper interface
  flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
  flow-server/src/test/java/com/vaadin/flow/component/HasHelperTest.java
Labels: +1.0.0

#8932 Add HasHelper interface (#8922)
  flow-server/src/main/java/com/vaadin/flow/component/HasHelper.java
  flow-server/src/test/java/com/vaadin/flow/component/HasHelperTest.java
Labels: +1.0.0, cherry picked, target/2.4

#8934 Don't store webpack dev server port if server start failed
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#8925 Cherry picks for starting web pack dev server and (p)npm install command in the separate thread
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/main/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformance.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRouteIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundDevModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundProdModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ViewTitleIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java
Labels: +1.0.0

#8930 Live reload on frontend changes
  .gitignore
  flow-client/package-lock.json
  flow-client/package.json
  flow-client/pom.xml
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
  flow-client/tsconfig.json
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-tests/test-live-reload/frontend/styles.css
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
Labels: +1.0.0

#8935 Remove progress plugin from web-pack config
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +1.0.0

#8938 Don't use the deprecated method
  flow-server/src/main/java/com/vaadin/flow/internal/HtmlUtils.java
Labels: +0.0.1, target/2.3, target/2.4, target/3.1, target/4.0, to be cherry picked

#8869 Fix redirect/forward for Optional HasUrlParameter
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.0.1

#8943 Fix log time units
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1

#8939 fix: fetch real type for generic typed parameter
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/CrudEndpoint.java
Labels: +0.0.1, ccdm

#8949 Cherry-picks for 2.3.5
  flow-server/src/main/java/com/vaadin/flow/internal/HtmlUtils.java
Labels: +0.0.1

#8937 Fixes from backporting frontend live-reload into master
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +1.0.0

#8961 Make the CustomInMemoryDataProvider implement listeners handling
  flow-data/src/test/java/com/vaadin/flow/data/provider/CustomInMemoryDataProvider.java
Labels: +0.0.1, target/4.0

#8957 Read attribute value from template
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/frontend/AttributeTemplate.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
Labels: +1.0.0

#8969 Make the CustomInMemoryDataProvider implement listeners handling (#8961)
  flow-data/src/test/java/com/vaadin/flow/data/provider/CustomInMemoryDataProvider.java
Labels: +0.0.1, cherry pick

#8941 feat(offline): emit offline resources list in generated webpack config
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +1.0.0, ccdm

#8980 Always consume the stdout stream from (p)npm and log at debug level (#7325)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1

#8956 Upgrade auto-installed Node to latest LTS and suppress some `npm install` errors
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Labels: +0.0.1, to be cherry picked

#8897 Fix typo in variable DEAULT_FLOW_RESOURCES_FOLDER
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/StatsContentTest.java
Labels: +0.1.0

#8986 Support for disabling Win-specific tests in CI
  flow-tests/pom.xml
  pom.xml
Labels: +0.0.1

#8992 feat: Endpoint generation based on @Deferrable
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/Deferrable.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/DeferrableEndpointTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/SingleMethodDeferrableEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/WholeClassDeferrableEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
Labels: +1.0.0, ccdm

#8995 Cherry picks to 4.0
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Labels: +0.0.1, cherry pick

#8971 Do not force installation of compatible pnpm version when system property `vaadin.ignoreVersionChecks` is set
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.3, target/2.4, target/4.0, to be cherry picked

#8998 Cache original index.html Document in production mode
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1, ccdm

#8990 Show webpack error on live reload of frontend resources
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-live-reload/frontend/styles.css
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
Labels: +1.0.0

#8997 fix: surround 404 check with spaces
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
Labels: +0.0.1, target/2.3, target/2.4, target/4.0, to be cherry picked

#8999 feat: support deferrable endpoint request
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
Labels: +1.0.0, ccdm

#8979 Implement lit template parser for limited template formats which extends LitTemplate element
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplate.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateInitializer.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParser.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParserImpl.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
  flow-server/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateParserImplTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/src/test/resources/frontend/my-lit-element-view.js
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#9003 Use JS rather than CSS file for testing Webpack live reload
  flow-tests/test-live-reload/frontend/code.js
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Labels: +1.0.0

#9002 Fixed: flow-server now closes resources properly when parsing java classes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1, target/2.3, target/4.0, to be cherry picked

#9007 Set enable state based on template element attribute
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/DisabledInitializationStrategy.java
  flow-server/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-tests/test-root-context/frontend/AttributeTemplate.js
  flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
Labels: +0.0.1

#9019 fix: don't reuse endpoint nullable checker state
  flow-server/src/main/java/com/vaadin/flow/server/connect/BeanValueTypeCheckHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, ccdm

#9017 Send clear event if no other changes done on attach
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
  flow-tests/test-root-context/frontend/SetInitialText.js
  flow-tests/test-root-context/frontend/lit/SetInitialText.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SetInitialTextLitView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/SetInitialTextView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SetInitialTextLitIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/SetInitialTextIT.java
Labels: +0.0.1

#9008 Read text for template element
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/TextInitializationStrategy.java
  flow-server/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-tests/test-root-context/frontend/AttributeTemplate.js
  flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ChildOrderView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
Labels: +0.1.0

#9020 Deprecate UI.getRouter() and use it only as internal
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
  flow-server/src/test/java/com/vaadin/flow/component/LocationObserverTest.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RoutingTestBase.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/ErrorStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapContextTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockUI.java
Labels: +0.1.0

#9022 refactor: move methods from endpoint nullable checker to a helper
  flow-server/src/main/java/com/vaadin/flow/server/connect/BeanValueTypeCheckHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullabeTypeCheckerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, ccdm

#9021 Keep ui reference to avoid its GC during test
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1

#9032 chore: fix typo
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Labels: +0.0.1, ccdm

#9034 4.0 cherry pick
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Labels: +0.0.1, ccdm, cherry pick

#9030 Add test for forwardTo from setParameter without BeforeEnterObserver.
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +1.0.0, routing, testing

#9031 Be aware of property value in the Element
  flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
  flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
Labels: +0.0.1

#9041 fix a flaky test in VaadinConnectControllerTest
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, ccdm

#9040 JavaScriptBootstrapHandler: Do not compute push url from service and request url on the server side
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteWildcardParameterIT.java
Labels: +0.0.1

#9044 4.0 cherry pick
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, ccdm, cherry pick

#9026 Set `display:none` in addition to `hidden` attribute when hiding elements inside a shadow root
  flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java
  flow-tests/test-root-context/frontend/lit/lit-template-inner.js
  flow-tests/test-root-context/frontend/lit/lit-template-outer.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/InnerTemplateVisibilityView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/InnerTemplateVisibilityIT.java
Labels: +1.0.0

#9048 Remove faux Serializable from AppShellSettings
  flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#9050 Clear routes.
  flow-server/src/main/java/com/vaadin/flow/router/internal/ConfigureRoutes.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteModel.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
Labels: +0.1.0, bug, routing

#9033 Force size re-estimate when requested range end equals assumed size
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0, target/4.0, to be cherry picked

#9055 Fix JavaDoc typos
  flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
Labels: +0.0.1

#9061 Restructure dev mode handler logic to avoid starting webpack twice
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1, target/2.4, target/4.0, to be cherry picked

#9052 Skip data provider verification in AbstractDataView if default one is used
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +0.1.0, target/4.0, to be cherry picked

#9074 Use regular stream instead rather than parallel
  flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
Labels: +0.0.1

#9071 fix: each UI should have its own CSRF token
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1, ccdm

#9079 CP: Treat URLs with "context" and "base" schemas as external (#8556)
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptView.java
  flow-tests/test-root-context/src/main/webapp/plain-script.js
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptIT.java
Labels: +0.0.1

#9060 Update javadoc of rerouteTo()/forwardTo()
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/LocationChangeEvent.java
Labels: +0.0.1

#9070 Add data communicator API for disabling data provider interactions
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.1.0

#9036 feat: submit cached endpoint requests in window online listener
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
Labels: +1.0.0, ccdm

#9075 chore: add @ts-ignore to DeferrableResult import
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
Labels: +1.0.0, ccdm

#8940 Move service worker generation to webpack config
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-core.dev.js
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-core.dev.js.map
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-core.prod.js
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-core.prod.js.map
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-precaching.dev.js
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-precaching.dev.js.map
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-precaching.prod.js
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-precaching.prod.js.map
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-sw.js
  flow-server/src/main/resources/META-INF/resources/VAADIN/static/server/workbox/workbox-sw.js.map
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/src/test/resources/META-INF/VAADIN/webapp/index.html
  flow-server/src/test/resources/META-INF/VAADIN/webapp/manifest.json
  flow-server/src/test/resources/META-INF/VAADIN/webapp/sw.js
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +1.0.0

#9072 fix: fail access check when no csrf token in session
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
Labels: +1.0.0, ccdm
