Repository vaadin/flow, pull requests merged in 2020-02, with the labels that each got.

#7464 upgrade ts version to 3.7.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +1.0.0, ccdm

#7453 Require explicit property set for development mode transpilation
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
Labels: +0.1.0

#6825 #6537 NpmTemplateParser can now be overridden
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
  flow-server/src/main/java/com/vaadin/flow/di/Instantiator.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
Labels: +1.0.0, waiting for author

#7456 Pin versions based on versions file provided by the Platform
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/main/resources/pnpmfile.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#7470 use npm when building flow-client
  flow-client/pom.xml
Labels: +1.0.0, ccdm

#7467 Add close error prompt feature
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1

#7475 remove webpack-babel-multi-target-plugin
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, ccdm

#7476 Rename user stat entry @vaadin/flow-frontend/Connect to endpoint
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
Labels: +0.0.1, ccdm

#7478 Use existing methods instead of repeating code
  flow-server/src/main/java/com/vaadin/flow/router/internal/ConfiguredRoutes.java
Labels: +0.0.1

#7477 Fix typos
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/client/ClientResourcesUtils.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/DependencyTreeCache.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternalUpdater.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/CustomAttribute.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ShadowRootHost.java
  flow-server/src/main/java/com/vaadin/flow/router/Route.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/ConfiguredRoutes.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AttachTemplateChildRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/RpcDecodeException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/templatemodel/AbstractBasicModelType.java
  flow-server/src/main/java/com/vaadin/flow/templatemodel/PathLookup.java
Labels: +0.0.1

#7474 Set config holder inside BootstrapContext even if there is not route target
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapContextTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PushLayout.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PushRouteNotFoundView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushRouteNotFoundIT.java
Labels: +0.0.1

#7480 Do not try to handle empty stream
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#7486 Do not try to handle empty stream 2.1 (#7480)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, 2.1, cherry pick

#7485 Do not try to handle empty stream 2.2 (#7480)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, 2.2, cherry pick

#7469 Clear previous request if it exists when it is not needed anymore
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
Labels: +1.0.0

#7450 add http status in vaadinConnectError when accessing service is denied
  flow-client/pnpm-lock.yaml
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, ccdm

#7490 Catch exception in scroll handler.
  flow-client/src/main/java/com/vaadin/client/ScrollPositionHandler.java
Labels: +0.0.1, to be cherry picked

#7455 test: fix ccdm tests in windows because of character issues
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/json/JsonTestEndpointGeneratedTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/openapi/OpenApiSpecBasedTests.java
Labels: +1.0.0, ccdm

#7479 expose the original Java exception message in VaadinConnectError
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
Labels: +0.0.1, ccdm

#7489 Call VaadinService::requestStart if push transport is websocket
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
Labels: +0.0.1

#7466 Parse Html contents as a body fragment
  flow-server/src/main/java/com/vaadin/flow/component/Html.java
  flow-server/src/test/java/com/vaadin/flow/component/HTMLTest.java
Labels: +1.0.0

#7492 Ignore duplicate message with a log, do not throw
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
Labels: +0.0.1

#7491 JavaDocs to clarify when BeforeLeave{Listener,Observer}s are not called
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveListener.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveObserver.java
Labels: +0.0.1, to be cherry picked

#7504 Use npmVersion if it exists instead of jsVersion.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Labels: +0.0.1

#7487 Update jackson version
  flow-server/pom.xml
Labels: +0.0.1, to be cherry picked

#7509 Inform users that `prepare-frontend` may need to be run in the case of missing frontend files and no token file
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
Labels: +0.0.1, to be cherry picked

#7471 CCDM: rename VaadinConnectException -> EndpointException
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/exception/EndpointException.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/exception/EndpointValidationException.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +1.0.0, ccdm

#7512 Use pnpm instead of npm
  flow-tests/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
  flow-tests/test-embedding/test-embedding-theme-variant/pom.xml
  flow-tests/test-lumo-theme/pom.xml
  flow-tests/test-material-theme/pom.xml
  flow-tests/test-misc/pom.xml
  flow-tests/test-mixed/pom-npm-production.xml
  flow-tests/test-mixed/pom-npm.xml
  flow-tests/test-mixed/pom-pnpm-production.xml
  flow-tests/test-mixed/pom.xml
  flow-tests/test-multi-war/test-war1/pom.xml
  flow-tests/test-multi-war/test-war2/pom.xml
  flow-tests/test-no-theme/pom.xml
  flow-tests/test-npm-only-features/test-default-theme/pom.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-devmode.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-prod-fallback.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-production.xml
  flow-tests/test-npm-only-features/test-npm-custom-frontend-directory/pom.xml
  flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  flow-tests/test-pwa/pom.xml
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-router-custom-context/pom.xml
  flow-tests/test-servlet/pom.xml
  flow-tests/test-subcontext/pom.xml
  flow-tests/test-themes/pom.xml
Labels: +0.0.1

#7518 Allow using JS reserved words as endpoint method names
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/reservedwordmethod/ReservedWordMethodEndpointGenerationTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/complexhierarchyendpoint/expected-ComplexHierarchyEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/denyall/expected-DenyAllEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-InheritedModelEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-GeneratorAnonymousAllowedTestClass.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexReturnTypeEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ModelEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nullable/expected-NullableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/reservedwordmethod/expected-ReservedWordMethodEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/selfreference/expected-SelfReferenceEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-default-class-no-tag.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-first-class-multiple-tags.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-multiple-lines-description.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-no-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-second-class-multiple-tags.ts
Labels: +0.0.1, ccdm

#7508 CCDM: make IndexHtmlHandler serve any request, execute it the last
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUrlPredicate.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +0.1.0

#7522 CCDM: VaadinRequest is available in Endpoints
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +1.0.0, ccdm

#7524 log: fix duplicated and erroneous message when starting webpack
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1, ccdm

#7501 when RPC parameters deserialization fails the error message should su…
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
Labels: +1.0.0, ccdm

#7529 chore: update jackson version to avoid failures with spring
  flow-server/pom.xml
Labels: +1.0.0, ccdm

#7526 modified removing the `CallOptions` parameter to avoid confusion
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/denyall/expected-DenyAllEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-GeneratorAnonymousAllowedTestClass.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json
Labels: +0.0.1, ccdm

#7517 Change UI behaviour of disabled DnD elems (#7114)
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-test-util/src/main/resources/dnd-simulation.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDDisabledView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDIT.java
Labels: +1.0.0

#7536 [FIX] Update links to documentation in DefaultDeploymentConfiguration
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1

#7543 Remove pnpm-lock.yaml file if npm is used
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#7537 CCDM: do not consider TypeScript client object in tests
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ExportedJSFunctionIT.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TimingInfoReportedView.java
Labels: +0.0.1

#7544 implementation feature `InternalServerError` component in v15 handlers
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-tests/test-dev-mode/pom.xml
Labels: +0.1.0, ccdm

#7545 Cheery-pick: Change UI behaviour of disabled DnD elems
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-test-util/src/main/resources/dnd-simulation.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDDisabledView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDIT.java
Labels: +0.0.1, target/2.1

#7506 Fix #6808.
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/IFrameTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/IFrameView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/IFrameIT.java
Labels: +0.1.0

#7535 Fix incorrectly using deploymentConfiguration directly
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.0.1, ccdm

#7554 Update branches info
  README.md
Labels: +0.0.1, target/2.2

#7568 Make a method to access {user_home}/.vaadin directory.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.2

#7577 Fix log info string format mismatch error
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
Labels: +0.0.1, ccdm

#7569 Use .vaadin folder from home folder to search node/npm binaries.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.2

#7582 Log webpack command executed during `build-frontend`
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Labels: +0.0.1, target/2.2

#7585 Add zip protocol support to DevModeInitializer
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, target/2.2

#6853 Convenience methods for RoutesChangedEvent #5310
  flow-server/src/main/java/com/vaadin/flow/router/RoutesChangedEvent.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
Labels: +0.1.0, target/2.2

#7597 Remove usage of com.google.common.base.Supplier
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#7580 Backport npm/pnpm/webpack command logging feature from V15
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.1.0

#7602 test: update chromedriver and test to test: update chromedriver and test to 80.0.3987.106
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, target/2.1, target/2.2

#7592 test(ccdm): remove global flag for running tests with v14 bootstrap
  .gitignore
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
  flow-tests/pom.xml
  flow-tests/test-ccdm/pnpm-lock.yaml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-embedding/pom.xml
  flow-tests/test-embedding/test-embedding-generic/frontend/index.ts
  flow-tests/test-embedding/test-embedding-theme-variant/frontend/index.ts
  flow-tests/test-multi-war/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/frontend/com/vaadin/flow/uitest/ui/dependencies/eager.js
  flow-tests/test-root-context/frontend/dependencies/eager.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RerouteView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerDefaultPropertyValueView.java
  flow-tests/test-root-context/src/main/webapp/dependencies/eager.js
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/FaultyLocationIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CountUIsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DnDIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ErrorPageIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RequestParametersHistoryIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RequestParametersIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ValueChangeModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebComponentsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DependenciesLoadingPageApiIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/CustomScrollCallbacksIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/webcomponent/PaperSliderIT.java
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/PushUtil.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/RoutedContextIT.java
  flow-tests/test-subcontext/pom.xml
Labels: +0.0.1, ccdm

#7571 Node and npm download and installation
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ArchiveExtractionException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ArchiveExtractor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultArchiveExtractor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DownloadException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/FileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/InstallationException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/Platform.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultArchiveExtractorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
  flow-server/src/test/java/com/vaadin/tests/server/component/FlowClassesSerializableTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0, target/2.2

#7606 Custom url mapping breaks endpoint requests
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinEndpointProperties.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGeneratorTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/application.properties.for.testing
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/expected-connect-client-custom.ts
Labels: +1.0.0, ccdm

#7609 Delete node_modules if it's structure doesn't match the current tool.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#7613 Keep a hard reference to ReflectionCache clear action
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
  flow-server/src/test/java/com/vaadin/flow/internal/ReflectionCacheTest.java
Labels: +0.0.1

#7616 chore: rename class to align with other generator tasks
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#7615 chore: not need to use the spread operator since array is filtered
  flow-server/src/main/resources/webpack.generated.js
Labels: +1.0.0, ccdm

#7617 Update chromedriver and test to 80.0.3987.106 (2.2) (#7602)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.1.0, cherry pick

#7605 Force using node from vaadin home folder
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0, target/2.2

#7618 Node and npm download and installation 2.2 (#7571)
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ArchiveExtractionException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ArchiveExtractor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultArchiveExtractor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DownloadException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/FileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/InstallationException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/Platform.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultArchiveExtractorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
  flow-server/src/test/java/com/vaadin/tests/server/component/FlowClassesSerializableTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0, cherry pick

#7607 Accept a flow-build-info
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, target/2.2

#7627 Update attribute value on attach
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractStreamResourceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
Labels: +1.0.0

#7629 Disable failing on CI test and improve expected exception checks
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0

#7630 Fix test on windows.
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +1.0.0, target/2.2

#7558 Remove polymer from default dependencies
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/template/AttachExistingElementByIdView.java
  flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
  flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/MaterialThemedTemplateView.java
  flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/NotThemedTemplateView.java
  flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/IdTestView.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/MyButton.java
  flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/InjectedElementInsideMixinBehaviorView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/template/RouterLinksTemplate.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java
Labels: +0.0.1, ccdm

#7621 CCDM: do not override tsconfig when index.ts is generated
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
  flow-tests/test-ccdm/tsconfig.json
Labels: +0.0.1, ccdm

#7625 Read proxy config from .npmrc file
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +1.0.0, target/2.2

#7631 Implement resynchronization of the client and server
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
  flow-client/src/test/java/com/vaadin/client/flow/StateTreeTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ResynchronizationView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ResynchronizationIT.java
Labels: +0.1.0

#7640 Revert "Remove polymer from default dependencies (#7558)"
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/template/AttachExistingElementByIdView.java
  flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
  flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/MaterialThemedTemplateView.java
  flow-tests/test-material-theme/src/main/java/com/vaadin/flow/uitest/ui/material/NotThemedTemplateView.java
  flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/IdTestView.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/MyButton.java
  flow-tests/test-npm-only-features/test-npm-general/src/main/java/com/vaadin/flow/testnpmonlyfeatures/general/ComponentAddedViaInitListenerView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/InjectedElementInsideMixinBehaviorView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityPanel.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/template/RouterLinksTemplate.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/NpmThemedComponentView.java
Labels: +0.0.1

#7645 Update chrome version for intern test in flow-client module
  flow-client/intern.json
  flow-client/scripts/client.js
Labels: +1.0.0, ccdm

#7642 Remove unused imports from BuildFrontendMojo
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Labels: +1.0.0

#7641 Clarify that the version number if for Flow and not Vaadin
  flow-server/src/main/java/com/vaadin/flow/server/Version.java
Labels: +0.0.1, target/1.0, target/2.1, target/2.2

#7635 Add logging for node install
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/2.2

#7654 Add logging for node install 2.2 (#7635)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, cherry pick

#7599 Removed org.apache.commons.text dependency
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.2

#7657 Removed org.apache.commons.text dependency 2.2 (#7599)
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, cherry pick

#7659 Ignore a test (which is ignored on master)
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0, ccdm

#7647 Don't block DevModeInitializer but spawn a thread where all long running tasks are executed
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/main/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformance.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRouteIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundDevModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundProdModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ViewTitleIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java
Labels: +1.0.0

#7638 Fix problem with multiple listenOns of ShortcutRegisteration
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
Labels: +1.0.0, target/2.2

#7661 Revert "Don't block DevModeInitializer but spawn a thread where all l…
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/main/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformance.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRouteIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundDevModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundProdModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ViewTitleIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java
Labels: +1.0.0

#7667 Fix unit test
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#7674 Update chromedriver and test to 80.0.3987.106 (#7602)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#7668 Implement resynchronization of the client and server
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
  flow-client/src/test/java/com/vaadin/client/flow/StateTreeTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ResynchronizationView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ResynchronizationIT.java
Labels: +0.1.0, cherry pick

#7673 prevent that MPR routes modify the hash fragment
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +0.1.0, ccdm

#7683 Avoid exposing `StateNode::fireAttachListeners` and StateNode::fireDetachListeners`
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
Labels: +1.0.0

#7682 Increase threshold for performance test
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#7692 fix typo in var name during re-refactor that causes misfunction and IOOBE
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +0.1.0, ccdm

#7672 handle forward from java view in flow client api
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.1.0, ccdm

#7662 Implement resynchronization of the client and server
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtStateTreeTest.java
  flow-client/src/test/java/com/vaadin/client/flow/StateTreeTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ResynchronizationView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ResynchronizationIT.java
Labels: +1.0.0, cherry pick

#7687 Fix problem with multiple listenOns of ShortcutRegisteration (#7638)
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
Labels: +0.0.1, cherry pick

#7690 Search for versions file using class finder instead of using classloader
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, target/2.2, target/3.0

#7383 Add registration creation shorthands
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/ReadOnlyHasValue.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/shared/GwtIncompatible.java
  flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
  flow-server/src/test/java/com/vaadin/flow/shared/RegistrationTest.java
Labels: +1.0.0, target/2.2

#7693 fix path when full location is provided
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +1.0.0, ccdm

#7675 Set theme variant and theme html attributes to the HTML tag instead of body
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
  flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/AbstractThemedTemplateIT.java
  flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateIT.java
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7698 Add registration creation shorthands (#7383)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/ReadOnlyHasValue.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCache.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/shared/GwtIncompatible.java
  flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
  flow-server/src/test/java/com/vaadin/flow/shared/RegistrationTest.java
Labels: +0.1.0, cherry pick

#7701 Remove FrontendUtils.getBowerExecutable()
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +1.0.0, ccdm

#7704 fix navigation when route ends with slash
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
Labels: +1.0.0, ccdm

#7697 Create vaadin json with defaults.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +1.0.0, bug

#7706 Added servlet parameter maxMessageSuspendTimeout
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtApplicationConnectionTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
Labels: +1.0.0, target/2.1, target/2.2

#7666 Use token file to write parameters for dev mode from maven config
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.0.1, target/2.2, target/3.0

#7710 Create vaadin json with defaults. (#7697)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, cherry pick

#7711 Create vaadin json with defaults. (#7697)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, cherry pick

#7712 Search for versions file using class finder instead of using classloader (#7690)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#7707 delay location.reload when session expires
  .gitignore
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +1.0.0, target/3.0
