Repository vaadin/flow, pull requests merged in 2020-08, with the labels that each got.

#8803 Set content type in UnsupportedBrowserHandler
  flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
Labels: +0.0.1

#8804 Overload EmailValidator to accept an empty value
  flow-data/src/main/java/com/vaadin/flow/data/validator/EmailValidator.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/EmailValidatorTest.java
Labels: +0.1.0

#8816 Use var instead of let to avoid magical JS error
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8823 Open the test page in IT before the client issue checkup occurs
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java
Labels: +0.1.0

#8808 Make a workaround for Spring boot run as jar
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/PwaRegistryTest.java
  flow-server/src/test/resources/META-INF/resources/icons/icon.png
Labels: +1.0.0

#8806 Add client-side authentication features
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +0.0.1, ccdm

#8833 Revert fix for #8729
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8819 Improve log message for skipping (p)npm install
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, target/2.3, target/2.4, target/4.0

#8836 Revert fix for #8729
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8841 Revert fix for #8729 in 4.0
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8350 chore: Add more files into .gitignore
  .gitignore
Labels: +0.0.1

#8843 Simpler CSS import for TS views and CSS @import support
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, ccdm

#8834 Fix integer overflow in Data Provider page number formula
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/4.0

#8826 Add transmission semantic for URI attribute values
  flow-client/src/main/java/com/vaadin/client/WidgetUtil.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtMultipleBindingTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPropertyElementBinderTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/ClientSelectComponent.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
Labels: +0.1.0

#8842 Fix setClassName to work as specified in javadoc
  flow-server/src/main/java/com/vaadin/flow/component/HasStyle.java
  flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java
Labels: +0.0.1, target/2.3, target/4.0

#8765 fixing error message when fails to load content of index.html (#8593)
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +1.0.0

#8810 #7911 Implement Component.isAttached().
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.1.0

#8835 fix(TypeScript): Ensure model validators are generated for fields of bean type
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +1.0.0, ccdm

#8851 Revert 'Overload EmailValidator to accept an empty value' feature
  flow-data/src/main/java/com/vaadin/flow/data/validator/EmailValidator.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/EmailValidatorTest.java
Labels: +1.0.0

#8863 Fix custom data provider impl in AbstractComponentDataViewTest
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
Labels: +0.0.1

#8850 Backend is requested for pages that don't exist
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1

#8866 fix: handle nav exception inside handleNavigation
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/UnauthenticatedException.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/UnauthenticatedExceptionHandler.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ViewThrowsException.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ViewWithServerViewButton.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/ServerSideNavigationExceptionHandlingIT.java
Labels: +0.0.1, ccdm

#8870 fix: Revert delay location.reload when session expires(#7707)
  .gitignore
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +0.0.1, ccdm

#8874 Filter type support in Data View interfaces
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/CustomInMemoryDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +1.0.0

#8875 Live reload on frontend changes
  flow-client/.eslintrc.js
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DevServerWatchDog.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-tests/test-live-reload/frontend/styles.css
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/LiveReloadView.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
Labels: +1.0.0

#8882 Add peer dependency forcing mechanism to VersionsJsonFilter (#8545)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.0.1

#8416 Improve Key interface
  flow-server/src/main/java/com/vaadin/flow/component/Key.java
Labels: +0.0.1

#8884 Remove mode verification on configuration build
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +1.0.0, target/3.1, target/4.0

#8887 Cherry pick for 3.1
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
Labels: +0.0.1, cherry pick

#8896 Only connect to devServer when it is started
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +1.0.0

#8899 Change the filter type from Void to wildcard in abstract data view test
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
Labels: target/4.0, to be cherry picked

#8900 Change the filter type from Void to wildcard in abstract data view test
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
Labels: +0.0.1, cherry pick

#8901 Update expected Chrome to 85
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +1.0.0

#8879 Update compression plugin
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#8876 Instantiate AppShell with Instantiator
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Labels: +0.0.1, ccdm

#8902 Update expected Chrome to 85 (#8901)
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#8903 Update expected Chrome to 85 (#8901)
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#8904 Update expected Chrome to 85 (#8901)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#8829 feat(TypeScript): Export endpoint superclass methods
  flow-server/src/main/java/com/vaadin/flow/server/connect/Endpoint.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/EndpointExposed.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGeneratorBaseTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/CrudEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/NonEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/NonEndpointImpl.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/PagedData.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/PersonEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/ReadOnlyEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/SuperClassMethodsTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-model-superclassmethods.PersonEndpoint.Person.ts
Labels: +1.0.0

#8917 fix(webpack): update lit-css-loader dependency
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, ccdm

#8908 Update compression plugin (#8879)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick

#8909 Update compression plugin (#8879)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick

#8910 Update compression plugin (#8879)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick

#8914 Instanticate AppShell with Instantiator (#8876)
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Labels: +0.0.1, ccdm, cherry pick
