Repository vaadin/flow, pull requests merged in 2020-06, with the labels that each got.

#8449 Throw immediately on finding AppShell annotation on non AppShell classes
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/pom.xml
Labels: +1.0.0

#8463 Use UI_NAVIGATE when invoking routing from navigate.
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
Labels: +0.0.1, bug

#8325 Removing deprecated parameter from DataNode constructor
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Labels: +0.0.1, target/2.2, target/2.3, target/3.0, target/3.1

#8470 Set z-index to all direct children of vaadin-devmode-gizmo's shadow DOM root
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1, target/2.3

#8467 Fix Javadoc typo in NavigationTargetFilter
  flow-server/src/main/java/com/vaadin/flow/server/startup/NavigationTargetFilter.java
Labels: +0.0.1, target/2.2, target/2.3, target/3.0, target/3.1

#8462 lit-element as a default runtime dependency (#8351)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +1.0.0

#8471 Quiet down logs for deployment
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
Labels: +0.0.1

#8459 Allow that user can override strategies in binder
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/test/frontend/form/FieldTests.ts
Labels: +1.0.0, ccdm

#8473 Force chokidar version to ^3.4.0 (#8432) (#8451)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/pnpmfile.js
Labels: +0.0.1, cherry pick

#8479 Add methods for filtering
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0

#8407 Update chrome driver to 83.0.4103.39
  drivers.xml
  flow-client/intern.json
Labels: +1.0.0, target/2.2, target/2.3, target/3.0, target/3.1

#8484 Updated doclink for live-reload
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1, target/2.3, to be cherry picked

#8483 Always lookup DOM elements inside the given context and not globally
  flow-client/src/main/java/com/vaadin/client/ElementUtil.java
  flow-tests/test-root-context/frontend/template-without-shadow-root-view.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootIT.java
Labels: +0.0.1

#8489 Disable devmode gizmo if production bundles but no devserver
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
Labels: +0.0.1, target/2.3, to be cherry picked

#8465 Do not use compatibility mode production frontend prefixes without compat mode
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/function/DeploymentConfigurationTest.java
  flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/NavigateToStyled.java
  flow-tests/test-mixed/src/main/java/com/vaadin/flow/mixedtest/ui/StyledDiv.java
  flow-tests/test-mixed/src/main/webapp/frontend/css/styles.css
  flow-tests/test-mixed/src/test/java/com/vaadin/flow/mixedtest/ui/NavigateToStyledIT.java
Labels: +0.0.1

#8488 fix: import custom Connect client with a relative path
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
Labels: +0.0.1, ccdm, target/3.1

#8498 8488 3.1 cherry-pick (Import custom Connect client with a relative path)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
Labels: +0.0.1

#8495 Fix typo in endpoints generator log message
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
Labels: +0.0.1

#8481 Add form status API
  drivers.xml
  flow-client/intern.json
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
Labels: +1.0.0, ccdm

#8472 Throw IAE if navigation target is not registered via Router
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
Labels: +0.0.1

#8501 Merge client-side form feature branch
  flow-client/README.md
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
  flow-client/webpack.tests.config.js
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGeneratorBaseTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJsonTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.1.0, ccdm

#8508 Merge form feature branch to master
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
Labels: +0.0.1, ccdm

#8507 Fix race condition in embedding tests
  drivers.xml
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/DefaultValueInitializationIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddedWebComponentIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/EmbeddingChromeBrowserTest.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/FactoryExporterIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/FireEventIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/PreserveOnRefreshIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/PushAnnotationIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/UpdatePropertyIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
Labels: +0.0.1, target/2.3

#8428 Fix duplicate event listeners in TemplateRenderer
  flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
Labels: +0.0.1

#8505 Usability and visual design improvements for devmode gizmo and notifications
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +1.0.0

#8509 New methods for collections
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0

#8517 Usability and visual design improvements for devmode gizmo and notifications (#8505)
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1, cherry pick

#8510 Address DX feedback for data views #8497
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0

#8519 Chunk module submodules
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/3.0, target/3.1

#8503 remove terser plugin from the default dependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/2.2, target/2.3, target/3.1

#8525 Fix a couple of tests that were failing randomly. (#7739)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1, cherry pick

#8526 Fix a couple of tests that were failing randomly. (#7739)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1, cherry pick

#8480 Throw a meaningfull exception on change property/attribute of Text
  flow-server/src/main/java/com/vaadin/flow/component/Text.java
  flow-server/src/test/java/com/vaadin/flow/component/TextTest.java
Labels: +1.0.0

#8528 Add updateItem to DataView #8499
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Item.java
Labels: +1.0.0

#8540 Retain binary compatibility for listenOn method
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
Labels: +0.1.0, target/2.3

#8539 Don't redirect in case of error in web component mode
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
Labels: +0.0.1

#8559 Add HasDataView interface
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java
Labels: +1.0.0

#8534 Support undefined size for DataCommunicator
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/SizeEstimateCallback.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/SizeEstimateQuery.java
Labels: +1.0.0

#8530 Throw an exception which provides an info about vetoed property change
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PropertyChangeDeniedException.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandlerTest.java
Labels: +0.1.0

#8563 Refactor appendvirtualchild
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
Labels: +0.0.1

#8041 Basic LitTemplate support based on LitElement for Java UIs
  flow-client/src/main/java/com/vaadin/client/LitUtils.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplate.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateDataAnalyzer.java
  flow-server/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateInitializer.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/test-root-context/frontend/lit/simple-lit-template-no-shadow-root.js
  flow-tests/test-root-context/frontend/lit/simple-lit-template-shadow-root.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitPerson.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootIT.java
Labels: +1.0.0

#8504 Always send and update innerHTML property value
  flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java
  flow-client/src/main/java/com/vaadin/client/flow/nodefeature/NodeMap.java
  flow-client/src/test/java/com/vaadin/client/flow/nodefeature/MapPropertyTest.java
  flow-client/src/test/java/com/vaadin/client/flow/nodefeature/NodeMapTest.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeMap.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeMapTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ElementInnerHtmlView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ElementInnerHtmlIT.java
Labels: +0.1.0

#8549 Adapt fix #8542 for #8541 to CCDM bootstrap (Flow.ts)
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Labels: +0.0.1, cherry pick

#8550 Protect add- methods in ListDataView from adding the duplicated items #8538
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0

#8561 Prevent NPE in Pwa handler
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Labels: +0.0.1, target/2.2, to be cherry picked

#8565 Require getDataView()
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
Labels: +1.0.0

#8545 Add peer dependency forcing mechanism to VersionsJsonFilter
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.0.1

#8527 Make repeat iterate BinderNode instances for array models
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
Labels: +1.0.0, ccdm

#8533 Add support for Unit in similar fashion to Vaadin 8
  flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
  flow-server/src/main/java/com/vaadin/flow/component/Unit.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
Labels: +1.0.0

#8529 Prevent StackOverflowError in Composite.
  flow-server/src/main/java/com/vaadin/flow/component/Composite.java
  flow-server/src/test/java/com/vaadin/flow/component/CompositeTest.java
Labels: +1.0.0

#8569 Prevent NPE in Pwa handler (#8561)
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Labels: +0.0.1

#8568 Update JavaDoc to not make promises
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
Labels: +1.0.0

#8566 Update slf4j version to resolve vulnerabilities
  pom.xml
Labels: +0.0.1

#8567 Clear thread local instances on connection lost in push handler
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
Labels: +0.0.1

#8580 Enable generating self-referencing arrays in TypeScript models
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1, ccdm

#8578 Add an AbstractLazyDataView
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
Labels: +1.0.0

#8585 Fix adding existing item
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0

#8424 Create new mixin interface HasLabel(#3241)
  flow-server/src/main/java/com/vaadin/flow/component/HasLabel.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/HasLabelTest.java
Labels: +0.1.0

#8574 Use correct javadocs for JavaScript annotation in the master btanch.
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
Labels: +0.0.1

#8590 Add client side API for listening DOM Node set for StateNode
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Labels: +0.0.1

#8581 Configure identity provider for a components through the Data View
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/IdentifierProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Item.java
Labels: +1.0.0

#8601 Remove async from client-side binder addValidator method
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
Labels: +0.0.1, ccdm

#8602 Simplify ValidationCallback return type
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/tsconfig.json
Labels: +0.0.1

#8596 Add client side API for listening DOM Node set for StateNode (#8590)
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Labels: +0.0.1

#8607 Remove flow-jrebel-plugin from flow-bom
  flow-bom/pom.xml
Labels: +0.0.1

#8598 Add impliesRequired Validator flag
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
Labels: +0.0.1, ccdm

#8584 Support Element.setPropertyBean
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
Labels: +0.1.0

#8587 Support Element.setProperty for lists and maps
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
Labels: +0.1.0

#8595 Check the issue after open the browser window.
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
Labels: +0.0.1

#8577 Avoid NPEs in WebBrowser
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java
Labels: +1.0.0

#8613 Merge feature/dataprovider to master
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/FilterUtils.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/IdentifierProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/SizeChangeEvent.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/SizeChangeListener.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Item.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +1.0.0

#8633 Make the items collection modifiable for data view listener test
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
Labels: +0.0.1

#8634 Rework AbstractListDataView::updateItem #8608
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +0.0.1

#8630 Push history when navigating to route-not-found view
  flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +1.0.0, target/2.2

#8622 Don't use preserve on refresh logic in case of the same UI
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +1.0.0

#8640 Push history when navigating to route-not-found view (#8630)
  flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +0.0.1, cherry pick

#8610 Destroy external frontend resources install process on JVM exit
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +1.0.0

#8612 Destroy external frontend resources install process on JVM exit
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1

#8626 Check whether the lifecycle state is already terminated before terminate
  flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +0.0.1

#8606 Make Registration for Component::addListener idempotent
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1

#8611 Allow Vaadin plugins to configure node download URL and version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0

#8599 Don't handle dynamic resources by the DevModeHandler
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +1.0.0

#8639 Abstract unit test for generic component-specific data views
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
Labels: +1.0.0

#8650 Allow Vaadin plugins to configure node download URL and version (#8611)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.1.0

#8657 Merge support for unknown item count to master
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
Labels: +1.0.0

#8660 Use setItems instead of setDataSource
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasItems.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
Labels: +1.0.0

#8659 Maven plugin: exposed the settings 'node.version' and 'node.download.…
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +1.0.0, target/2.3, to be cherry picked
