Repository vaadin/flow, pull requests merged in 2020-07, with the labels that each got.

#8672 Merge 2.2 to 2.3
  flow-client/src/main/java/com/vaadin/client/flow/ExecuteJavaScriptProcessor.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
  flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractStreamResourceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
Labels: +0.0.1

#8635 Add matrix support to client-side form binding
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +1.0.0, ccdm

#8671 Fix hierarchy for HasHierarchicalDataProvider
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +1.0.0

#8675 Maven plugin: exposed the settings 'node.version' and 'node.download.…
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +0.0.1

#8662 Use ItemCount instead of size and RowCount #8651
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ItemCountChangeEvent.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ItemCountChangeListener.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasLazyDataViewTest.java
Labels: +1.0.0

#8663 Rename the API for generic data view #8618
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/HasDataView.java
Labels: +1.0.0

#8674 Avoid tsconfig issue #8658 for now
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/tsconfig.json
Labels: +0.0.1, ccdm

#8678 Apply new HasDataView API for HasHierarchicalDataProviderTest
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +1.0.0

#8677 Add registration for @vaadin/form package
  flow-client/package.json
  flow-client/pom.xml
  flow-client/scripts/version.js
  flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts
  flow-client/src/main/resources/version.txt
  flow-client/src/test/frontend/form/IndexTests.ts
  flow-client/webpack.tests.config.js
Labels: +1.0.0, ccdm

#8673 fix: use default JSR-380 error messages in client-side validators
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
Labels: +1.0.0, ccdm

#8680 feat: enable effective tree shaking for @vaadin/form
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, ccdm

#8683 Clear client-side validation and visits on .reset() and .clear()
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
Labels: +0.0.1, ccdm

#8687 Move contains(T item) to ListDataView
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0

#8676 Add getItem(int index) to DataView #8652
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +1.0.0

#8682 Rename and move updateItem #8653
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +1.0.0

#8692 Fix exact item count resolving if scrolled far
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ItemCountChangeEvent.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0

#8684 fix: add client-side validation for @PastOrPresent and @FutureOrPresent
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +1.0.0, ccdm

#8690 fix: render server errors and submitting state
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
Labels: +1.0.0, ccdm

#8681 Fall back to user.dir / cwd as frontend build base directory only if it is a project directory
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +1.0.0

#8700 Update ProxyConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
Labels: +0.0.1

#8701 Fix priority order of npmrc files
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#8703 More flexible npm proxy regex
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1

#8698 Store scroll position in state when entering route not found view
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +0.0.1

#8697 Update testbench version to the one in v17
  pom.xml
Labels: +0.0.1

#8694 Add client side API for listening DOM Node set for StateNode (#8590)
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Labels: +0.0.1, cherry pick

#8685 Update vaadin-parent to 2.0.3
  pom.xml
Labels: +0.0.1

#8706 Exclude HasItems from HasItemsAndComponents so as to let the components support DataView
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasItemComponents.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasItemsAndComponents.java
Labels: +1.0.0

#8715 Make it easier to use to paged repositories for data provider data #8557
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/QueryTrace.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0

#8709 Store scroll position in state when entering route not found view (#8698)
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +0.0.1, cherry pick

#8727 Fix for #8669 - add getLocationChangeEvent() to AfterNavigationEvent
  flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
Labels: +1.0.0

#8725 When moving from one UI to another, move elements contained in body rather than those contained in wrapper
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshReAddIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshIT.java
Labels: +1.0.0

#8726 Introduce an API to data communicator for paged queries disabling
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.1.0

#8724 Check for client-side router after loading page for disabling ITs
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +1.0.0

#8731 chore: truthy check for object model value
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
Labels: +0.0.1, ccdm

#8732 Update chrome version to 84
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#8733 Update chrome version to 84
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#8734 Update chrome version to 84
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#8735 Update chrome version to 84
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, cherry pick

#8717 Added more docs for the mutation methods.
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataView.java
Labels: +0.0.1

#8737 Add LocalTime type support in Endpoints
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/datetime/DateTimeEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DateTimeConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/VaadinConnectTypeConversionEndpoints.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1, ccdm

#8742 Rename binder.reset(value) to binder.read(value)
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
Labels: +0.0.1, ccdm

#8749 Fix drivers zip hash
  drivers.xml
Labels: +0.0.1

#8747 fix: BinderNode errors property
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
Labels: +0.0.1, ccdm

#8750 Fix drivers zip hash
  drivers.xml
Labels: +0.0.1

#8751 Fix drivers zip hash
  drivers.xml
Labels: +0.0.1

#8752 Fix drivers zip hash
  drivers.xml
Labels: +0.0.1

#8754 chore: prepend _ for symbol names
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-client/tslint.json
Labels: +0.0.1, ccdm

#8755 fix: consider import when checking has annotation
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/GeneratorUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/GeneratorUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/model/NonVaadinEndpoint.java
Labels: +0.0.1, ccdm

#8739 Store webpack dev server port in tempfile named from JVM unique constant and project folder
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/pom.xml
  flow-tests/test-jetty-reload/pom.xml
  flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
  flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
Labels: +0.0.1

#8764 Store webpack dev server port in tempfile named from JVM unique constant and project folder (#8739)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/pom.xml
  flow-tests/test-jetty-reload/pom.xml
  flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
  flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
Labels: +0.0.1, cherry pick

#8777 chore: apply symbol renaming in model template
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1

#8775 fix: don't clear node if cannot handle resync msg
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
Labels: +0.0.1

#8772 Use fake iframe element to check reload result and replace on success.
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8778 chore: add in-code documentation for ts form
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
Labels: +0.0.1

#8783 fix: circular ref results in stackoverflow
  flow-server/src/main/java/com/vaadin/flow/server/connect/BeanValueTypeCheckHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
Labels: +0.0.1, ccdm

#8782 Use fake iframe element to check reload result and replace on success.
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8786 Add forgotten properties to InitParameters from Constants in 2.3
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
Labels: +0.1.0

#8792 Sanitize string before removing comments from it.
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.0.1

#8793 Avoid try-resource construction with catch for status code set
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceIT.java
Labels: +0.0.1

#8794 ListDataView: addItemAfter doesn't work with filter
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +0.0.1

#8796 fix: relax Flow client content-type check
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, ccdm

#8795 Avoid try-resource construction with catch for status code set (#8793)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExceptionInStreamResourceIT.java
Labels: +0.0.1

#8797 fix: relax Flow client content-type check (#8796)
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, cherry pick

#8798 Don't remove children immediately: make checks and then remove
  flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
  flow-server/src/test/java/com/vaadin/flow/component/HasComponentsTest.java
Labels: +0.0.1

#8799 Extend javadocs for Text and clarify not-supported API
  flow-server/src/main/java/com/vaadin/flow/component/Text.java
Labels: +0.1.0

#8788 Avoid findIndex JS Array function.
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.1.0
