Repository vaadin/flow, pull requests merged in 2020-12, with the labels that each got.

#9536 chore: removed `hasClientIssue("8236")` guard as ITs now pass
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollIT.java
Labels: +0.0.1, fusion

#9545 chore: update chrome expectation to 87 (#9445)
  drivers.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +1.0.0

#9547 fix: add waitForDevServer to offline ITs
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +1.0.0, fusion

#9548 Fix: Update Lit bundle parser regex.
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
Labels: +0.0.1, cherry pick

#9546 Fix: Update Lit bundle parser regex.
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
Labels: +0.0.1

#9550 fix: Enable lit css importing
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-themes/frontend/index.html
  flow-tests/test-themes/frontend/index.ts
  flow-tests/test-themes/frontend/typescript/hello-world-view.css
  flow-tests/test-themes/frontend/typescript/hello-world-view.ts
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9553 fix: use provided executor for frontend tools
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1

#9558 feat: Resource handling to not need plugin copying
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/theme-loader/package.json
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#9569 fix: use provided executor for frontend tools (#9553)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1, cherry pick

#9568 fix: use provided executor for frontend tools (#9553)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1

#9567 fix: use provided executor for frontend tools (#9553)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1, cherry pick

#9575 fix: file-loader name for windows execution
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#9524 Fixed flaky tests caused by gc:ed variable ui in ValidatorTestBase.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/ValidatorTestBase.java
Labels: +0.0.1

#9572 refactor: get Executor service from Lookup instead init params
  flow-server/src/main/java/com/vaadin/flow/di/Lookup.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/LookupInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#9580 fix: Add missing refreshAll method to data view
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +0.1.0, target/5.0, to be cherry picked

#9582 Cherry pick to 5.0
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +0.1.0, cherry pick

#9576 chore: Update contributing guide with setup info
  CONTRIBUTING.md
  README.md
Labels: +0.0.1

#9292 Make VaadinService.dependencyFilters unmodifiable
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1, target/2.5, target/5.0, to be cherry picked

#9577 feat: add entry for @Deferrable to Vaadin usage statistics
  flow-client/scripts/version.js
  flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts
  flow-client/src/test/frontend/DeferrableEndpointTest.ts
  flow-client/webpack.tests.config.js
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
Labels: +1.0.0, fusion

#9583 fix: encode attribute value during transfer from embedded web app
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-tests/test-embedding/test-embedding-generic/pom.xml
Labels: +0.1.0

#9588 feat: Embedded component appTheme support
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
  flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java
  flow-tests/test-embedding/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/components/vaadin-radio-button.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/components/vaadin-text-field.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/document.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/global.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/img/bg.jpg
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/theme.json
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/not-used/global.css
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyPolymerField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponentExporter.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/servlets/EmbeddedServlet.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +1.0.0

#9600 fix: Vaadin.Flow.clients.TypeScript.isActive for endpoint requests
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, fusion

#9543 feat: Enable importing CSS from node_modules
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-themes/frontend/theme/app-theme/theme.json
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9609 refactor: simplify ResourceProvider
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/main/java/com/vaadin/flow/di/ResourceProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/LookupInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/testdata/TestResourceProvider.java
Labels: +1.0.0

#9618 chore: add internal classes to access classloader and init context
  flow-server/bnd.bnd
  flow-server/src/main/java/com/vaadin/flow/internal/ApplicationClassLoaderAccess.java
  flow-server/src/main/java/com/vaadin/flow/internal/VaadinContextInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#9621 test: test was flaky in production mode
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
Labels: +1.0.0, fusion, offline

#9593 fix: loading indicator visible and isActive true while endpoint fetch
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +1.0.0, fusion

#9590 Fix: theme files can now be referenced as theme/theme-name
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +1.0.0

#9616 Fix: Generated theme.js is now named theme.generated.js
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
Labels: +0.1.0

#9626 refactor: rename the app-theme root folder from theme to themes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/theme-loader/package.json
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/components/vaadin-radio-button.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/components/vaadin-text-field.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/document.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/global.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/img/bg.jpg
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/theme.json
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/not-used/global.css
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-radio-button.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-text-field.css
  flow-tests/test-themes/frontend/themes/app-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-themes/frontend/themes/app-theme/global.css
  flow-tests/test-themes/frontend/themes/app-theme/icons/archive.png
  flow-tests/test-themes/frontend/themes/app-theme/img/bg.jpg
  flow-tests/test-themes/frontend/themes/app-theme/sub-css/sub.css
  flow-tests/test-themes/frontend/themes/app-theme/theme.json
  flow-tests/test-themes/frontend/themes/no-copy/no-copy.txt
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1, DX, theming

#9634 refactor: refine renaming and incorrect paths in ThemeIT
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9619 fix: corrected position of SW plugin
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +1.0.0, fusion, offline

#9636 fix(offline): do not depend on global connection state for isActive
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
Labels: +1.0.0, fusion, offline

#9631 chore: fix flaky tests that depends on mock count
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +0.0.1, fusion

#9629 fix(offline): do not cache CSRF token and clear on offline logout
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +1.0.0, fusion, offline

#9638 Remove deferrable feature
  flow-client/scripts/version.js
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/DeferrableEndpoint.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Offline.ts
  flow-client/src/main/resources/META-INF/resources/frontend/index.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/DeferrableEndpointTest.ts
  flow-client/src/test/frontend/OfflineTests.ts
  flow-client/webpack.tests.config.js
  flow-server/src/main/java/com/vaadin/flow/server/connect/Deferrable.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/DeferrableEndpointTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/SingleMethodDeferrableEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/deferrable/WholeClassDeferrableEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/CrudEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-SingleMethodDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/deferrable/expected-WholeClassDeferrableEndpoint.ts
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
Labels: +1.0.0, fusion

#9311 chore: create deepClean profile
  flow-tests/pom.xml
Labels: +0.0.1

#9646 test: add document.css level styles tests
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#9651 chore: improve IT stability
  flow-client/src/test/frontend/FlowTests.ts
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +1.0.0, fusion, offline

#9662 fix: expose loadingStarted and loadingFinished
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +1.0.0, fusion, offline

#9635 refactor: extract common config functionality and introduce add config
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
Labels: +1.0.0

#9604 fix(TypeScript): binder should allow typing decimal numbers
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
Labels: +0.0.1, fusion

#9674 chore: avoid race condition in test
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, fusion

#9592 feat: allow endpoints to work on non-public classes
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/packageprivate/PackagePrivateEndpoint.java
Labels: +0.0.1, fusion

#9652 fix(offline): Rewrite <base href> in service worker using sw scope
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-tests/test-ccdm-flow-navigation/frontend/index.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/main/main-view.ts
  flow-tests/test-ccdm-flow-navigation/pom-production.xml
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/SessionViewIT.java
Labels: +1.0.0, fusion

#9643 fix: serve compressed files
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
  flow-tests/test-misc/src/main/webapp/textfile.txt
  flow-tests/test-misc/src/main/webapp/textfile.txt.gz
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/CompressedResourceIT.java
Labels: +1.0.0, fusion, offline

#9649 fix(offline): simple state transitions when only Connect client is loaded
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, fusion, offline

#9657 fix: use LinkedHashSet (not HashSet) for deterministic CompositeDataGenerator
  flow-data/src/main/java/com/vaadin/flow/data/provider/CompositeDataGenerator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
Labels: +1.0.0

#9559 feat: document level npm css
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/document.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/global.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/theme.json
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#9653 chore: update ChromeDriver to 87.0.4280.88
  drivers.xml
  flow-client/intern.json
Labels: +0.0.1, target/2.4, target/2.5, target/5.0, to be cherry picked

#9686 Fix: add the missing otf font extension.
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-themes/frontend/themes/app-theme/font/IBMPlexMono-Regular.otf
  flow-tests/test-themes/frontend/themes/app-theme/global.css
Labels: +0.0.1, theming

#9673 cherry-pick 5.0
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
Labels: +0.0.1, fusion

#9672 cherry-pick 4.0
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
Labels: +0.0.1, fusion

#9697 chore: improve stability of two tests
  flow-client/src/test/frontend/FlowTests.ts
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +1.0.0, fusion

#9613 Add IT test for CSS loading order
  flow-tests/test-themes/frontend/src/css-loading-view.css
  flow-tests/test-themes/frontend/themes/app-theme/global.css
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/CssLoadingView.java
  flow-tests/test-themes/src/main/webapp/styles/page-stylesheet.css
  flow-tests/test-themes/src/main/webapp/styles/stylesheet.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
Labels: +0.0.1

#9706 refactor!: expose connectionIndicator as constant instead of via getter
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-tests/test-ccdm-flow-navigation/frontend/index.ts
Labels: +1.0.0, fusion, offline

#9642 Extract app config from deployment config
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractPropertyConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinConfigurationException.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/CustomUIClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushAtmosphereHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TestUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/LookupInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ProductionModeTimingDataViewTestServlet.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ProductionModeViewTestServlet.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
  flow-tests/test-memory-leaks/src/main/java/com/vaadin/flow/memoryleaks/ui/MemoryLeakUI.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/ItApplicationConfigurationFactory.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
  flow-tests/test-scalability/src/main/java/com/vaadin/flow/test/scalability/HelloWorldUI.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +1.0.0

#9648 Feat: enable having a parent theme
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/bg.jpg
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/child.css
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/font/IBMPlexMono-Regular.otf
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/img/gobo.png
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/img/viking.png
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/theme.json
  flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/servlets/WorkaroundServlet.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/ParentThemeView.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-radio-button.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-text-field.css
  flow-tests/test-themes/frontend/themes/app-theme/global.css
  flow-tests/test-themes/frontend/themes/app-theme/theme.json
  flow-tests/test-themes/frontend/themes/parent-theme/parent.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +1.0.0

#9710 fix: flaky unit test due to race for port numbers
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1, target/2.4, target/2.5, target/5.0, testing, to be cherry picked

#9676 fix: verify theme folder existence based on app-theme name in @Theme
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
Labels: +1.0.0, DX, theming

#9715 fix: avoid BeforeClient executions for nodes with different StateTree
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
Labels: +1.0.0

#9716 fix: @ServiceRanking is not handled by the osgi bundle generation tool
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/ItApplicationConfigurationFactory.java
Labels: +0.0.1

#9724 fix: use proper logging for installing pnpm and its directory
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/2.4, target/2.5, target/5.0, to be cherry picked

#9728 test: mark ThemeLiveReloadIT as not thread safe
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1

#9729 fix: lookup for all available Executor services instead of only one
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1

#9733 fix: offline indicator visibility
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, fusion, offline
