Repository vaadin/flow, pull requests merged in 2020-10, with the labels that each got.

#9088 fix: Rewrite fix for clearing Current instances
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
Labels: +0.0.1, target/2.4, target/4.0, to be cherry picked

#9081 Use a default page size for DataCommunicator
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/4.0, to be cherry picked

#9091 fix: Rename method name to avoid double negation
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0, data provider

#9094 feat(offline): expose isDeferred flag on MiddlewareContext
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, ccdm

#9093 fix: Fix JavaScriptBootstrapUI::getChildren
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.0.1, target/4.0, to be cherry picked

#9101 fix: IT for OSGi: add a listener for one more mapping
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PlainScriptViaJavaScriptView.java
  flow-tests/test-root-context/src/main/webapp/context/plain-script.js
Labels: +0.0.1

#9086 Do more accurate check for error messages in IT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +0.0.1, target/2.4, target/4.0, to be cherry picked

#9105 Do more accurate check for error messages in IT (#9086)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +0.0.1

#9100 fix documentation for KeyboardEvent.getCode
  flow-server/src/main/java/com/vaadin/flow/component/internal/KeyboardEvent.java
Labels: +0.0.1

#9122 fix: Set disabled status for component mapped to an Element
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-tests/test-root-context/frontend/DisabledPolymerTemplateElement.js
  flow-tests/test-root-context/frontend/lit/DisabledLitTemplateElement.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/DisabledLitTemplateElementView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/DisabledPolymerTemplateElementView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/DisabledLitTemplateElementIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/AbstractDisabledTemplateElementIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/DisabledPolymerTemplateElementIT.java
Labels: +0.0.1

#9124 refactor: allow components to fire a count change event
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.1.0, data provider

#9125 Re-implement the EventHandlerRpcHandler
  .gitignore
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/PublishedEventRpcHandlerUtil.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/PublishedServerEventHandlerRpcHandler.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/rpc/PublishedEventRpcHandlerUtilTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
Labels: +0.1.0

#8468 Make handleFileUploadValidationAndData and sendUploadResponse protected
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.1.0

#9138 Upgrade to TypeScript 4
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-ccdm/package.json
Labels: +0.0.1

#9128 feat(offline): add processDeferredCalls / onDeferredCall API to ConnectClient
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, ccdm

#9127 fix: don't check import in compilation unit for @Deferrable
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/CrudEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
Labels: +1.0.0, ccdm

#9139 refactor: revert 'allow components to fire a count change event'
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0, data provider

#9141 refactor: revert Set disabled status for component mapped to an Element (#9122)
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-tests/test-root-context/frontend/DisabledPolymerTemplateElement.js
  flow-tests/test-root-context/frontend/lit/DisabledLitTemplateElement.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/DisabledLitTemplateElementView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/DisabledPolymerTemplateElementView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/DisabledLitTemplateElementIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/AbstractDisabledTemplateElementIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/DisabledPolymerTemplateElementIT.java
Labels: +0.0.1

#9149 test: Navigation test between modes
  flow-tests/pom.xml
  flow-tests/test-ccdm-flow-navigation/frontend/index.html
  flow-tests/test-ccdm-flow-navigation/frontend/index.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.ts
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
Labels: +0.0.1

#9129 chore: Fix tests for windows execution
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-tests/pom.xml
  flow-tests/test-ccdm/package.json
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-material-theme/pom.xml
  flow-tests/test-mixed/pom-npm-production.xml
  flow-tests/test-mixed/pom-npm.xml
  flow-tests/test-mixed/pom-pnpm-production.xml
  flow-tests/test-mixed/pom.xml
  flow-tests/test-multi-war/deployment/pom.xml
  flow-tests/test-npm-only-features/test-default-theme/src/main/java/com/vaadin/flow/testonlynpmfeatures/defaulttheme/TemplateWithClientSideImports.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/MyButton.java
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-ui-context/pom.xml
Labels: +0.1.0

#9133 fix: store app shell title into UI instead of AppShellRegistry
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-ccdm/frontend/index.html
  flow-tests/test-ccdm/frontend/index.js
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/NavigateToServerSideViewWithoutTitleIT.java
Labels: +1.0.0, ccdm, target/4.0

#9156 feat!: remove deprecated AppShellRegistry.getTitle()
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Labels: +1.0.0, ccdm

#9153 fix: declare webworker lib for sw.ts with TS triple-slash directive
  flow-client/tsconfig.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/main/resources/sw.ts
  flow-server/src/main/resources/tsconfig.json
Labels: +1.0.0, ccdm

#9066 Fix docs typo
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
Labels: +0.0.1, target/2.4, to be cherry picked

#9154 feat: add support for Range header to StaticFileServer
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
Labels: +1.0.0, target/2.4

#9176 chore!: bump httpclient to 4.5.13
  flow-server/pom.xml
Labels: +0.0.1, target/2.4, target/4.0, to be cherry picked

#9168 feat!: don't support disabled for lit id elements
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/IllegalAttributeException.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializer.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
  flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
Labels: +0.0.1

#9171 Make LitTemplateParserImpl public. Fixes #9169
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParser.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitClassesSerializableTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
Labels: +0.0.1

#9179 fix: include import CSSResult in generated types.d.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-tests/test-ccdm/frontend/css-importing-test.ts
  flow-tests/test-ccdm/frontend/empty.css
Labels: +0.0.1, fusion

#9190 fix: update development plugins
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/2.4, target/2.5, target/4.0

#9180 Simplify check for recursive getContent() in Composite
  flow-server/src/main/java/com/vaadin/flow/component/Composite.java
Labels: +0.0.1

#9172 fix: only register endpoint request handler when endpoint presents
  flow-server/src/main/java/com/vaadin/flow/internal/InternalConstants.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
Labels: +0.1.0, fusion

#9161 fix(TypeScript): client-side form binder validation errors because of value having unused deep optional fields
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
Labels: +0.0.1, fusion

#9195 fix: Support .ts files in parsers
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-lit-template/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-polymer-template/src/test/resources/META-INF/VAADIN/config/stats.json
Labels: +0.0.1

#9197 fix: Use ArrayList while creating ListDataProvider from items array
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +1.0.0, target/4.0, to be cherry picked

#9201 Revert "fix: only register endpoint request handler when endpoint pre…
  flow-server/src/main/java/com/vaadin/flow/internal/InternalConstants.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
Labels: +1.0.0, fusion

#9208 fix: register endpoint controller only when there are endpoints
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
Labels: +0.1.0, fusion

#9198 feat: disposable filter setup API in data communicator
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.1.0

#9210 Merge master into feature/offline
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/IllegalAttributeException.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializer.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/LitTemplateParser.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitClassesSerializableTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-lit-template/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-polymer-template/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/component/Composite.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-tests/test-ccdm/frontend/css-importing-test.ts
  flow-tests/test-ccdm/frontend/empty.css
  flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
Labels: +0.1.0, fusion

#9183 fix: implement navigation fallback
  flow-server/src/main/resources/sw.ts
Labels: +1.0.0

#9148 Update README with branch versions
  README.md
Labels: +0.0.1

#9221 chore: Update chrome to 86
  drivers.xml
  flow-client/intern.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, target/2.4, target/2.5, target/4.0

#9204 fix: add maven plugin documentation
  flow-maven-plugin/README.md
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
Labels: +0.0.1

#9233 test: Fix duplicate registration
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Labels: +0.0.1, target/2.4, target/2.5, target/4.0

#9238 test: Fix duplicate registration (#9233)
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Labels: +0.0.1, cherry pick

#9226 fix: use relative path reference to index.html (`.` instead of `/`)
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +1.0.0, fusion

#9181 fix(offline): support offlinePath from PWA annotation
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/sw.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
  flow-tests/test-pwa/src/main/webapp/offline.html
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +1.0.0, fusion

#9254 refactor: Remove log usage in embedded components
  flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
Labels: +0.0.1

#9257 refactor: expose the items count API to components
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.1.0

#9200 feat: offline stub for server-side views
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/OfflineStub.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/OfflineServerViewIT.java
Labels: +1.0.0, fusion

#9253 fix: make field with @Id nullable in TypeScript
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/SchemaGenerator.java
  flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/ExplicitNullableTypeCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +1.0.0, fusion

#9262 refactor: Make httpclient dependency optional for OSGi
  flow-server/bnd.bnd
Labels: +1.0.0, OSGi

#9244 feat: defer deferrable endpoint calls on network failure
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +1.0.0, fusion

#9265 fix: Add content type to dev-mode-not-ready response (#9095)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#9266 chore: unit test for devmode-not-ready page contents and type
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#9261 Add test for navigation fallback
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-tests/test-ccdm-flow-navigation/frontend/index.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/another/another-view.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/main/main-view.ts
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/AppShell.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/OfflineServerViewIT.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +1.0.0

#9258 fix(offline): resolve offlineResources at runtime
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-tests/test-pwa/pom.xml
  flow-tests/test-pwa/public/yes.png
  flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +1.0.0, fusion
