Repository vaadin/flow, pull requests merged in 2020-04, with the labels that each got.

#7909 Don't stub npm as pnpm should be installed
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +0.0.1, target/2.2

#7910 Revert: "Revert 'delay location.reload (#7707)' (#7789)"
  .gitignore
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +0.0.1, ccdm

#7946 link to documentation when PWA annotation is misplaced
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +0.1.0, ccdm

#7949 Upgrade byte buddy dependency
  pom.xml
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7944 generator uses custom endpoint name instead of using connect-client.d…
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateConnect.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateConnectTest.java
Labels: +1.0.0, ccdm

#7945 Switch pnpm to be default for 3.1
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-tests/pom.xml
Labels: +0.1.0

#7950 remove flowResourcesFolder parameter in FlowModeAbstractMojo
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +1.0.0, ccdm

#7974 Revert "Accept setting DataProvider of subclasses (#6617) (#7652)"
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasFilterableDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasFilterableDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/WildcardDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +0.0.1

#7969 Do not create buildFolder in dev mode
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/2.2

#7957 Add vaadin-devmode-gizmo element with live-reload functionality
  flow-client/package.json
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/LiveReload.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Labels: +1.0.0

#7916 Run (p)npm install and webpack dev server in a separate thread
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerStopTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/main/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformance.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BackButtonServerRoundTripIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BaseHrefIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DynamicallyRegisteredRouteIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundDevModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteNotFoundProdModeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterParallelIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ViewTitleIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PushIT.java
Labels: +1.0.0

#7976 Live-reload sends a heartbeat to keep the dedicated push channel alive
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
Labels: +0.0.1

#7979 Run npm install if only .staging
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7989 Remove compatibilty mode files.
  flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
  flow-maven-plugin/src/main/resources/gulpfile.js
  flow-maven-plugin/src/main/resources/package.json
  flow-maven-plugin/src/main/resources/yarn.lock
Labels: +0.0.1

#7986 2.1 cherry pick PR
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, cherry pick

#7983 Run npm install if only .staging
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, cherry pick

#7988 Cherry-picks for 3.0
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
  flow-maven-plugin/src/main/resources/gulpfile.js
  flow-maven-plugin/src/main/resources/package.json
  flow-maven-plugin/src/main/resources/yarn.lock
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/FrontendVaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectEndpointsValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/FrontendVaadinServletTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectEndpointsValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletContainerInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassFinder.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/JsInjectedDiv.java
Labels: +1.0.0

#7997 Temporary disable ITs to speed up client developing
  flow-server/pom.xml
  flow-tests/pom.xml
Labels: +0.0.1, ccdm

#7975 Show flow loading indicator when requesting server routes and endpoints
  flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, ccdm

#7952 Make a workaround for skinnywar/Wildfly (#7904)
  flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ConnectEndpointsValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ConnectEndpointsValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletContainerInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassFinder.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#7993 Disable development mode gizmo for exported webcomponents
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Labels: +0.1.0

#7998 Revert "Accept setting DataProvider of subclasses (#6617) (#7652)"
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasFilterableDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasFilterableDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/WildcardDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +0.0.1

#7990 IllegalStateException when running a Vaadin Spring project on WebLogic server #502
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +1.0.0

#8003 Fix compile error in DevModeInitializerTest
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.1.0

#8002 Update lumo and material styles for v16
  flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
  flow-theme-integrations/material/src/main/java/com/vaadin/flow/theme/material/Material.java
Labels: +0.0.1

#8005 Close websocket connection when disabling live reload
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Labels: +0.0.1

#8013 Do not throw for @ParentLayout w/o RouterLayout
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
Labels: +0.0.1

#8012 Do not throw for @ParentLayout w/o RouterLayout
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
Labels: +0.0.1

#8011 Add tests for package cleaning
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.1.0, target/2.2, target/3.0

#8019 Revert "Set direction along with the Locale for the UI (#7294)"
  flow-server/src/main/java/com/vaadin/flow/component/Direction.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1, target/2.1, target/2.2, target/3.1

#8016 [Security Fix]Use Vaadin's own ObjectMapper instead of the one from Spring
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.1.0, ccdm

#8023 7975 8016 3.0 cherry-pick
  flow-client/src/main/java/com/vaadin/client/LoadingIndicator.java
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.1.0, ccdm

#8015 Identify live reload backend technology on the server and show in browser
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-jrebel-plugin/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadImplTest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Labels: +1.0.0

#8024 Add UI.setDirection API
  flow-server/src/main/java/com/vaadin/flow/component/Direction.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/i18n/LocaleChangeEvent.java
  flow-server/src/test/java/com/vaadin/flow/component/LocationObserverTest.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DirectionChangeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DirectionChangeIT.java
Labels: +1.0.0

#8030 Disable live reload
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-tests/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
  pom.xml
Labels: +1.0.0

#8042 Increase Chrome version
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#8044 Increase Chrome version
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#8057 Style dev mode waiting page
  flow-server/src/main/resources/com/vaadin/flow/server/dev-mode-not-ready.html
Labels: +0.0.1

#8056 Add more data to stats.json
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/2.2, target/3.0, target/3.1

#8045 Remove devmode widget inclusion from TS
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
Labels: +0.0.1

#8069 Add stats.json content validation
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/StatsContentTest.java
Labels: +0.0.1

#8068 Style and beautify Live Reload (#7835)
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Labels: +0.0.1

#8051 inherit the default behaviour of spring for internal object mapper
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/BeanWithPrivateFields.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/MixedRestAndEndpointApplication.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/MyRestController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/VaadinConnectEndpoints.java
Labels: +1.0.0, ccdm

#8091 3.1 cherry pick
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/BeanWithPrivateFields.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/MixedRestAndEndpointApplication.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/MyRestController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/VaadinConnectEndpoints.java
Labels: +1.0.0

#8070 Show alert when using @PreserveOnRefresh together with live reload
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.d.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/PreserveOnRefreshLiveReloadView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/PreserveOnRefreshLiveReloadIT.java
Labels: +0.0.1

#8080 Devmode gizmo: Do not use href target "#" to avoid topscroll and redirect
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.1.0

#8095 Fix endpoint serialization problems
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/BeanWithJacksonAnnotation.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/VaadinConnectEndpoints.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ArrayConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BeanConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BooleanConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ByteConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/CharacterConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/CollectionConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DateTimeConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DoubleConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/EnumConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/FloatConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/IntegerConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/LongConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/MapConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ShortConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/StringConversionTest.java
Labels: +0.0.1, ccdm

#8093 3.0 cherry pick
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/BeanWithJacksonAnnotation.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/BeanWithPrivateFields.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/MixedRestAndEndpointApplication.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/MyRestController.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/rest/VaadinConnectEndpoints.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ArrayConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BeanConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BooleanConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ByteConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/CharacterConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/CollectionConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DateTimeConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/DoubleConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/EnumConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/FloatConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/IntegerConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/LongConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/MapConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/ShortConversionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/StringConversionTest.java
Labels: +1.0.0

#8099 Explicitly set the direction of the devmode gizmo to LTR
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8110 Be aware of skinny war workaround in OSGi support
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
Labels: +0.0.1

#8116 Live reload: Theme update and improved notification system
  flow-client/.eslintrc.js
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/PreserveOnRefreshLiveReloadIT.java
Labels: +0.0.1

#8111 Be aware of skinny war workaround in OSGi support
  flow-osgi/pom.xml
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-tests/servlet-containers/felix-jetty/pom.xml
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  pom.xml
Labels: +0.0.1

#8117 Fix vfs resource test
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, target/3.0, target/3.1

#8123 Manage flow-jrebel-plugin version under flow-bom
  flow-bom/pom.xml
Labels: +0.0.1

#8124 Remove Constraint in favor of Validator
  flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
Labels: +0.1.0, ccdm

#8128 Return back code which has been accidentally removed.
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.1.0

#8008 Adding FormValidator library for client forms
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/FormValidator.ts
  flow-client/src/test/frontend/FormValidatorTests.ts
  flow-client/webpack.tests.config.js
Labels: +0.1.0, ccdm

#8134 Disable new Push tests in OSGI
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushRouteNotFoundIT.java
Labels: +0.0.1

#8130 Disable new Push tests in OSGI
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RedirectToPushIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCloseConnectionIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
Labels: +0.0.1

#8143 Tuned live-reload gizmo (from @juuso-vaadin)
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
Labels: +0.0.1

#8137 generate form models
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGeneratorBaseTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
Labels: +0.1.0, ccdm

#8152 Export Required class
  flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
  flow-client/src/test/frontend/FormValidatorTests.ts
Labels: +0.1.0, ccdm

#8154 AnyModel does not exist, use ObjectModel instead
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
Labels: +0.1.0, ccdm

#8159 Generate Validations for Models
  flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/FormValidator.ts
  flow-client/src/test/frontend/FormValidatorTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
Labels: +0.1.0, ccdm

#8158 Remove PWA install prompt feature (#8038)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/resources/com/vaadin/flow/server/default-pwa-prompt.html
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
Labels: +1.0.0

#8167 Deprecate enableInstallPrompt() method (#8038)
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
Labels: +0.1.0

#8151 Update ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: +0.0.1

#8160 Accept user versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/main/resources/pnpmfile.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
  flow-server/src/test/resources/versions/no_vaadin_package.json
  flow-server/src/test/resources/versions/package.json
  flow-server/src/test/resources/versions/user_package.json
  flow-server/src/test/resources/versions/user_versions.json
  flow-server/src/test/resources/versions/versions.json
Labels: +0.0.1, target/2.2, target/3.0, target/3.1

#8180 Adding a separated flag for client-routing
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
Labels: +1.0.0, ccdm

#8179 Change PWA javadocs to reflect phase out of Install Prompt
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
Labels: +0.0.1

#8190 Support live reload on gitpod.io
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.js
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-client/webpack.tests.config.js
Labels: +1.0.0

#8181 Add createEmptyValue to Models to simplify instantiation
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/Binder.ts
  flow-client/src/test/frontend/BinderTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
Labels: +0.1.0, ccdm

#8211 fix ts compilation because of unused imports
  flow-client/src/main/resources/META-INF/resources/frontend/FormValidator.ts
  flow-client/src/test/frontend/FormValidatorTests.ts
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
Labels: +0.1.0

#8207 Remove duplicate plugin execution
  flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Labels: +0.0.1, target/3.0, target/3.1

#8216 fix ts error when there is nothing used in an import
  flow-server/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
Labels: +1.0.0, ccdm
