Repository vaadin/flow, pull requests merged in 2020-03, with the labels that each got.

#7691 fix: add router-ignore attribute to Anchor with StreamResource
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
Labels: +1.0.0, ccdm, target/3.0

#7720 chore: re-factor webpack watchdog code.
  flow-server/src/main/resources/webpack.generated.js
Labels: +1.0.0, ccdm

#7728 Make session expired test stable (#7699)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1

#7718 Added servlet parameter maxMessageSuspendTimeout (#7706)
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtApplicationConnectionTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
Labels: +0.1.0, cherry pick

#7733 Cheery pick 7720
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, ccdm

#7731 delay location.reload when session expires (#7707)
  .gitignore
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +0.0.1, ccdm

#7729 Make session expired test stable (#7699)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1

#7732 7673, 7692, 7693 3.0 cherry pick
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +0.1.0, ccdm

#7730 7691 3.0 cherry pick
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
Labels: +0.0.1, ccdm

#7713 Search for versions file using class finder instead of using classloader
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#7717 Added servlet parameter maxMessageSuspendTimeout (#7706)
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtApplicationConnectionTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
Labels: +0.1.0, cherry pick

#7716 Added servlet parameter maxMessageSuspendTimeout (#7706)
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtApplicationConnectionTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
Labels: +0.1.0, cherry pick

#7739 Fix a test which is failing randomly.
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +1.0.0, ccdm

#7735 make stronger checking about have forwardTo in server-views to preven…
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
Labels: +1.0.0, ccdm

#7726 Reset system message provider before running any test
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1

#7709 Fix the dependency of DevModeInitializer on ServletRegistration
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +1.0.0

#7719 handle forward between server-side views and also update url
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SetParameterForwardToIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
Labels: +1.0.0, ccdm

#7614 Fix exported webcomponents in client-side
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/resources/InvalidStats.json
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/src/test/resources/MissFormatStats.json
  flow-server/src/test/resources/ValidStats.json
  flow-tests/test-embedding/pom.xml
  flow-tests/test-multi-war/pom.xml
Labels: +1.0.0, ccdm, target/3.0

#7748 7614 3.0 cherry-pick
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/resources/InvalidStats.json
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-server/src/test/resources/MissFormatStats.json
  flow-server/src/test/resources/ValidStats.json
  flow-tests/test-embedding/pom.xml
  flow-tests/test-multi-war/pom.xml
Labels: +1.0.0, ccdm

#7749 7739 3.0 cherry-pick
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InternalErrorIT.java
Labels: +0.0.1, ccdm

#7747 be more specific when modifying the hash fragment rpc
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +1.0.0, ccdm, target/3.0

#7750 7747 3.0 cherry-pick
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +0.0.1, ccdm

#7715 Set theme variant and theme html attributes to the HTML tag instead of
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
  flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateIT.java
Labels: +0.0.1

#7714 Set theme variant and theme html attributes to the HTML tag instead of body
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-tests/test-lumo-theme/src/main/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateView.java
  flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/AbstractThemedTemplateIT.java
  flow-tests/test-lumo-theme/src/test/java/com/vaadin/flow/uitest/ui/lumo/ExplicitLumoTemplateIT.java
Labels: +0.0.1

#7695 Update formatter plugin
  pom.xml
Labels: +1.0.0, target/2.1, target/2.2, target/3.0

#7734 Revert "Remove FrontendUtils.getBowerExecutable() (#7701)"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.1.0, ccdm

#7743 Cherry Pick: Fix the dependency of DevModeInitializer on ServletRegistration (#7709)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +1.0.0, cherry pick

#7751 Fix DevModeInitializerTest.onStartup_emptyServletRegistrations_shouldCreateDevModeHandler
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, cherry picked

#7737 Do not run endpoints csrf check when disable-xsrf-protection flag is set
  flow-server/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  flow-server/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionIT.java
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +1.0.0, ccdm, target/3.1

#7769 fix webpack problem in os windows because of path separator
  flow-server/src/main/resources/webpack.generated.js
Labels: +1.0.0, ccdm, target/3.0

#7772 7769 3.0 cherry-pick
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, ccdm

#7777 Update dev dependency versions.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/3.0

#7778 Move push tests category to test util module, exclude Push tests
  flow-test-util/src/main/java/com/vaadin/flow/testcategory/PushTests.java
  flow-tests/pom.xml
Labels: +0.0.1

#7779 Update dev dependency versions. (#7777)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#7789 Revert "delay location.reload when session expires (#7707)"
  .gitignore
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +0.0.1, ccdm

#7787 Remove some leftovers from "frontend" protocol removal change.
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DragSource.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/DropTarget.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/FrontendVaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/FrontendVaadinServletTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/JsInjectedDiv.java
Labels: +1.0.0, target/3.0

#7795 Revert "delay location.reload when session expires (#7707) (#7731)"
  .gitignore
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +0.0.1

#7796 Correct push with preserve on refresh test.
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushWithPreserveOnRefreshIT.java
Labels: +1.0.0, target/3.0

#7788 Change default 100vw to 100% body size settings.
  flow-server/src/main/java/com/vaadin/flow/component/page/BodySize.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.1.0, target/2.2, target/3.0

#7802 Add API (with further possibility to make SPI) to communicate via refresh channel
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadAccessTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadImplTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#7803 Backport disable audit for npm
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#7807 Change default 100vw to 100% body size settings. (#7788)
  flow-server/src/main/java/com/vaadin/flow/component/page/BodySize.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1, cherry pick

#7808 Change default 100vw to 100% body size settings. (#7788)
  flow-server/src/main/java/com/vaadin/flow/component/page/BodySize.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1, cherry pick

#7815 Accept only major version String in FrontendVersion CTOR
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7812 Use absolute URI for require JS
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/PushWithRequireJSUI.java
Labels: +0.0.1

#7780 Cherry pick for dev dep versions update (#7768)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#7652 Accept setting DataProvider of subclasses (#6617)
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasFilterableDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasFilterableDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/WildcardDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +0.0.1

#7816 Accept only major version String in FrontendVersion CTOR (#7815)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.0.1

#7817 Accept only major version String in FrontendVersion CTOR (#7815)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.0.1

#7818 Accept only major version String in FrontendVersion CTOR (#7815)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.0.1

#7810 LiveReload JRebel integration.
  flow-jrebel-plugin/pom.xml
  flow-jrebel-plugin/src/main/java/com/vaadin/flow/server/jrebel/JRebelInitializer.java
  flow-jrebel-plugin/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-jrebel-plugin/src/test/java/com/vaadin/flow/server/jrebel/JRebelInitializerTest.java
  pom.xml
Labels: +0.0.1, DX, enhancement

#7797 Move generic element helpers out from PolymerUtils
  flow-client/src/main/java/com/vaadin/client/ElementUtil.java
  flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
  flow-tests/test-root-context/frontend/template-without-shadow-root-view.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootIT.java
Labels: +0.0.1

#7809 Added internal methods for updating routes when classes are added / modified / deleted
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
Labels: +0.1.0

#7824 Don't store optimize bundle in dev mode in the token file.
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +0.0.1

#7842 Removed dead code (pre 3)
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
Labels: +1.0.0

#7853 Upgrade the Jetty Maven Plugin version
  pom.xml
Labels: +0.0.1

#7765 let TS generator detect custom endpoint name
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java
  flow-server/src/test/resources/java/CustomEndpoint.java
  flow-server/src/test/resources/java/EndpointNoValue.java
Labels: +1.0.0, ccdm

#7827 revert removing the "router-ignore" attribute on setHref() and remove…
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +1.0.0, ccdm

#7849 Extract frontend executable functionality to a separate contextual class.
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#7857 Don't catch Exception
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +1.0.0

#7828 Add a unit test for #5411
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1

#7839 Do not spam console with misleading test exceptions
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ViewOrUITest.java
Labels: +0.0.1

#7860 Maintain one AtmosphereResource per live-reload connection in BrowserLiveReload
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadImpl.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadImplTest.java
Labels: +0.1.0

#7865 7827-3.0-cherry-pick
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.0.1, ccdm

#7866 7765-3.0-cherry-pick
  flow-server/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateOpenApiTest.java
  flow-server/src/test/resources/java/CustomEndpoint.java
  flow-server/src/test/resources/java/EndpointNoValue.java
Labels: +0.0.1, ccdm

#7864 adding checking for "target/flow-frontend" in BundleParser to get the…
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
Labels: +0.0.1, ccdm

#7867 7864-3.0-cherry-pick
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/stats.json
Labels: +0.0.1, ccdm

#7852 Output commands using logger with debug level only
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +1.0.0

#7829 Add Live Reload overlay to the client
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/LiveReload.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/StorageUtil.java
  flow-client/src/main/resources/com/vaadin/ClientEngineXSI.gwt.xml
  flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ViewOrUITest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ExceptionStacktraceIT.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ScriptInjectIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
Labels: +0.0.1

#7879 Disable failing test because of #7878.
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/ReconnectLongPollingIT.java
Labels: +0.0.1

#7869 Always cleanup before generating files
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, target/2.2

#7880 Clean up temp file if not used.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7863 Install pnpm into vaadin home folder
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#7872 Let user know when application is deployed
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Labels: +0.1.0

#7873 Fix regression in progress plugin after upgrading webpack version
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, ccdm

#7892 Always cleanup before generating files 3.0 (#7869)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, cherry pick

#7889 Clean up temp file if not used. 3.0 (#7880)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Labels: +0.0.1, cherry pick

#7893 Always cleanup before generating files 2.2 (#7869)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, cherry pick

#7890 Clean up temp file if not used. 2.2 (#7880)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Labels: +0.0.1, cherry pick

#7891 Clean up temp file if not used. 2.1 (#7880)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Labels: +0.0.1, cherry pick

#7895 7873 3.0 cherry-pick
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, ccdm

#7887 Do not crash if JRebel is not on classpath
  flow-jrebel-plugin/src/main/java/com/vaadin/flow/server/jrebel/JRebelClassEventListener.java
  flow-jrebel-plugin/src/main/java/com/vaadin/flow/server/jrebel/JRebelInitializer.java
  flow-jrebel-plugin/src/test/java/com/vaadin/flow/server/jrebel/JRebelInitializerTest.java
Labels: +1.0.0

#7898 Let user know when application is deployed (#7872)
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Labels: +0.1.0

#7886 Added toggle for live-reload on a per-window basis
  flow-client/src/main/java/com/vaadin/client/LiveReload.java
  flow-client/src/main/java/com/vaadin/client/StorageUtil.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Labels: +1.0.0

#7843 update vaadin-parent-2.0.2
  pom.xml
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7894 Install pnpm into vaadin home folder (#7863)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#7882 Collect all error lines
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1, target/2.1

#7846 Compare frontend locations to vfs patterns first
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +1.0.0

#7905 CP: Update vaadin-parent-2.0.2 (#7843)
  pom.xml
Labels: +0.0.1, cherry pick

#7906 CP: Update vaadin-parent-2.0.2 (#7843)
  pom.xml
Labels: +0.0.1, cherry pick

#7907 CP: Update vaadin-parent-2.0.2 (#7843)
  pom.xml
Labels: +0.0.1

#7912 Collect all error lines 2.1 (#7882)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1, cherry pick

#7913 CP: Compare frontend locations to vfs patterns first (#7846)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, cherry pick

#7838 Apply push setting after navigation
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RedirectToPushView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RedirectToPushIT.java
Labels: +1.0.0

#7914 CP: Compare frontend locations to vfs patterns first (#7846)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, cherry pick

#7917 Add stats for pnpm usage
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +1.0.0

#7915 CP: Compare frontend locations to vfs patterns first (#7846)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, cherry pick

#7825 CP: Accept setting DataProvider of subclasses (#6617) (#7652)
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasFilterableDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ListDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/HasFilterableDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/WildcardDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/DataSerializableTest.java
Labels: +0.0.1, cherry pick

#7870 Validate Route and ParentLayout annotations presence at the same time
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
Labels: +1.0.0

#7669 Reload the page on ESC
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
Labels: +0.0.1

#7921 Disable live reload on the client side temporary
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Labels: +0.0.1

#7884 Add liveReload.enabled config parameter to enable/disable Live Reload
  flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/LiveReload.java
  flow-client/src/main/java/com/vaadin/client/bootstrap/Bootstrapper.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadAccessTest.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  flow-tests/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DevModeConfigView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DevModeConfigIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
  pom.xml
Labels: +0.1.0

#7904 Make a workaround for skinnywar/Wildfly
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletContainerInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassFinder.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#7951 Lock terser version to 4.6.7
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/2.1, target/2.2, target/3.0

#7956 Lock terser version to 4.6.7 (#7951)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#7908 Show a notification in the UI after live reload happened (#7820)
  flow-client/src/main/java/com/vaadin/client/LiveReload.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/LiveReloadIT.java
Labels: +1.0.0
