Repository vaadin/flow, pull requests merged in 2021-08, with the labels that each got.

#11505 chore: update ChromeDriver to 92
  drivers.xml
  flow-client/intern.json
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11482 fix: don't override web.xml, annotation config with classpath flow-build-info.json settings
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.0.1

#11507 fix: add JSR305 to the generated Karaf feature
  flow-server/pom.xml
Labels: +0.0.1

#11511 chore: update chrome driver to 92 (2.6)
  drivers.xml
Labels: +0.0.1

#11512 chore: update chromedriver to 92 (2.7)
  drivers.xml
Labels: +0.0.1

#11420 feat: implement ability to add Fusion-only npm packages
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUseFusionPackage.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/EndpointGeneratorTaskFactoryImpl.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/TaskUseFusionPackageImpl.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/frontend/NodeTasksEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: +0.1.0, fusion

#11520 fix: Prevent deadlock in findOrCreateVaadinSession
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +1.0.0, cherry pick

#11516 fix: Use byte[] instead of String to store stats.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/2.6, target/7.0, target/2.7, target/8.0

#11521 chore!: deperecate PageConfigurator since it has broken design
  flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/PageConfigurator.java
Labels: +0.1.0, target/2.6

#11527 fix: update workbox version to prevent webpack failure
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +1.0.0

#11529 fix: Use byte[] instead of String to store stats.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/2.6

#11531 fix: update workbox version to prevent webpack failure (#11527)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#11532 fix: update workbox version to prevent webpack failure (#11527)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#11522 refactor: add a new parser for TypeScript types in Fusion Generator
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/GeneratorUtils.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/MainGenerator.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/typescript/CodeGenerator.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/typescript/CodeGeneratorUtils.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/typescript/ModelGenerator.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/typescript/TypeParser.java
  fusion-endpoint/src/main/resources/com/vaadin/fusion/generator/EntityModelTemplate.mustache
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/complextypes/ComplexTypeEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/complextypes/ComplexTypeEndpointTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/tsmodel/TsFormEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/typescript/TypeParserTest.java
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/complextypes/expected-ComplexTypeEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/complextypes/expected-model-complextypes.ComplexTypeEndpoint.ComplexTypeModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: fusion, +0.0.1

#11517 fix: Fail-fast if the path to npm cache contains whitespaces
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.1.0, target/2.7

#11538 fix: set Vaadin session attribute using lock
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Labels: +0.0.1, target/2.6, target/7.0, target/2.7, target/8.0

#11540 fix: Correct comment in webpack config file (#10475)
  flow-server/src/main/resources/webpack.config.js
Labels: +0.0.1

#11471 fix: register data provider listener only if it has not been registered
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/2.6, target/7.0, target/2.7, target/8.0

#11548 fix: clean up the old listeners of data provider
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, cherry pick, target/2.6

#11299 fix!: use Double Cookie Submission for Fusion CSRF protection
  client/packages/client-fusion/src/Connect.ts
  client/packages/client-fusion/test/Connect.test.ts
  flow-client/src/main/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/SessionView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/SessionViewIT.java
  flow-tests/test-ccdm/frontend/index.html
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/TestApplicationServiceInitListener.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/CsrfCookieIT.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfChecker.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfIndexHtmlRequestListener.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/startup/CsrfServiceInitListener.java
  fusion-endpoint/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/auth/CsrfIndexHtmlRequestListenerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/auth/FusionAccessCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/startup/CsrfServiceInitListenerTest.java
Labels: fusion, +1.0.0

#11562 fix: only copy javascript files.
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/2.6

#11539 fix: Fail-fast if the path to npm cache contains whitespaces (CP: 2.7)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.1.0, cherry pick

#11563 fix: clean up managed default versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1, target/2.6

#11549 feat: implement ability to add Fusion-only npm packages (#11420)
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFusion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateOpenAPI.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUseFusionPackage.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/EndpointGeneratorTaskFactoryImpl.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/TaskGenerateFusionImpl.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/TaskGenerateOpenAPIImpl.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/frontend/TaskUseFusionPackageImpl.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/frontend/NodeTasksEndpointTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/frontend/TaskGenerateFusionTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/frontend/TaskGenerateOpenAPITest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: fusion, +1.0.0

#11568 fix: clean up managed default versions (#11563)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1, cherry pick

#11566 feat(TypeScript): add Frontend path alias (#9898) (CP: 2.7)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Labels: +0.0.1, cherry pick

#11552 fix: do not serve UI for invalid location
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
Labels: +0.1.0, target/2.7, target/8.0

#11570 fix: set the lock field to a fake lock for unbound session
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
Labels: +0.0.1, target/8.0

#11577 Update to JSoup 1.14.2
  pom.xml
Labels: +0.0.1

#11565 fix: don't fire shortcut event if ancestor of component is not visible
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
Labels: +0.0.1, target/2.6, target/7.0, target/2.7, target/8.0

#11579 fix: generate model fields in the same order as in Java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/SchemaGenerator.java
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/collectionendpoint/expected-model-collectionendpoint.CollectionEndpoint.Collection.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-core.Version.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-inheritedmodel.InheritedModelEndpoint.ChildModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.ArraySchema.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Discriminator.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Schema.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.XML.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-models.ExternalDocumentation.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-core.Version.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.Role.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.User.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-openapi-custom-application-properties.json
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-openapi.json
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-model.ModelEndpoint.Account.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-model.ModelEndpoint.Group.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-subpackage.ModelFromDifferentPackage.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-model-modelpackage.ModelPackageEndpoint.Account.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-model-subpackage.Account.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.NonNullableModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-model-subpackage.SameClassNameModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/selfreference/expected-model-selfreference.SelfReference.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: fusion, +0.0.1

#11585 fix: blacklist npm versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/2.6

#11567 fix: pin platform trans. deps with npm CP: #10864
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +1.0.0

#11586 fix: Remove old data provider listener on component attach
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1

#11588 fix: fix build issue with npm 7.20.3+
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/2.6

#11592 fix: explain deprecation of PageConfigurator [skip-ci]
  flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/PageConfigurator.java
Labels: +0.0.1, target/2.6

#11593 chore(client): fix CI issues
  client/lerna.json
  client/package.json
  client/packages/client-common/package.json
  client/packages/client-fusion/package.json
Labels: fusion, +1.0.0

#11597 chore(client): include package-lock.json
  client/.gitignore
  client/package-lock.json
  client/web-test-runner.config.js
Labels: fusion, +0.0.1

#11598 fix: filter vaadin-core from versions pinning (CP: #11027) (#11037)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Labels: +0.0.1

#11596 fix: Remove old data provider listener on component attach (CP: 8.0)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, cherry pick, target/7.0

#11553 fix: don't bootstrap UI for invalid location
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java
Labels: +0.0.1, target/7.0, target/8.0

#11589 refactor!: move renderer package to flow-components
  flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentDataGenerator.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/BasicRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/ClickableRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/ComponentRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/IconRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/LocalDateRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/LocalDateTimeRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/NativeButtonRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/NumberRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/Renderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/Rendering.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/TemplateRenderer.java
  flow-data/src/main/java/com/vaadin/flow/data/renderer/TextRenderer.java
  flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
  flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
  flow-data/src/test/java/com/vaadin/flow/data/renderer/ComponentRendererTest.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/IconRendererTest.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/NativeButtonRendererTest.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/NumberRendererTest.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/RendererUtilTest.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/TemplateRendererTest.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/TextRendererTest.java
Labels: +1.0.0

#11601 feat: Implement Component.isAttached(). (#8810)
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.1.0, cherry pick

#11610 chore: change usage of deprecated TextNote constructor
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
Labels: +0.0.1, target/1.0, target/2.6, target/7.0, target/8.0

#11595 chore: Updated flow-components repo in issue template
  .github/ISSUE_TEMPLATE.md
Labels: +0.0.1

#11605 Use latest Node (16.7.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#11607 fix: upgrade to lit 2.0.0-rc.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, target/2.6, target/7.0, target/2.7, target/8.0

#11503 documentation: Add missing throws in JavaDocs [skip ci]
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
Labels: +1.0.0

#11631 Revert "fix: remove href attribute for disabled Anchor (#11121)" (#11…
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.1.0

#11632 Revert "fix: remove href attribute for disabled Anchor (#11121)" (#11…
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.1.0

#11638 Always allow the client placeholder view to be loaded
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
Labels: +0.1.0, target/8.0

#11672 fix: not fail for missing window.Vaadin.Flow (CP: 7.0)
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1, cherry pick

#11627 fix: add mkdirp as default devDependency
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/stats-plugin/package.json
Labels: +0.0.1

#11634 refactor(flow-server): bump construct-style-sheets-polyfill version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: fusion, +0.0.1

#11642 Do not copy transfer encoding from the webpack dev server
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
Labels: +0.0.1, target/2.6, target/7.0, target/2.7, target/8.0

#11625 fix: return ServletConfig during servlet destroy invocation
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
Labels: +0.0.1, target/7.0, target/8.0

#11678 fix: Do not use Flow namespace for information not related to Flow
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/7.0, target/8.0

#11671 fix: bump webpack version in client package.json
  flow-client/package.json
Labels: +0.0.1, target/7.0, target/8.0

#11648 feat: Support Pageable, Page and UUID in endpoints
  fusion-endpoint/pom.xml
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/EndpointTransferMapper.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/OrderDTO.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/PageMapper.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/PageableDTO.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/PageableMapper.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/SortDTO.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/SortMapper.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/UUIDMapper.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/OpenAPIObjectGenerator.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/SchemaGenerator.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/endpointransfermapper/EndpointTransferMapperTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/AbstractEndpointGenerationTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/mappedtype/MappedTypeEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/mappedtype/MappedTypeEndpointTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/pageendpoint/PageEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/pageendpoint/PageEndpointGenerationTest.java
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/mappedtype/expected-MappedTypeEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/pageendpoint/expected-PageEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/pageendpoint/expected-model-pageendpoint.PageEndpoint.Foo.ts
Labels: fusion, +0.0.1

#11689 chore: update 8.0 release info in readme [skip ci]
  README.md
Labels: +0.0.1
