Repository vaadin/flow, pull requests merged in 2021-03, with the labels that each got.

#10150 Do not emit errors for unused variables/imports/parameters
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Labels: +0.0.1

#10134 chore: security helper with list of should-be-public urls
  flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Labels: +1.0.0, fusion

#10075 Clarify warning comment for setEnabled
  flow-server/src/main/java/com/vaadin/flow/component/HasEnabled.java
Labels: +0.0.1

#10157 Use time-constant comparison for CSRF tokens in endpoint
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
Labels: +0.0.1, fusion, target/5.0, target/6.0

#10156 Actually create 'export' bundle only when there are exported web components
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, fusion

#10162 10109 remove only added routes
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/di/OneTimeInitializerPredicate.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#10170 feat: Embedded component appTheme support (#9588)
  .gitignore
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/WebComponentModulesGenerator.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
  flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java
  flow-tests/test-embedding/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/components/vaadin-radio-button.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/components/vaadin-text-field.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/document.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/global.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/img/bg.jpg
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/embedded-theme/theme.json
  flow-tests/test-embedding/test-embedding-application-theme/frontend/theme/not-used/global.css
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyPolymerField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponentExporter.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/servlets/EmbeddedServlet.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +1.0.0

#10176 fix: don't clean registry on every new routes set (#10162)
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/di/OneTimeInitializerPredicate.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#10186 chore: make LookupInitializer::instantiate method protected
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
Labels: +0.1.0, target/6.0

#10111 Do not return array methods from body.$ when looking for elements
  flow-client/src/main/java/com/vaadin/client/ElementUtil.java
  flow-tests/test-root-context/frontend/lit/simple-lit-template-shadow-root.js
  flow-tests/test-root-context/frontend/template-without-shadow-root-view.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/PolymerTemplateWithoutShadowRootIT.java
Labels: +0.0.1

#10184 test: add wait before fetching the scroll position
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +0.0.1

#10161 chore: lint TS using ESLint
  flow-client/.eslintrc.js
  flow-client/.prettierrc.js
  flow-client/package.json
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionIndicator.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/OfflineStub.ts
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Binder.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Field.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validation.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/tslint.json
Labels: +1.0.0, fusion

#10181 feat: Improved theme support not allowed in compatibility mode
  flow-server/src/main/java/com/vaadin/flow/theme/ThemeUtil.java
  flow-server/src/test/java/com/vaadin/flow/theme/ThemeUtilTest.java
Labels: +0.0.1

#9699 feat: use superclass of VadinServlet/Request if possible
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletRequest.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletResponse.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/FaviconHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/CustomVaadinServiceImplementationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
Labels: +1.0.0, waiting for author

#10191 fix: offline path should be relative to current path not root
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/OfflineWithCustomContextIT.java
  flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/AppShell.java
  flow-tests/test-router-custom-context/src/main/webapp/offline.html
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/AbstractContextIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/PwaTestIT.java
Labels: +0.0.1, fusion, target/6.0

#10194 fix: set default PWA start_url as "." instead of ""
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/PwaConfigurationTest.java
Labels: +0.1.0, fusion, target/6.0

#10205 chore: swap name of 2 offline IT tests
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/OfflineWithCustomContextIT.java
Labels: +0.0.1, fusion, target/6.0

#10209 test: add wait before getting scroll position (#10184)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrokenRouterLinkIT.java
Labels: +0.0.1

#10218 chore: automatic end-of-line for prettier
  flow-client/.prettierrc.js
Labels: +0.0.1, fusion

#10224 chore: Activate LogoutWithNotificationServlet for OSGi environment
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1, target/6.0

#10226 Custom theme parent theme feature
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/bg.jpg
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/child.css
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/font/IBMPlexMono-Regular.otf
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/img/gobo.png
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/img/viking.png
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/theme.json
  flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/servlets/WorkaroundServlet.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/ParentThemeView.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-radio-button.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-text-field.css
  flow-tests/test-themes/frontend/themes/app-theme/global.css
  flow-tests/test-themes/frontend/themes/app-theme/theme.json
  flow-tests/test-themes/frontend/themes/parent-theme/parent.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#10239 Revert "feat: global CSS loader (#10036)"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.global.css
  flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.ts
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/CssLoaderIT.java
Labels: +0.0.1, fusion

#10229 refactor: use StaticFileHandler as a service
  flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandlerFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0, target/6.0

#10250 refactor: use StaticFileHandler as a service (#10229)
  flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandlerFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#10244 perf: Cache stats.json loaded from class path
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +1.0.0, target/2.4, target/2.5, target/2.6, target/5.0, target/6.0

#10254 fix: Revert "Execute error handling as a last action in message handler"
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationServlet.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
Labels: +0.1.0, target/5.0, target/6.0

#10257 fix: do not interpret a bean implementing Iterable as a collection
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/SchemaResolverTest.java
Labels: +0.0.1, fusion

#10264 fix: fix shortcuts when listenOn is a dialog
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutsTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.1.0, target/2.5, target/2.6, target/6.0

#10261 fix: avoid exposing ServletContext resources via StaticFileServer
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServletContextResourceIT.java
Labels: +0.1.0

#10263 chore: delete pnpm-lock.yaml
  flow-client/pnpm-lock.yaml
Labels: +0.0.1, fusion

#10269 fix: avoid exposing ServletContext resources via StaticFileServer (#10261)
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServletContextResourceIT.java
Labels: +0.1.0

#10262 Write generated theme file to the generated folder
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
Labels: +0.0.1, target/6.0

#10268 fix: avoid exposing ServletContext resources via StaticFileServer
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ServletContextResourceIT.java
Labels: +0.1.0

#10273 test: add forgotten unit test
  flow-server/src/test/java/com/vaadin/flow/server/OSGiStaticFileServerTest.java
Labels: +0.1.0, target/2.4, target/2.5

#10275 fix: fix shortcuts when listenOn is a dialog (#10264)
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutsTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.1.0

#10274 fix: fix shortcuts when listenOn is a dialog (#10264)
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutsTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +1.0.0

#10287 test: disable flaky test
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10285 chore: FrameworkUtil class presence doesn't mean OSGi
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
Labels: +0.0.1, target/2.4, target/2.5

#10280 fix: close InputStream in FrontendUtils
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/2.4, target/2.5, target/2.6, target/5.0, target/6.0

#10293 fix: FrameworkUtil class presence doesn't mean OSGi (#10285)
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
Labels: +0.0.1

#10294 fix: FrameworkUtil class presence doesn't mean OSGi (#10285)
  flow-server/src/main/java/com/vaadin/flow/server/osgi/OSGiAccess.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/EnableOSGiRunner.java
Labels: +0.0.1

#10267 test: enable logging for TaskRunNpmInstall tests
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, fusion

#10299 test: disable flaky test
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1, target/5.0

#10301 test: Disable DevModeHandlerTest flaky test
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#10259 fix: Revert "Execute error handling as a last action in message handler" (#10254) (CP: 5.0)
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtMessageHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationServlet.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
Labels: +0.0.1, cherry pick

#10308 chore: update chromium drivers
  drivers.xml
  flow-client/intern.json
Labels: +0.0.1, target/2.4, target/2.5, target/2.6, target/5.0, target/6.0

#10314 test: Disable LogoutIT flaky test
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +0.0.1, target/6.0

#10303 perf: Cache stats.json loaded from class path
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0, cherry pick, target/2.5

#10322 chore: update cromium drivers
  drivers.xml
Labels: +0.0.1, target/2.4, target/2.5

#10144 fix: only use the export chunk for exported web components if it is found
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/resources/META-INF/VAADIN/config/stats_no_export.json
Labels: +0.0.1, fusion

#10316 fix: keep theme generated files from removing by endpoints generator
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/stalefiles/NewEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/stalefiles/StaleFilesTest.java
Labels: +0.0.1, fusion, target/6.0

#10315 fix: close InputStream properly in FrontendUtils
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, cherry pick, target/2.5, target/2.6

#10336 test: Disable LogoutIT flaky test
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +0.0.1, target/2.5, target/2.6, target/5.0

#10332 chore: disable flaky test
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#10349 chore: remove contributing docs
  CONTRIBUTING.md
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10334 fix: move fusion-endpoint dependency
  flow-plugins/flow-maven-plugin/pom.xml
  flow-plugins/flow-plugin-base/pom.xml
Labels: +0.0.1

#10145 fix: only inject scripts not already loaded when using an exported wc
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Labels: +0.0.1, fusion

#10356 fix: avoid access to arbitrary resource via parent
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/osgi/VaadinBundleTracker.java
Labels: +1.0.0

#10330 perf: Cache stats.json loaded from class path (#10303)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +1.0.0, cherry pick

#10354 feat: Allow spaces in addClassNames arguments array
  flow-server/src/main/java/com/vaadin/flow/component/HasStyle.java
  flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java
Labels: +1.0.0

#10358 fix: No deploy wihout lookup
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Labels: +0.0.1

#10370 chore: fix ITs behavior inside OSGi
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/OSGiMarker.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/OSGiMarkerImpl.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/routing/PushLayout.java
Labels: +0.0.1

#10380 chore: Add missing import and header
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/OSGiMarkerImpl.java
Labels: +0.0.1

#10333 fix: Add reflections input filter
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
Labels: +0.0.1

#10361 chore: skip service worker plugin for non PWAs
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1, fusion, target/6.0

#10385 fix: Add API to control whether Binder converts back to presentation (CP: #10343) (6.0)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.1.0

#10359 chore: refactor flaky test
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.0.1

#10374 chore: removed hasClientIssue(8236) guard
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
Labels: +0.0.1, fusion, target/6.0

#10387 fix: Prevent NPE when writing field value to bean
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1, target/6.0

#10389 chore: enable SessionCloseLogoutIT
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutIT.java
Labels: +0.0.1, target/6.0

#10376 chore: removed some hasUnknownClientIssue() guard
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/dependencies/DynamicDependencyIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/webcomponent/PaperSliderIT.java
Labels: +0.0.1, fusion, target/6.0

#10404 chore: use setLocation instead of JS to stop application properly
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SessionCloseLogoutView.java
Labels: +0.0.1, target/2.5

#10406 chore: Increase startup time threshold
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#10407 chore: Increase startup time threshold
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#10403 chore: fix DialogShortcutIT initialization
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.0.1, cherry-picked-2.5, cherry-picked-2.6, target/6.0

#10388 fix: Make shortcuts not break writing on inputs
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DialogShortcutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10399 CP: Binder Changes to 2.6
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.1.0

#10398 test: Remove the test because it relies on Webpack startup time
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1, target/6.0

#10382 Add explicit return type
  flow-client/src/main/resources/META-INF/resources/frontend/form/BinderNode.ts
Labels: +0.0.1

#10386 fix: do not serve appshell/offline page for cached resource
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +0.0.1, fusion, target/6.0

#10422 chore: fix javadoc in binder for other converter methods
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1

#10418 add customized install and deploy plugins for gradle created jars
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +1.0.0, gradle

#10417 fix: remember original state after LOADING (#10099)
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, cherry pick, fusion

#10427 Keep modules light
  flow-client/pom.xml
  flow-data/pom.xml
  flow-dnd/pom.xml
  flow-html-components/pom.xml
  flow-lit-template/pom.xml
  flow-plugins/flow-maven-plugin/pom.xml
  flow-polymer-template/pom.xml
  flow-push/pom.xml
  flow-server/pom.xml
  fusion-endpoint/pom.xml
  pom.xml
Labels: +1.0.0

#10430 dont run dev deps.
  pom.xml
Labels: +1.0.0

#10435 fix: Jar package, gradle build
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +1.0.0

#10436 fix: Simplifiy sw.js polling
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
Labels: +0.0.1

#10439 set deploy-file config url by using altDeploymentRepository cmdline arg
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +1.0.0, gradle

#10433 test: Enable LogoutIT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10443 chore: Disable flaky test in MigrationTest
  flow-migration/src/test/java/com/vaadin/flow/migration/MigrationTest.java
Labels: +0.0.1, target/2.5

#10360 feat: render custom offline page in app shell
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/OfflineStub.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +0.1.0, fusion, target/6.0

#10456 fix: do lazy initialization in a thread-safe way
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10444 Do not use the request charset when reading a file from the classpath
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/InitialPageSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/InlineTargets.java
Labels: +1.0.0

#10459 test: replace hasClientIssue with @Ignore for test which fails in fusion
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
Labels: +0.0.1, target/6.0

#10461 fix: do lazy initialization in a thread-safe way (#10456)
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
Labels: +0.0.1, target/2.5

#10457 test: enable PushRouteNotFoundIT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/PushRouteNotFoundIT.java
Labels: +0.0.1, target/6.0

#10462 test: ignore FragmentLinkIT instead of using hasClientIssue
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/FragmentLinkIT.java
Labels: +0.0.1, target/6.0

#10463 test: enable RefreshCloseConnectionIT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCloseConnectionIT.java
Labels: +0.0.1, target/6.0

#10464 test: ignore RouterSessionExpirationIT instead of using hasClientIssue
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterSessionExpirationIT.java
Labels: +0.0.1, target/6.0

#10471 test: disable HistoryIT because of fusion issue 82113
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
Labels: +0.0.1, target/6.0

#10475 fix: Correct comment in webpack config file
  flow-server/src/main/resources/webpack.config.js
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10454 cherry pick #10360 to 6.0
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/main/resources/META-INF/resources/frontend/OfflineStub.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +0.1.0, fusion

#10478 test: remove hasClientUnknownIssue call and enable CountUIsIT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CountUIsIT.java
Labels: +0.0.1, target/6.0

#10465 Do not format parts that break tests
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/json/JsonTestEndpoint.java
Labels: +0.0.1

#10437 feat: add endpoint request checker util
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/EndpointUtilTest.java
Labels: +0.0.1

#10428 fix: Remove images and icons from public URL list
  flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
Labels: +0.0.1

#10237 Use latest typescript
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#10278 Add file link to generated model
  fusion-endpoint/src/main/resources/com/vaadin/flow/server/connect/generator/EntityModelTemplate.mustache
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1

#10486 test: refactor test to extract failing parts and disable them
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
Labels: +0.0.1, target/6.0

#10490 chore: disable flaky theme component test
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#10494 test: disable flaky CountUIsIT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CountUIsIT.java
Labels: +0.0.1, target/6.0

#10434 feat: allow creation of Text and Element from nullable text content
  flow-server/src/main/java/com/vaadin/flow/component/Text.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/test/java/com/vaadin/flow/component/TextTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +0.0.1, target/2.6

#10492 test: disable CustomScrollCallbacksIT failing with fusion
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/CustomScrollCallbacksIT.java
Labels: +0.0.1, target/6.0

#10480 test: remove hasUnknownClientIssue and enable JavaScriptReturnValueIT
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/JavaScriptReturnValueIT.java
Labels: +0.0.1, target/6.0

#10483 test: disable page its because of fusion issue instead hasClientIssue
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
Labels: +0.0.1, target/6.0

#10507 fix: use warn instead of trace for WC exporters discovering
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentExporterUtils.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10514 test: disable failing part in NavigationTriggerIT instead hasClientIssue
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
Labels: +0.0.1, target/6.0

#10524 fix: avoid NPE in WebBrowser methods
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
Labels: +0.0.1, target/2.5

#10523 fix: allow spaces between html function call and back tick
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10522 test: remove hasClientIssue and hasUnknownClientIssue TB methods
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
Labels: +0.0.1, target/6.0
