Repository vaadin/flow, pull requests merged in 2021-11, with the labels that each got.

#12202 fix: Use correct configuration in FeatureFlags
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Labels: +0.0.1

#12199 chore: Update bnd to latest in 3.x series
  pom.xml
Labels: +0.0.1

#12189 chore: Upgrade to latest Node 16
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1

#12210 test: Fix Vite test
  flow-tests/test-frontend/vite-basics/pom.xml
Labels: +0.0.1, vite

#12003 fix: Limit the requested pages to a given threshold
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/1.0, target/2.7, target/8.0

#12176 chore: Remove obsolete comment and assert in Binder
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1

#12207 Revert "feat: use array of values for @Route instead of only one (#11…
  flow-server/src/main/java/com/vaadin/flow/router/Route.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteAliasObject.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EndPointData.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouteConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockVaadinContext.java
  flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
Labels: +0.0.1

#12209 test: Add feature test to validate enabling feature.
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/FeatureView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/FeatureIT.java
Labels: +0.0.1, vite

#12206 test: Fix most 'scanned from multiple locations' warnings
  flow-tests/test-frontend/vite-basics/pom.xml
Labels: +0.0.1, vite

#12208 fix: Split Vite configuration into a generated part and a customizable part
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
  flow-server/src/main/resources/vite.config.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
Labels: +0.0.1, vite

#12197 fix: Hide example feature again
  flow-server/src/main/java/com/vaadin/experimental/Feature.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevModeGizmoElement.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/DebugWindowFeatureFlagsIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +0.0.1, vite

#12214 refactor: Create webpack and vite instances the same way
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerStopTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Labels: +0.0.1, vite

#12187 chore: simplify web components generation avoiding reflective call
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java
Labels: +0.0.1, target/2.7, target/8.0

#12233 chore: extract URI encoding to a helper
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
Labels: +0.0.1, vite

#12234 chore: Upgrade Vite to 2.7.0-beta.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite

#12231 fix: Only log RouteNotFoundError if debugging is enabled
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
Labels: +0.0.1

#12230 feat: add vite watchdog
  flow-server/src/main/resources/vite.generated.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Labels: +0.0.1, vite

#12215 chore: Fix formatting issues in pom.xml files
  flow-jandex/pom.xml
  flow-plugins/flow-plugin-base/pom.xml
  flow-plugins/pom.xml
  flow-polymer-template/pom.xml
  flow-tests/pom.xml
  flow-tests/servlet-containers/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-jetty-reload/pom.xml
  flow-tests/test-no-theme/pom.xml
  flow-tests/test-theme-no-polymer/pom.xml
  flow-tests/test-themes/pom.xml
  flow-tests/test-v14-bootstrap/pom.xml
  fusion-endpoint/pom.xml
  pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#12190 chore: No longer log that standard bootstrap is used
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
Labels: +0.0.1

#12216 chore: Mute sonar issues as this is no performance problem
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Labels: +0.0.1

#12235 chore: Close input stream after using it
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
Labels: +0.0.1, target/2.7, target/8.0

#12241 Fix compilation for missing import.
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Labels: +0.0.1

#12225 fix: Use encoded path for dev server
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Labels: +0.0.1, vite

#12174 chore: Log debug info using debug level
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
Labels: fusion, +0.0.1

#12191 chore: do not try to enforce javadoc in endpoint classes
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/typescript/CodeGenerator.java
Labels: fusion, +0.0.1

#12192 chore: log file writing debug info using debug level
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/ClientAPIGenerator.java
Labels: fusion, +0.0.1

#12201 chore: rename template from .ts.template to .template.ts
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/ClientAPIGenerator.java
  fusion-endpoint/src/main/resources/connect-client.default.template.ts
Labels: fusion, +0.0.1, vite

#12211 test: try to make test more stable by letting the server choose the port
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
Labels: +0.0.1, vite

#12249 chore: Update testbench version
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevModeGizmoElement.java
  pom.xml
Labels: +0.0.1, target/8.0

#12257 chore: update testbench version
  pom.xml
Labels: +0.0.1

#12258 Revert "chore(deps): bump formatter-maven-plugin from 2.16.0 to 2.17.0"
  pom.xml
Labels: +0.0.1

#12254 chore: Remove unused imports
  flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
  flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ServerSideForwardView.java
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/ServerSidePostponeView.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestLayout.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/PreserveOnRefreshExporter.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
  flow-tests/test-embedding/test-embedding-theme-variant/src/test/java/com/vaadin/flow/webcomponent/ThemedVariantComponentIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/MiscelaneousView.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/NpmThemedComponentIT.java
  flow-tests/test-multi-war/test-war1/src/main/java/com/vaadin/flow/multiwar/war1/MainView.java
  flow-tests/test-multi-war/test-war2/src/main/java/com/vaadin/flow/multiwar/war2/MainView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateNoShadowRootView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/SimpleLitTemplateShadowRootView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DirectionChangeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/IFrameIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
  flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/DependencyLayout.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#12019 fix: set style property priority using proper API method
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StylePriorityView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StylePriorityIT.java
Labels: +0.0.1, target/2.7, target/8.0

#12267 Revert "refactor: Use maven vaadin plugin classloader as a parent for URLClassloader in ClassFinder (#12050) (#12171)"
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/AnnotationValuesExtractorTest.java
  flow-migration/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
Labels: +0.0.1

#12270 fix: Auto-update Node for alternative directory
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1

#12238 fix: Limit the requested pages to a given threshold (#12003)(CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, cherry pick, target/1.0

#12266 test: Simplify test and use valid URLs
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Labels: +0.0.1, vite

#12271 fix: Changed copied server info to format "header: value" to be easier to read
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
Labels: +0.0.1

#12275 fix: Limit the requested pages to a given threshold (#12238)(CP: 1.0)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, cherry pick

#12272 chore: Move dev server connection checking to super class
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
Labels: +0.0.1, vite

#12273 chrore: Update byte-buddy for better Java 17 compatibility
  pom.xml
Labels: +0.0.1

#12256 refactor: Integrate dev server static resource serving with StaticFileServer
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Labels: +0.0.1, vite

#12282 chore: Make prettier configuration available for all modules and format JS/TS files
  .prettierrc.js
  flow-client/src/main/frontend/FlowBootstrap.js
  flow-client/src/test/frontend/FlowTests.ts
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector-es6.js
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-server/src/main/resources/com/vaadin/flow/component/page/windowResizeListener.js
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-server/src/main/resources/plugins/build-status-plugin/build-status-plugin.js
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
  flow-server/src/main/resources/pnpmfile.js
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/main/resources/webpack.config.js
  flow-server/src/main/resources/webpack.generated.js
  flow-test-util/src/main/resources/dnd-simulation.js
Labels: +0.0.1, vite

#12291 fix: Make URLUtil.encodeURI behave like encodeURI in JavaScript and add encodeURIComponent
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
Labels: +0.0.1

#12263 refactor!: Remove StaticFileHandler.isStaticResourceRequest
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/InvalidLocationIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.0.1, vite

#12293 refactor: write response error without possibility for an exception
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerTest.java
Labels: fusion, +0.0.1

#12296 Revert "chore: update testbench version (#12257)"
  pom.xml
Labels: +0.0.1

#12297 test: Stop using deprecated Mockito API
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationRegistryTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Labels: +0.0.1

#12286 fix: Do not force Vite to use a single chunk
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, vite

#12228 fix: ensure Flow client container is pre-attached on navigation
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
Labels: fusion, +0.0.1

#12304 fix: Clean Vite production output folder on build
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1, vite

#12181 fix: Clear changed bindings after initing field values
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/2.7, target/8.0

#12299 test: Delete unused file
  flow-server/src/test/java/com/vaadin/tests/server/component/AbstractListenerMethodsTestBase.java
Labels: +0.0.1

#12289 chore: Fix enforcer deprecation
  pom.xml
Labels: +0.0.1

#12305 chore: upgrade to Vite 2.7.0-beta.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite

#12290 test: replace usage of deprecated Matchers with ArgumentMatchers
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentConfigurationRegistryTest.java
Labels: +0.0.1

#12311 test: Remove generated files
  flow-tests/test-frontend/vite-production/vite.config.ts
  flow-tests/test-frontend/vite-production/vite.generated.ts
Labels: +0.0.1, vite

#12302 fix: Use Vite's mergeConfig to merge values instead of overwriting
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, vite

#12278 refactor: Remove usage of manifest.json and method for checking if dev server can serve a request
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
Labels: +0.0.1, vite

#12313 Revert "fix: Clean Vite production output folder on build"
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1

#12303 fix: Only transform the main index.html entrypoint in Vite
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, vite

#12314 test: Ensure theme images work with Vite
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
  flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
Labels: +0.0.1, vite

#12317 fix: Ensure that side effects of readBean do not set hasChanges true (#12181)(CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, cherry pick

#12319 fix: Ensure that side effects of readBean do not set hasChanges true (#12181)(CP: 8.0)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#12318 refactor: minimize stats.json for V14 bootstrap mode
  flow-server/src/main/resources/plugins/stats-plugin/package.json
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
  flow-server/src/main/resources/plugins/webpack-plugins.json
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/StatsContentTest.java
Labels: +0.0.1

#12325 chore: upgrade gradle 7.3
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
Labels: +0.0.1

#12321 fix: Log dev server output using standard logger
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Labels: +0.0.1, vite

#12326 test: Stop using Mockito API removed in next major
  flow-client/src/test/java/com/vaadin/client/flow/StateTreeTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Labels: +0.0.1

#12308 feat: Compress Vite output by default in production
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-production/pom.xml
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/CompressionIT.java
Labels: +0.0.1, vite

#12259 feat: support vite in v14 bootstrap
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: embedding flow, +1.0.0, vite

#12292 chore: Maven and Gradle plugins should not be OSGi bundles
  flow-plugins/flow-plugin-base/pom.xml
  flow-plugins/pom.xml
Labels: +0.0.1

#12329 fix: Vite fallback chunk
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-tests/test-frontend/vite-production/frontend/templates/LitComponent.ts
  flow-tests/test-frontend/vite-production/frontend/templates/PolymerComponent.ts
  flow-tests/test-frontend/vite-test-assets/src/main/java/com/vaadin/viteapp/views/template/ReflectivelyReferencedComponent.java
  flow-tests/test-frontend/vite-test-assets/src/main/java/com/vaadin/viteapp/views/template/TemplateView.java
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/templates/LitComponent.ts
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/templates/PolymerComponent.ts
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/templates/ReflectivelyReferencedComponent.ts
  flow-tests/test-frontend/vite-test-assets/src/test/java/com/vaadin/viteapp/TemplateIT.java
Labels: +0.0.1, vite

#12183 fix: Avoid processing value change event due writing back of converted value
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +1.0.0, target/2.7, target/8.0

#12337 fix: Remove disused plugins from package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#12327 feat: Enable serving Brotli resources by default
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
Labels: +0.0.1

#12338 fix: Avoid processing value change event due writing back of converted value (#12183) (CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#12340 fix: Avoid processing value change event due writing back of converted value (#12183) (CP: 8.0)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#12348 chore: update testbench to 7.0.3
  pom.xml
Labels: +0.0.1

#12352 fix: Use correct URL for generated/vaadin.ts
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#12331 chore: clean up code and make Sonar happier
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Labels: +0.0.1

#12357 chore: update commons-compress to 1.21
  flow-server/pom.xml
Labels: +0.0.1, target/8.0

#12361 chore: update Testbench to 7.0.3
  pom.xml
Labels: +0.0.1

#12359 feat: Update to Vite 2.7.0-beta.5
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite

#12341 refactor: Move CSRF checking from AccessChecker to FusionController
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionControllerConfiguration.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfChecker.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/FusionAccessChecker.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/EndpointUtilTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerConfigurationTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerMockBuilder.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/ServletContextTestSetup.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/auth/CsrfCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/auth/FusionAccessCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/generator/endpoints/AbstractEndpointGenerationTest.java
Labels: fusion, +0.0.1

#12353 fix: Make webpack work with Node 17
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Labels: +0.1.0, target/2.7, target/8.0

#12371 fix: Make webpack work with Node 17.1+
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
Labels: +0.1.0

#12372 fix: Make webpack work with Node 17.1+
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.1.0

#12344 feat: Add typescript checker plugin
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, vite

#12373 fix: Write generated index.ts to frontend/generated
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/GenerationOutputDirectory.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/frontend/NodeTasksEndpointTest.java
Labels: +0.0.1, vite

#12375 fix: update URL if Vite reload happens during navigation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vite-devmode.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/GenerationOutputDirectory.java
Labels: +0.1.0

#12386 test: Make more stable on CI
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Labels: +0.0.1

#12374 chore: Split message to two lines to be readable
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1, target/8.0

#12334 feat: add support for @EventData of type Component
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBusUtil.java
  flow-server/src/main/java/com/vaadin/flow/dom/DomEvent.java
  flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
  flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithComponentData.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithRouterLinkData.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedToDomEventWithElementData.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java
  flow-tests/test-root-context/reference-screenshots/.gitkeep
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractEventDataView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComponentEventDataView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/EventTargetView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AbstractEventDataIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComponentEventDataIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/EventTargetIT.java
Labels: +1.0.0

#12391 fix: Update supported browser versions to those that support globalThis
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.0.1, target/8.0

#12382 fix: Make Vite serve the index page only when using the exact URL of it
  flow-server/src/main/resources/vite.generated.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
Labels: +1.0.0

#12394 Upgrade to vite 2.7.0 beta7
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite

#12398 chore: Remove unnecessary build-tool
  build-tools/.dtrackignore
  build-tools/pom.xml
  build-tools/src/test/java/com/vaadin/LicenseCheckTest.java
  pom.xml
Labels: +0.0.1

#12390 fix: Restrict which files Vite publishes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
Labels: +0.0.1, vite

#12410 chore: stabilize vite dev-mode ITs
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeReloadIT.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ViteDevModeIT.java
Labels: +0.0.1

#12401 Replace forums with Stack Overflow in Contributing file
  CONTRIBUTING.md
Labels: +0.0.1, target/2.7, target/8.0

#12414 test: Simplify test
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeReloadIT.java
Labels: +0.0.1

#12416 chore: Fix AfterNavigationEvent JavaDoc
  flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
Labels: +0.0.1, target/2.7, target/8.0

#12409 feat: add HeartbeatListener to UI
  flow-server/src/main/java/com/vaadin/flow/component/HeartbeatEvent.java
  flow-server/src/main/java/com/vaadin/flow/component/HeartbeatListener.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/HeartbeatHandlerTest.java
Labels: +1.0.0

#12417 chore: Upgrade to Vite 2.7.0-beta.8
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/9.0

#12415 fix: Inject theme rules only once when using Vite
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
Labels: +0.0.1, vite, target/9.0

#12406 fix: Do not use --ignore-existing which is only available in npm 6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1

#12408 fix: Prevent Vite from reloading if live reload has been turned off
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vite-devmode.ts
Labels: +0.0.1, vite

#12437 fix: Do not fail SpringBootTests if a Lookup instance is not available
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfChecker.java
Labels: +0.0.1, target/9.0

#12438 fix: fix the mobile-dnd polyfill versions
  flow-dnd/pom.xml
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
Labels: +0.0.1, target/8.0, target/9.0

#12363 feat: enable pwa for vite
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateServicWorkerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: pwa, +0.0.1, vite

#12445 chore: reflect that builderFolder was renamed frontendBundleFolder in PWA config
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#12447 chore: fix formatting issues
  flow-data/src/test/java/com/vaadin/flow/data/provider/ReplaceListDataProvider.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/ReplaceListDataProviderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/RangeValidatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/RegexpValidatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/StringLengthValidatorTest.java
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/LabelTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/PropertyFilterTest.java
  flow-server/src/main/java/com/vaadin/flow/router/PageTitle.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
  flow-server/src/test/java/com/vaadin/flow/component/HasStyleTest.java
  flow-server/src/test/java/com/vaadin/flow/component/InvalidMappedToDomEvent.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedDomEventWithComponentData.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/StyleUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/CaseUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/ConstantPoolTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/CustomElementNameValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonSerializerTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/RangeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsGetFieldValueByTypeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsGetPrimitiveFieldValueTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/AbstractMapFeatureTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/PollConfigurationMapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/EnumDecoderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/StringToNumberDecoderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/util/SharedUtilTests.java
  flow-server/src/test/java/com/vaadin/flow/shared/util/UniqueSerializableTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevModeGizmoElement.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/FusionControllerMockBuilder.java
Labels: +0.0.1

#12448 chore: update node-fetch
  flow-client/package.json
Labels: +0.0.1

#12430 chore: Make formatter:format work again
  pom.xml
Labels: +0.0.1

#12449 fix: Require Firefox 78 or later
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.0.1, target/9.0

#12446 test: do not run slow tests in normal validations
  flow-client/pom.xml
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithNumerousDataTest.java
  flow-server/pom.xml
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/testcategory/SlowTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/ChromeTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/IgnoreOSGi.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/PushTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/ScreenshotTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/SlowTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/TestCategory.java
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testcategory/PushTests.java
  flow-tests/pom.xml
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/InfiniteRerouteLoopIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ClearNodeChildrenIT.java
  pom.xml
Labels: +0.0.1

#12431 fix: Make ClassFinder deterministic
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ExtraNodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
Labels: +0.0.1

#12444 fix: fix the mobile-dnd polyfill versions (#12438) (CP: 8.0)
  flow-dnd/pom.xml
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
Labels: +0.0.1

#12402 feat: Make it easier to see the relevant part of InternalServerError
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
Labels: +0.0.1

#12454 test: add GH actions for CI validations
  .github/workflows/validation.yml
  flow-tests/test-jetty-reload/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
  flow-tests/test-mixed/src/test/java/com/vaadin/flow/mixedtest/ui/IdTestIT.java
Labels: +0.0.1

#12461 chore: mvn formatter:format
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Labels: +0.0.1

#12452 test: do not run slow tests in normal validations (#12446) (CP: 9.0)
  flow-client/pom.xml
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithNumerousDataTest.java
  flow-server/pom.xml
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/testcategory/SlowTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/ChromeTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/IgnoreOSGi.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/PushTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/ScreenshotTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/SlowTests.java
  flow-test-generic/src/main/java/com/vaadin/flow/testcategory/TestCategory.java
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testcategory/PushTests.java
  flow-tests/pom.xml
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/routing/InfiniteRerouteLoopIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ClearNodeChildrenIT.java
  pom.xml
Labels: +0.0.1

#12463 chore: Vite 2.7 beta9
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite, target/9.0

#12432 fix: Do not decode + as space
  flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
Labels: +0.0.1, target/2.7, target/8.0, target/9.0, target/2.8

#12435 chore: enable ignored tests
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/2.7

#12381 New mechanism for usage data collection
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/JsonHelpers.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProKey.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProjectHelpers.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsConstants.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsContainer.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsSender.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/AbstractStatisticsTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/DevModeUsageStatisticsTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/ProjectHelpersTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/StatisticsSenderTest.java
  vaadin-dev-server/src/test/resources/stats-data/.vaadin/proKey
  vaadin-dev-server/src/test/resources/stats-data/.vaadin/userKey
  vaadin-dev-server/src/test/resources/stats-data/client-data-1.txt
  vaadin-dev-server/src/test/resources/stats-data/empty/empty.txt
  vaadin-dev-server/src/test/resources/stats-data/gradle-project-folder1/settings.gradle
  vaadin-dev-server/src/test/resources/stats-data/gradle-project-folder2/settings.gradle
  vaadin-dev-server/src/test/resources/stats-data/maven-project-folder1/pom.xml
  vaadin-dev-server/src/test/resources/stats-data/maven-project-folder2/pom.xml
  vaadin-dev-server/src/test/resources/stats-data/usage-statistics-1.json
  vaadin-dev-server/src/test/resources/stats-data/usage-statistics-2.json
Labels: +1.0.0

#12474 fix(Fusion): support PathPattern parsed mapping for endpoint prefix
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionControllerConfiguration.java
Labels: fusion, +0.0.1

#12473 fix: Render only one error page when trying to go to a view without access
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
Labels: +0.0.1

#12451 fix: remove duplicates when collecting BeforeEnterObservers
  flow-server/src/main/java/com/vaadin/flow/router/EventUtil.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNestedBeforeEnterCounter.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNestedBeforeEnterView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNestedBeforeEnterIT.java
Labels: +0.0.1, target/2.7, target/8.0, target/9.0, target/2.8

#12480 chore: set fail-fast to false to GA matrices
  .github/workflows/validation.yml
Labels: +0.0.1

#12472 chore: Adds a FrontendTools constructor that can be used from the app
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.1.0

#12484 chore: add option to run manually validation action
  .github/workflows/validation.yml
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushLongPollingUpdateDivIT.java
Labels: +0.0.1

#12433 chore: Replace Assert.assertThat with non-deprecated MatcherAssert
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/JarContentsManagerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerCssTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/CustomElementsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidatorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentExporterUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/ui/DependencyTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/util/SharedUtilTests.java
Labels: +0.0.1
