Repository vaadin/flow, pull requests merged in 2021-07, with the labels that each got.

#11369 fix: use textContent instead of innerHTML for error elements (#11354)
  flow-client/package-lock.json
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtErrotHandlerTest.java
Labels: +0.0.1

#11374 chore: add excludepattern
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.0.1

#11372 fix: don't create a new UI instance for service worker resource
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.1.0, target/2.6, target/2.7, target/7.0

#11373 fix: format numbers in NumberRenderer using Locale if it's provided
  flow-data/src/main/java/com/vaadin/flow/data/renderer/NumberRenderer.java
  flow-data/src/test/java/com/vaadin/flow/data/renderer/NumberRendererTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0

#11377 fix: reset HTTP session on CLOSED state, not immidiately
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0

#11370 fix: Move generated theme files to frontend/generated
  .gitignore
  drivers.xml
  flow-server/README.md
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Labels: +0.0.1

#11367 fix: use dedicated exception for Location validation
  flow-server/src/main/java/com/vaadin/flow/router/InvalidLocationException.java
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.1.0, target/2.7

#11368 fix: use textContent instead of innerHTML for error elements (#11354)
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtErrotHandlerTest.java
Labels: +0.0.1

#11379 fix: use proper classloader for template model
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/TemplateModelProxyHandler.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0

#11385 fix: don't create a new UI instance for service worker resource (#11372)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.1.0, target/2.6

#11386 fix: don't create a new UI instance for service worker resource (#11372)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.1.0

#11387 fix: reset HTTP session on CLOSED state, not immidiately (#11377)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/2.6

#11328 feat!: make all generated data structures immutable
  fusion-endpoint/src/main/java/com/vaadin/fusion/generator/VaadinConnectTsGenerator.java
  fusion-endpoint/src/main/resources/com/vaadin/fusion/generator/EntityTemplate.mustache
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/collectionendpoint/expected-model-collectionendpoint.CollectionEndpoint.Collection.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/complexhierarchyendpoint/expected-model-complexhierarchymodel.GrandParentModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/complexhierarchyendpoint/expected-model-complexhierarchymodel.Model.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/complexhierarchyendpoint/expected-model-complexhierarchymodel.ParentModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/enumtype/expected-EnumEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-core.Version.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-inheritedmodel.InheritedModelEndpoint.ChildModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-inheritedmodel.InheritedModelEndpoint.ParentModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.ArraySchema.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Discriminator.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.Schema.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-media.XML.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/inheritedmodel/expected-model-models.ExternalDocumentation.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/iterableendpoint/expected-IterableEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/iterableendpoint/expected-model-iterableendpoint.IterableEndpoint.Foo.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-JsonTestEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-core.Version.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.Role.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.Status.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/json/expected-model-json.JsonTestEndpoint.User.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-ComplexReturnTypeEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-ModelEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-model.ModelEndpoint.Account.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-model.ModelEndpoint.Group.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/model/expected-model-subpackage.ModelFromDifferentPackage.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-model-modelpackage.ModelPackageEndpoint.Account.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/modelpackage/expected-model-subpackage.Account.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-NonNullableEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.NonNullableModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.ParameterType.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.ReturnType.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-model-sameclassname.SameClassNameEndpoint.SameClassNameModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-model-subpackage.SameClassNameModel.SubProperty.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-model-subpackage.SameClassNameModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/sameclassname/expected-model-subpackage.SubProperty.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/selfreference/expected-model-selfreference.SelfReference.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/superclassmethods/expected-model-superclassmethods.PersonEndpoint.Person.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/openapi/expected-FooBarEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/openapi/expected-default-class-no-tag.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/openapi/expected-first-class-multiple-tags.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/openapi/expected-multiple-lines-description.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/openapi/expected-second-class-multiple-tags.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1, fusion

#11400 fix: upgrade bytebuddy version for Java 18
  pom.xml
Labels: +0.0.1, target/2.7

#11403 fix: update non-nullable model to the new readonly structures
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-NonNullableEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/fusion/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.VaadinNonNullableModel.ts
Labels: +0.0.1, fusion

#11407 Revert "fix: reset HTTP session on CLOSED state, not immidiately (#11…
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1

#11408 Revert "fix: reset HTTP session on CLOSED state, not immidiately (#11…
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1

#11409 Revert "fix: reset HTTP session on CLOSED state, not immidiately (#11…
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1

#11406 Revert "fix: reset HTTP session on CLOSED state, not immidiately (#11…
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1

#11411 Update versions mentioned in readme
  README.md
Labels: +0.0.1

#11412 Revert "fix: reset HTTP session on CLOSED state, not immidiately (#11…
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +1.0.0

#11399 fix: use dedicated exception for Location validation (#11367)
  flow-server/src/main/java/com/vaadin/flow/router/InvalidLocationException.java
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapContextTest.java
Labels: +0.1.0

#11384 feat: extract validation error handler from Binder
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/BinderValidationErrorHandler.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/DefaultBinderValidationErrorHandler.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/DefaultBinderValidationErrorHandlerTest.java
Labels: +1.0.0, target/2.7, target/8.0

#11423 fix: undeprecate Uses
  flow-server/src/main/java/com/vaadin/flow/component/dependency/Uses.java
Labels: +0.1.0, target/7.0, target/8.0

#11419 fix: use dedicated namespace for fallback style imports
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11425 fix: correct unit test for serializing VaadinSession
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/8.0

#11428 fix: Reuse existing filesystem
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11416 fix: reset session field only when HTTP session is invalidated
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionIT.java
Labels: +0.1.0, target/2.6, target/2.7, target/7.0, target/8.0

#11410 fix: avoid merge conflicts during properties collection
  flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java
Labels: +1.0.0, target/2.6, target/2.7, target/7.0, target/8.0

#11447 fix: Don't revisit visited classes.
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerCssTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
Labels: +0.0.1

#11450 fix: Show only single permanent notification
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11453 fix: Show only single permanent notification (#11450)
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
Labels: +0.0.1, cherry pick, target/2.6

#11457 chore: update slf4j to 1.7.32
  pom.xml
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11463 fix: don't check logger in frontend version validation test
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11468 fix: don't check logger in frontend version validation test (#11463)
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.6

#11464 fix: update mock logging
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11474 fix: update mock logging (#11464)
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
Labels: +0.0.1, target/2.6

#11456 fix: remove functionality which tries to pin dev dependencies
  flow-dev-deps/pom.xml
  flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/resources/build.properties
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-mixed/pom-pnpm-production.xml
  pom.xml
Labels: +1.0.0, target/2.6, target/2.7, target/7.0, target/8.0

#11477 fix: remove functionality which tries to pin dev dependencies (#11456)
  flow-dev-deps/pom.xml
  flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/resources/build.properties
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-mixed/pom-pnpm-production.xml
  pom.xml
Labels: +1.0.0, target/2.6

#11476 fix: remove functionality which tries to pin dev dependencies (#11456)
  flow-dev-deps/pom.xml
  flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/resources/build.properties
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-mixed/pom-pnpm-production.xml
  pom.xml
Labels: +1.0.0, target/7.0

#11483 fix: remove functionality which tries to pin dev dependencies (#11456…
  flow-dev-deps/pom.xml
  flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/resources/build.properties
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-mixed/pom-pnpm-production.xml
  pom.xml
Labels: +1.0.0

#11484 fix: remove functionality which tries to pin dev dependencies (#11456…
  flow-dev-deps/pom.xml
  flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/LockDevDepVersionsMojo.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BuildUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/resources/build.properties
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-mixed/pom-pnpm-production.xml
  pom.xml
Labels: +1.0.0

#11481 fix: remove extra assertion
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionIT.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11491 fix: use package json file in unit tests
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/7.0, target/8.0

#11492 fix: reset session field only when HTTP session is invalidated (#11416)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InvalidateHttpSessionIT.java
Labels: +0.0.1, cherry pick, target/2.6

#11498 test: use package json file in unit tests (#11491)
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, cherry pick, target/2.6

#11497 feat!: update jsoup version
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/UsageStatisticsExporterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  pom.xml
Labels: +0.0.1
