Repository vaadin/flow, pull requests merged in 2021-05, with the labels that each got.

#10869 chore: add missing cleanup to tests
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +0.0.1

#10874 Upgrade to LitElement 2.5.0 and lit-html 1.4.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0, target/2.5, target/2.6, target/6.0, target/7.0

#10879 fix: upgrade to LitElement 2.5.0 and lit-html 1.4.0 (#10874) (CP: 6.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#10880 fix: upgrade to LitElement 2.5.0 and lit-html 1.4.0 (#10874) (CP: 2.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#10881 fix: upgrade to LitElement 2.5.0 and lit-html 1.4.0 (#10874) (CP: 2.5)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#10885 chore: Update maven plugins versions
  pom.xml
Labels: +0.0.1, target/2.5, target/2.6, target/6.0, target/7.0

#10886 chore: code formamtting
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
Labels: +0.0.1

#10317 chore: add ignored test for long polling and @PreserveOnRefresh
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PushLongPollingWithPreserveOnRefreshView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushLongPollingWithPreserveOnRefreshIT.java
Labels: +0.0.1

#10750 test: unignore tests in PopStateHandlerIT
  flow-client/src/main/frontend/Flow.ts
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
Labels: +1.0.0, fusion

#10897 fix: use trimmed line in imports rewrite
  flow-migration/src/main/java/com/vaadin/flow/migration/CopyMigratedResourcesStep.java
  flow-migration/src/test/java/com/vaadin/flow/migration/CopyMigratedResourcesStepTest.java
Labels: +0.0.1, target/2.5

#10902 chore: Fix Sonar complaint
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0, target/7.0

#8397 Add target constants for Anchor to use with alternate setTarget method (#8346)
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTarget.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTargetValue.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTargetValueTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Labels: +1.0.0

#10864 fix: pin platform transitive dependencies with npm
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +1.0.0

#10772 Auto-install Node 16
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Labels: +0.0.1

#10911 fix: include flow-dnd module to flow-bom
  flow-bom/pom.xml
Labels: +0.0.1, target/2.6, target/7.0

#10910 test: enable ignored cases in NavigationTriggerIT
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
Labels: +1.0.0, fusion

#10912 fix: upgrade to LitElement 2.5.1 and lit-html 1.4.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10917 fix: upgrade to LitElement 2.5.1 and lit-html 1.4.1 (#10912) (CP: 2.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#10923 chore: update vaadin-lumo-styles to 1.6.1
  flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
Labels: +1.0.0

#10894 fix: log limitation of adding new styles while switching themes
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
Labels: +1.0.0, target/2.6, target/2.7, target/6.0, target/7.0, theming

#10921 fix: allow empty segments at start
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/PathUtilTest.java
Labels: +0.1.0, target/2.5, target/2.6, target/2.7, target/6.0, target/7.0

#10934 Always update webpack.generated.js
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, target/2.5, target/2.6

#10938 fix: allow empty segments at start (#10921)
  flow-server/src/main/java/com/vaadin/flow/router/internal/PathUtil.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterConfigurationUrlResolvingTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/PathUtilTest.java
Labels: +1.0.0, cherry pick, target/2.5, target/2.6

#10945 Fix incorrect import
  flow-client/src/main/frontend/ConnectionIndicator.ts
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/main/frontend/form/Field.ts
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
  flow-lit-template/src/test/resources/META-INF/VAADIN/config/stats.json
  flow-tests/test-application-theme/test-theme-reusable/frontend/ts-component.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/another/another-view.ts
  flow-tests/test-ccdm-flow-navigation/frontend/views/main/main-view.ts
  flow-tests/test-live-reload/frontend/custom-component.ts
  flow-tests/test-themes/frontend/typescript/hello-world-view.ts
Labels: +0.0.1

#10946 chore: fix a locale-dependent Binder unit test
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#10940 feat: Add target enums for Anchor (#8346) (#8397)
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTarget.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/AnchorTargetValue.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTargetValueTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Labels: +1.0.0

#10891 feat: Upgrade from es2017 to es2019
  flow-client/tsconfig.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/main/resources/tsconfig.json
Labels: +0.0.1

#10955 fix: use defined version for devDependencies.
  flow-client/package.json
Labels: +0.0.1

#10953 fix: Enable use of external css using `@import`
  flow-server/README.md
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/docImport.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/document.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/styles.css
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-themes/frontend/themes/app-theme/styles.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#10954 fix(Fusion): binding nullable fields with combo-box throws when clearing
  flow-client/src/main/frontend/form/BinderNode.ts
  flow-client/src/test/frontend/form/BinderTests.ts
Labels: +0.0.1, fusion, target/6.0, target/7.0

#10975 fix: Use IOUtils toStream and toString
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/resources/specialCharacterValue.json
Labels: +0.0.1, target/6.0, target/7.0

#10974 fix: Use IOUtils toStream and toString
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/resources/specialCharacterValue.json
Labels: +0.0.1, target/2.6

#10979 fix: update the used Opcode from 7 to 8
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/RepeatedAnnotationVisitor.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#10991 Change construct-style-sheets-polyfill to be a runtime dependency
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#10989 Fix an inconsistency about the attribute name in HierarchicalFilterUtils.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalFilterUtils.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#10996 fix: Change construct-style-sheets-polyfill to be a runtime dependency (#10991)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick, target/2.6

#10973 fix: Remove old router layouts content before navigation
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#10990 chore: add fix for download test
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +0.0.1, target/7.0

#11012 fix: Remove old router layouts content before navigation (#10973)(CP: 2.6)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
Labels: +0.0.1, cherry pick

#11013 fix: Remove old router layouts content before navigation (#10973)(CP: 2.7)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/RouterLayoutCustomScopeServlet.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RemoveRoutersLayoutContentIT.java
Labels: +0.0.1, cherry pick

#10903 feat: Implement HasStyle in LitTemplate so you can add class names to the root element
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/LitTemplate.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
Labels: +0.0.1, target/2.7, target/7.0

#11018 test: Explicitly register test servlet in OSGi
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#11027 fix: filter vaadin-core from versions pinning
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Labels: +0.0.1

#11030 test: Explicitly register test servlet in OSGi (#11018)(CP: 2.7)
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1, cherry pick

#11028 test: Explicitly register test servlet in OSGi (#11018)(CP: 2.6)
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1, cherry pick

#11043 fix: don't update cached extended details inside callback
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
Labels: +1.0.0, target/2.6, target/2.7, target/6.0, target/7.0

#11033 fix: Using a custom RouteRegistry
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationRouteTarget.java
  flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/TestAbstractRouteRegistry.java
  flow-tests/pom.xml
  flow-tests/test-custom-route-registry/pom.xml
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomErrorHandler.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomInitListener.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomNotFoundView.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRoute.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRouteRegistry.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServlet.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServletService.java
  flow-tests/test-custom-route-registry/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-custom-route-registry/src/test/java/com/vaadin/flow/custom/CustomRouteIT.java
Labels: +0.1.0, routing, target/2.6, target/2.7, target/6.0, target/7.0

#11040 Permit access to /themes/**
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Labels: +0.0.1, target/7.0

#11055 fix: Using a custom RouteRegistry (#11033)
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationRouteTarget.java
  flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/TestAbstractRouteRegistry.java
  flow-tests/pom.xml
  flow-tests/test-custom-route-registry/pom.xml
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomErrorHandler.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomInitListener.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomNotFoundView.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRoute.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRouteRegistry.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServlet.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServletService.java
  flow-tests/test-custom-route-registry/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-custom-route-registry/src/test/java/com/vaadin/flow/custom/CustomRouteIT.java
Labels: +0.1.0, cherry pick, target/2.6

#11039 fix: fix external url reference
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-application-theme/reusable-theme/src/main/java/com/vaadin/reusabletheme/Dependency.java
  flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/frontend/css/styles.css
  flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/path/img/icon.png
  flow-tests/test-application-theme/test-theme-live-reload/frontend/themes/app-theme/styles.css
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeView.java
  flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
Labels: +0.0.1, target/2.6

#11054 fix: Using a custom RouteRegistry (#11033)
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/NavigationRouteTarget.java
  flow-server/src/main/java/com/vaadin/flow/server/ErrorRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/TestAbstractRouteRegistry.java
  flow-tests/pom.xml
  flow-tests/test-custom-route-registry/pom.xml
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomErrorHandler.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomInitListener.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomNotFoundView.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRoute.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomRouteRegistry.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServlet.java
  flow-tests/test-custom-route-registry/src/main/java/com/vaadin/flow/custom/CustomServletService.java
  flow-tests/test-custom-route-registry/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-custom-route-registry/src/test/java/com/vaadin/flow/custom/CustomRouteIT.java
Labels: +0.1.0, cherry pick

#10999 fix: use relative path for default login/logout processing url
  flow-client/src/main/frontend/Authentication.ts
Labels: +0.0.1, fusion

#11062 feat: bump lit-css-loader for Lit 2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#10863 feat: Make helper method public to allow Spring to use it
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Labels: +0.1.0

#11065 fix: x64 version for mac if node old
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/Platform.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Labels: +1.0.0, target/2.6, target/2.7, target/6.0, target/7.0

#11066 fix: A request to /foo matches a servlet mapping of /foo/*
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Labels: +0.0.1

#11059 fix: Correctly resolve paths when using a context path
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
Labels: +0.0.1, fusion

#11034 test: fix mockito errors accessing protected API in JDK16
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/AbstractTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
  pom.xml
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#11078 Reapply "test: fix mockito errors accessing protected API in JDK16 (#11034) (CP: 7.0)"
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/AbstractTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
  pom.xml
Labels: +0.0.1

#11063 fix: Annotate default error handlers.
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.1.0, target/2.7, target/7.0

#11089 fix: Annotate default error handlers. (#11063)
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.1.0, target/2.6

#11090 fix: Annotate default error handlers. (#11063)
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.1.0, target/6.0

#11079 test: mock npm and webpack for endpoint tests
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeInitializerEndpointTest.java
Labels: +0.0.1, fusion

#11075 fix: avoid NPE in Location parsing
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
Labels: +1.0.0, target/2.6, target/2.7, target/6.0, target/7.0

#11084 test: fix mockito errors accessing protected API in JDK16 (#11034) (CP: 2.6)
  flow-client/package-lock.json
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/FrontendDataProviderTest.java
  flow-migration/src/test/java/com/vaadin/flow/migration/RewriteLegacyAnnotationsStepTest.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  pom.xml
Labels: +0.0.1

#11085 test: fix mockito errors accessing protected API in JDK16 (#11034) (CP: 2.7)
  flow-client/package-lock.json
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/common/FrontendDataProviderTest.java
  flow-migration/src/test/java/com/vaadin/flow/migration/RewriteLegacyAnnotationsStepTest.java
  flow-server/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  pom.xml
Labels: +0.0.1

#11072 fix: don't serve directories as static files
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
Labels: +0.0.1, target/1.0, target/2.6, target/2.7, target/6.0, target/7.0

#11101 chore: bump gradle wrapper version to support jdk16
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  flow-plugins/flow-gradle-plugin/gradlew
  flow-plugins/flow-gradle-plugin/gradlew.bat
Labels: +0.0.1, target/7.0

#11109 chore: fix CI indentation issue
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/IndentationUtils.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/TestUtils.java
Labels: +0.0.1, fusion

#11099 fix: prevent passing bad character to dev-server
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerImpl.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeHandlerImplTest.java
Labels: +0.0.1, target/2.6, target/2.7, target/6.0, target/7.0

#11038 chore: ping merged_by when CP failed [skip ci]
  scripts/cherryPick.js
Labels: +0.0.1

#11118 fix: make primitive types non-nullable by default in generated TS file
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/ExplicitNullableTypeChecker.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiObjectGenerator.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaGenerator.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/nonnullable/NonNullableEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormEndpoint.java
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/complexhierarchyendpoint/expected-model-complexhierarchymodel.GrandParentModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-model-core.Version.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-model-core.Version.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi-custom-application-properties.json
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-openapi.json
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nonnullable/expected-model-nonnullable.NonNullableEndpoint.NonNullableModel.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1, fusion

#11116 fix: prevent passing bad character to wp (#11099)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#11114 fix: prevent passing bad character to wp (#11099)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +1.0.0

#11115 fix: prevent passing bad character to wp (#11099)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#11113 fix: prevent passing bad character to wp (#11099)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#11102 chore: warn about missing DevModeHandlerManager
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
Labels: +0.0.1
