Repository vaadin/flow, pull requests merged in 2021-02, with the labels that each got.

#9908 fix: remove problematic dependencies
  fusion-endpoint/pom.xml
Labels: +0.1.0, fusion

#9898 feat(TypeScript): add Frontend path alias
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
  flow-tests/test-ccdm-flow-navigation/frontend/views/main/main-view.ts
  flow-tests/test-ccdm/frontend/index.js
Labels: +0.0.1, fusion

#9928 chore: remove verify browser version test
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/VerifyBrowserVersionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1, target/1.0, target/2.4, target/2.5, target/5.0

#9914 fix: Tasks are sorted for execution
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/UnknownTaskException.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
Labels: +0.1.0

#9929 Upgrade manifest plugin to 3.0.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#9932 chore: remove verify browser version test
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/VerifyBrowserVersionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#9933 chore: remove verify browser version test
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/VerifyBrowserVersionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +0.0.1

#9927 feat: add Karaf features via artifacts classifier for Flow
  flow-data/pom.xml
  flow-data/src/main/feature/feature.xml
  flow-lit-template/pom.xml
  flow-polymer-template/pom.xml
  flow-server/pom.xml
  flow-server/src/main/feature/feature.xml
  flow/pom.xml
  flow/src/main/feature/feature.xml
  pom.xml
Labels: +0.0.1

#9941 fix: fix dev deps test after changing in webpack config
  flow-dev-deps/src/test/java/com/vaadin/flow/devdeps/DevDepsFileTest.java
Labels: +0.0.1

#9938 Remove unused copy plugin
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +0.0.1, target/5.0

#9946 fix: use maven3 cargo plugin
  flow-tests/servlet-containers/pom.xml
  flow-tests/servlet-containers/tomcat85/pom.xml
  flow-tests/servlet-containers/tomcat9/pom.xml
Labels: +0.0.1

#9942 test: Linux local build fixes
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
Labels: +0.0.1

#9951 fix: fix tomcat ITs
  flow-tests/servlet-containers/pom.xml
  flow-tests/servlet-containers/tomcat85/pom.xml
  flow-tests/servlet-containers/tomcat9/pom.xml
Labels: +0.0.1

#9950 fix: fix tomcat ITs
  flow-tests/servlet-containers/pom.xml
  flow-tests/servlet-containers/tomcat85/pom.xml
  flow-tests/servlet-containers/tomcat9/pom.xml
Labels: +0.0.1

#9939 chore: remove browser version verification
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/VerifyBrowserVersionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/VerifyBrowserVersionIT.java
Labels: +1.0.0

#9883 chore: add missing license header and removed unused imports
  flow-server/src/test/java/com/vaadin/flow/component/CompositeNestedTest.java
  flow-server/src/test/java/com/vaadin/flow/component/CompositeTest.java
  flow-server/src/test/java/com/vaadin/flow/component/CompositeTextNodeTest.java
  flow-server/src/test/java/com/vaadin/flow/component/DefaultWebComponentExporterFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/component/HasThemeTest.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedToDomEvent.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedToDomEventMultipleConstructors.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedToDomInvalidEventData.java
  flow-server/src/test/java/com/vaadin/flow/component/MappedToDomNoDataEvent.java
  flow-server/src/test/java/com/vaadin/flow/component/ServerEvent.java
  flow-server/src/test/java/com/vaadin/flow/component/ServerNoDataEvent.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/component/WebComponentExporterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
Labels: +0.0.1

#9943 build: enable reuse of forks during unit tests
  flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  pom.xml
Labels: +0.1.0

#9955 fix: Importing binary file in frontend file
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/resources/dice.jpg
Labels: +0.0.1, target/2.4, target/2.5, target/5.0

#9931 fix: Remove old devDependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1, target/2.4, target/2.5, target/5.0

#9958 Use the same enum name in TS as in Java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/enumtype/EnumEndpoint.java
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-model-enumtype.EnumEndpoint.MyEnum.ts
Labels: +0.0.1

#9956 feat: generate .npmrc with default pnpm option
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/resources/npmrc
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, fusion

#9962 chore: correct karaf plugin configuration
  flow-data/pom.xml
  flow-server/pom.xml
  flow/pom.xml
Labels: +0.0.1

#9966 chore: fix flaky test
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1

#9935 Upgrade loader deps
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#9936 Upgrade lit-html + LitElement
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#9920 picks: Pick chrome driver (5.0)
  drivers.xml
  flow-client/intern.json
Labels: +0.0.1

#9968 chore: Recommend lit over polymer
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/EventHandler.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/ModelItem.java
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
Labels: +0.0.1

#9985 chore: Remove redundant UnsupportedEncodingException
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
Labels: +0.1.0

#9979 fix: ensure app shell is always in offline manifest
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, fusion

#9990 test: sinon.spy instead of timer for stabler test
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.1.0, fusion

#9972 feat(TypeScript): add endpoint wrapper class-like exports
  fusion-endpoint/src/main/resources/com/vaadin/flow/server/connect/generator/TypeScriptApiTemplate.mustache
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/complexhierarchyendpoint/expected-ComplexHierarchyEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/denyall/expected-DenyAllEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/enumtype/expected-EnumEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/inheritedmodel/expected-InheritedModelEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-GeneratorAnonymousAllowedTestClass.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/json/expected-JsonTestEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexReturnTypeEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/model/expected-ModelEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/nullable/expected-NullableEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/reservedwordmethod/expected-ReservedWordMethodEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/selfreference/expected-SelfReferenceEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-FooBarEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-default-class-no-tag.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-first-class-multiple-tags.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-multiple-lines-description.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-no-tsdoc.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-partly-tsdoc.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/openapi/expected-second-class-multiple-tags.ts
Labels: +0.0.1, fusion

#9995 test: increase timeout for frontend compilation to fix UrlValidationIT
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
Labels: +1.0.0

#9998 chore: Open a view before testing.
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
Labels: +0.0.1

#9996 chore: post a comment if cherry pick failed
  scripts/cherryPick.js
Labels: +0.0.1

#9934 Cleanup: Use env instead of custom parameter to webpack
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#10004 chore: Open a view before testing. (#9998)
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/UrlValidationIT.java
Labels: +0.0.1

#10012 fix: Use latest webpack 4 to fix using npm v7
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/6.0

#10014 fix: level up namespace of devModeGizmo and theming objects to Vaadin
  flow-client/src/main/resources/META-INF/resources/frontend/VaadinDevmodeGizmo.ts
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1

#9872 chore!: mark Abstract class with appropriate modifier
  flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
Labels: +1.0.0

#10006 Use latest Typescript
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, fusion

#10019 chore: remove broken code
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Labels: +1.0.0

#10020 fix: Resolve requested range properly after filtering the lazy backend
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, data provider, target/5.0, target/6.0

#10026 fix: NumberValidator accepts undefined for optional fields
  flow-client/src/main/resources/META-INF/resources/frontend/form/Models.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/Validators.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
Labels: +0.0.1, fusion

#10001 fix: Skip adding url parameter template if already present
  flow-server/src/main/java/com/vaadin/flow/router/RoutesChangedEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/HasUrlParameterFormatTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryTestBase.java
Labels: +0.1.0, routing

#10034 chore: Increase application startup time threshold
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#9937 Upgrade to Workbox 6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1, fusion

#9783 fix: make FCR try to attach child on appear
  flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.html
  flow-data/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Labels: +0.0.1, target/2.4, target/2.5, target/2.6, target/5.0, target/6.0

#10046 fix: check if Flow is initiated for connection indicator
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/test/frontend/ConnectTests.ts
Labels: +0.0.1, fusion

#10024 feat: enable fetching browser URL
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PageView.java
Labels: +0.1.0, target/2.5, target/2.6

#10044 chore: collect the commits based on update
  scripts/cherryPick.js
Labels: +0.0.1

#10041 fix: Don't throw an exception if servlet class can't be loaded (#8233)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1, cherry pick

#10042 fix: Don't throw an exception if servlet class can't be loaded (#8233)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1, cherry pick

#10043 fix: Don't throw an exception if servlet class can't be loaded (#8233)
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1, cherry pick

#10037 Cherry pick from 2.5 to 2.6
  flow-server/src/main/java/com/vaadin/flow/router/RoutesChangedEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/HasUrlParameterFormat.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/HasUrlParameterFormatTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryTestBase.java
Labels: +0.1.0, cherry pick

#10022 fix: remove obsoleted client engine pre-compression
  flow-client/pom.xml
  flow-client/src/main/resources/com/vaadin/ClientEngineXSI.gwt.xml
  flow-client/src/test/java/com/vaadin/client/flow/ClientEngineSizeIT.java
Labels: +0.0.1, target/6.0

#10036 feat: global CSS loader
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#10061 chore: enable merging the auto CP pull request
  scripts/autoMerge.js
Labels: +0.0.1, target/2.4, target/2.5, target/2.6, target/5.0, target/6.0

#10060 [6.0] feat: global CSS loader (#10036)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, fusion

#10066 chore: Ignore flaky test
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/6.0

#10063 feat: support Unit in similar fashion to Vaadin 8 (#8533)
  flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
  flow-server/src/main/java/com/vaadin/flow/component/Unit.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
Labels: +1.0.0

#10062 feat: support Unit in similar fashion to Vaadin 8 (#8533)
  flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
  flow-server/src/main/java/com/vaadin/flow/component/Unit.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
Labels: +1.0.0

#10025 Update adopted stylesheet polyfill
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/6.0

#10077 chore: remove broken code (#10019)
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
Labels: +0.0.1

#10078 chore: Update how input field is gotten
  flow-tests/test-application-theme/test-reusable-as-parent/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
  flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1, target/6.0

#10081 chore: write package json for default changes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1, target/2.4, target/2.5, target/2.6, target/6.0

#9824 feat: add getters for used Unit to HasSize
  flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
  flow-server/src/main/java/com/vaadin/flow/component/Unit.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeUnitTest.java
  flow-server/src/test/java/com/vaadin/flow/component/UnitTest.java
Labels: +0.1.0, target/2.5, target/2.6

#10085 fix: add style-loader dependency
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.global.css
  flow-tests/test-ccdm-flow-navigation/frontend/views/about/about-view.ts
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/CssLoaderIT.java
Labels: +0.0.1, fusion

#10097 Revert "feat: global CSS loader (#10036) (#10060)"
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, fusion

#10092 chore: write package json for default changes (#10081)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1

#10093 chore: write package json for default changes (#10081)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1

#10094 chore: write package json for default changes (#10081)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCreatePackageJson.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1

#10098 chore: Fix initalizing to devServers
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1, target/5.0, target/6.0

#10100 chore: enable PWA in OSGi
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AppShellPredicate.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/di/AppShellPredicateImplTest.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#10110 chore: enable PWA in OSGi (#10100)
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AppShellPredicate.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/di/AppShellPredicateImplTest.java
  flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#9709 Process Iterable same way as Collection type
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/SchemaResolver.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/iterableendpoint/IterableEndpoint.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/iterableendpoint/IterableEndpointGenerationTest.java
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/iterableendpoint/expected-IterableEndpoint.ts
  fusion-endpoint/src/test/resources/com/vaadin/flow/server/connect/generator/endpoints/iterableendpoint/expected-model-iterableendpoint.IterableEndpoint.Foo.ts
Labels: +0.0.1, fusion

#10099 fix: remember original state after LOADING
  flow-client/src/main/resources/META-INF/resources/frontend/Connect.ts
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +0.0.1, fusion

#10118 chore: detect illegal LookupServletContainerInitializer execution in OSGi
  flow-server/src/main/java/com/vaadin/flow/di/AbstractLookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/LookupServletContainerInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0, target/6.0

#10007 fix: service worker communicate offline state to client
  flow-client/src/main/resources/META-INF/resources/frontend/ConnectionState.ts
  flow-client/src/main/resources/META-INF/resources/frontend/form/index.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
Labels: +0.0.1, cherry pick, fusion, target/6.0

#10128 fix: treat "clear all" as permanent initial state
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
  flow-tests/test-root-context/frontend/lit/test-form.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/ReattachView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/TestForm.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/ReattachIT.java
Labels: +1.0.0, target/2.4, target/2.5, target/2.6, target/4.0, target/5.0, target/6.0
