Repository vaadin/flow, pull requests merged in 2021-04, with the labels that each got.

#10423 fix: Provide info on file name when Json parsing fails
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10506 fix: use getContentLengthLong instead getContentLength
  flow-server/src/main/java/com/vaadin/flow/server/VaadinRequest.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinRequestTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletRequestTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Labels: +1.0.0, target/2.5, target/2.6, target/6.0

#10424 fix: make spring test not dependent on platform
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +1.0.0

#10541 chore: ignore flaky dialog shortcut tests
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.0.1, target/6.0

#10526 feat!: endpoint access is denied by default
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
Labels: +0.0.1, fusion

#10466 test: Refactor ThemeLiveReloadIT
  flow-tests/test-application-theme/test-theme-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadView.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1, target/2.6, target/6.0

#10365 test: Fix flaky tests in WebComponentIT
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
Labels: +1.0.0, target/2.5, target/2.6, target/6.0

#10553 fix: don't use ErrorHandler for IOExceptions in StreamReceiverHandler
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10561 chore: remove license header from build.gradle
  flow-plugins/flow-gradle-plugin/build.gradle
Labels: +1.0.0, gradle

#10551 Run mvn formatter:format
  flow-server/src/main/java/com/vaadin/flow/component/Text.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
Labels: +0.0.1

#10556 fix: consider first added route as main route and always return it first
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteSegment.java
  flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10448 Add getService() to BootstrapContext
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/InlineTargets.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
Labels: +0.1.0

#10548 fix: Provide info on file name when Json parsing fails (#10423) (CP 2.5)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, cherry pick

#10549 fix: Provide info on file name when Json parsing fails (#10423)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, cherry pick

#10534 refactor: Split public resources according to security context
  flow-server/src/main/java/com/vaadin/flow/internal/SecurityHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
Labels: +0.0.1

#10570 Allow passing null and paths starting with "/" to Location
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
Labels: +1.0.0

#10542 feat: Add gradle plugin
  flow-plugins/flow-gradle-plugin/.gitignore
  flow-plugins/flow-gradle-plugin/README.md
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  flow-plugins/flow-gradle-plugin/gradlew
  flow-plugins/flow-gradle-plugin/gradlew.bat
  flow-plugins/flow-gradle-plugin/pom.xml
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ReflectionsClassFinder.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
  flow-plugins/pom.xml
Labels: +1.0.0, gradle

#10449 Provide route path and parameters through BootstrapContext
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerPushConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +1.0.0

#10574 chore: use another compression plugin which uses only gzip (not brotli)
  flow-client/pom.xml
Labels: +0.0.1, target/2.5

#10546 test: Refactor ThemeLiveReloadIT (#10466) (CP 6.0)
  flow-tests/test-application-theme/test-theme-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadView.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1, cherry pick

#10431 Make JavaScriptBootHandler only respond to servlet path and not all sub paths
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapContextTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +1.0.0, fusion

#10578 chore: use another compression plugin which uses only gzip (not brotli)
  flow-client/pom.xml
Labels: +0.0.1

#10576 fix: force pnpm version <= 5
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10573 Make EndpointUtil available for injection
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
Labels: +1.0.0

#10591 chore: keep hard reference to UI instance to avoid its GC-ion
  flow-server/src/test/java/com/vaadin/flow/router/EventUtilTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10592 Chore: skip functionalTests for gradle
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1

#10363 chore: internal helper identifying framework internal requests
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.1.0, fusion

#10415 test: Remove the test because it relies on Webpack startup time
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
Labels: +0.0.1, cherry pick

#10599 fix: Skip any generated files in theme live reload plugin
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
Labels: +0.0.1

#10577 fix: store spring csrf to bootstrap page
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, fusion, target/6.0

#10569 fix: Do not use hardcoded target directory
  .gitignore
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-plugins/flow-gradle-plugin/pom.xml
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerClassLoaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/StatsContentTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/frontend/fusion/NodeTasksEndpointTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +1.0.0

#10601 6.0 cherry pick
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, fusion

#10562 Do not include test sources in 'target'
  flow-server/pom.xml
Labels: +0.0.1

#10604 Include Spring CSRF parameter name also
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1

#10605 chore: clarify VaadinContext::getAttribute semantic
  flow-server/src/main/java/com/vaadin/flow/server/VaadinContext.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10607 chore: clarify javadocs for VaadinSession::close
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10603 Include offline-stub.html in public resources
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
Labels: +0.0.1, fusion

#10618 test: disable flaky tests for 2.5
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.0.1

#10602 chore: push comment before following steps when cherrypicking
  scripts/cherryPick.js
Labels: +1.0.0

#10622 fix: Extract theme name from proper folder and skip generated files
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/6.0

#10620 chore: make thread-safe access to NpmTemplateParser internal state
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10627 Consider generated icons public resources
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Labels: +0.0.1

#10631 fix: avoid log an error if frontend tool can't be found
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10628 fix: Log webpack output on failure
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1, target/2.6

#10596 fix: Use (p)npm to install flow plugins
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/WebpackPluginsUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJsonTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Labels: +1.0.0

#10617 test: ignore the file path comparison in comment of generated ts model
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +0.0.1, fusion

#10610 refactor: separate endpoint registry out from connect controller
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointRegistry.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerMockBuilder.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
Labels: +0.0.1, fusion

#10623 fix: Watch for a new CSS only in components folder
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#10639 refactor: reverse inverse logic naming
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
Labels: +0.0.1

#10634 fix: cannot login to authentication protected view
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
Labels: +1.0.0, fusion, target/6.0

#10638 fix: windows drive can be upper or lower case
  pom.xml
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10653 chore: skip closed but no merged PRs for cherry pick
  scripts/cherryPick.js
Labels: +0.0.1

#10655 fix: Exclude theme name from plugin parameters
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#10611 feat: add EndpointUtil.isAnonymousEndpoint
  fusion-endpoint/pom.xml
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/TestEndpoints.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/EndpointUtilTest.java
Labels: +0.0.1, fusion

#10547 test: Refactor ThemeLiveReloadIT (#10466) (CP 2.6)
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-application-theme/test-theme-live-reload/frontend/themes/app-theme/styles.css
  flow-tests/test-application-theme/test-theme-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadView.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1, cherry pick

#10661 test: wait for dev-mode-server in test
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, fusion, target/6.0

#10664 fix: add missing plugin property
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#10660 fix: avoid extra events on route reinitialization
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
Labels: +0.0.1, target/6.0

#10662 refactor: clarify naming and simplify logic
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
Labels: +0.0.1

#10584 test: Add a test for component styles live reload
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/frontend/themes/app-theme/styles.css
  flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AppShell.java
  flow-tests/test-application-theme/test-theme-component-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadView.java
  flow-tests/test-application-theme/test-theme-component-live-reload/src/main/java/com/vaadin/flow/uitest/ui/TestThemedTextField.java
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1, target/2.6, target/6.0

#10669 chore: explain JavaScript annotation behavior
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10663 fix: include redirectUrl in the return value of login()
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
Labels: +0.0.1, fusion, target/6.0

#10674 chore: Format with formatter:format
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/tsmodel/TsFormTest.java
Labels: +0.0.1

#10678 test: Test styles.css auto-generated in dev mode
  flow-tests/test-application-theme/test-theme-live-reload/frontend/themes/app-theme/styles.css
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1

#10635 fix: Accept newer framework managed versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
  flow-server/src/test/resources/versions/package.json
  flow-server/src/test/resources/versions/versions.json
Labels: +1.0.0, target/2.5, target/2.6, target/6.0

#10687 chore: mention query parameters in reroute and forward methods
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10640 fix: Compare file content from stream
  flow-server/src/main/java/com/vaadin/flow/server/frontend/JarContentsManager.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10692 chore: mention query parameters in reroute and forward methods (#10687)
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
Labels: +0.0.1

#10694 chore: mention query parameters in reroute and forward methods (#10687)
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
Labels: +0.0.1

#10693 chore: mention query parameters in reroute and forward methods (#10687)
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
Labels: +0.0.1

#10695 chore: remove idb dependency for deferred request feature that was removed
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, fusion, target/6.0

#10699 chore: mark fusion-endpoint as test dependency for flow maven plugin
  flow-plugins/flow-maven-plugin/pom.xml
  flow-plugins/flow-plugin-base/pom.xml
Labels: +0.0.1

#10701 fix: properly remove block comments from templates
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10697 Assume a non-redirect response for login requests
  flow-client/src/main/resources/META-INF/resources/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
Labels: +0.0.1

#10711 Revert "chore: mark fusion-endpoint as test dependnecy for flow maven…
  flow-plugins/flow-maven-plugin/pom.xml
  flow-plugins/flow-plugin-base/pom.xml
Labels: +0.0.1

#10712 fix: properly remove block comments from templates (#10701)
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.0.1

#10713 fix: properly remove block comments from templates (#10701)
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.0.1

#10656 fix: allow TypeScript in V14 server bootstrapping mode
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, fusion, target/6.0

#10702 refactor: separate endpoint CSRF checker out from access checking
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/CsrfChecker.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
Labels: +0.0.1, fusion

#10706 refactor: delete unnecessary separate case for anonymous users
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
Labels: +0.0.1, fusion

#10700 test: Add support for passing additional options to headless chrome
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractParallelTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10716 fix: report the parameter name in the exception message
  flow-server/src/main/java/com/vaadin/flow/router/RouteParameters.java
  flow-server/src/test/java/com/vaadin/flow/router/RouteParametersTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10719 fix: improve locationPrefix impl
  flow-server/src/main/java/com/vaadin/flow/router/HighlightConditions.java
  flow-server/src/test/java/com/vaadin/flow/router/HighlightConditionsTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10721 chore: use squash for cherry picks from bot [skip-ci]
  scripts/autoMerge.js
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10725 Fix VaadinConnectControllerConfiguration and add test
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfigurationTest.java
Labels: +0.0.1

#10734 chore: Clarify idempotence of Registrations
  flow-server/src/main/java/com/vaadin/flow/shared/Registration.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10718 chore: Move theme live reload tests to it's own profile
  flow-test-util/src/main/java/com/vaadin/flow/testcategory/ThemeLiveReloadTests.java
  flow-tests/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1, target/2.6, target/6.0

#10738 chore: reduce amount of info log messages during startup
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10707 refactor: split AccessAnnotationChecker out from VaadinConnectAccessChecker
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectControllerConfiguration.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/AccessAnnotationChecker.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/EndpointUtilTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/TestEndpoints.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/AccessAnnotationCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/generator/endpoints/AbstractEndpointGenerationTest.java
Labels: +0.0.1, fusion

#10747 chore: reduce amount of info log messages during startup (#10738)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/OpenApiSpecGenerator.java
Labels: +0.0.1

#10749 chore: reduce amount of info log messages during startup (#10738)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
Labels: +0.0.1

#10748 chore: reduce amount of info log messages during startup (#10738)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
Labels: +0.0.1

#10746 fix: Check assets for url handling
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
  flow-tests/test-themes/frontend/themes/app-theme/styles.css
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1, target/2.6, target/6.0

#10751 chore: update theme javadoc
  flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
Labels: +0.0.1

#10745 chore: Define default profile on root level
  pom.xml
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10753 fix: use global node and tools if they are available first
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.1.0, target/2.5, target/2.6, target/6.0

#10737 fix: backwards-compatible offline in V14 legacy mode
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/PwaConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
  flow-tests/pom.xml
  flow-tests/test-v14-bootstrap/pom-production.xml
  flow-tests/test-v14-bootstrap/pom.xml
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/pwatest/ui/PwaTestView.java
  flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +1.0.0, fusion

#10777 chore: Revert test categories
  flow-test-util/src/main/java/com/vaadin/flow/testcategory/ThemeLiveReloadTests.java
  flow-tests/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
  pom.xml
Labels: +0.0.1, target/6.0

#10768 fix: don't update bean property which is read-only bound
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10714 fix: properly remove block comments from templates (#10701)
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.0.1

#10784 fix: don't update bean property which is read-only bound (#10768)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#10629 test: Add test for custom theme name switch
  flow-tests/pom.xml
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/frontend/themes/app-theme/styles.css
  flow-tests/test-application-theme/test-theme-switch-live-reload/frontend/themes/other-theme/styles.css
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AppShell.java
  flow-tests/test-application-theme/test-theme-switch-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadView.java
  flow-tests/test-application-theme/test-theme-switch-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
Labels: +0.0.1, target/2.6, target/6.0

#10783 chore: improve component renderer mistakes detection
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractComponentDataGenerator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ComponentDataGenerator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractComponentDataGeneratorTest.java
Labels: +1.0.0, target/2.5, target/2.6, target/6.0

#10765 fix: don't publish flow-client TS sources in JAR
  .gitignore
  flow-client/.eslintrc.js
  flow-client/package.json
  flow-client/scripts/.eslintrc.js
  flow-client/scripts/client.js
  flow-client/scripts/version.js
  flow-client/src/main/frontend/Authentication.ts
  flow-client/src/main/frontend/Connect.ts
  flow-client/src/main/frontend/ConnectionIndicator.ts
  flow-client/src/main/frontend/ConnectionState.ts
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/main/frontend/FlowBootstrap.d.ts
  flow-client/src/main/frontend/FlowBootstrap.js
  flow-client/src/main/frontend/FlowClient.d.ts
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/main/frontend/form/Binder.ts
  flow-client/src/main/frontend/form/BinderNode.ts
  flow-client/src/main/frontend/form/Field.ts
  flow-client/src/main/frontend/form/Models.ts
  flow-client/src/main/frontend/form/Validation.ts
  flow-client/src/main/frontend/form/Validators.ts
  flow-client/src/main/frontend/form/index.ts
  flow-client/src/main/frontend/index.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/ConnectionIndicatorTests.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/IndexTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
  flow-client/tsconfig.json
Labels: +1.0.0, fusion, target/6.0

#10786 test: Add test for custom theme name switch (#10629) (CP: 2.6)
  flow-tests/pom.xml
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/frontend/themes/app-theme/styles.css
  flow-tests/test-application-theme/test-theme-switch-live-reload/frontend/themes/other-theme/styles.css
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadView.java
  flow-tests/test-application-theme/test-theme-switch-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
Labels: +0.0.1, cherry pick

#10774 Fixed outdated documentation about Push annotation
  flow-server/src/main/java/com/vaadin/flow/component/page/Push.java
Labels: +0.0.1

#10793 fix: avoid ConcurrentModificationException in Binder
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10787 fix: update CSRF tokens with the ones returned in the login call
  flow-client/src/main/frontend/Authentication.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
Labels: +0.0.1

#10788 chore: improve exceptions handling in WC exporter handling
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporterFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
  flow-server/src/test/java/com/vaadin/flow/component/DefaultWebComponentExporterFactoryTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10801 fix: extend and clarify valid tag names
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10795 fix: don't publish flow-client TS sources separately in JAR (#10765) (CP: 6.0)
  .gitignore
  flow-client/.eslintrc.js
  flow-client/package.json
  flow-client/scripts/.eslintrc.js
  flow-client/scripts/client.js
  flow-client/scripts/version.js
  flow-client/src/main/frontend/Authentication.ts
  flow-client/src/main/frontend/Connect.ts
  flow-client/src/main/frontend/ConnectionIndicator.ts
  flow-client/src/main/frontend/ConnectionState.ts
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/main/frontend/FlowBootstrap.d.ts
  flow-client/src/main/frontend/FlowBootstrap.js
  flow-client/src/main/frontend/FlowClient.d.ts
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/main/frontend/form/Binder.ts
  flow-client/src/main/frontend/form/BinderNode.ts
  flow-client/src/main/frontend/form/Field.ts
  flow-client/src/main/frontend/form/Models.ts
  flow-client/src/main/frontend/form/Validation.ts
  flow-client/src/main/frontend/form/Validators.ts
  flow-client/src/main/frontend/form/index.ts
  flow-client/src/main/frontend/index.ts
  flow-client/src/test/frontend/AuthenticationTests.ts
  flow-client/src/test/frontend/ConnectTests.ts
  flow-client/src/test/frontend/ConnectionIndicatorTests.ts
  flow-client/src/test/frontend/ConnectionStateTests.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-client/src/test/frontend/form/BinderTests.ts
  flow-client/src/test/frontend/form/FieldTests.ts
  flow-client/src/test/frontend/form/IndexTests.ts
  flow-client/src/test/frontend/form/ModelTests.ts
  flow-client/src/test/frontend/form/TestModels.ts
  flow-client/src/test/frontend/form/ValidationTests.ts
  flow-client/src/test/frontend/form/ValidatorsTests.ts
  flow-client/tsconfig.json
Labels: +0.0.1, cherry pick, fusion

#10802 chore: clarify attribute/property value behavior in templates
  flow-server/src/main/java/com/vaadin/flow/component/template/Id.java
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10720 feat: support class level endpoint access checking
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/AccessAnnotationChecker.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/AccessAnnotationCheckerTest.java
Labels: +0.0.1

#10730 test: Make access control test independent of Spring and endpoints
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/AccessAnnotationChecker.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/AccessControlTestClasses.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/auth/AccessAnnotationCheckerTest.java
Labels: +0.0.1

#10814 chore: deploy flow-buildtools in order to be used in other projects
  build-tools/pom.xml
Labels: +1.0.0, target/2.6, target/6.0

#10815 fix: flow-client build on Windows
  flow-client/package.json
Labels: +0.0.1, fusion, target/6.0

#10820 fix: update attribute name for fetching spring csrf token
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, fusion

#10775 Improved Java docs for AppShellConfigurator
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
Labels: +1.0.0

#10779 fix: Warn to delete component CSS with theme generated in one run
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-tests/test-application-theme/test-theme-component-live-reload/frontend/themes/app-theme/components/empty
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Labels: +0.0.1, target/6.0

#10812 refactor!: revert "feat: use superclass of VaadinServlet/Request (#9699)"
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletRequest.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletResponse.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/FaviconHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/CustomVaadinServiceImplementationTest.java
Labels: +1.0.0

#10828 fix: Warn to delete component CSS with theme generated in one run
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-tests/test-application-theme/test-theme-component-live-reload/frontend/themes/app-theme/components/empty
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Labels: +0.0.1, cherry pick

#10827 fix: Warn to delete component CSS with theme generated in one run
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-tests/test-application-theme/test-theme-component-live-reload/frontend/themes/app-theme/components/empty
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Labels: +0.0.1, cherry pick

#10832 chore: run formatter:format
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
  flow-server/src/main/java/com/vaadin/flow/component/page/Push.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/PwaConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-tests/test-application-theme/test-theme-switch-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#10823 fix: preserve internal JS UI state properly
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.0.1, target/6.0

#10830 fix: Adapt warning message to 2.6
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/package.json
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
Labels: +0.0.1

#10847 chore: deploy flow-buildtools in order to be used in other projects (#10814) (CP: 2.5)
  build-tools/pom.xml
Labels: +0.0.1

#10855 chore: fix probable merge failures
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/7.0

#10852 chore: Update README file
  README.md
Labels: +0.0.1, target/2.5, target/2.6, target/6.0

#10831 fix: don't set text based on template parsing data
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/InjectableLitElementInitializerTest.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/LitTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/AbstractInjectableElementInitializer.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/IdCollector.java
  flow-server/src/main/java/com/vaadin/flow/component/template/internal/TextInitializationStrategy.java
  flow-tests/test-root-context/frontend/AttributeTemplate.js
  flow-tests/test-root-context/frontend/lit/AttributeLitTemplate.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/littemplate/LitTemplateAttributeView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/ChildOrderView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/ChildOrderIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateAttributeIT.java
Labels: +1.0.0, target/2.5, target/2.6, target/6.0, target/7.0

#10767 feat: Add helpers for using current request and simplify naming
  flow-server/src/main/java/com/vaadin/flow/server/auth/AccessAnnotationChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/EndpointUtil.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java
Labels: +1.0.0, target/7.0

#10836 feat: Backport 'Inject Lumo CSS also into shadow roots' to 2.6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/theme.json
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeView.java
  flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/ReusableThemeIT.java
Labels: +1.0.0
