Repository vaadin/flow, pull requests merged in 2021-01, with the labels that each got.

#9694 Update StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, target/2.4, target/2.5, target/5.0, to be cherry picked

#9641 chore: fix double slashes in exception message
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1

#9718 Always install webpack plugins
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
Labels: +0.0.1

#9740 Use CSS import in component theming
  flow-tests/test-themes/frontend/themes/app-theme/components/background-color.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-radio-button.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-text-field.css
Labels: +0.0.1

#9739 fix: verify server live by HEAD to /sw.js instead of /
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
Labels: +1.0.0, fusion, offline

#9742 chore: fix exception message
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1

#9743 Fix: resource loading string
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Labels: +0.0.1, embedding flow

#9727 Refactor Lookup initialization for Servlet 3.0 containers
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/function/VaadinApplicationInitializationBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  flow-server/src/test/java/com/vaadin/flow/di/LookupIntializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/LookupInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/LookupServletContainerInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#9747 test: ignore ThemeLiveReloadIT
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1

#9725 fix: AppTheme is not applied in client-side Fusion
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/test-ccdm/.gitignore
  flow-tests/test-ccdm/frontend/themes/my-theme/global.css
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-ccdm/src/main/java/com/vaadin/flow/ccdmtest/AppShell.java
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/AppThemeTestIT.java
  fusion-endpoint/src/main/java/com/vaadin/flow/server/frontend/fusion/EndpointGeneratorTaskFactoryImpl.java
Labels: +0.1.0

#9758 fix: wrong this binding in loadingStarted/Finished
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
Labels: +1.0.0, fusion

#9744 feat!: Application theme only considers styles.css
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/styles.css
  flow-tests/test-application-theme/test-reusable-as-parent/frontend/themes/child-theme/styles.css
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/styles.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/not-used/styles.css
  flow-tests/test-themes/frontend/themes/app-theme/styles.css
  flow-tests/test-themes/frontend/themes/app-theme/unused.css
  flow-tests/test-themes/frontend/themes/parent-theme/styles.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9761 chore: s/global.css/styles.css/ in IT
  flow-tests/test-ccdm/frontend/themes/my-theme/styles.css
Labels: +0.0.1

#9763 fix: update vaadin-lumo-styles to 1.6.1
  flow-theme-integrations/lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
Labels: +0.0.1

#9770 chore: Update chrome driver checksum for linux
  drivers.xml
Labels: +0.0.1

#9771 chore: rethrow exception from flowInit
  flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts
Labels: +0.0.1

#9775 chore: Move imported css to sub folder
  flow-tests/test-themes/frontend/themes/app-theme/components/shared/background-color.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-radio-button.css
  flow-tests/test-themes/frontend/themes/app-theme/components/vaadin-text-field.css
Labels: +0.0.1, testing

#9753 fix: Generate TS definition for theme-generated.js
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
Labels: +0.1.0

#9788 chore: Bump Node.js default version to last LTS
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Labels: +1.0.0

#9227 fix: Update changed value to field with formatting
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +1.0.0

#9776 fix: Resource is not available in java if not referenced in a CSS file
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-tests/test-themes/frontend/themes/app-theme/img/dice.jpg
  flow-tests/test-themes/frontend/themes/app-theme/styles.css
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +1.0.0

#9790 test: Use portable line separators in TaskGeneratedBootstrapTest
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
Labels: +0.0.1

#9795 chore: remove debug log statement
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1, fusion

#9734 feat: implement HasOrderedComponents in HTML layout elements
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Article.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Aside.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Div.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Footer.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Header.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Main.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Nav.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Section.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ArticleTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AsideTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/DivTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/FooterTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HeaderTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/MainTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NavTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/SectionTest.java
Labels: +0.1.0

#9784 chore: framework#11859 Expired session: use 403 Forbidden instead of 410
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/HeartbeatHandler.java
Labels: +1.0.0

#9721 feat: replace awesome-typescript-loader with ts-loader
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
Labels: +1.0.0, fusion

#9803 fix(tests): add JSON HTTP server to stub webpackDevServer
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +0.0.1, fusion

#9777 Refactor startup initializers to use VaadinContext
  flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DeferredServletContextInitializers.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinContextStartupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinInitializerException.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#9805 Revert "feat: replace awesome-typescript-loader with ts-loader (#9721)"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
Labels: +0.0.1, fusion

#9781 Use Chokidar 3.5 to avoid deprecated fsevents 2.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#9807 chore: update log for level for plugins
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
Labels: +0.0.1

#9812 fix: Only create needed folders
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
Labels: +0.0.1

#9810 fix(tests): extend timeouts for stub webpack server connection attempts
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, fusion

#9735 feat: implement NativeDetails as html component
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeDetailsElement.java
  flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsElementIT.java
  flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/NativeDetailsView.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeDetailsTest.java
  flow-server/src/main/java/com/vaadin/flow/component/Tag.java
Labels: +1.0.0

#9814 Use existing getRequestUrl method
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
Labels: +0.0.1

#9764 test: Fix random failures of ThemeLiveReloadIT
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +1.0.0

#9748 chore: pick flaky test fixes from master
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +0.0.1

#9819 chore: Update tests to not accept faulty annotations
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-reusable/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-misc/pom.xml
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/AppShell.java
  flow-tests/test-router-custom-context/src/main/java/com/vaadin/flow/contexttest/ui/DependencyLayout.java
  flow-tests/test-themes/pom.xml
Labels: +0.0.1

#9816 fix: delay deletion of frontend/generated/vaadin.ts
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/generator/VaadinConnectTsGenerator.java
Labels: +0.0.1, fusion

#9516 fix: Add empty list handling to DataCommunicator#collectKeysToFlush
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.0.1, target/2.4, target/2.5, target/5.0

#9820 refactor!: Move theme-generated.js to frontend/generated
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
Labels: +1.0.0

#9831 test: Test reusable custom theme with embedded application
  flow-tests/test-embedding/embedding-reusable-custom-theme/pom.xml
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/java/com/vaadin/reusabletheme/Dependency.java
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/components/vaadin-radio-button.css
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/components/vaadin-text-field.css
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/document.css
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/img/bg.jpg
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/styles.css
  flow-tests/test-embedding/embedding-reusable-custom-theme/src/main/resources/META-INF/resources/themes/reusable-theme/theme.json
  flow-tests/test-embedding/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/MyPolymerField.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponentExporter.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/servlets/EmbeddedServlet.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#9843 test: Ignore flaky ThemeLiveReloadIT
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1

#9823 fix: Also load default JAR resources for DevModeInitializer
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/resources/dir-with-theme-resources/META-INF/resources/themes/reusable-theme/theme.json
  flow-server/src/test/resources/jar-with-themes-resources.jar
Labels: +0.1.0

#9847 Test that theme styles override Lumo styles
  flow-tests/test-themes/frontend/themes/app-theme/styles.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#9841 fix: Clean theme file if no theme defined
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
Labels: +0.0.1

#9852 Fix concurrency issue
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
Labels: +0.0.1

#9836 refactor!: Rename connect.generated as it now used for flow either
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +1.0.0, fusion

#9851 chore: Make NodeTasks less failure prone
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/startup/fusion/DevModeInitializerEndpointTest.java
Labels: +1.0.0

#9860 test: Revert user.dir system property after test
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
Labels: +0.0.1

#9846 fix: configure accessChecker in a thread safe way
  fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/VaadinConnectController.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerMockBuilder.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/VaadinConnectControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/rest/EndpointWithRestControllerTest.java
  fusion-endpoint/src/test/java/com/vaadin/flow/server/connect/typeconversion/BaseTypeConversionTest.java
Labels: +0.0.1, fusion

#9866 fix: properly initialize and destroy Vaadin Servlet
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
Labels: +1.0.0

#9859 fix: Lock versions to what is set in package.json
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0

#9842 Inject Lumo CSS into shadow roots
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-application-theme/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/theme.json
  flow-tests/test-application-theme/test-theme-reusable/frontend/ts-component.ts
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/TSView.java
  flow-tests/test-application-theme/test-theme-reusable/src/test/java/com/vaadin/flow/uitest/ui/theme/TSIT.java
Labels: +0.0.1

#9867 Use newest constructed stylesheet polyfill
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#9856 fix: peer dependency errors in npm 7 install
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyLitField.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyLitField.java
Labels: +1.0.0, fusion

#9876 Merge 2.4 into 2.5
  .gitignore
  drivers.xml
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/CompositeDataGenerator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/CompositeDataGeneratorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
  flow-data/src/test/java/com/vaadin/flow/data/validator/ValidatorTestBase.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/HeartbeatHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DevModeHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TestingServiceInitListener.java
Labels: +1.0.0

#9875 Use time-constant comparison for CSRF tokens
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.0.1

#9879 Chore: update chromedriver hash for linux
  drivers.xml
Labels: +0.0.1

#9848 feat: support current pnpm versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/resources/pnpmfile.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTestBase.java
Labels: +1.0.0, fusion

#9892 fix: bump jackson library version
  flow-server/pom.xml
Labels: +0.0.1

#9896 fix: use time-constant comparison for security tokens
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1

#9890 chore:Add script for flow cherry pick
  scripts/cherryPick.js
Labels: +0.0.1, target/2.4, target/2.5, target/5.0

#9897 Clarify CSRF token comments
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
Labels: +0.0.1, target/2.4, target/2.5, target/5.0, to be cherry picked

#9906 chore: stop the cherry pick properly
  scripts/cherryPick.js
Labels: +0.0.1, target/2.4, target/2.5, target/5.0

#9915 fix: revert changes made for resolving start-stop issue
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1

#9844 Remove unused private method
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
Labels: +0.0.1
