Repository vaadin/flow, pull requests merged in 2021-10, with the labels that each got.

#11954 chore: Rename DevModeHandlerImpl to WebpackHandler to better describe what it does
  flow-tests/test-jetty-reload/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeInitializerEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerStopTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: +0.0.1

#11960 chore: Check that webpack actually works when checking connection
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Labels: +0.0.1

#11956 fix: remove detach listeners from listenOn components on detach owner
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
Labels: +0.0.1, target/7.0, target/2.7, target/8.0

#11964 fix: Deprecate old FrontendTools constructors
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.1.0

#11955 fix: Close only for click on Close
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, target/7.0, target/2.7, target/8.0

#11948 feat: allow to use null from clients side with primitives
  flow-polymer-template/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
Labels: +0.0.1

#11973 fix: Close only for click on Close (#11955)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
Labels: +0.0.1, cherry pick

#11971 Use latest common-frontend
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: fusion, +0.0.1

#9760 chore: Bump Node.js supported version as it's getting EOL
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#11919 feat: add WhiteSpace setter and getter methods
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-server/src/main/java/com/vaadin/flow/component/HasText.java
  flow-server/src/test/java/com/vaadin/flow/component/HasTextTest.java
  flow-server/src/test/java/com/vaadin/flow/component/WhiteSpaceTest.java
Labels: +1.0.0

#11974 fix: return immidiately if VaadinSession is not initialized
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/7.0, target/2.7, target/8.0

#11986 fix: return immidiately if VaadinSession is not initialized (#11974)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/7.0

#11912 fix: make webpack respect path aliases in tsconfig
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/webpack.generated.js
Labels: fusion, +0.0.1

#11922 feat: reuse Spring csrf token
  flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfToken.java
  flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfChecker.java
  fusion-endpoint/src/main/java/com/vaadin/fusion/auth/CsrfIndexHtmlRequestListener.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/auth/CsrfCheckerTest.java
  fusion-endpoint/src/test/java/com/vaadin/fusion/auth/CsrfIndexHtmlRequestListenerTest.java
Labels: fusion, +1.0.0
