Repository vaadin/flow, pull requests merged in 2021-12, with the labels that each got.

#12487 Updated ASM8 to ASM9
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/RepeatedAnnotationVisitor.java
Labels: +0.0.1

#12507 feat: enable pwa for vite (#12363)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateServicWorkerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: +0.0.1, cherry pick

#12503 fix: clean info after build
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Labels: +0.0.1

#12424 fix: Make linking to packages in the file system work
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/vite-basics/package-outside-npm/index.js
  flow-tests/test-frontend/vite-basics/package-outside-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/package2-outside-npm/index.js
  flow-tests/test-frontend/vite-basics/package2-outside-npm/package.json
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ExternalPackageIT.java
  flow-tests/test-frontend/vite-basics/vite.config.ts
Labels: +0.0.1, target/9.0, target/2.8

#12518 test: Use file: instead of link: for npm compatibility
  flow-tests/test-frontend/vite-basics/package.json
Labels: +0.0.1, target/9.0

#12522 chore: Upgrade to Vite 2.7.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, target/9.0

#12505 chore: fix install locally string
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +1.0.0, target/2.7, target/8.0, target/9.0, target/2.8

#12500 fix: add scope to dependencies
  flow-plugins/flow-maven-plugin/pom.xml
Labels: +0.0.1, target/9.0, target/2.8

#12526 chore: fix install locally string (#12505)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +1.0.0, cherry pick

#12533 chore: redistribute modules to avoid failures when running in the same folder
  .github/workflows/validation.yml
Labels: +0.0.1

#12534 fix: Updated ASM8 to ASM9 (#12487)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/RepeatedAnnotationVisitor.java
Labels: +0.0.1, target/2.7

#12501 chore: replace exec-maven-plugin with gradle-maven-plugin
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1

#12535 chore: simpler condition when build fails
  .github/workflows/validation.yml
Labels: +0.0.1, target/9.0

#12537 chore: redistribute modules in CI actions (#12533 #12535) (CP: 9.0)
  .github/workflows/validation.yml
Labels: +0.0.1

#12508 chore: Upgrade jaxb
  pom.xml
Labels: +0.0.1, target/9.0

#12509 chore: Upgrade workbox
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/9.0

#12521 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/vite-bug-report.md
Labels: +0.0.1

#12543 Revert "chore(deps-dev): bump org.eclipse.core.contenttype from 3.7.1000 to 3.8.100"
  flow-client/pom.xml
Labels: +0.0.1

#12531 fix: Do not throw NPE for UI.access called when session has expired
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1, target/9.0

#12547 fix: Do not throw NPE for UI.access called when session has expired (#12531)
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1

#12551 Revert "chore: replace exec-maven-plugin with gradle-maven-plugin (#12501)
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1

#12553 fix: outdated links to production mode docs
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
Labels: +0.0.1

#12552 Revert "chore: replace exec-maven-plugin with gradle-maven-plugin (#12501) (#12545)"
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1

#12530 fix: output version string when version parsing fails
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/9.0

#12558 fix: outdated links to production mode docs (#12553)
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
Labels: +0.0.1, cherry pick, target/2.7

#12564 test: add script for better control of module/test splitting
  .github/workflows/validation.yml
  scripts/computeMatrix.js
Labels: +0.0.1, target/9.0

#12491 chore: close streams
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexHtml.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateServiceWorker.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12562 Bump TypeScript to 4.5.3
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12573 test: Remove unnecessary shadow root helpers
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/template/AttachExistingElementByIdIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/InnerTemplateVisibilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
Labels: +0.0.1, target/8.0, target/9.0

#12571 feat: Only send index.html when the browser requests a HTML page
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.1.0

#12567 chore: update chromedriver to 96
  drivers.xml
  flow-client/intern.json
Labels: +0.1.0

#12577 test: Remove unnecessary shadow root helpers (#12573) (CP: 8.0)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/template/AttachExistingElementByIdIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/littemplate/InnerTemplateVisibilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
Labels: +0.0.1

#12579 chore: close streams (#12491)
  flow-migration/src/test/java/com/vaadin/flow/migration/RewriteLegacyAnnotationsStepTest.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
Labels: +0.0.1, target/2.7

#12591 fix: Do not throw NPE for UI.access called when session has expired (#12531)
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1, target/2.7

#12597 chore: Fix formatting
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
Labels: +0.0.1

#12587 chore: Fix linting warnings
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/main/frontend/FlowBootstrap.js
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
Labels: +0.0.1, target/9.0

#12601 test: Remove unnecessary shadow root helpers (#12573)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/template/AbstractAttachExistingElementByIdIT.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/template/BundledTemplateInTemplateWithIdIT.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/WebComponentIT.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/LiveReloadIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/InnerTemplateVisibilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/imports/LazyWidgetIT.java
  flow-tests/test-themes-legacy/src/test/java/com/vaadin/flow/uitest/ui/template/ThemedTemplateIT.java
  flow-tests/test-themes-legacy/src/test/java/com/vaadin/flow/uitest/ui/theme/MyThemeIT.java
Labels: +0.0.1, target/2.8

#12608 chore: README.md up to date
  README.md
Labels: +0.0.1

#12609 fix: Do not use --ignore-existing which is only available in npm 6 (#12406)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1, cherry pick

#12585 chore: Change bug report template to a form
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: +0.0.1

#12611 chore: Update to Vite 2.7.4
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/9.0

#12617 test: fix memory leak in tests during build
  flow-tests/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-ccdm-flow-navigation/pom-production.xml
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
  flow-tests/test-frontend/vite-basics/pom.xml
  flow-tests/test-fusion-csrf-context/pom.xml
  flow-tests/test-fusion-csrf/pom.xml
  flow-tests/test-jetty-reload/pom.xml
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-mixed/pom-npm.xml
  flow-tests/test-mixed/pom.xml
  flow-tests/test-npm-only-features/pom.xml
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-ui-context/pom.xml
Labels: +0.0.1

#12621 test: Wait for vaadin to be ready
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/2.7

#12618 test: Remove duplicate Jetty plugin definition
  flow-tests/test-no-theme/pom.xml
Labels: +0.0.1

#12626 feat: upgrade Fusion npm packages to 0.0.16
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
Labels: fusion, +0.0.1

#12616 fix: Proper handling of href when the anchor is disabled/enabled
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.1.0, target/8.0, target/9.0, target/2.8

#12581 chore: introduce sonar cloud validation
  .github/workflows/sonar.yml
  pom.xml
Labels: +0.0.1

#12633 fix: Proper handling of href when the anchor is disabled/enabled (#12616)
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.1.0, cherry pick, target/2.7

#12643 test: Gradle tests must use local repo
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1, target/8.0, target/9.0

#12563 test: Split pnpm and npm tests into separate modules
  flow-test-util/src/main/java/com/vaadin/flow/testutil/FileTestUtil.java
  flow-tests/pom.xml
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/test-npm/README.md
  flow-tests/test-frontend/test-npm/frontend/my-component.js
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/pom-production.xml
  flow-tests/test-frontend/test-npm/pom.xml
  flow-tests/test-frontend/test-npm/src/main/java/com/vaadin/flow/mixedtest/ui/IdTestView.java
  flow-tests/test-frontend/test-npm/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
  flow-tests/test-frontend/test-npm/src/test/java/com/vaadin/flow/mixedtest/ui/IdTestIT.java
  flow-tests/test-frontend/test-npm/src/test/java/com/vaadin/flow/mixedtest/ui/NpmUsedIT.java
  flow-tests/test-frontend/test-pnpm/README.md
  flow-tests/test-frontend/test-pnpm/frontend/my-component.js
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
  flow-tests/test-frontend/test-pnpm/pom-production.xml
  flow-tests/test-frontend/test-pnpm/pom.xml
  flow-tests/test-frontend/test-pnpm/src/main/java/com/vaadin/flow/mixedtest/ui/IdTestView.java
  flow-tests/test-frontend/test-pnpm/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
  flow-tests/test-frontend/test-pnpm/src/test/java/com/vaadin/flow/mixedtest/ui/IdTestIT.java
  flow-tests/test-frontend/test-pnpm/src/test/java/com/vaadin/flow/mixedtest/ui/PnpmUsedIT.java
  flow-tests/test-mixed/README.md
  scripts/computeMatrix.js
Labels: +0.0.1, target/9.0

#12434 feat: allow adding true modal dialogs to UI
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/AllowInert.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/InertData.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeFeatureRegistry.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeFeatures.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/NavigationRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/InertDataTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeFeatureTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/NavigationRpcHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/InertComponentView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ModalDialogView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InertComponentIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
Labels: +0.1.0

#12582 test: run tests in sub-sub-modules
  .github/workflows/validation.yml
  flow-tests/pom.xml
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-embedding/pom.xml
  flow-tests/test-frontend/pom.xml
  flow-tests/test-fusion-csrf/pom.xml
  flow-tests/test-multi-war/test-war2/pom.xml
  flow-tests/test-root-context/pom.xml
  scripts/computeMatrix.js
Labels: +0.0.1, target/9.0

#12632 fix: Proper handling of href when the anchor is disabled/enabled (#12616)
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.1.0, cherry pick

#12651 test: run tests in sub-sub-modules (#12582) (CP: 9.0)
  .github/workflows/validation.yml
  flow-tests/pom.xml
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-embedding/pom.xml
  flow-tests/test-frontend/pom.xml
  flow-tests/test-fusion-csrf/pom.xml
  flow-tests/test-multi-war/test-war2/pom.xml
  flow-tests/test-root-context/pom.xml
  scripts/computeMatrix.js
Labels: +0.0.1

#12627 test: Ignore Vite generated file [skip-ci]
  .gitignore
Labels: +0.0.1
