Repository vaadin/flow, pull requests merged in 2022-12, with the labels that each got.

#15325 refactor: Extract options to a separate file
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0, target/23.3

#15324 feat: add refresh flag to navigation event
  flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEnterEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +1.0.0, target/2.8, target/23.2, target/23.3

#15315 fix: Prefix web component client app with wc-
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +1.0.0, target/23.3

#15327 refactor: Merge constructors and use setters instead
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#15328 chore: Update TestBench to 8.2.0.beta1
  pom.xml
Labels: +0.0.1

#15343 test: Always run postinstall for esbuild in flow-client
  flow-client/pom.xml
Labels: +0.0.1, target/23.3

#15334 chore: Upgrade to Vite v4.0.0-alpha.6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1

#15335 Pass options to task
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestEndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexHtml.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateServiceWorker.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentHtml.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPlugins.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexHtmlTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateServicWorkerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentHtmlTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: +1.0.0, target/23.3

#15351 fix: Use root servlet mapping for push url in OSGi case
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
Labels: +0.0.1

#14921 test: Add tests for new license checker config parameter
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/test/java/com/vaadin/flow/function/DeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
Labels: +0.0.1

#15314 fix: do not remove expanded items from key mapper
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +0.0.1, Contribution, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#15362 chore: update testbench to 8.2.0
  pom.xml
Labels: +0.0.1

#15344 fix: Component locale works without UI and i18n
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1, target/2.8, target/23.2, target/23.3

#15369 test: Delete unused dependency
  flow-plugins/flow-maven-plugin/pom.xml
Labels: +0.0.1, target/23.3

#15379 test: Delete unused dependency (#15369) (CP: 23.3)
  flow-plugins/flow-maven-plugin/pom.xml
Labels: +0.1.0, cherry pick

#15380 test: ensure ComponentTest preconditions
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
Labels: +0.0.1

#15381 test: ensure ComponentTest preconditions (CP: 23.3)
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
Labels: +0.0.1, cherry pick, target/23.2

#15382 test: ensure ComponentTest preconditions (CP: 2.8)
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
Labels: +0.0.1, cherry pick

#15129 feat: Add the authentication context API to the Vaadin Web Security
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityUtils.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/BankService.java
  vaadin-spring/pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/UidlRedirectStrategy.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UidlRedirectStrategyTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtSecurityContextRepositoryTest.java
Labels: +0.0.1

#15393 fix: npm version collection on windows
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#15389 chore: Make project folder available in ApplicationConfiguration
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
Labels: +1.0.0

#15374 refactor: Rename TaskInstallWebpackPlugins to TaskInstallFrontendBuildPlugins
  flow-server/README.md
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendPluginsUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPlugins.java
  flow-server/src/main/resources/plugins/plugins.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPluginsTest.java
Labels: +1.0.0, target/23.3

#15397 chore: log server sync id stack at trace level
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
Labels: +0.0.1, target/23.2, target/23.3

#15409 fix: Do not serve Vite index.html for /index.html
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
Labels: +0.0.1, target/23.3

#15408 test: Do not spam log with lit dev mode warnings
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
Labels: +0.0.1, target/23.3

#15377 chore: Upgrade to Vite v4.0.0-beta.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +1.0.0

#15411 test: Do not spam log about where chromedriver is
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
Labels: +0.0.1, target/23.3

#15403 chore: Remove unused imports
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPolymerModelTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/server/scanner/ReflectionsClassFinderTest.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractAnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/ReturnChannelHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractTaskClientGeneratorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/spring/test/PathRewritingProxyServlet.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/spring/test/Proxy.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerClassLoaderTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/AbstractDevModeBrowserLauncherTest.java
Labels: +0.0.1

#15417 chore: Upgrade to Vite 4.0.0.beta7
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15413 fix: Vite production build errors with transitive dependencies
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-basics/package-outside-npm/index.js
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/package2-outside-npm/index.js
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ExternalPackageIT.java
  flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/.gitignore
  flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/index.js
  flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/node_modules/package-transitive
  flow-tests/test-frontend/vite-test-assets/packages/package-outside-npm/package.json
  flow-tests/test-frontend/vite-test-assets/packages/package-transitive/index.js
  flow-tests/test-frontend/vite-test-assets/packages/package-transitive/package.json
  flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/.gitignore
  flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/index.js
  flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/node_modules/package-transitive
  flow-tests/test-frontend/vite-test-assets/packages/package2-outside-npm/package.json
Labels: hilla, +0.0.1

#15355 fix: added HasDynamicTitle checking in parent layouts
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +1.0.0, target/9.0, target/2.8, target/23.2, target/23.3

#15422 chore: Upgrade to Vite 4.0.0
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15426 fix: added HasDynamicTitle checking in parent layouts (#15355) (CP 2.8)
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.0.1, cherry pick

#15261 chore: update GHA to get rid of the warning.
  .github/workflows/validation.yml
Labels: +0.0.1

#15434 chore: re-enable the check for outside collaborators
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.2, target/23.3

#15432 test: Upgrade to Jetty 11.0.13
  pom.xml
Labels: +0.0.1, target/23.2, target/23.3

#15428 chore: allow re-running failed jobs in GH actions
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.2, target/23.3

#15443 chore: align with master (#15435, #15231, #15428, #15151, #15230, #15224, #15226) (CP: 23.2)
  .github/workflows/validation.yml
  scripts/computeMatrix.js
Labels: +0.0.1

#15442 chore: align with master (#15435, #15231, #15428, #15151, #15230, #15224, #15226) (CP: 23.3)
  .github/workflows/validation.yml
  scripts/computeMatrix.js
Labels: +0.0.1

#15440 chore: Upgrade to Jetty 10.0.13
  pom.xml
Labels: +0.0.1, target/23.2

#15439 fix: don't warn about new license checker in production mode
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
Labels: +0.0.1

#15453 chore: fix retry job exit status (#15450) (CP: 23.2)
  .github/workflows/validation.yml
Labels: +0.0.1

#15449 fix: avoid duplicate JS const declaration on license checker script
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.1.0, target/23.2, target/23.3

#15451 chore: reduce upload/download artifact times
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.2, target/23.3

#15448 chore: Upgrade to Jetty 10.0.13 (#15440) (CP: 23.2)
  pom.xml
Labels: +0.0.1, cherry pick

#15414 fix: Correctly handle URL encoding in routes
  flow-client/src/main/frontend/Flow.ts
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/SpecialCharactersView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/test-ccdm/frontend/index.html
  flow-tests/test-ccdm/frontend/index.js
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/FaultyLocationIT.java
Labels: +1.0.0, target/23.3

#15462 test: Delete tests that take 1h
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/ExtremelyLongPushTimeUI.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/ExtremelyLongPushTimeWebsocketUI.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/testcategory/ExtremelySlowTest.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/ExtremelyLongPushTimeIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/ExtremelyLongPushTimeWebsocketIT.java
Labels: +1.0.0, target/23.3

#15463 test: Delete ignored tests which do not work
  flow-tests/test-root-ui-context/frontend/RouterLinks.js
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/template/RouterLinksTemplate.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/template/RouterLinksUI.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/template/RouterLinksIT.java
Labels: +1.0.0, target/23.3

#15441 feat: Merge JavaScriptBootstrapUI into UI.
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternalUpdater.java
  flow-server/src/main/java/com/vaadin/flow/router/NavigationTrigger.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +1.0.0

#15420 chore: Add note about restriction regarding LitTemplate
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JsModule.java
Labels: +1.0.0, target/23.2, target/23.3

#15446 feat: Add a feature flag for Express Build
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ApplicationConfigurationTest.java
  flow-tests/test-root-context/src/main/resources/vaadin-featureflags.properties
Labels: +1.0.0

#15461 fix: Correctly handle URL encoding in routes (#15414) (CP: 23.3)
  flow-client/src/main/frontend/Flow.ts
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/router/Location.java
  flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/HelloWorldView.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/SpecialCharactersView.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/test-ccdm/frontend/index.html
  flow-tests/test-ccdm/frontend/index.js
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/FaultyLocationIT.java
Labels: +1.0.0

#15470 test: Delete duplicate test
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/TrackMessageSizeUI.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/TrackMessageSizeIT.java
Labels: +1.0.0

#15472 test: Delete seemingly unnecessary and complex tests
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/devtools/DevToolsView.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/DevToolsDisabledServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/MapSyncRpcHandlerTestServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/RpcLoggerServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/LockingUI.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/NoRouterUI.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/NotSyncedPropertyUpdate.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/RpcLogger.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/LockingIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/NoRouterIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/NotSyncedPropertyUpdateIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/RPCLoggerIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/devtools/DevToolsIT.java
Labels: +1.0.0

#15477 [Snyk] Upgrade io.dropwizard.metrics:metrics-core from 4.2.12 to 4.2.13
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
Labels: +0.0.1

#15479 chore: fix typo in actions workflow expression
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.2, target/23.3

#15473 test: Delete empty test-root-ui-context module
  flow-tests/pom.xml
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/CustomDeploymentConfiguration.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ErrorTarget.java
  flow-tests/test-root-ui-context/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/AssertionTest.java
Labels: +0.0.1

#15000 fix: Use es2019 for TS compiler
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Labels: +0.0.1

#15493 fix: vite module path for windows
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#15487 feat: added method to get authenticate principal name
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
Labels: +0.0.1, target/23.3

#15495 test: Make test more stable
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
Labels: +0.0.1, target/23.3

#15491 chore: Upgrade Vite plugin checker to a Vite 4 compatible version
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15483 chore: remove unexisting module in v24
  scripts/computeMatrix.js
Labels: +0.0.1

#15507 test: Delete seemingly unnecessary and complex tests (#15472) (CP: 23.3)
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/devtools/DevToolsView.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/DevToolsDisabledServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/MapSyncRpcHandlerTestServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/RpcLoggerServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/LockingUI.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/NoRouterUI.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/NotSyncedPropertyUpdate.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/RpcLogger.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/LockingIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/NoRouterIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/NotSyncedPropertyUpdateIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/RPCLoggerIT.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/devtools/DevToolsIT.java
Labels: +0.0.1

#15508 test: Delete duplicate test (#15470) (CP: 23.3)
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/ui/push/TrackMessageSizeUI.java
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/TrackMessageSizeIT.java
Labels: +0.0.1

#15486 chore: rename "Experimental Features" to "Feature Flags"
  flow-client/src/main/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, target/23.3

#15513 chore: Upgrade plugin-replace to latest (5.0.1)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15488 [Snyk] Upgrade io.github.classgraph:classgraph from 4.8.150 to 4.8.151
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
Labels: +0.0.1

#15515 test: Delete empty test-root-ui-context module (#15473) (CP: 23.3)
  flow-tests/pom.xml
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/CustomDeploymentConfiguration.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ErrorTarget.java
  flow-tests/test-root-ui-context/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/AssertionTest.java
Labels: +0.0.1

#15504 feat: Compare bundle and package.json contents
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +1.0.0

#15517 fix: collect changes until UI is not dirty
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3

#15492 chore: Upgrade to workbox 6.5.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, target/23.3

#15497 fix: remove Serializable interface from AuthenticationContext
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
Labels: +0.0.1, target/23.3

#15521 fix: collect changes until UI is not dirty (#15517) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.0.1, cherry pick, target/9.0, target/2.8, target/23.2

#15514 chore: Upgrade to Vite 4.0.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +1.0.0

#15506 doc: Add a note about removing dev-bundle
  flow-client/README.md
Labels: +0.0.1

#15527 fix: collect changes until UI is not dirty (#15517) (#15521) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.0.1, cherry pick

#15525 fix: collect changes until UI is not dirty (#15517) (#15521) (CP: 9.0)
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.0.1, cherry pick

#15522 test: Ignore recently added PUSH + WebSockets tests for OSGi env
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/BasicPushIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/BasicPushWebsocketIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/BasicPushWebsocketXhrIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/EnableDisablePushIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/IdlePushChannelWebsocketIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/MakeComponentVisibleWithPushIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushConfigurationWebSocketIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushErrorHandlingIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushLargeDataWebsocketIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushToggleComponentVisibilityIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushWithRequireJSIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/ReconnectWebsocketIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/SendMultibyteCharactersWebSocketIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/TogglePushIT.java
Labels: +0.0.1, target/23.3

#15526 feat: Add dev-bundle-plugin
  flow-plugins/flow-dev-bundle-plugin/README.md
  flow-plugins/flow-dev-bundle-plugin/pom.xml
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-maven-plugin/README.md
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/packaging/SplitPackagesTest.java
  flow-tests/pom.xml
  flow-tests/test-dev-bundle/.gitignore
  flow-tests/test-dev-bundle/pom.xml
  flow-tests/test-dev-bundle/src/main/java/com/vaadin/devbundle/Deps.java
  flow-tests/test-dev-bundle/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-npm-only-features/pom.xml
  flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/package.json
  flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/pom.xml
  flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/src/main/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/MultipleNpmPackageAnnotationsView.java
  flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/src/main/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NpmPackageLayout.java
  flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/MultipleNpmPackageAnnotationsIT.java
Labels: +0.0.1

#15518 feat: Serve theme files separately from dev bundle
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/tests/util/TestUtil.java
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-theme-dev-bundle/.gitignore
  flow-tests/test-application-theme/test-theme-dev-bundle/frontend/index.html
  flow-tests/test-application-theme/test-theme-dev-bundle/frontend/themes/my-theme/fonts/ostrich-sans-regular.ttf
  flow-tests/test-application-theme/test-theme-dev-bundle/frontend/themes/my-theme/imported.css
  flow-tests/test-application-theme/test-theme-dev-bundle/frontend/themes/my-theme/styles.css
  flow-tests/test-application-theme/test-theme-dev-bundle/frontend/themes/my-theme/theme.json
  flow-tests/test-application-theme/test-theme-dev-bundle/pom.xml
  flow-tests/test-application-theme/test-theme-dev-bundle/src/main/java/com/vaadin/flow/devbuild/AppShell.java
  flow-tests/test-application-theme/test-theme-dev-bundle/src/main/java/com/vaadin/flow/devbuild/DevBundleThemeView.java
  flow-tests/test-application-theme/test-theme-dev-bundle/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-application-theme/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
  scripts/computeMatrix.js
Labels: +0.0.1

#15421 feat: Session resynchronization for embedded webcomponents
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/.gitignore
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/index.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/web-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginForm.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginFormExporter.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/UserService.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/webapp/basic-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
  scripts/computeMatrix.js
Labels: +0.0.1

#15541 feat: Session resynchronization for embedded webcomponents (#15421) (CP: 23.3)
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/.gitignore
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/index.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/web-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginForm.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginFormExporter.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/UserService.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/webapp/basic-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
  scripts/computeMatrix.js
Labels: +0.1.0, cherry pick

#15542 feat: Session resynchronization for embedded webcomponents (#15421) (CP: 23.2)
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/.gitignore
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/index.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/web-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginForm.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginFormExporter.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/UserService.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/webapp/basic-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
  scripts/computeMatrix.js
Labels: +0.1.0, cherry pick

#14035 fix: flush all changes for events that triggers event listeners
  flow-client/src/main/java/com/vaadin/client/flow/binding/Debouncer.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsWithValueChangeModeView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsWithValueChangeModeIT.java
Labels: +1.0.0, Contribution

#15556 chore: Upgrade to servlet detector 1.0.2 (#15555) (CP: 23.3)
  flow-server/pom.xml
Labels: +0.0.1

#15551 feat: Session resynchronization for embedded webcomponents (#15421) (CP: 2.8)
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
Labels: +0.1.0

#15559 fix: ensure default logout url starts with '/'
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1, Contribution

#15543 feat: Session resynchronization for embedded webcomponents (#15421) (CP: 9.0)
  flow-client/src/main/java/com/vaadin/client/DefaultRegistry.java
  flow-client/src/main/java/com/vaadin/client/Registry.java
  flow-client/src/main/java/com/vaadin/client/SystemErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/.gitignore
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/index.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/frontend/web-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginForm.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/LoginFormExporter.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/java/com/vaadin/viteapp/UserService.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/main/webapp/basic-component.html
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
  scripts/computeMatrix.js
Labels: +0.1.0

#15537 feat: Enable validating in memory package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-tests/test-npm-only-features/test-dev-bundle-no-plugin/package.json
Labels: +1.0.0, express-build

#15560 chore: Upgrade to Spring Boot 2.7.7
  pom.xml
Labels: +0.0.1

#15557 chore: update plugins to avoid warning
  .github/workflows/validation.yml
Labels: +0.0.1

#15549 chore: allow GHA takes base branch changed PRs
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.2, target/23.3

#15554 feat: Validate bundle frontend files
  flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0, express-build

#15558 feat: Add live-reload for theme files in Express Build
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccessor.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-tests/test-application-theme/test-theme-dev-bundle/pom.xml
  flow-tests/test-application-theme/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0, express-build

#15587 chore: Sync versions with Spring Boot 3.0.1
  flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/pom.xml
  pom.xml
Labels: +0.0.1

#15588 chore: Upgrade rollup plugins to latest (5.0.2)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15580 refactor: Move dev tools TS to vaadin-dev-server
  flow-client/src/test/frontend/vaadin-dev-tools-tests.js
  flow-client/webpack.tests.config.js
  flow-tests/test-dev-bundle/pom.xml
  vaadin-dev-server/src/main/resources/META-INF/frontend/License.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/copy-to-clipboard.js
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#15586 fix: Use current folder when prepare-frontend has not run
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Labels: +0.0.1

#15594 feat: Track where components are created and attached
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
  flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.0.1
