Repository vaadin/flow, pull requests merged in 2022-01, with the labels that each got.

#12654 test: remove duplicates from the module list
  scripts/computeMatrix.js
Labels: +0.0.1, target/9.0

#12440 feat: Bump minimum Java version to 11
  flow-client/pom.xml
  pom.xml
Labels: +0.0.1

#12612 feat: use new endpoint generator if available
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
Labels: fusion, +0.1.0

#12588 test: Let the machine choose a random port to avoid collisions
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/AbstractStatisticsTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/StatisticsSenderTest.java
Labels: +0.0.1, target/9.0

#12642 fix(Fusion): Spring Boot 2.4 string patterns request mapping compatibility
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionControllerConfiguration.java
Labels: fusion, +0.1.0, target/9.0

#12572 feat!: use npm by default
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Labels: fusion, +0.1.0

#12660 chore: Upgrade to Node 17 + npm 8.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#12657 feat: add possibility to set header values for StreamResource (#11860) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/StreamResourceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
Labels: +0.1.0, cherry pick

#12658 feat: add possibility to set header values for StreamResource (#11860) (CP: 2.7)
  flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/StreamResourceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
Labels: +0.1.0, cherry pick

#12659 fix: better exception for failing removal
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.1.0, target/2.7, target/9.0, target/2.8

#12512 feat: Run postinstall only for selected npm packages
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/frontend/fake-package-with-postinstall.json
  flow-tests/test-frontend/vite-basics/package-outside-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/package2-outside-npm/package.json
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.1.0

#12670 chore!: remove webpackTemplate and webpackGeneratedTemplate options
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#12598 chore: Only use jaxb-impl 2.3.5
  flow-data/pom.xml
  pom.xml
Labels: +0.1.0, target/2.7, target/9.0, target/2.8

#12675 fix: check if --openssl-legacy-provider required for Node
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Labels: +0.0.1, target/9.0

#12679 fix: check if --openssl-legacy-provider required for Node (#12675)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1, cherry pick

#12680 fix: check if --openssl-legacy-provider required for Node (#12675)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1, cherry pick

#12665 refactor: make isAttached iterative
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12635 feat: lock versions with npm overrides
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: fusion, +1.0.0

#12688 fix: Require Java 11 in bundles
  flow-client/bnd.bnd
  flow-data/bnd.bnd
  flow-dnd/bnd.bnd
  flow-html-components/bnd.bnd
  flow-lit-template/bnd.bnd
  flow-plugins/flow-plugin-base/bnd.bnd
  flow-polymer-template/bnd.bnd
  flow-push/bnd.bnd
  flow-server/bnd.bnd
  flow-tests/test-root-context/bnd.bnd
Labels: +0.0.1

#12700 fix: use configured push parameter
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12674 fix: remove <custom-style> and use registerStyles
  flow-server/src/main/java/com/vaadin/flow/component/dependency/CssImport.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Labels: +1.0.0

#12710 fix: add wepack dev server parameter --host=127.0.0.1
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1, target/2.7

#12701 fix: copy source maps for frontend resources
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/resources/dir-with-frontend-resources/META-INF/resources/frontend/resourceInFolder.js.map
  flow-server/src/test/resources/dir-with-modern-frontend/META-INF/frontend/resourceInFolder.js.map
  flow-server/src/test/resources/jar-with-frontend-resources.jar
  flow-server/src/test/resources/jar-with-modern-frontend.jar
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12689 fix: Always use defined node version
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.1.0, target/2.8

#12712 chore: remove usage of jcenter
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: testing, gradle, +0.0.1, target/9.0

#12724 chore: fix potential NPE in usagestatistics
  flow-server/src/main/java/com/vaadin/flow/internal/UsageStatistics.java
Labels: +1.0.0

#12720 chore: retry maven downloads for tyring to fix random network errors …
  .github/workflows/validation.yml
Labels: +0.0.1

#12726 fix: --openssl-legacy-provider also in build-frontend
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Labels: +0.1.0, target/9.0

#12715 fix: Remove read-only flag on copy
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFilesTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12695 fix: Always use defined node version
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +1.0.0

#12734 chore: update test package-lock
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1

#12727 chore: Download Atmosphere JS instead of having it in the project
  flow-push/pom.xml
  flow-push/src/main/resources/META-INF/resources/VAADIN/static/push/vaadinPush-min.js
  flow-push/src/main/resources/META-INF/resources/VAADIN/static/push/vaadinPush.js
  flow-push/src/main/templates/vaadinPush.js.tpl
  pom.xml
Labels: +0.0.1

#12716 fix: handle non versions in isUserChanged
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12702 fix: Reduce excessive endpoint mapping logging
  fusion-endpoint/src/main/java/com/vaadin/fusion/endpointransfermapper/EndpointTransferMapper.java
Labels: +1.0.0

#12738 fix: Upgrade to Atmosphere 2.7.3 and Atmopshere JS 3.1.3
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PushLongPollingWithPreserveOnRefreshIT.java
  pom.xml
Labels: +0.1.0

#12748 test: Use a separate backing file for each stats test
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/AbstractStatisticsTest.java
Labels: +0.1.0

#12751 test: Bind to localhost to ensure the port is free
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/StatisticsSenderTest.java
Labels: +0.0.1, target/9.0

#12749 fix: --openssl-legacy-provider also in build-frontend (#12726)
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
Labels: +0.1.0, cherry pick

#12755 chore: add controller package name to spring.factories
  fusion-endpoint/src/main/resources/META-INF/spring.factories
Labels: fusion, +0.0.1

#12733 fix: --openssl-legacy-provider also in build-frontend
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.1.0, target/2.7

#12728 Remove 'Fusion' prefixes from class names
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateEndpoint.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  fusion-endpoint/src/main/java/dev/hilla/Endpoint.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointProperties.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointUtil.java
  fusion-endpoint/src/main/java/dev/hilla/ExplicitNullableTypeCheckerHelper.java
  fusion-endpoint/src/main/java/dev/hilla/auth/CsrfChecker.java
  fusion-endpoint/src/main/java/dev/hilla/auth/CsrfIndexHtmlRequestListener.java
  fusion-endpoint/src/main/java/dev/hilla/auth/EndpointAccessChecker.java
  fusion-endpoint/src/main/java/dev/hilla/exception/EndpointException.java
  fusion-endpoint/src/main/java/dev/hilla/frontend/AbstractTaskEndpointGenerator.java
  fusion-endpoint/src/main/java/dev/hilla/frontend/EndpointGeneratorTaskFactoryImpl.java
  fusion-endpoint/src/main/java/dev/hilla/frontend/TaskGenerateEndpointImpl.java
  fusion-endpoint/src/main/java/dev/hilla/frontend/TaskGenerateOpenAPIImpl.java
  fusion-endpoint/src/main/java/dev/hilla/generator/typescript/CodeGenerator.java
  fusion-endpoint/src/main/java/dev/hilla/startup/EndpointsValidator.java
  fusion-endpoint/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  fusion-endpoint/src/main/resources/META-INF/spring.factories
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerConfigurationTest.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerMockBuilder.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerTest.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointUtilTest.java
  fusion-endpoint/src/test/java/dev/hilla/auth/EndpointAccessCheckerTest.java
  fusion-endpoint/src/test/java/dev/hilla/frontend/NodeTasksEndpointTest.java
  fusion-endpoint/src/test/java/dev/hilla/frontend/TaskGenerateEndpointTest.java
  fusion-endpoint/src/test/java/dev/hilla/generator/endpoints/AbstractEndpointGenerationTest.java
  fusion-endpoint/src/test/java/dev/hilla/rest/EndpointWithRestControllerTest.java
  fusion-endpoint/src/test/java/dev/hilla/rest/TestEndpoints.java
  fusion-endpoint/src/test/java/dev/hilla/startup/EndpointsValidatorTest.java
  fusion-endpoint/src/test/java/dev/hilla/typeconversion/BaseTypeConversionTest.java
  fusion-endpoint/src/test/java/dev/hilla/typeconversion/EndpointTestBean.java
  fusion-endpoint/src/test/java/dev/hilla/typeconversion/TestTypeConversionEndpoints.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: +1.0.0

#12754 test: Remove unused dependency
  flow-client/pom.xml
Labels: +0.0.1

#12760 test: Simplify and be more future proof by using Spring helpers
  fusion-endpoint/src/test/java/dev/hilla/EndpointUtilTest.java
Labels: +0.0.1

#12758 test: Make tests independent of system locale
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#12781 fix: Force an older babel version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12773 fix: Upgrade Atmosphere for OSGi compatibility
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1

#12779 test: replace maven-clean-plugin execution with flow:clean-frontend
  flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
Labels: +0.0.1

#12768 feat: Fallback to alternative node when preferred is unsupported
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.0.1

#12785 fix: use bundle-version instead of package version
  flow-server/bnd.bnd
Labels: OSGi, +0.0.1

#12788 fix: Force an older babel version (#12781)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick, target/2.7

#12790 fix: Force an older babel version (#12781)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick

#12784 fix: Fix serialization of a recently deserialized session
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
Labels: +0.0.1, target/9.0

#12797 Revert "fix: Force an older babel version"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12804 Revert "fix: Force an older babel version (#12781) (#12792)"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12803 Revert "fix: Force an older babel version (#12781)"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12805 test: Ignore generated index.html files inside tests
  .gitignore
Labels: +0.0.1

#12802 Revert "fix: Force an older babel version (#12781) (#12790)"
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12697 fix: remove duplicate builder execution
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  pom.xml
Labels: +0.0.1, target/2.7

#12813 test: Do not send any data from tests automatically
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/AbstractStatisticsTest.java
Labels: +0.0.1

#12782 feat: add task for generating client-side feature flags file
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
Labels: +0.1.0

#12809 fix: don't mention Webpack in error messages when Vite is used
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1

#12799 chore: Chromedriver 97
  drivers.xml
  flow-client/intern.json
Labels: +0.0.1

#12801 test: Delete seemingly unnecessary war deployment
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
Labels: +0.0.1

#12800 test: Delete seemingly unnecessary properties
  flow-tests/test-memory-leaks/src/test/java/com/vaadin/flow/memoryleaks/ui/RedeployLeakIT.java
Labels: +0.0.1

#12771 fix: join servlet context path to Vite base path in dev mode
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-context-path-production/frontend/themes/vite-context-path-production/styles.css
  flow-tests/test-frontend/vite-context-path-production/frontend/themes/vite-context-path-production/theme.json
  flow-tests/test-frontend/vite-context-path-production/pom.xml
  flow-tests/test-frontend/vite-context-path-production/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-context-path-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-context-path-production/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-context-path-production/src/test/java/com/vaadin/viteapp/ContextPathIT.java
  flow-tests/test-frontend/vite-context-path-production/vite.config.ts
  flow-tests/test-frontend/vite-context-path/frontend/themes/vite-context-path/styles.css
  flow-tests/test-frontend/vite-context-path/frontend/themes/vite-context-path/theme.json
  flow-tests/test-frontend/vite-context-path/pom.xml
  flow-tests/test-frontend/vite-context-path/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-context-path/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-context-path/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/ContextPathIT.java
  flow-tests/test-frontend/vite-context-path/vite.config.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
Labels: +0.0.1

#12821 feat!: rename fusion npm packages to hilla
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/main/resources/connect-client.default.template.ts
  fusion-endpoint/src/main/resources/dev/hilla/generator/EntityModelTemplate.mustache
  fusion-endpoint/src/test/java/dev/hilla/frontend/TaskGenerateEndpointTest.java
  fusion-endpoint/src/test/resources/dev/hilla/generator/expected-connect-client-custom.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/expected-connect-client-default.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/tsmodel/expected-TsFormEndpoint.ts
Labels: +0.0.1

#12731 fix: copy source maps for frontend resources (#12701) (CP: 2.7)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/resources/dir-with-frontend-resources/META-INF/resources/frontend/resourceInFolder.js.map
  flow-server/src/test/resources/dir-with-modern-frontend/META-INF/frontend/resourceInFolder.js.map
  flow-server/src/test/resources/jar-with-frontend-resources.jar
  flow-server/src/test/resources/jar-with-modern-frontend.jar
Labels: +1.0.0

#12729 fix: copy source maps for frontend resources (#12701) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/resources/dir-with-frontend-resources/META-INF/resources/frontend/resourceInFolder.js.map
  flow-server/src/test/resources/dir-with-modern-frontend/META-INF/frontend/resourceInFolder.js.map
  flow-server/src/test/resources/jar-with-frontend-resources.jar
  flow-server/src/test/resources/jar-with-modern-frontend.jar
Labels: +0.0.1

#12808 fix: Use service already assigned
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
Labels: +0.0.1, target/9.0, target/2.8

#12787 fix: install all packages from versions.json also when using pnpm
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1

#12829 fix: Log exception for closed socket
  flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
Labels: +0.0.1, target/9.0, target/2.8

#12791 feat!: Update to Testbench 8
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-root-context/pom.xml
  pom.xml
Labels: +1.0.0

#12378 feat: Add async mode to flush operation and API to turn it on
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
Labels: +0.1.0

#12568 feat: Add async mode to flush operation and API to turn it on
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
Labels: +0.1.0

#12840 test: speed up test significantly
  flow-tests/test-application-theme/test-theme-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ThemeLiveReloadIT.java
Labels: +0.0.1

#12822 fix: reliable deletion of node_modules
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0, target/9.0

#12845 chore: do not run sonar actions but let TC to do it
  .github/workflows/sonar.yml
Labels: +0.0.1

#12849 fix: do not store UI reference in DataCommunicator
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.0.1, target/9.0, target/2.8

#12843 fix: Check if node_modules exists
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/9.0

#12817 test: ModalDialogIT Wait for child element presence before performing assertions
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
Labels: +0.0.1

#12830 test: DialogShortcutIT Wait for child element presence before performing assertions
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DialogShortcutIT.java
Labels: +0.0.1, target/2.7, target/2.8

#12847 fix: Improve exception message if dev server startup fails
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java
Labels: +0.0.1

#12844 fix: update node-fetch to 2.6.7
  flow-client/package.json
Labels: +0.0.1, target/9.0

#12774 chore: Remove flow-component-demo-helpers
  flow-component-demo-helpers/.dtrackignore
  flow-component-demo-helpers/pom.xml
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/Card.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoServer.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/ComponentDemoTest.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoNavigationBar.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/DemoView.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/SourceCodeExample.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/SourceContent.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/SourceContentResolver.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/TabbedComponentDemoTest.java
  flow-component-demo-helpers/src/main/java/com/vaadin/flow/demo/WhenDefinedManager.java
  flow-component-demo-helpers/src/main/resources/META-INF/resources/frontend/src/css/component-card.css
  flow-component-demo-helpers/src/main/resources/META-INF/resources/frontend/src/css/demo.css
  flow-component-demo-helpers/src/main/resources/META-INF/resources/frontend/src/css/prism.css
  flow-component-demo-helpers/src/main/resources/META-INF/resources/frontend/src/css/sources.css
  flow-component-demo-helpers/src/main/resources/META-INF/resources/frontend/src/script/prism.js
  pom.xml
Labels: +0.0.1

#12852 fix: Check if node_modules exists (#12843)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.1.0, cherry pick

#12856 fix: update node-fetch to 2.6.7 (#12844)
  flow-client/package.json
Labels: +0.0.1, cherry pick

#12859 test: Delete unnecessary scanInterval
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
Labels: +0.0.1

#12793 fix: handle faulty imports
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +1.0.0, target/2.7, target/9.0, target/2.8

#12858 chore: update junit versions
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
Labels: +0.0.1, target/9.0

#12868 test: Log warning about not finding vaadin_versions only once
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
Labels: +0.0.1

#12853 test: Adapt ComponentThemeLiveReloadIT for changes in vaadin-text-field structure
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Labels: +0.0.1

#12867 test: Rename test to be more descriptive
  flow-tests/pom.xml
  flow-tests/test-redeployment/context.xml
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/SessionValueView.java
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/SessionValueIT.java
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
Labels: +0.0.1

#12865 test: collect Vite context path tests in one package
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-context-path-production/frontend/themes/vite-context-path-production/styles.css
  flow-tests/test-frontend/vite-context-path-production/frontend/themes/vite-context-path-production/theme.json
  flow-tests/test-frontend/vite-context-path-production/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-context-path-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-context-path-production/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-context-path-production/src/test/java/com/vaadin/viteapp/ContextPathIT.java
  flow-tests/test-frontend/vite-context-path-production/vite.config.ts
  flow-tests/test-frontend/vite-context-path/pom-production.xml
Labels: +1.0.0, vite

#12866 fix: handle faulty imports (#12793)
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.1.0, cherry pick, target/2.7

#12864 fix: handle faulty imports (#12793)
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ImportExtractor.java
  flow-server/src/test/java/com/vaadin/flow/internal/StringUtilTest.java
Labels: +0.1.0, cherry pick

#12874 fix: reliable deletion of node_modules
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0, cherry pick, target/2.7

#12863 fix: update css-loader
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Labels: +0.0.1

#12879 test: Increase npm timeout
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#12878 chore: Make sonar happier
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
Labels: +0.0.1

#12882 fix: Do not log conversion error in StringToUuidConverter
  flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12885 fix: Do not log conversion error in StringToUuidConverter (#12882) (CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
Labels: +0.0.1

#12886 fix: Do not log conversion error in StringToUuidConverter (#12882) (CP: 2.8)
  flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
Labels: +0.0.1

#12820 chore: update readme
  README.md
Labels: +0.0.1

#12890 chore: Upgrade workbox-build to 6.4.2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12875 fix: add scope to dependencies (#12500) (#12527)
  flow-maven-plugin/pom.xml
Labels: +0.0.1, cherry pick

#12898 chore: Upgrade to Vite v2.8.0-beta.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite

#12895 refactor: add `vaadin:` prefix to internal Vite plugins
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, vite
