Repository vaadin/flow, pull requests merged in 2022-06, with the labels that each got.

#13886 Use webpack 5 for tests to avoid md4 related issues
  flow-client/package.json
  flow-client/webpack.tests.config.js
Labels: +0.0.1, target/23.1

#13888 chore: let action to pick the latest node 16.
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.0, target/23.1

#13890 chore: let action pick the latest Node 16 (CP: 23.1)
  .github/workflows/validation.yml
Labels: +0.0.1

#13891 chore: let action pick the latest Node 16 (CP: 23.0)
  .github/workflows/validation.yml
Labels: +0.0.1

#13894 chore: Update TestBench version
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, target/23.0, target/23.1

#13879 fix: Fix Vite to use vaadin/bundles on Windows
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.0, target/23.1

#13893 chore: update Hilla dependency versions
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
Labels: +0.0.1, target/23.1

#13895 chore: Update TestBench version (#13894) (CP: 23.1)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, target/23.0

#13903 Annotate OptionalParameter with @Nullable
  flow-server/src/main/java/com/vaadin/flow/router/OptionalParameter.java
Labels: +0.1.0, Contribution

#13911 test: Upgrade to TestBench 8.0.2
  pom.xml
Labels: +0.0.1, target/23.0, target/23.1

#13902 feat: notify component about identifier provider changes
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/IdentifierProviderChangeEvent.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +0.1.0, Contribution

#13914 test: Upgrade to TestBench 8.0.2 & bump webdrivermanager from 5.1.1 to 5.2.0 (#13911) (#13869)
  pom.xml
Labels: +0.0.1

#13915 test: Upgrade to TestBench 8.0.2 & bump webdrivermanager from 5.1.1 to 5.2.0 (#13911) (#13869)
  pom.xml
Labels: +0.0.1

#13908 fix: Include RouteAliases in RouteNotFoundError message
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterIT.java
Labels: +0.0.1, Contribution, target/9.0, target/23.0, target/23.1

#13883 fix: Use KeyMapper by default to generate unique keys
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +0.0.1

#13917 fix: Run postinstall for the project itself when there is a script defined
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/PostinstallIT.java
Labels: +0.0.1, target/23.1

#13938 Revert "feat: Annotate OptionalParameter with @Nullable (#13903)"
  flow-server/src/main/java/com/vaadin/flow/router/OptionalParameter.java
Labels: +0.1.0

#13932 chore: Change license checker feature flag to concern only offline
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#13923 fix: Add missing media-queries and resources for PWA splash screen
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-server/src/test/java/com/vaadin/flow/server/PwaRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#13950 fix: Add missing media-queries and resources for PWA splash screen (#13923)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/PwaRegistryTest.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1, target/2.8

#13942 fix: Scan Hilla packages by default
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: hilla, +0.1.0, target/23.0, target/23.1

#13954 fix: Update webpack-cli to a latest version
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#13959 fix: Update webpack-cli to a latest version (#13954)(CP: 9.0)
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Labels: +0.0.1, cherry pick

#13957 fix: Update webpack-cli to a latest version (#13954)(CP: 23.1)
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Labels: +0.0.1, cherry pick

#13958 fix: Update webpack-cli to a latest version (#13954)(CP: 23.0)
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Labels: +0.0.1, cherry pick

#13906 feat: Add API to modify a view after UI.navigate
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  pom.xml
Labels: +0.1.0, Contribution

#13937 chore: Upgrade to latest esbuild-loader
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: hilla, +0.0.1, target/23.1

#13977 chore: Pin org.osgi.service.prefs version
  flow-client/pom.xml
Labels: +0.0.1, target/1.0, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#13973 chore: update timeout to 20 minutes
  .github/workflows/validation.yml
Labels: +0.0.1

#13986 chore: update unit tests timeout to 20 minutes
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.0, target/23.1

#13940 feat: enable components to notify binder when validation state changes
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasValidator.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/ValidationStatusChangeEvent.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/ValidationStatusChangeListener.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestHasValidatorDatePicker.java
Labels: +1.0.0, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#13878 feat: add AbortSignal parameter to generated Hilla endpoint methods
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/main/resources/dev/hilla/generator/TypeScriptApiTemplate.mustache
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/collectionendpoint/expected-CollectionEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/complexhierarchyendpoint/expected-ComplexHierarchyEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/complextypes/expected-ComplexTypeEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/datetime/expected-DateTimeEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/denyall/expected-DenyAllEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/enumtype/expected-EnumEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/flux/expected-FluxTestEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/inheritedmodel/expected-InheritedModelEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/iterableendpoint/expected-IterableEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/json/expected-GeneratorAnonymousAllowedTestClass.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/json/expected-JsonTestEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/mappedtype/expected-MappedTypeEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/model/expected-ComplexReturnTypeEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/model/expected-ComplexTypeParamsEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/model/expected-ModelEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/modelpackage/expected-ModelPackageEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/modelpackage/expected-SubModelPackageEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/nonnullable/expected-NonNullableEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/nonnullapiendpoint/expected-NonNullApiEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/pageendpoint/expected-PageEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/reservedwordmethod/expected-ReservedWordMethodEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/sameclassname/expected-SameClassNameEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/selfreference/expected-SelfReferenceEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/superclassmethods/expected-PersonEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-FooBarEndpoint.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-default-class-no-tag.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-first-class-multiple-tags.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-multiple-lines-description.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-no-tsdoc.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-partly-tsdoc.ts
  fusion-endpoint/src/test/resources/dev/hilla/generator/openapi/expected-second-class-multiple-tags.ts
Labels: hilla, +0.0.1

#13936 refactor: make vaadin-dev-server not depend on fusion-endpoint
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
Labels: hilla, +0.0.1, Contribution

#14000 chore: Do not print warnings about the push script
  flow-push/pom.xml
Labels: +0.0.1, target/23.1

#14015 chore: upgrade to TB 8.1.0.alpha7
  pom.xml
Labels: +0.0.1

#14012 feat: Make the Router lookup method available for others to use
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
Labels: +0.1.0

#14023 chore: Remove non thread safe plugin that is not even used
  pom.xml
Labels: +0.0.1, target/23.1

#13960 fix: Do not expose /vaadinServlet/* publicly
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringServlet.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringServletTest.java
Labels: +0.0.1

#14010 test: Fix test scopes
  flow-tests/test-application-theme/test-reusable-as-parent-vite/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
  flow-tests/test-application-theme/test-theme-reusable-vite/pom.xml
  flow-tests/test-application-theme/test-theme-reusable/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
  flow-tests/test-frontend/vite-basics/pom.xml
  flow-tests/test-frontend/vite-context-path/pom.xml
  flow-tests/test-frontend/vite-production/pom.xml
  flow-tests/test-frontend/vite-test-assets/pom.xml
  flow-tests/test-root-context/pom.xml
  flow-tests/test-themes/pom.xml
Labels: +1.0.0, target/23.1

#14002 feat: Find a parent component with a given type
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.1.0, Contribution

#14028 fix: Do not rely on web components calling the license checker
  flow-client/src/main/frontend/License.ts
  flow-client/src/main/frontend/vaadin-dev-tools.ts
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
Labels: +1.0.0

#14014 fix: separate core and commercial components version files
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.1.0

#14045 fix: Set preventAssignment to true to avoid warnings
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.1

#14052 fix: Make SW generation work with Vite 3
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#14058 fix: rename global js constant conflicting with require.js
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-tests/test-root-ui-context/src/main/java/com/vaadin/flow/uitest/servlet/ApplicationRunnerServlet.java
Labels: +0.0.1

#14054 chore: Bump Spring Boot to 2.7.1
  pom.xml
Labels: +0.0.1, target/23.1

#14065 chore: Bump Spring Boot to 2.7.1 (#14054)
  pom.xml
Labels: +0.0.1

#14040 fix: Fix ip binding problem with Vite 3
  flow-server/src/main/resources/vite.generated.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.0.1

#14036 fix: Use correct view when using eagerServerLoad
  flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-tests/pom.xml
  flow-tests/test-eager-bootstrap/pom.xml
  flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/HelloView.java
  flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/RootView.java
  flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/BasicViewsIT.java
  flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/LowLevelFetchIT.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#14078 fix: Use correct view when using eagerServerLoad (#14036) (CP: 9.0)
  flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-tests/pom.xml
  flow-tests/test-eager-bootstrap/pom.xml
  flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/HelloView.java
  flow-tests/test-eager-bootstrap/src/main/java/com/vaadin/flow/eagerbootstrap/RootView.java
  flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/BasicViewsIT.java
  flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/LowLevelFetchIT.java
Labels: +0.0.1

#14079 test: add tests for handling separate versions in NodeUpdater
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.0.1

#14083 chore: update log message after versions.json separation
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
Labels: +0.0.1

#14005 chore: Simplify Gradle build so no dependency copying is needed
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#14085 chore: Upgrade to Polymer 3.5.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#14088 chore: Simplify Gradle build so no dependency copying is needed (#14005)(CP: 23)
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1

#14089 chore: Simplify Gradle build so no dependency copying is needed (#14005) (CP: 9.0)
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/pom.xml
Labels: +0.0.1

#14099 fix: Support Vite 3 ping URL
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
Labels: +0.0.1

#14100 fix: Set Vite hot reload port to match the server port
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#14093 fix: separate core and commercial components version files
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.1.0, target/2.7, target/9.0, target/2.8, target/23.0

#14097 chore: Upgrade Lit to 2.2.6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#14105 chore: Use latest vite-plugin-checker
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#14103 fix: ignore quotes in CSS url directive
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-frontend/vite-basics/frontend/themes/vite-basics/styles.css
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
Labels: +0.0.1, target/23.1

#14034 Improving UX of Query parameters
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
  flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouteAndQueryParametersView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouteAndQueryParametersIT.java
Labels: +0.1.0, Contribution

#14108 chore: upgrade TB to 8.1.0.alpha8
  pom.xml
Labels: +0.0.1

#14112 fix: Always set the strict offline flag and do not rely on default value
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1

#14113 chore: fix HasValidator javadoc
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasValidator.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14109 fix: ignore quotes in CSS url directive (#14103) (CP 23.1)
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-tests/test-frontend/vite-basics/frontend/themes/vite-basics/styles.css
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
Labels: +0.0.1, cherry pick
