Repository vaadin/flow, pull requests merged in 2022-09, with the labels that each got.

#14452 chore: Mainly use Implementation-version
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1

#14448 fix!: Security upgrade of org.jsoup:jsoup to 1.15.3
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  pom.xml
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0

#14456 chore: Update TestBench to 8.1.0
  pom.xml
Labels: +0.0.1

#14458 fix!: Security upgrade org.jsoup:jsoup to 1.15.3
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  pom.xml
Labels: +0.0.1

#14459 fix!: Security upgrade org.jsoup:jsoup to 1.15.3
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  pom.xml
Labels: +0.0.1

#14460 fix: Do not handle Vite special URLs in the service worker
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
Labels: +0.0.1

#14457 refactor: remove unused code
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#14466 chore: Upgrade license checker to 1.7.2
  pom.xml
Labels: +0.0.1

#14472 Make Lit import rewrites lazy
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-production/frontend/lit-invalid-imports.ts
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
Labels: +0.0.1

#14471 chore: Upgrade to Vite 3.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#14480 fix!: Security upgrade org.jsoup:jsoup to 1.15.3
  flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java
  pom.xml
Labels: +0.0.1

#14481 Mention Html component in Label's JavaDoc
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Label.java
Labels: +0.0.1

#14486 Add ?inline for CSSimports so they do not end up in the document
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-tests/test-frontend/vite-basics/frontend/cssimport-textfield.css
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
Labels: +0.0.1

#14488 chore: Upgrade to license checker 1.8.1
  pom.xml
Labels: +0.0.1

#14491 chore: update the GHA branch (23.2)
  .github/workflows/validation.yml
Labels: +1.0.0

#14493 chore: Sync test Lumo class with the real Lumo class
  flow-tests/test-lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
Labels: +0.0.1

#14461 test: remove spring-data-jpa and h2 db from ITs
  flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/DataGenerator.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityUtils.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/Account.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/AccountRepository.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/UserInfo.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/UserInfoRepository.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/AccountService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/BankService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/service/UserInfoService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
Labels: +0.0.1

#14494 test: Run tests using 23.2.0
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
Labels: +0.0.1

#14489 Log why Vite recompiles using debug level and a separate logger
  flow-server/src/main/resources/vite.generated.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java
Labels: +0.0.1, target/23.2

#14504 chore: add JDK names in GH actions config file
  .github/workflows/validation.yml
  flow-plugins/pom.xml
  pom.xml
  scripts/computeMatrix.js
Labels: +1.0.0

#14502 chore: Upgrade to license checker 1.9.0
  pom.xml
Labels: +0.0.1, target/23.2

#14501 fix: set load-on-startup for automatically registered Vaadin servlet
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Labels: +0.0.1, target/23.2

#14519 chore: Align TS version in flow-client with flow-server
  flow-client/package.json
Labels: +0.0.1

#14522 chore: Update platform and web-components versions
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1

#14487 feat: Allow setting content of the Html component
  flow-server/src/main/java/com/vaadin/flow/component/Html.java
  flow-server/src/test/java/com/vaadin/flow/component/HTMLTest.java
Labels: +0.1.0, Contribution

#14516 fix: Remove presence check on item refresh
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
Labels: +0.1.0

#14533 chore: Log theme plugin debug info as debug
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
Labels: +0.0.1

#14478 fix: Be more sensible when adding changes to list of pending changes
  flow-server/src/main/java/com/vaadin/flow/internal/change/AbstractListChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/change/ListAddChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
Labels: +0.1.0, Contribution, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14548 chore: update NpmPackage.version javadocs
  flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
Labels: +0.1.0

#14527 fix: Added support for custom frontendDirectory in TaskCopyTemplateFiles
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFilesTest.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-templates/test-form.js
  flow-tests/test-frontend/vite-production-custom-frontend/pom.xml
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/littemplate/TestForm.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/view/TestView.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  scripts/computeMatrix.js
Labels: +0.1.0, target/9.0, target/23.1, target/23.2

#14559 fix: Added support for custom frontendDirectory in TaskCopyTemplateFiles (#14527) (CP 9.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-production-custom-frontend/.pnpmfile.cjs
  flow-tests/test-frontend/vite-production-custom-frontend/frontend-custom/lit-templates/test-form.js
  flow-tests/test-frontend/vite-production-custom-frontend/pom.xml
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/littemplate/TestForm.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/main/java/com/vaadin/viteapp/view/TestView.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-production-custom-frontend/vite.config.ts
  flow-tests/test-frontend/vite-production-custom-frontend/vite.generated.ts
  scripts/computeMatrix.js
Labels: cherry pick

#14541 fix: adapt iPad detection for iOS 15
  flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
  flow-server/src/test/java/com/vaadin/flow/component/page/ExtendedClientDetailsTest.java
Labels: +0.1.0

#14547 fix: adapt iPad detection for iOS 15
  flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
  flow-server/src/test/java/com/vaadin/flow/component/page/ExtendedClientDetailsTest.java
Labels: +0.0.1, target/2.7

#14529 chore: remove not needed dependency since it comes from flow-server
  flow-plugins/flow-maven-plugin/pom.xml
Labels: +0.0.1

#14463 GitHub Workflows security hardening
  .github/workflows/validation.yml
Labels: +0.0.1, Contribution

#14536 fix: add build resource dir to classpath element to scan
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
Labels: +0.0.1, target/9.0, target/23.1, target/23.2

#14566 fix: add build resource dir to classpath element to scan (#14536) (CP: 9.0)
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
Labels: +0.1.0, cherry pick

#14560 chore: Read default dependencies from a package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/webpack/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +1.0.0

#14574 chore: GitHub Workflows security hardening (#14463) (CP: 9.0)
  .github/workflows/validation.yml
Labels: +0.1.0

#14568 test: fixed vaadin-themable-mixin version
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1

#14569 test: fixed vaadin-themable-mixin version
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1

#14578 test: Make test more stable
  flow-tests/test-root-ui-context/src/test/java/com/vaadin/flow/uitest/ui/push/AbstractClientServerCounterIT.java
Labels: +0.0.1

#14510 fix: Do not overwrite generated files with the same content
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractTaskClientGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractTaskClientGeneratorTest.java
Labels: +0.0.1

#14571 feat: Allow rerouting to an external URL
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.1.0

#14581 chore: Update automatically installed Node version to 16.17
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.1.0

#14584 test: Update Node in test
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0

#14576 fix: Redirect to login page without showing the 404 page
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
Labels: +0.1.0

#14594 chore: Revert "chore(deps)!: bump slf4j.version from 1.7.36 to 2.0.0 (#14409)"
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  pom.xml
Labels: +0.0.1

#14596 fix: Use KeyMapper by default to generate unique keys (#13883) (CP:2.8)
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +0.0.1, cherry pick

#14595 fix: use FrontendUtils::deleteNodeModules (#12905) (CP:2.8)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
Labels: +0.0.1, cherry pick, target/2.7

#14597 fix: update css-loader(#12863)(CP:2.8)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick, target/2.7

#14586 fix: Be more sensible when adding changes to list of pending changes (#14478) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/internal/change/AbstractListChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/change/ListAddChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/NodeListAddRemoveTest.java
Labels: +0.1.0, cherry pick, target/2.7

#14577 Unify VaadinWebSecurityConfigurerAdapter and VaadinWebSecurity
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#14613 chore: fix gradle profile activation
  flow-plugins/pom.xml
Labels: +0.0.1, target/9.0, target/23.1, target/23.2

#14556 fix: sort classes by name in ReflectionsClassFinder
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/server/scanner/ReflectionsClassFinderTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14588 chore: remind Flow view must grant anonymous access if using setLoginView with path
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1, target/9.0, target/23.1, target/23.2

#14626 chore: remind Flow view must grant anonymous access if using setLoginView with path (#14588) (CP: 23.1)
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1, cherry pick, target/9.0

#14614 fix: Redirect to the correct server view also when coming from a non-root URL
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LoginView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
Labels: +0.1.0

#14634 chore: Upgrade to Node 16.17.1 with security fixes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/2.8, target/23.2

#14640 chore: Upgrade Node to 14.20.1 with security fixes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/2.7

#14637 chore(deps): bump byte-buddy from 1.12.14 to 1.12.17 (#14599)
  pom.xml
Labels: +0.0.1

#14607 chore: log initialization time for PWARegistry
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
Labels: +0.0.1

#14523 fix: Fix navigation to secured view with oauth2 without router-ignore
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessAnnotationCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandlerTest.java
Labels: +0.0.1

#14652 chore: Use <code> tag rather than <tt> in javadoc
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
Labels: +0.0.1

#14590 fix: Make linking to packages in the file system work (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, cherry pick

#14591 chore: Only use jaxb-impl 2.3.5 (#12598) (CP: 2.8)
  flow-data/pom.xml
  pom.xml
Labels: +0.0.1, cherry pick, target/2.7

#14618 test: Test Spring Boot behind a reverse proxy
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-reverseproxy/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-reverseproxy/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reverseproxy/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/Proxy.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/AbstractSpringTest.java
  scripts/computeMatrix.js
Labels: +0.0.1

#14656 test: Test Spring Security behind a reverse proxy
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/test/java/com/vaadin/flow/internal/UrlUtilTest.java
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/src/main/java/com/vaadin/flow/spring/flowsecurityreverseproxy/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/src/test/java/com/vaadin/flow/spring/flowsecurityreverseproxy/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityUtils.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
Labels: +0.1.0

#14660 fix: Use es2020 for Vite, es2019 for webpack
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/main/resources/tsconfig.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
Labels: +0.1.0, target/23.2

#14666 test: Extract Spring test helpers to a helpers package
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-helpers/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/spring/test/DummyOAuth2Server.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/spring/test/Proxy.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/test/java/com/vaadin/flow/spring/test/AbstractSpringTest.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/test/java/com/vaadin/flow/spring/test/SpringBootOnly.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-reverseproxy/src/test/java/com/vaadin/flow/spring/flowsecurityreverseproxy/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  scripts/computeMatrix.js
Labels: +0.1.0

#14638 fix: Only map websockets to servlet path and not any sub paths
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-reverseproxy/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/CustomWebSocket.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/CustomWebSocketIT.java
  flow-tests/vaadin-spring-tests/test-spring-war/pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
Labels: +0.0.1

#14629 feat: Adapt to a new auto configuration in Spring Boot
  vaadin-spring/src/main/resources/META-INF/spring.factories
  vaadin-spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: +1.0.0, Contribution

#14635 chore: Upgrade to Node 18
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.1.0

#14672 chore: update component version to 23.3.0-alpha2
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
Labels: +0.0.1

#14676 fix: Only map websockets to servlet path and not any sub paths (#14638) (CP 23.2)
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/CustomWebSocket.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/CustomWebSocketIT.java
  flow-tests/vaadin-spring-tests/test-spring-war/pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
Labels: +0.1.0

#14631 feat: Register VaadinSecurityContextHolderStrategy as a bean
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +1.0.0, Contribution

#14675 fix: Make paths work as version numbers in @NpmPackage
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1, target/23.2

#14668 test: fix TaskCopyTemplateFilesTest for windows (#14667)
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFilesTest.java
Labels: testing, +0.0.1, windows, target/23.1, target/23.2

#14681 fix: make system property feature flag value always override stored one
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Labels: +0.0.1, target/23.2

#14632 fix: Do not use a fixed download root
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14691 fix: Do not use a fixed download root (#14632)
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#14647 fix: Cancel previous flush request if new one is forced
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.0.1

#14678 fix: Throw exception if Vite and deprecatedV14Bootstrapping are used
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-tests/test-root-ui-context/src/main/resources/vaadin-featureflags.properties
Labels: +1.0.0, target/23.2

#14705 fix: Cancel previous flush request if new one is forced (#14647) (CP: 2.8)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.0.1, cherry pick, target/2.7

#14704 fix: Do not use a fixed download root (#14632)
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Labels: +0.0.1, cherry pick, target/2.7

#14702 [Snyk] Upgrade com.typesafe.akka:akka-actor_2.13 from 2.6.19 to 2.6.20
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
Labels: +0.0.1

#14696 fix: Write version.json from the currently constructed package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +1.0.0, target/23.2

#14708 chore: call a String a String
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#14711 fix: Cancel previous flush request if new one is forced (#14647) (#14705) (CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
Labels: +0.0.1, cherry pick
