Repository vaadin/flow, pull requests merged in 2022-03, with the labels that each got.

#13172 fix: remove home node_modules before install
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
Labels: +0.0.1, target/23.0

#13177 Fix @CssImport for Vite
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-tests/test-application-theme/test-theme-component-live-reload/src/main/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadView.java
  flow-tests/test-frontend/vite-basics/frontend/cssimport-textfield.css
  flow-tests/test-frontend/vite-basics/frontend/cssimport.css
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
  flow-tests/test-frontend/vite-test-assets/pom.xml
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/ThemableTextField.java
Labels: +0.0.1, vite, target/23.0

#13182 test: Fix test so that it is not slow and broken
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadIT.java
Labels: +0.0.1, target/9.0, target/23.0

#13143 fix: configure Spring Security to handle vaadin.urlMapping
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurityurlmapping/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/test/java/com/vaadin/flow/spring/flowsecurityurlmapping/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/.gitignore
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/frontend/connect-client.ts
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/ElementsEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/PublicEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/SessionEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/UserInfoEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurityurlmapping/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/test/java/com/vaadin/flow/spring/fusionsecuritycontextpath/SecurityIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
  scripts/computeMatrix.js
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
Labels: +0.1.0, target/23.0

#13186 chore: Update spring-boot.version to 2.6.4
  pom.xml
Labels: +0.0.1, target/23.0

#13158 fix: let vaadinPush.js script always be served by Vaadin
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ActivatePushView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VaadinPushScriptIT.java
Labels: +0.0.1, target/23.0

#13174 fix: Alter handling of cases where key value is not present
  flow-server/src/main/java/com/vaadin/flow/component/Key.java
Labels: +0.1.0, target/9.0, target/23.0

#13147 chore: Upgrade to Vite 2.8.6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite, target/23.0

#13212 Never save /error as the navigation target after login
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCache.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCacheTest.java
Labels: +0.0.1, target/23.0

#13213 chore: Remove unused imports
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ActivatePushView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurityurlmapping/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/UserInfoEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurityurlmapping/Application.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#13189 fix: do not clean manual dev references
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1, target/23.0

#13218 test: Properly lock component versions in tests
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
Labels: +0.0.1, need to pick manually 23.0

#13227 test: Properly lock component versions in tests (#13218) (CP: 23.0)
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
Labels: +0.0.1

#13228 chore: Fix code smells
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1, target/23.0

#13225 test: Add missing plugin version
  flow-tests/test-redeployment/pom.xml
Labels: +0.0.1, target/23.0

#13210 fix: Include vaadin-spring in flow-bom
  flow-bom/pom.xml
Labels: +0.0.1, target/23.0

#13223 fix: Always lock chokidar version to avoid chokidar 2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1, target/23.0

#13217 fix: Use configured error path instead of hard coded one
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCache.java
Labels: +0.0.1, target/23.0

#13220 fix: Do not assume a tool is broken if it outputs to stderr
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsLocator.java
Labels: +0.0.1, target/23.0

#13167 fix: check postinstall before run
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, target/23.0

#13214 fix: Do not accidentally invoke a global node through postinstall scripts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/23.0

#13134 fix: Allow all Java features when parsing endpoint code
  .github/workflows/validation.yml
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/frontend/index.html
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/frontend/index.ts
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/frontend/test-component.ts
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/pom.xml
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/main/java/com/vaadin/flow/connect/AppEndpoint.java
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/main/java/com/vaadin/flow/connect/Application.java
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/src/test/java/com/vaadin/flow/connect/AppViewIT.java
  fusion-endpoint/src/main/java/dev/hilla/generator/OpenAPIObjectGenerator.java
Labels: hilla, +0.0.1, target/23.0

#13183 test: Restored BeanBinderTest with tests for select components
  flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/testcomponents/TestSelectComponent.java
Labels: +0.0.1

#13239 fix: Use configured error path instead of hard coded one (#13217)
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCache.java
Labels: +0.0.1

#13236 chore: Upgrade to Vite 2.8.6 (#13147)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +1.0.0

#13209 fix: Do not load service worker with Vite in 23.0
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1

#13245 test: Delete unnecessary version
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
Labels: +0.0.1

#13229 chore: Improve resynchronization error message
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
Labels: +0.0.1, target/23.0

#13243 chore: Merge duplicate properties
  flow-data/pom.xml
  fusion-endpoint/pom.xml
  pom.xml
Labels: +0.0.1

#13244 chore: Merge Spring version properties
  flow-tests/test-redeployment/pom.xml
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-endpoints-custom-client/pom.xml
  flow-tests/vaadin-spring-tests/test-endpoints-latest-java/pom.xml
  flow-tests/vaadin-spring-tests/test-endpoints/pom.xml
  flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-scan/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-undertow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-jwt/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
  fusion-endpoint/pom.xml
  pom.xml
  vaadin-spring/pom.xml
Labels: +0.0.1

#13248 test: Use Jetty 10 also in Gradle tests
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +0.0.1

#13246 fix: distinct dom-module ids
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
Labels: +0.0.1, target/23.0

#13255 Chore: upgrade hilla npmpackage to latest (CP: 23.0)
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
Labels: +0.0.1

#13252 chore: update hilla npmpackage to the latest
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
Labels: +0.0.1, target/23.0

#13258 test: fix test for jetty10
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +0.0.1

#13136 refactor: Make EndpointInvoker independent of http request
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointInvoker.java
  fusion-endpoint/src/main/java/dev/hilla/auth/EndpointAccessChecker.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerMockBuilder.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerTest.java
Labels: hilla, +0.0.1

#13249 chore: fix typo
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
Labels: +0.0.1, target/23.0

#13262 fix: Upgrade to new Atmosphere
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1, target/23.0

#13263 fix: shortcut event to modal component instead of UI
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
Labels: +0.0.1, target/23.0

#13264 fix: allow server registered return calls
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ReturnChannelMap.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ReturnChannelHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/ReturnChannelHandlerTest.java
Labels: +1.0.0, target/23.0

#13226 feat: Clarify multiple-AppShellConfigurator exception message
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +0.0.1, target/23.0

#13242 feat: Only send index.html when the browser requests a HTML page
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.1.0

#13272 fix: set shortcut listener to modal only if owner is child
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ModalDialogView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
Labels: +0.0.1, target/23.0

#13278 feat: Only send index.html when the browser requests a HTML page (#13242) (CP: 23.0)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.1.0

#13148 feat: add Vite support for exported web components
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentHtml.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/web-component.html
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentHtmlTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-embedded/.gitignore
  flow-tests/test-frontend/vite-embedded/frontend/index.html
  flow-tests/test-frontend/vite-embedded/frontend/themes/my-theme/styles.css
  flow-tests/test-frontend/vite-embedded/frontend/web-component.html
  flow-tests/test-frontend/vite-embedded/pom-production.xml
  flow-tests/test-frontend/vite-embedded/pom.xml
  flow-tests/test-frontend/vite-embedded/src/main/java/com/vaadin/viteapp/BasicComponent.java
  flow-tests/test-frontend/vite-embedded/src/main/java/com/vaadin/viteapp/PushComponent.java
  flow-tests/test-frontend/vite-embedded/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-embedded/src/main/webapp/basic-component.html
  flow-tests/test-frontend/vite-embedded/src/main/webapp/push-component.html
  flow-tests/test-frontend/vite-embedded/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
  flow-tests/test-frontend/vite-embedded/src/test/java/com/vaadin/viteapp/PushComponentIT.java
  flow-tests/test-frontend/vite-embedded/vite.config.ts
  fusion-endpoint/src/main/java/dev/hilla/generator/GenerationOutputDirectory.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
Labels: +0.1.0

#13179 feat: Add scrollIntoView method to Component
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/scroll/ScrollableView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/ScrollableViewIT.java
Labels: +1.0.0

#13282 fix: require Safari 14 minimum
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Labels: +0.0.1, target/23.0

#13259 test: Remove dependency to outdated oauth2 library
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-contextpath/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-boot-scan/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-scan/src/main/java/com/vaadin/flow/spring/scan/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-boot-undertow/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-undertow/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/DummyOAuth2Server.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/CoExistingSpringEndpointsIT.java
  flow-tests/vaadin-spring-tests/test-spring-war/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-white-list/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-white-list/src/main/java/com/vaadin/flow/spring/test/whitelist/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring/pom.xml
  flow-tests/vaadin-spring-tests/test-spring/src/main/java/com/vaadin/flow/spring/test/TestConfiguration.java
Labels: +0.0.1

#13254 fix: Don't use plugins through npm
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/main/resources/webpack.generated.js
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1, target/23.0

#13290 chore: update parent project to 2.0.5
  pom.xml
Labels: +0.0.1, target/2.7, target/9.0, target/23.0

#13294 chore: update parent project to 2.0.5 (#13290)
  pom.xml
Labels: +0.0.1, target/2.7

#13296 fix: avoid manipulate absolute stream resource URL in web-component mode
  flow-client/src/main/java/com/vaadin/client/WidgetUtil.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/StreamResourceExporter.java
  flow-tests/test-embedding/embedding-test-assets/src/main/java/com/vaadin/flow/webcomponent/servlets/CustomStreamResourceRegistryServlet.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/StreamResourceIT.java
  flow-tests/test-embedding/webapp/npm/streamResource.html
Labels: +0.0.1, target/2.7, target/2.8, target/23.0

#13291 fix: Warn for duplicate npm classes
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
Labels: +0.1.0, target/2.7, target/2.8, target/23.0

#13302 fix: Do not run any Maven goals automatically in Eclipse / VS Code
  flow-plugins/flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Labels: +0.0.1, target/23.0

#13309 fix: Warn for duplicate npm classes (#13291)
  flow-migration/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
Labels: +0.1.0, target/2.7

#13320 Only import the needed parts of lumo-styles
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1, target/9.0, target/23.0

#13312 Use Node 16.14.2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.0

#13323 fix: enable use of tsx files in add-ons
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/resources/jar-with-frontend-resources.jar
  flow-server/src/test/resources/jar-with-modern-frontend.jar
Labels: +0.0.1

#13333 chore: fix javadoc
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#13331 feat: Allow navigation with RouterLinks when inert
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUI.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/NavigationRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/NavigationRpcHandlerTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InertComponentIT.java
Labels: +0.0.1, target/23.0

#13328 test: fix join to explicitly use \n
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
Labels: +0.0.1

#13351 Add spacing between feature flag toggles
  flow-client/src/main/frontend/VaadinDevmodeGizmo.ts
Labels: +0.0.1, target/9.0, target/23.0

#13344 feat: Enable usage of pnpm >5
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#13340 fix!: Avoid duplicated field bindings
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
Labels: +0.0.1

#13357 chore: Update spring-boot.version to 2.6.5
  pom.xml
Labels: +0.0.1, target/23.0

#13361 chore: Update spring-boot.version to 2.6.5 (#13357)
  pom.xml
Labels: +0.0.1

#13363 Be more graceful with exceptions when reading usage stats
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsStorage.java
Labels: +0.0.1, target/9.0, target/23.0

#13372 chore: update test lock file for new versions
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1

#13365 chore: Upgrade to Atmosphere 2.7.3
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1

#13360 fix: change build-frontend goal phase
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Labels: +0.0.1, target/9.0, target/23.0

#13374 fix: validate node and npm on creation
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, target/23.0

#13359 fix: Upgrade to v2.9.0-beta.10
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#13384 fix: validate node and npm on creation (#13374)
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, cherry pick

#13388 test: test chrome and firefox version 100 useragents
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Labels: +0.0.1

#13386 fix: clean and do not add plugins
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
Labels: +0.0.1, target/23.0

#13390 fix: use bundle-version instead of package version (#12785)
  flow-server/bnd.bnd
Labels: +0.0.1, cherry pick, target/2.7

#13399 Upgrade to Vite 2.9.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#13343 fix: Always register EndpointController
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
Labels: hilla, +0.0.1
