Repository vaadin/flow, pull requests merged in 2022-08, with the labels that each got.

#14234 fix: support import without url keyword in theme generator
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1, target/23.1

#14237 fix: handle duplicated root entries in manifest
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
Labels: +0.0.1, target/23.1

#14209 feat: Introduce getListeners(eventType) method on com.vaadin.flow.component.ComponentEventBus
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentUtilTest.java
Labels: +0.1.0

#14242 fix: Make findAncestor return Object for backward compatibility
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +1.0.0

#14238 chore: Change Fusion to Hilla
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1, Contribution

#14233 feat: swallow exceptions on unparseable NPM package versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, Contribution

#14245 fix: configure Spring Security to handle vaadin.urlMapping (CP: 9.0)
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/DefaultMappingServlet.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/NestedMappingServlet.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerOnNestedMappingIT.java
Labels: +0.1.0, cherry pick

#14236 fix: Not show warning if no poll listener
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java
Labels: +0.0.1

#14252 Revert "test: workaround for internal selenium grid (#14174)"
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
  flow-tests/test-frontend/vite-pwa-production/pom.xml
  flow-tests/test-frontend/vite-pwa/pom.xml
Labels: +0.0.1

#14254 chore: use a patch user permission checking
  .github/workflows/validation.yml
Labels: +0.0.1

#14257 fix: let Vite process theme also on theme.js changes
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.1

#14260 fix: handle theme files creation and deletion with Vite
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.1

#14062 chore: Upgrade to Vite 3.0.2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-frontend/vite-pwa/src/test/java/com/vaadin/viteapp/MainIT.java
Labels: +1.0.0

#14271 test: open java.net module to allow reset of URL URLStreamHandlerFactory
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#14273 test: restore user.home system property after test
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/ProjectHelpersTest.java
Labels: +0.0.1

#14268 Fix: Allow windowResize during modality
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
Labels: +0.0.1

#14284 test: use devTools to set offline mode
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-ccdm-flow-navigation/vite.config.ts
Labels: +1.0.0

#14272 Revert "feat: add feature flag for Grid multi-sort priority (#14246)"
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0, Contribution

#14259 fix: Fix removal of windows junctions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14296 test: reduce flakyness of ccdm flow navigation tests
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/ReconnectIntervalConfigurer.java
  flow-tests/test-ccdm-flow-navigation/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  pom.xml
Labels: +1.0.0

#14298 fix: Fix removal of windows junctions (#14259)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0, cherry pick, target/2.7

#14297 fix: Fix removal of windows junctions (#14259)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.1.0, cherry pick

#14285 feat: add a feature flag for new field validation behavior
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0

#14289 feat: add feature flag for Hilla multi-module engine
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java
Labels: hilla, +1.0.0

#14295 fix: use rollup-plugin-postcss-lit with Vite
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +1.0.0

#14306 test: expect SocketException after stopping webpack handler
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
Labels: +1.0.0

#14305 test: Update npm version for test
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#14307 fix: regenerate theme files if not existing during Vite resolution
  flow-server/src/main/resources/vite.generated.ts
Labels: +1.0.0

#14299 test: Explicitly set dev mode for Vite basic tests
  flow-tests/test-frontend/vite-basics/pom.xml
Labels: +1.0.0

#14311 test: Update npm version for test
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: testing, +0.0.1

#14316 fix: Add missing general styles to webcomponents shadow dom
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
Labels: +0.1.0, target/23.0, target/23.1

#14276 fix: Ensure internal parent set to null when node is detached
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Labels: +1.0.0, Contribution

#14314 Haslabel v14 edited commit
  flow-server/src/main/java/com/vaadin/flow/component/HasLabel.java
  flow-server/src/test/java/com/vaadin/flow/component/HasLabelTest.java
Labels: +1.0.0

#14312 feat: Support Object type keys in Component#getTranslation (#14287) (CP 2.8)
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
Labels: +1.0.0

#14317 test: set --host Vite flag in development mode
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
Labels: +0.1.0

#14321 chore: remove map feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0

#14315 chore: Update testbench to 8.1.0.beta1
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-tests/test-pwa/src/test/java-webpack/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/OfflineWithCustomContextIT.java
  flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  pom.xml
Labels: +0.1.0

#14287 feat: Support Object type keys in Component#getTranslation
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
Labels: +1.0.0, Contribution

#14280 feat: HasLabel backporting to v14
  flow-server/src/main/java/com/vaadin/flow/component/HasLabel.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/HasLabelTest.java
Labels: +1.0.0, Contribution

#14320 chore: Remove unused reactor-bom
  pom.xml
Labels: +0.1.0

#14324 feat!: Fully enable new license checker
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#14318 chore: upgrade to webpack-dev-server 4.10.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.1.0

#14322 fix: Request Desktop Site feature with only MajorVersion
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Labels: +0.1.0, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14319 chore: Upgrade to Vite 3.0.4
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.1.0

#14325 fix: Add missing general styles to webcomponents shadow dom (#14316)(CP: 23.1)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
Labels: +0.1.0, target/23.0

#14335 chore: Upgrade to Lit 2.3.0
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#14337 Rename the parameter logoutUrl to logoutSuccessUrl
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#14345 chore: Update to testbench beta3
  pom.xml
Labels: +0.0.1

#14343 chore: update @NoTheme Javadoc
  flow-server/src/main/java/com/vaadin/flow/theme/NoTheme.java
Labels: +0.0.1

#14300 fix: Support Alpine by detecting OS using /etc/alpine-release
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/Platform.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/PlatformTest.java
Labels: +0.1.0, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14356 fix: Fix asset handling in Vite production mode
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/plugins/rollup-plugin-postcss-lit-custom/package.json
  flow-server/src/main/resources/plugins/rollup-plugin-postcss-lit-custom/rollup-plugin-postcss-lit.js
  flow-server/src/main/resources/plugins/webpack-plugins.json
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallWebpackPluginsTest.java
Labels: +0.1.0

#14358 fix(Vite): handle default exports from Vaadin bundle
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-basics/frontend/testscopemaploader.js
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-context-path/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-test-assets/packages/@testscope/all/all.js
  flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/package.json
  flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/src/lib.js
  flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/src/testscope-map.js
  flow-tests/test-frontend/vite-test-assets/packages/@testscope/map/testscope-map.js
  flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles-old/vaadin-bundle.json
  flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/vaadin-bundle.json
  flow-tests/test-frontend/vite-test-assets/packages/@vaadin/bundles/vaadin.js
Labels: hilla, +0.1.0

#14339 fix: run TaskGenerateHilla after npm install
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: hilla, +0.0.1

#14365 fix: Add missing general styles to webcomponents shadow dom (#14316) (CP: 23.0)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-tests/test-embedding/embedding-test-assets/src/test/java/com/vaadin/flow/webcomponent/NpmOnlyIndexIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
Labels: +0.1.0

#14361 chore: Upgrade to Node 16.17
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.1.0

#14367 fix: postpone http request on online listener
  flow-client/src/main/frontend/Flow.ts
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
Labels: +0.0.1

#14371 chore: Update PreserveOnRefresh's javadoc
  flow-server/src/main/java/com/vaadin/flow/router/PreserveOnRefresh.java
Labels: +0.0.1, Contribution, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14378 chore: VaadinWebSecurityConfigurerAdapter javadoc update
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#14383 fix: execute PushRequestHandler before DevModeHandler
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
Labels: +0.0.1

#14391 fix!: Avoid duplicated field bindings
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
Labels: +0.0.1, target/2.7

#14390 fix: initialize PwaHandler only once
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
Labels: +0.0.1, target/23.0, target/23.1

#14400 chore: Upgrade Vite 3.0.9
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#14397 fix: Not modify browser history if location has no hash
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14402 feat: Give an access to ViewAccessChecker in subclasses
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#14408 feat: allow to set a feature flag using a system property
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Labels: +0.1.0

#14357 fix!: Revert always load static files from context root (#13795)
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/servlets/ServletWithPath.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test-webpack/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VaadinPushScriptIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationUrlMappedTest.java
Labels: +1.0.0

#14423 fix: hange prefix to `vaadin.` for feature flag system properties
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0

#14425 Revert "test: Add VAADIN mapping to OSGi servlet registrations (#13855)"
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1

#14426 fix: Make frontend servlet check more tolerant
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
Labels: +0.0.1

#14424 chore: [Snyk] Security upgrade org.jsoup:jsoup from 1.15.2 to 1.15.3
  pom.xml
Labels: +0.0.1

#14389 fix: No client updates when Element::setText does nothing
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +0.0.1, Contribution, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14437 Revert "fix: No client updates when Element::setText does nothing (#14389)
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +0.0.1

#14436 fix: Never cache the "waiting for frontend build" page
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#14418 feat!: throw exception if webpack config file exist and running with Vite
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingVite.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingViteTest.java
  flow-tests/test-application-theme/test-theme-component-live-reload/webpack.config.js
Labels: +0.1.0, vite

#14412 feat: Automatically use available converters in Binder (CP: 2.8)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/ConverterFactory.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/DefaultConverterFactory.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BeanBinderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/DefaultConverterFactoryTest.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/bean/ConvertibleValues.java
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
  flow-server/src/test/java/com/vaadin/flow/internal/ReflectToolsTest.java
Labels: +0.1.0, Contribution

#14443 Check license also for jars with cvdlName
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.1.0

#14446 fix: Skip checking library code for TypeScript errors
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/main/resources/tsconfig.json
Labels: +0.0.1

#14447 chore: Update testbench version
  pom.xml
Labels: +0.0.1

#14450 chore: Upgrade to license checker 1.7
  pom.xml
Labels: +0.0.1
