Repository vaadin/flow, pull requests merged in 2022-02, with the labels that each got.

#12897 test: Use WebDriverManager to manage chromedriver
  flow-client/scripts/client.js
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
  flow-tests/pom.xml
  flow-tests/servlet-containers/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-reusable/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-ccdm-flow-navigation/pom-production.xml
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-custom-route-registry/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
  flow-tests/test-embedding/test-embedding-theme-variant/pom.xml
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/test-npm/pom-production.xml
  flow-tests/test-frontend/test-npm/pom.xml
  flow-tests/test-frontend/test-pnpm/pom-production.xml
  flow-tests/test-frontend/test-pnpm/pom.xml
  flow-tests/test-fusion-csrf-context/pom.xml
  flow-tests/test-fusion-csrf/pom.xml
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-memory-leaks/pom.xml
  flow-tests/test-misc/pom.xml
  flow-tests/test-multi-war/deployment/pom.xml
  flow-tests/test-no-theme/pom.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-devmode.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-prod-fallback.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-production.xml
  flow-tests/test-npm-only-features/test-npm-custom-frontend-directory/pom.xml
  flow-tests/test-npm-only-features/test-npm-general/pom.xml
  flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  flow-tests/test-pwa/pom-production.xml
  flow-tests/test-pwa/pom.xml
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-router-custom-context/pom.xml
  flow-tests/test-servlet/pom.xml
  flow-tests/test-theme-no-polymer/pom.xml
  flow-tests/test-themes/pom.xml
  flow-tests/test-v14-bootstrap/pom-production.xml
  flow-tests/test-v14-bootstrap/pom.xml
  pom.xml
Labels: +0.0.1

#12905 fix: use FrontendUtils::deleteNodeModules
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
Labels: +0.0.1, target/2.7, target/2.8

#12891 fix: update webpack versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/pom-production.xml
  flow-tests/test-frontend/test-npm/pom.xml
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
  flow-tests/test-frontend/test-pnpm/pom-production.xml
  flow-tests/test-frontend/test-pnpm/pom.xml
  pom.xml
Labels: +0.0.1

#12872 chore: set timeout to GH actions
  .github/workflows/validation.yml
Labels: +0.0.1

#12910 Add extra log information for failing visitor
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12917 chore: Update to testbench 8.0.0.beta2
  flow-test-util/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  pom.xml
Labels: +0.0.1

#12899 doc: fix typo in java doc in AppShellConfigurator
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
Labels: +0.0.1

#12906 Fix: do not remove package-lock on platform update
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1

#12916 fix!: no double decode query parameters
  flow-server/src/main/java/com/vaadin/flow/router/LocationUtil.java
  flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
  flow-server/src/test/java/com/vaadin/flow/router/LocationTest.java
  flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8

#12926 fix: Allow server side modality for components UI tree
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
Labels: +0.0.1

#12911 fix: also consider package.json for lock versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, target/9.0

#12915 fix: also consider package.json for lock versions
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, target/2.7

#12921 fix: Use service already assigned (#12808) (#12835)
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
Labels: +0.0.1, cherry pick

#12927 chore: Upgrade to Vite 2.8.0 beta 5
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, vite

#12932 fix: also consider package.json for lock versions (#12915)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1, cherry pick

#12934 fix: Do not print frontend build error when stopping the server
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevServerOutputTracker.java
Labels: +0.0.1

#12857 fix: make Vite PWA apps work offline in prod mode
  flow-server/src/main/resources/vite.generated.ts
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/pom.xml
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/main/webapp/offline.html
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/test/java/com/vaadin/viteapp/MainIT.java
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/vite.config.ts
  flow-tests/test-frontend/vite-pwa-production/.gitignore
  flow-tests/test-frontend/vite-pwa-production/frontend/about-view.ts
  flow-tests/test-frontend/vite-pwa-production/frontend/home-view.ts
  flow-tests/test-frontend/vite-pwa-production/frontend/index.html
  flow-tests/test-frontend/vite-pwa-production/frontend/index.ts
  flow-tests/test-frontend/vite-pwa-production/frontend/themes/my-theme/fonts/Roboto-Regular.woff
  flow-tests/test-frontend/vite-pwa-production/frontend/themes/my-theme/images/bg.jpeg
  flow-tests/test-frontend/vite-pwa-production/frontend/themes/my-theme/styles.css
  flow-tests/test-frontend/vite-pwa-production/pom.xml
  flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-frontend/vite-pwa-production/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java
  flow-tests/test-frontend/vite-pwa-production/vite.config.ts
Labels: +0.0.1, vite

#12935 chore: Upgrade to latest Polymer
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#12947 test: ignore broken test
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
Labels: +0.0.1, target/23.0

#12946 chore: remove redundant version
  flow-tests/test-ccdm-flow-navigation/pom-production.xml
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
Labels: +0.0.1

#12945 test: Decrease webpack aggregate timeout for ComponentThemeLiveReloadIT
  flow-tests/test-application-theme/test-theme-component-live-reload/src/test/java/com/vaadin/flow/uitest/ui/ComponentThemeLiveReloadIT.java
  flow-tests/test-application-theme/test-theme-component-live-reload/webpack.config.js
Labels: +1.0.0, target/23.0

#12960 chore: Upgrade to Vite 2.8 beta7
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12962 chore: Upgrade to Vite 2.8
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12958 test: Find elements by part attribute instead of id (#10331)
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/2.7

#12966 test: Significantly increase webpack limit and log time to TeamCity instead
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1

#12952 fix: Return 404 for /VAADIN/ urls which do not map to a file
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/FileAccessIT.java
Labels: +0.1.0, target/23.0

#12951 fix: clean default system error messages
  flow-server/src/main/java/com/vaadin/flow/server/SystemMessages.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
Labels: +0.0.1, target/9.0, target/23.0

#12979 chore: Delete misleading 'should work' information
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/23.0

#12982 fix: upgrade fusion npm pkg version to fix bugs
  fusion-endpoint/src/main/java/com/vaadin/fusion/FusionController.java
Labels: hilla, +0.0.1

#12996 Fix: export experimental package for OSGi
  flow-server/bnd.bnd
Labels: +0.0.1, target/23.0

#12999 chore: fix how disabledPnpm flag was set for TaskUpdateImports
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
Labels: +0.0.1

#13003 chore: remove unecessary jetty-maven-plugin scan configuration
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
Labels: +0.0.1, target/9.0, target/23.0

#13006 chore: remove unecessary jetty-maven-plugin scan configuration
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
Labels: +0.0.1, target/2.7

#13012 chore: Upgrade to Vite 2.8.2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#12993 chore: do not import modules of featured-flag components
  flow-server/src/main/java/com/vaadin/experimental/Feature.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
Labels: +1.0.0, target/23.0

#13023 chore: Upgrade to TestBench 8 beta 3
  pom.xml
Labels: +0.0.1

#13005 fix: cleanup url before resolving resource path in css-loader
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/2.7

#12990 test: Ensure file is closed after reading lines
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0

#12989 chore: bump jetty.version
  pom.xml
Labels: +0.0.1, target/2.7

#13029 chore: link to Hilla repository
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: +0.0.1

#13027 test: Delete unnecessary test overrides for Spring
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1

#13022 fix: Update jaxb-runtime
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
Labels: +0.0.1, target/23.0

#13021 fix: Get boolean only if eventData has the key
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementListenersTest.java
Labels: +1.0.0

#12998 fix!: Supported node is updated to 16.14
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +1.0.0, target/23.0

#13042 test: Remove polymer webjar
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
Labels: +0.0.1, target/23.0

#13026 feat: Add modality helpers
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.1.0, target/23.0

#13045 test: Double check that the port for ChromeDriver is really free
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Labels: +1.0.0, target/23.0

#13047 fix: Slow npm warning when no package-lock
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
Labels: +0.1.0, target/23.0

#13050 chore: Upgrade to latest lit
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.1.0, target/23.0

#13053 fix: respect PWA offline property in the Vite config
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/pom.xml
Labels: +0.0.1, target/23.0

#12963 fix: don't create a new UI instance for service worker resource
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1

#13063 chore: update webdrivermanager version
  flow-test-util/pom.xml
Labels: +0.0.1

#13056 chore: delete garbage
  flow-server/versions.json
Labels: +0.0.1

#13072 fix: enable skipDefaultLibCheck in the default TS config
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Labels: +0.0.1, vite

#13069 test: Enable upload test
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
Labels: +0.0.1, target/23.0

#13020 test: Rewrite tests to use Spring Boot + devtools for reload
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-redeployment/frontend/themes/app-theme/styles.css
  flow-tests/test-redeployment/frontend/themes/other-theme/styles.css
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/AppShell.java
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/Application.java
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/SessionValueView.java
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadView.java
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortView.java
  flow-tests/test-redeployment/src/main/resources/application.properties
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/SessionValueIT.java
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/ThemeSwitchLiveReloadIT.java
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
Labels: +0.1.0, target/23.0

#13078 chore: update webpack-dev-server
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1

#13055 chore: Record npm install time
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/StatisticsConstants.java
Labels: +0.1.0, target/23.0

#13059 fix: save platform version in node_modules
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
Labels: +0.1.0, target/23.0

#13093 chore: Tell sonarcloud the comment is not code...
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
Labels: +0.0.1

#13088 Remove unused imports
  flow-data/src/main/java/com/vaadin/flow/data/converter/StringToUuidConverter.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateServicWorkerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/CustomElementsTest.java
  flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ExternalPackageIT.java
  flow-tests/test-frontend/vite-pwa-production-custom-offline-path/src/test/java/com/vaadin/viteapp/MainIT.java
  flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateScalabilityIT.java
  flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/src/main/java/org/vaadin/example/Application.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/ParentTemplateIT.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/StreamResourceIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/UserInfo.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MainView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/UserInfoEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/UserInfoEndpoint.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/test/java/com/vaadin/flow/spring/fusionform/FusionFormIT.java
  flow-tests/vaadin-spring-tests/test-ts-services-custom-client/src/test/java/com/vaadin/flow/connect/AppViewIT.java
  fusion-endpoint/src/main/java/dev/hilla/generator/SchemaGenerator.java
  fusion-endpoint/src/test/java/dev/hilla/generator/endpoints/AbstractEndpointGenerationTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/WebpackHandler.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandlerTest.java
Labels: +0.0.1, target/23.0

#13085 chore: replace update-frontend with a more descriptive string
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
Labels: +0.0.1, target/23.0

#13083 chore: remove mentions of deleted webpackTemplate
  flow-plugins/flow-maven-plugin/README.md
Labels: +0.1.0

#13090 test: Fix chromedriver binding issues
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Labels: +0.0.1, target/23.0

#13100 test: Use Jetty 10 compatible configuration
  flow-tests/test-pwa/pom-production.xml
  flow-tests/test-pwa/pom.xml
Labels: +0.0.1, target/23.0

#13102 fix: Fix usage of deprecated webpack API
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1, target/23.0

#13087 fix: handle service worker content in production mode when running on non root servlet mapping (#13073)
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/DefaultMappingServlet.java
  flow-tests/test-ccdm-flow-navigation/src/main/java/com/vaadin/flow/navigate/NestedMappingServlet.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerOnNestedMappingIT.java
Labels: +0.0.1

#13106 chore: Fix code smells
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +1.0.0, target/23.0

#13112 fix: add Vaadin entry points to `optimizeDeps.entries`
  flow-server/src/main/resources/vite.generated.ts
Labels: +1.0.0, vite

#13107 fix: apply theme in V14 legacy mode
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Labels: +0.1.0, target/23.0

#13118 refactor: format `vite.generated.ts` with Prettier
  flow-server/src/main/resources/vite.generated.ts
Labels: vite, target/23.0

#13122 fix: remove the duplicate of optimizeDeps.entries
  flow-server/src/main/resources/vite.generated.ts
Labels: vite

#13124 chore: run the Vite config through Prettier (CP: 23.0)
  flow-server/src/main/resources/vite.generated.ts
Labels: +1.0.0

#13127 test: test Vite PWA with a custom offline path in dev mode
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/webapp/offline.html
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/test/java/com/vaadin/viteapp/MainIT.java
  flow-tests/test-frontend/vite-pwa-custom-offline-path/vite.config.ts
Labels: +0.0.1

#13126 test: do not leave server in Vite state
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/FeatureIT.java
Labels: +0.0.1, target/23.0

#13089 refactor: Split method invocation part out to EndpointInvoker
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointInvoker.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerConfigurationTest.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerMockBuilder.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/AbstractDevModeBrowserLauncherTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinDefaultRequestCacheTest.java
Labels: hilla, +0.0.1

#13132 Change log level when a VaadinSession is getting unbound
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
Labels: +0.0.1, target/9.0, target/23.0

#13119 chore: Add some stats to GH actions build, optimise timings
  .github/workflows/validation.yml
  scripts/computeMatrix.js
Labels: +1.0.0, target/23.0

#13138 chore: Do not scream about npm
  flow-server/.dtrack.yml
  flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, target/23.0

#13135 Fix Theme.java doc
  flow-server/src/main/java/com/vaadin/flow/theme/Theme.java
Labels: +0.0.1

#13150 chore(deps): bump vaadin-testbench-core from 8.0.0.beta2 to 8.0.0
  pom.xml
Labels: +0.0.1, target/23.0

#13151 Show patience notice right before npm install starts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1, target/23.0

#12798 test: Upgrade to Jetty 10
  flow-tests/pom.xml
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
  flow-tests/test-fusion-csrf/pom.xml
  flow-tests/test-memory-leaks/pom.xml
  flow-tests/test-multi-war/deployment/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-router-custom-context/pom.xml
  flow-tests/vaadin-spring-tests/pom.xml
  pom.xml
Labels: +0.0.1, target/23.0

#13170 fix: clean overrides for removed dependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1, target/23.0
