Repository vaadin/flow, pull requests merged in 2022-05, with the labels that each got.

#13657 chore: Upgrade jackson-databind (#13430)
  flow-server/pom.xml
  fusion-endpoint/pom.xml
  pom.xml
Labels: +0.0.1

#13641 chore: Upgrade to Node 16.15.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.0

#13668 fix: Disable strict peer dependencies to make pnpm 7 work
  flow-server/src/main/resources/npmrc
Labels: +0.0.1

#13666 fix: Only run new license checker when flag is enabled
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
Labels: +0.0.1

#13629 chore: use pull_request_target event and check-user-permissions to allow validations from external contributions
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.0

#13670 Upgrade to license checker 1.4 for offline support
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CvdlProducts.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +0.0.1

#13663 fix: Do not include AppShellConfigurator interface as an implementation #13608
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
Labels: +0.0.1, target/9.0, target/23.0

#13680 chore: remove pull_request event to avoid running twice
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.0

#13682 chore: Remove duplicated build parts
  vaadin-spring/pom.xml
Labels: +0.0.1, target/23.0

#13634 fix: ignore server-modality for poll RPC invocations (CP: #13604)
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandlerTest.java
Labels: +0.1.0

#13683 chore: Remove duplicated build parts (#13682)
  vaadin-spring/pom.xml
Labels: +0.1.0, cherry pick

#13685 chore: Upgrade to webpack-dev-server 4.9.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#13689 chore: update vaadin.version to 23.2-SNAPSHOT
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1

#13656 fix: Serialize byte[] as Array<number>
  fusion-endpoint/src/main/java/dev/hilla/ByteArrayModule.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointInvoker.java
  fusion-endpoint/src/test/java/dev/hilla/rest/EndpointWithRestControllerTest.java
  fusion-endpoint/src/test/java/dev/hilla/rest/TestEndpoints.java
Labels: hilla, +0.0.1, target/23.0, target/23.1

#13691 chore: fix GH action stats
  scripts/computeMatrix.js
Labels: +0.0.1

#13678 chore: Remove invalid javadoc
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JavaScript.java
  flow-server/src/main/java/com/vaadin/flow/component/dependency/JsModule.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#13696 test: Fix test for Java 17.0.3+
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1, target/23.0, target/23.1

#13697 chore: Use latest Java for validation again
  .github/workflows/validation.yml
Labels: +0.0.1

#13711 feat: add flag for CE backend support
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.1.0, target/23.1

#13710 test: Automatically setup chromedriver version for flow-client tests (#13484) (CP: 23.0)
  flow-client/.gitignore
  flow-client/pom.xml
  flow-client/src/test/npm/intern.json
  flow-test-util/pom.xml
  pom.xml
Labels: +0.0.1, cherry pick, target/2.7, target/9.0, target/2.8

#13712 chore: fix regex for getting modules and adjust weights
  .github/workflows/validation.yml
  scripts/computeMatrix.js
Labels: +0.0.1, target/23.1

#13715 test: Automatically setup chromedriver version for flow-client tests (#13710) (CP 9.0)
  flow-client/.gitignore
  flow-client/pom.xml
  flow-client/src/test/npm/intern.json
  flow-test-util/pom.xml
  pom.xml
Labels: +0.0.1, cherry pick

#13709 chore: Remove drivers.xml from project
  drivers.xml
Labels: +0.1.0, target/9.0, target/23.0, target/23.1

#13698 fix: Serialize byte[] as Array<number> (#13656) (CP: 23.0)
  fusion-endpoint/src/main/java/dev/hilla/ByteArrayModule.java
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/test/java/dev/hilla/rest/EndpointWithRestControllerTest.java
  fusion-endpoint/src/test/java/dev/hilla/rest/TestEndpoints.java
Labels: hilla, +0.0.1, cherry pick

#13714 chore(deps): bump spring.boot.version from 2.6.6 to 2.6.7
  pom.xml
Labels: +0.0.1

#13674 refactor: Make ViewAccessControl more extensible
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/ViewAccessCheckerTest.java
Labels: +0.1.0

#13734 chore: do not run twice unit tests
  .github/workflows/validation.yml
Labels: +0.0.1

#13677 fix: Ensure @HandlesTypes types are not included in the collection
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractAnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AnnotationValidator.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ErrorNavigationTargetInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentConfigurationRegistryInitializer.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/WebComponentExporterAwareValidator.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AnnotationValidatorTest.java
Labels: +0.1.0, target/23.1

#13735 Improve dev mode startup message and styling
  vaadin-dev-server/src/main/resources/com/vaadin/base/devserver/dev-mode-not-ready.html
Labels: +0.0.1

#13732 test: Try several times to start a webpack server instead of failing the build
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
Labels: +0.0.1, target/23.0, target/23.1

#13675 feat: Support view access checking in background threads with Spring
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/Configurator.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  fusion-endpoint/src/main/java/dev/hilla/AuthenticationUtil.java
  fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/AuthenticationUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringViewAccessCheckerTest.java
Labels: +0.1.0, target/23.1

#13756 refactor: use the cvdlName getter for retrieving the product name
  flow-client/src/main/frontend/License.ts
Labels: +0.0.1, target/23.1

#13708 fix: Ignore CancellationException for running UI update tasks
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#13764 fix: Move the clean-frontend phase to be before clean (#13763)
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FrontendDanceMojo.java
Labels: +0.0.1, target/2.7

#13773 fix: Do not serve static resources from dev server if dev server startup failed
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#13759 fix: clean default system error messages (#12951)
  flow-server/src/main/java/com/vaadin/flow/server/SystemMessages.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutWithNotificationIT.java
Labels: +0.0.1, target/2.7

#13725 Fix: devmode popup will show Hilla instead of Vaadin in Hilla applications
  flow-client/src/main/frontend/vaadin-dev-tools.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/ServerInfoTest.java
Labels: hilla, +0.0.1, target/23.0, target/23.1

#13728 test: Add tests for PushMessageHandler
  fusion-endpoint/src/main/java/dev/hilla/FeatureFlagCondition.java
  fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
  fusion-endpoint/src/test/java/dev/hilla/ServletContextTestSetup.java
  fusion-endpoint/src/test/java/dev/hilla/push/PushMessageHandlerTest.java
Labels: hilla, +0.0.1, target/23.1

#13400 chore: Change debug level to info as this logging is frequent in harmless cases
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#13791 fix: Always get url mapping using helpers when using Spring Boot
  vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/RootMappedCondition.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeBrowserLauncherVaadinAndServletMappingTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/RootMappedConditionTest.java
Labels: +0.0.1, target/23.1

#13733 fix: Improve message sender / handler robustness in resync scenarios
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/dom/GwtDomApiTest.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#13800 test: Use 'urlmapping' instead of 'vaadin' for clarity
  flow-tests/vaadin-spring-tests/test-spring-security-flow-contextpath/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurityurlmapping/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-urlmapping/src/test/java/com/vaadin/flow/spring/flowsecurityurlmapping/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-contextpath/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurityurlmapping/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-fusion-urlmapping/src/test/java/com/vaadin/flow/spring/fusionsecuritycontextpath/SecurityIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/main/resources/application.properties
Labels: +0.0.1, target/23.1

#13746 fix: Avoid potential slow Set#removeAll call in HierarchicalCommunicator
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
Labels: +0.0.1

#13809 Fix: Use /HILLA/push as the Hilla push endpoint
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
  fusion-endpoint/src/main/java/dev/hilla/push/EngineIoHandler.java
  fusion-endpoint/src/main/java/dev/hilla/push/SocketIoWebsocketConfigurer.java
Labels: hilla, +0.0.1, target/23.1

#13824 test: Start chromedriver with --silent
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Labels: +0.0.1

#13729 fix: Clean up flux subscription on browser disconnect
  fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
  fusion-endpoint/src/main/java/dev/hilla/push/SocketIoHandler.java
  fusion-endpoint/src/test/java/dev/hilla/push/PushMessageHandlerTest.java
Labels: hilla, +0.0.1, target/23.1

#13828 chore: cleanup compute matrix
  scripts/computeMatrix.js
Labels: +0.0.1

#13730 fix: Properly clean up when a flux immediately errors or completes
  fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
  fusion-endpoint/src/test/java/dev/hilla/push/PushMessageHandlerTest.java
Labels: hilla, +0.0.1, target/23.1

#13615 feat: Support @NonNullApi to define @Nonnull for all methods in a package
  fusion-endpoint/src/main/java/dev/hilla/EndpointInvoker.java
  fusion-endpoint/src/main/java/dev/hilla/ExplicitNullableTypeChecker.java
  fusion-endpoint/src/main/java/dev/hilla/ExplicitNullableTypeCheckerHelper.java
  fusion-endpoint/src/main/java/dev/hilla/generator/GeneratorType.java
  fusion-endpoint/src/main/java/dev/hilla/generator/OpenAPIObjectGenerator.java
  fusion-endpoint/src/main/java/dev/hilla/generator/SchemaGenerator.java
  fusion-endpoint/src/main/java/dev/hilla/generator/SchemaResolver.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointControllerTest.java
  fusion-endpoint/src/test/java/dev/hilla/ExplicitNullableTypeCheckerTest.java
  fusion-endpoint/src/test/java/dev/hilla/generator/SchemaResolverTest.java
  fusion-endpoint/src/test/java/dev/hilla/generator/endpoints/AbstractEndpointGenerationTest.java
  fusion-endpoint/src/test/java/dev/hilla/generator/endpoints/nonnullapiendpoint/NonNullApiEndpoint.java
  fusion-endpoint/src/test/java/dev/hilla/generator/endpoints/nonnullapiendpoint/NonNullApiEndpointTest.java
  fusion-endpoint/src/test/java/dev/hilla/generator/endpoints/nonnullapiendpoint/package-info.java
  fusion-endpoint/src/test/resources/dev/hilla/generator/endpoints/nonnullapiendpoint/expected-NonNullApiEndpoint.ts
Labels: hilla, +0.0.1

#13731 feat: Support listening to browser unsubscribe in endpoint methods
  fusion-endpoint/src/main/java/dev/hilla/EndpointSubscription.java
  fusion-endpoint/src/main/java/dev/hilla/generator/GeneratorType.java
  fusion-endpoint/src/main/java/dev/hilla/generator/SchemaResolver.java
  fusion-endpoint/src/main/java/dev/hilla/push/PushMessageHandler.java
  fusion-endpoint/src/test/java/dev/hilla/push/PushMessageHandlerTest.java
Labels: hilla, +0.0.1, target/23.1

#13808 fix: Workaround Spring Boot UnsupportedOperationException for error page requests
  fusion-endpoint/src/main/java/dev/hilla/EndpointUtil.java
  fusion-endpoint/src/test/java/dev/hilla/EndpointUtilTest.java
Labels: hilla, +0.0.1, target/23.1

#13795 fix!: Always load static files from context root
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/internal/UrlUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-common/src/main/java/com/vaadin/flow/uitest/servlet/ViewTestServlet.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/CompressionIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/VaadinPushScriptIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.1.0, target/23.1

#13825 fix: Update PageTitle after processing AfterNavigation listeners
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SetTitleAfterNavigationEventView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ViewTitleIT.java
Labels: +0.0.1, target/9.0, target/23.0, target/23.1

#13821 chore: Upgrade to Spring Boot 2.7 and Security 5.7.1
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/Account.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/data/UserInfo.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/main/java/com/vaadin/flow/spring/fusionsecurity/data/Account.java
  flow-tests/vaadin-spring-tests/test-spring-security-fusion/src/main/java/com/vaadin/flow/spring/fusionsecurity/data/UserInfo.java
  pom.xml
Labels: +0.0.1, target/23.1

#13833 chore(deps): bump jackson-databind from 2.13.2.2 to 2.13.3 (#13784) (CP: 23.1)
  pom.xml
Labels: +0.0.1

#13845 fix: Pass url mapping to Atmosphere
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationUrlMappedTest.java
Labels: +0.1.0, target/23.1

#13820 [Snyk] Upgrade lit from 2.2.1 to 2.2.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#13829 feat: Add constructors to Router Link without text.
  flow-server/src/main/java/com/vaadin/flow/router/RouterLink.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterLinkTest.java
Labels: +0.1.0

#13165 refactor: make Webpack use web-component.html
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/resources/META-INF/VAADIN/webapp/web-component.html
Labels: +0.1.0, target/23.1

#13855 test: Add VAADIN mapping to OSGi servlet registrations
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/osgi/Activator.java
Labels: +0.0.1, target/23.1

#13857 Revert "refactor: make Webpack use web-component.html (#13165)"
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerTest.java
  flow-server/src/test/resources/META-INF/VAADIN/webapp/web-component.html
Labels: +1.0.0, target/23.1

#13853 chore: Upgrade Hilla to 1.1 rc1
  fusion-endpoint/src/main/java/dev/hilla/EndpointController.java
Labels: +0.0.1, target/23.1

#13859 Move license checker dependency to vaadin-dev-server and plugin
  flow-plugins/flow-plugin-base/pom.xml
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  pom.xml
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1, target/23.1

#13861 chore: Move license checker dependency to vaadin-dev-server and plugin (#13859) (CP: 23.1)
  flow-plugins/flow-plugin-base/pom.xml
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  pom.xml
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1

#13801 test: Use WebDriverManager to manage chromedriver (#12897) (CP: 2.8)
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
  flow-tests/pom.xml
  flow-tests/servlet-containers/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-reusable/pom.xml
  flow-tests/test-application-theme/test-theme-switch-live-reload/pom.xml
  flow-tests/test-custom-route-registry/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-embedding/test-embedding-application-theme/pom.xml
  flow-tests/test-embedding/test-embedding-generic-compatibility/pom.xml
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode-compatibility/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
  flow-tests/test-embedding/test-embedding-reusable-theme/pom.xml
  flow-tests/test-embedding/test-embedding-theme-variant-compatibility/pom.xml
  flow-tests/test-embedding/test-embedding-theme-variant/pom.xml
  flow-tests/test-frontend-production-custom-context/pom.xml
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-lumo-theme/pom.xml
  flow-tests/test-material-theme/pom.xml
  flow-tests/test-memory-leaks/pom.xml
  flow-tests/test-misc/pom-bower.xml
  flow-tests/test-misc/pom.xml
  flow-tests/test-mixed/pom-bower-devmode.xml
  flow-tests/test-mixed/pom-bower-production.xml
  flow-tests/test-mixed/pom-npm-production.xml
  flow-tests/test-mixed/pom-npm.xml
  flow-tests/test-mixed/pom-pnpm-production.xml
  flow-tests/test-mixed/pom.xml
  flow-tests/test-multi-war/deployment/pom.xml
  flow-tests/test-no-root-context/pom.xml
  flow-tests/test-no-theme/pom.xml
  flow-tests/test-npm-only-features/test-default-theme/pom.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-devmode.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-prod-fallback.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-production.xml
  flow-tests/test-npm-only-features/test-npm-custom-frontend-directory/pom.xml
  flow-tests/test-npm-only-features/test-npm-general/pom.xml
  flow-tests/test-npm-only-features/test-npm-no-buildmojo/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  flow-tests/test-pwa/pom.xml
  flow-tests/test-root-context/pom.xml
  flow-tests/test-root-ui-context/pom.xml
  flow-tests/test-router-custom-context/pom.xml
  flow-tests/test-servlet/pom.xml
  flow-tests/test-subcontext/pom.xml
  flow-tests/test-themes-legacy/pom-npm.xml
  flow-tests/test-themes-legacy/pom.xml
  flow-tests/test-themes/pom.xml
  pom.xml
Labels: +0.0.1, cherry pick, target/2.7

#13867 test: Compute matrix taking into account the recently added tests
  flow-tests/test-application-theme/pom.xml
  flow-tests/test-application-theme/test-reusable-as-parent-vite/src/test/java/com/vaadin/flow/uitest/ui/theme/ParentThemeIT.java
  scripts/computeMatrix.js
Labels: +0.0.1, Contribution

#13875 fix: upgrade lit default version from 2.2.1 to 2.2.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1
