Repository vaadin/flow, pull requests merged in 2022-11, with the labels that each got.

#14963 chore: Remove commons fileupload snapshot dependency
  flow-commons-upload/bnd.bnd
  flow-commons-upload/pom.xml
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItem.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemFactory.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemHeaders.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemHeadersSupport.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemIterator.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemStream.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUpload.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUploadBase.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUploadException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/InvalidFileNameException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/MultipartStream.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/ParameterParser.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/ProgressListener.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/RequestContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/UploadContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/DiskFileItem.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/DiskFileItemFactory.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/impl/FileItemIteratorImpl.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/impl/FileItemStreamImpl.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/impl/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltFileCleaner.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltFileUpload.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltRequestContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileSizeLimitExceededException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileUploadIOException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/IOFileUploadException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/InvalidContentTypeException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/SizeException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/SizeLimitExceededException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/Closeable.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/FileItemHeadersImpl.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/LimitedInputStream.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/Streams.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/Base64Decoder.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/MimeUtility.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/ParseException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/QuotedPrintableDecoder.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/RFC2231Utility.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/package-info.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  pom.xml
Labels: +1.0.0

#14965 fix. remove locking and attribute usage
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#14966 chore: Require JavaSE-17 for OSGi
  flow-client/bnd.bnd
  flow-commons-upload/bnd.bnd
  flow-data/bnd.bnd
  flow-dnd/bnd.bnd
  flow-html-components/bnd.bnd
  flow-lit-template/bnd.bnd
  flow-polymer-template/bnd.bnd
  flow-push/bnd.bnd
  flow-server/bnd.bnd
Labels: +1.0.0

#14973 chore: Remove unused method
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#14977 chore: remove spreadsheet feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0, target/23.3

#14982 chore: Remove unused code
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/BundleParserTest.java
Labels: +0.0.1, target/23.3

#14990 chore: Update TestBench to 9.0.0.alpha2
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#14975 chore: Upgrade to Spring auth server RC1
  pom.xml
Labels: +0.0.1

#14995 chore: update actions version to run node 16
  .github/workflows/validation.yml
Labels: +1.0.0

#14976 fix. remove locking and attribute usage (#14965)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, cherry pick

#14996 chore: update github/action file to get rid of the warnings
  .github/workflows/validation.yml
Labels: +1.0.0

#15008 chore: Upgrade to Lit 2.4.1
  flow-client/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pnpm-lock.yaml
Labels: +1.0.0, target/23.3

#15012 chore: fix syntax error in build script
  .github/workflows/validation.yml
Labels: +0.0.1

#15003 test: update felix versions
  flow-tests/servlet-containers/felix-jetty/pom.xml
Labels: +0.0.1

#15013 chore: Make handler public to be compatible with spring native
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletConfiguration.java
Labels: +0.0.1

#15016 test: revert felix versions
  flow-tests/servlet-containers/felix-jetty/pom.xml
Labels: +0.0.1

#15005 fix: Interpret a directory import as an import for index.js in the directory
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-tests/test-frontend/vite-basics/frontend/a-directory/index.js
  flow-tests/test-frontend/vite-basics/frontend/importdir.js
  flow-tests/test-frontend/vite-basics/frontend/index.html
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
  flow-tests/test-root-context/frontend/a-directory/index.js
  flow-tests/test-root-context/frontend/importdir.js
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/frontend/DirectoryImportView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/frontend/DirectoryImportIT.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#15024 test: update gretty version
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +0.0.1, target/9.0, target/23.1, target/23.2, target/23.3

#15014 feat: Basics for Spring native support
  flow-server/src/main/java/com/vaadin/flow/di/LookupInitializer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinHintsRegistrar.java
  vaadin-spring/src/main/resources/META-INF/spring/aot.factories
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
Labels: +0.0.1

#15032 chore: Upgrade default installed Node to 16.18.1 with security fixes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#15046 test: use non-prefixed version of text-field
  flow-tests/test-application-theme/test-reusable-as-parent-vite/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
  flow-tests/test-application-theme/test-reusable-as-parent/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
  flow-tests/test-application-theme/test-theme-reusable-vite/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
  flow-tests/test-application-theme/test-theme-reusable/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyComponent.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/MyComponent.java
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/ThemableTextField.java
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
Labels: +0.0.1, target/23.3

#15044 chore!: Enable auto update of installed Node by default
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.0.1, target/23.3

#15049 chore(deps): bump webdrivermanager from 5.3.0 to 5.3.1 (#15042) (CP: 23.3)
  pom.xml
Labels: +0.0.1

#15033 chore: Upgrade default installed Node to 14.21.1 with security fixes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#15045 doc: Explain how to use Gradle plugin from the local Maven repo
  flow-plugins/flow-gradle-plugin/README.md
Labels: +1.0.0

#15037 chore: Remove blacklisted npm versions which are out of date
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: target/23.3

#15057 chore: Remove special jar resources allow
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.3

#15056 chore: Make @vaadin/flow-frontend jar-resources change backwards compatible
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.3

#15054 fix: Do not log null if servlet deployer is disabled
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
Labels: +0.0.1, target/23.1, target/23.2, target/23.3

#14972 feat: Add polymer2lit converter
  .gitignore
  flow-plugins/flow-maven-plugin/pom.xml
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ConvertPolymerMojo.java
  flow-plugins/flow-plugin-base/pom.xml
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/ConvertPolymerExecutorTest.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/TestUtil.java
  flow-polymer2lit/README.md
  flow-polymer2lit/convert.ts
  flow-polymer2lit/package.json
  flow-polymer2lit/pom.xml
  flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/FrontendConverter.java
  flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/ServerConverter.java
  flow-polymer2lit/src/test/java/com/vaadin/flow/polymer2lit/FrontendConverterTest.java
  flow-polymer2lit/src/test/java/com/vaadin/flow/polymer2lit/ServerConverterTest.java
  flow-polymer2lit/src/test/resources/frontend/expected/basic-bindings-with-lit1.js
  flow-polymer2lit/src/test/resources/frontend/expected/basic-bindings.js
  flow-polymer2lit/src/test/resources/frontend/expected/computed-property.js
  flow-polymer2lit/src/test/resources/frontend/expected/disabled-using-method.js
  flow-polymer2lit/src/test/resources/frontend/expected/dom-if.js
  flow-polymer2lit/src/test/resources/frontend/expected/dom-repeat.js
  flow-polymer2lit/src/test/resources/frontend/expected/event-handlers.js
  flow-polymer2lit/src/test/resources/frontend/expected/grid-columns.js
  flow-polymer2lit/src/test/resources/frontend/expected/inline-styles.js
  flow-polymer2lit/src/test/resources/frontend/expected/light-dom.js
  flow-polymer2lit/src/test/resources/frontend/expected/multiple-bindings.js
  flow-polymer2lit/src/test/resources/frontend/expected/nested-dom-repeat.js
  flow-polymer2lit/src/test/resources/frontend/expected/order-card-from-bakery.js
  flow-polymer2lit/src/test/resources/frontend/expected/ready-callback.js
  flow-polymer2lit/src/test/resources/frontend/expected/simple-observer.js
  flow-polymer2lit/src/test/resources/frontend/expected/sub-properties-with-disabled-optional-chaining.js
  flow-polymer2lit/src/test/resources/frontend/expected/sub-properties.js
  flow-polymer2lit/src/test/resources/frontend/expected/this-dollar-mapped-element-ids.js
  flow-polymer2lit/src/test/resources/frontend/expected/two-way-binding.js
  flow-polymer2lit/src/test/resources/frontend/in/basic-bindings.js
  flow-polymer2lit/src/test/resources/frontend/in/computed-property.js
  flow-polymer2lit/src/test/resources/frontend/in/disabled-using-method.js
  flow-polymer2lit/src/test/resources/frontend/in/dom-if.js
  flow-polymer2lit/src/test/resources/frontend/in/dom-repeat.js
  flow-polymer2lit/src/test/resources/frontend/in/event-handlers.js
  flow-polymer2lit/src/test/resources/frontend/in/grid-columns.js
  flow-polymer2lit/src/test/resources/frontend/in/inline-styles.js
  flow-polymer2lit/src/test/resources/frontend/in/light-dom.js
  flow-polymer2lit/src/test/resources/frontend/in/multiple-bindings.js
  flow-polymer2lit/src/test/resources/frontend/in/nested-dom-repeat.js
  flow-polymer2lit/src/test/resources/frontend/in/order-card-from-bakery.js
  flow-polymer2lit/src/test/resources/frontend/in/ready-callback.js
  flow-polymer2lit/src/test/resources/frontend/in/simple-observer.js
  flow-polymer2lit/src/test/resources/frontend/in/sub-properties.js
  flow-polymer2lit/src/test/resources/frontend/in/this-dollar-mapped-element-ids.js
  flow-polymer2lit/src/test/resources/frontend/in/two-way-binding.js
  flow-polymer2lit/src/test/resources/server/expected/BasicGettersSetters.java
  flow-polymer2lit/src/test/resources/server/expected/NoModel.java
  flow-polymer2lit/src/test/resources/server/in/BasicGettersSetters.java
  flow-polymer2lit/src/test/resources/server/in/NoModel.java
  pom.xml
Labels: +0.0.1

#15043 chore!: Require Node 18 (npm 8.6)
  .github/workflows/validation.yml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.0.1

#15065 chore: bump testbench to 9.0.0.alpha4
  pom.xml
Labels: +0.0.1

#15075 chore(deps-dev): bump loader-utils from 2.0.0 to 2.0.3 (#15017) (CP: 23.2)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.1

#15067 chore: Add dependency needed to properly compile VaadinWebSecurity
  vaadin-spring/pom.xml
Labels: +0.0.1, target/23.3

#15064 test: Make test pass with non English default locale
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderInstanceFieldTest.java
Labels: +0.0.1, target/23.3

#15048 feat: Add Gradle support for polymer2lit
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinConvertPolymerTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
  flow-polymer2lit/README.md
Labels: +0.0.1

#15055 Revert "test: update gretty version (#15024) (#15028)"
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +0.0.1

#15088 Skip IBMRestServlet when checking for VaadinServlet
  flow-server/src/main/java/com/vaadin/flow/server/communication/JSR356WebsocketInitializer.java
Labels: +0.0.1, target/9.0, target/23.1, target/23.2, target/23.3

#15062 chore: Upgrade TestBench to 8.1.3
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ConnectionIndicatorIT.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/ServiceWorkerIT.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BodyScrollIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebComponentsIT.java
  flow-tests/test-router-custom-context/src/test/java/com/vaadin/flow/contexttest/ui/OfflineWithCustomContextIT.java
  flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
  pom.xml
Labels: +0.0.1

#15082 doc: Use more appropriate prepositions
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ConvertPolymerMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
  flow-polymer2lit/README.md
  flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/FrontendConverter.java
  flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/ServerConverter.java
Labels: +0.0.1

#15083 test: Rename ConvertPolymerExecutorTest to ConvertPolymerCommandTest
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/ConvertPolymerCommandTest.java
Labels: +0.0.1

#15018 chore: pick the github action change to 9.0 branch
  .github/workflows/validation.yml
Labels: +0.0.1

#15020 chore: update github/action file to get rid of the warnings (23.2)
  .github/workflows/validation.yml
Labels: +0.0.1

#15021 chore: update github/action file to get rid of the warnings (23.3)
  .github/workflows/validation.yml
Labels: +0.0.1

#15096 fix: Add a default value to expressions when optional chaining is enabled
  flow-polymer2lit/convert.ts
  flow-polymer2lit/src/test/resources/frontend/expected/dom-repeat.js
  flow-polymer2lit/src/test/resources/frontend/expected/inline-styles.js
  flow-polymer2lit/src/test/resources/frontend/expected/multiple-bindings.js
  flow-polymer2lit/src/test/resources/frontend/expected/nested-dom-repeat.js
  flow-polymer2lit/src/test/resources/frontend/expected/order-card-from-bakery.js
Labels: +0.0.1

#15098 chore: Upgrade to Spring Boot 3 RC2
  flow-commons-upload/pom.xml
  flow-lit-template/pom.xml
  flow-plugins/flow-plugin-base/pom.xml
  flow-polymer-template/pom.xml
  flow-server/src/test/java/com/vaadin/flow/server/MockServletContext.java
  flow-tests/test-memory-leaks/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot/pom.xml
  pom.xml
Labels: +0.0.1

#15101 test: Add slfj impl so tests show output
  flow-polymer2lit/pom.xml
Labels: +0.0.1

#15106 chore: rename constant which is not related to only webpack
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoWebpackTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
Labels: +1.0.0, target/23.3

#15107 fix: linux node installation (#14657) (#14825)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/NodeInstallerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.1.0, cherry pick

#15108 chore: Show command output when it fails
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3

#15104 fix: Improve polymer2lit error handling
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/ConvertPolymerCommandTest.java
  flow-polymer2lit/convert.ts
  flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/FrontendConverter.java
  flow-polymer2lit/src/main/java/com/vaadin/flow/polymer2lit/ServerConverter.java
  flow-polymer2lit/src/test/java/com/vaadin/flow/polymer2lit/FrontendConverterTest.java
Labels: +1.0.0

#15097 doc: Enhance polymer2lit documentation
  flow-polymer2lit/README.md
Labels: +0.0.1

#14948 chore: Upgrade to Vite 3.2.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1, target/23.3

#15031 chore: Upgrade default installed Node to 16.18.1 with security fixes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.1.0

#15068 [Snyk] Upgrade org.glassfish.jaxb:jaxb-runtime from 2.3.6 to 2.3.7
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, target/23.2, target/23.3

#15117 chore: Use new enough node for build
  .github/workflows/validation.yml
Labels: +0.0.1

#15099 fix: Create an individual npm script for compiling convert.ts
  flow-polymer2lit/package.json
  flow-polymer2lit/pom.xml
Labels: +0.0.1

#15122 chore: upgrade to Jackson 2.14
  pom.xml
Labels: +0.0.1

#15123 chore(deps): bump jackson-databind from 2.13.4 to 2.13.4.2 (#14846)
  pom.xml
Labels: +0.0.1, cherry pick, target/9.0, target/2.8, target/23.1

#15125 chore: Do not check enableDevServer() where it is not needed
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +1.0.0, target/23.3

#15124 fix: Filter chunks to minimize stats.json
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
Labels: +0.0.1

#15142 chore(deps): bump jackson-databind from 2.13.4 to 2.13.4.2 (#14846)
  pom.xml
Labels: +1.0.0, cherry pick

#15144 chore(deps): bump jackson-databind from 2.13.4 to 2.13.4.2 (#14846)
  pom.xml
Labels: +0.0.1, cherry pick

#15143 chore(deps): bump jackson-databind from 2.13.4 to 2.13.4.2 (#14846)
  pom.xml
Labels: +0.0.1, cherry pick

#15134 chore: Do not use deprecated API
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +1.0.0, target/23.3

#15135 chore: ensure the folder for the stats file exists
  flow-server/src/main/resources/vite.generated.ts
Labels: +1.0.0, target/23.3

#15126 refactor: Write stats output folder from Java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.3

#15141 fix: suppress error handler for upload
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#15131 test: Use the first feature flag instead of a specific one
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/FeatureIT.java
Labels: +0.0.1, target/23.3

#15022 chore: Use open util package to open a browser
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/BrowserLauncher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/util/BrowserLauncher.java
  vaadin-dev-server/src/main/node-bundle/README
  vaadin-dev-server/src/main/node-bundle/node-util.js
  vaadin-dev-server/src/main/node-bundle/package.json
  vaadin-dev-server/src/main/node-bundle/rollup.config.js
  vaadin-dev-server/src/main/resources/vaadin-dev-server-node-bundle.js
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/BrowserLauncherTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
Labels: +0.1.0, target/23.3

#15132 chore: Upgrade to Vite 3.2.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/23.3

#15163 chore: Use the open util package to open a URL in a browser (#15022) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/BrowserLauncher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/util/BrowserLauncher.java
  vaadin-dev-server/src/main/node-bundle/README
  vaadin-dev-server/src/main/node-bundle/node-util.js
  vaadin-dev-server/src/main/node-bundle/package.json
  vaadin-dev-server/src/main/node-bundle/rollup.config.js
  vaadin-dev-server/src/main/resources/vaadin-dev-server-node-bundle.js
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/BrowserLauncherTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
Labels: +0.1.0

#15165 fix: set useDefineForClassFields to false in tsconfig.json
  flow-server/src/main/resources/tsconfig.json
Labels: +0.1.0, target/23.3

#15136 test: Delete webpack specific tests
  flow-tests/pom.xml
  flow-tests/test-custom-frontend-directory/pom.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom-webpack.xml
  flow-tests/test-pwa/pom-production-webpack.xml
  flow-tests/test-pwa/pom-webpack.xml
Labels: +1.0.0

#15169 chore: Upgrade loader-utils to 2.0.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/webpack/package.json
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
Labels: +0.1.0, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#15085 chore: Use env instead of custom parameter to webpack (#9934) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +1.0.0

#15155 chore: Show statistics after Polymer to Lit conversion
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
Labels: +0.0.1

#15170 add 23.3 branch to validation workflow [skip ci]
  .github/workflows/validation.yml
Labels: +0.1.0

#15168 chore: Upgrade license-checker to 1.11.1
  pom.xml
Labels: +0.1.0, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#15175 chore: Upgrade loader-utils to 2.0.4 (#15169) (#15174) (CP: 23.2)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.1

#15181 chore: Upgrade license-checker to 1.11.1 (#15168) (CP: 23.1)
  pom.xml
Labels: +0.0.1

#15185 chore: Upgrade loader-utils to 2.0.4 (#15169) (#15174) (#15175) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#15139 chore: Upgrade Spring, Jetty and servlet version in Gradle tests
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +1.0.0

#15186 feat: port dependency filtering from v14 gradle plugin
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ClasspathFilter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
Labels: +0.0.1, target/9.0, target/23.1, target/23.2, target/23.3

#15187 test: Update jakarta.websocket to 2.1.0
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1

#15151 chore: Set TB license also for unit tests
  .github/workflows/validation.yml
Labels: +0.0.1

#15189 test: Regenerate package-lock to make dependabot happy
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1

#15190 chore!: Remove feature flag for old license checker which is no longer available
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#15197 doc: Add minor improvements to README.md
  flow-polymer2lit/README.md
Labels: +1.0.0

#15199 fix: set useDefineForClassFields in generated tsconfig.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
Labels: +1.0.0, target/23.3

#15138 feat!: Enable license checking for flow-polymer-template
  flow-polymer-template/LICENSE.txt
  flow-polymer-template/bnd.bnd
  flow-polymer-template/pom.xml
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/AbstractTemplate.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/EventHandler.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/Id.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/IdCollector.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/IdMapper.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializer.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/JsoupUtils.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/ModelItem.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/RepeatIndex.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateDataAnalyzer.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateParser.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/rpc/PolymerPublishedEventRpcHandler.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/AbstractBasicModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/AllowClientUpdates.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/BasicComplexModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/BasicModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/BeanModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ClientUpdateMode.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ComplexModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ConvertedModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/Encode.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/Exclude.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/Include.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/InvalidTemplateModelException.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ListModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ModelDescriptor.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ModelEncoder.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/ModelType.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/PathLookup.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/PropertyFilter.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/PropertyMapBuilder.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/TemplateModel.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/TemplateModelListProxy.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/TemplateModelProxyHandler.java
  flow-polymer-template/src/main/java/com/vaadin/flow/templatemodel/TemplateModelUtil.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/AbstractTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/DeprecatedIdTemplateComponentTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/TemplateComponentTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/HasCurrentService.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/InjectablePolymerElementInitializerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/TemplateInitializerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/rpc/PolymerPublishedEventRpcHandlerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/BeanModelTypeTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/KnownUnsupportedTypesTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/ModelDescriptorTest.java
  flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/PropertyFilterTest.java
Labels: +1.0.0

#15172 test: Remove V14 bootstrap tests
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoWebpackTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/PwaConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  flow-tests/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/src/test/java/com/vaadin/flow/testnpmonlyfeatures/performanceregression/StartupPerformanceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RedirectToPushIT.java
  flow-tests/test-v14-bootstrap/pom-production.xml
  flow-tests/test-v14-bootstrap/pom.xml
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/navigation/ui/FirstView.java
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/navigation/ui/SecondView.java
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/pwatest/ui/ParentLayout.java
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/pwatest/ui/PwaTestView.java
  flow-tests/test-v14-bootstrap/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/navigation/ui/BrowserNavigationServerRoundTripIT.java
  flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1

#15196 feat: port dependency filtering from v14 gradle plugin (#15186)
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ClasspathFilter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
Labels: +0.0.1, cherry pick

#15206 chore: update the expected default npm version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#15207 chore: Upgrade license checker to 1.11.2
  pom.xml
Labels: +0.0.1, target/2.8, target/23.2, target/23.3

#15194 chore: Upgrade to TypeScript 4.9.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, target/23.3

#15152 fix: fix faulty cleanup of stats.json
  flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-server/src/main/resources/plugins/stats-plugin/package.json
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
Labels: +0.0.1

#15216 refactor: Record project folder inside node_modules instead
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, target/23.3

#15220 fix: Added MAXIMUM_ALLOWED_ITEMS_LOWER_LIMIT for small pageSizes
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1

#15019 chore: update github/action file to get rid of the warnings (23.1)
  .github/workflows/validation.yml
Labels: +0.0.1

#15226 chore: Upgrade build plugin to fix set-output warning
  .github/workflows/validation.yml
Labels: +0.0.1

#15224 chore: Store unit test output separately
  .github/workflows/validation.yml
Labels: +0.0.1

#15230 chore: Show files downloaded in the build
  .github/workflows/validation.yml
Labels: +0.0.1

#15231 chore: Do not delete test results from the build
  .github/workflows/validation.yml
Labels: +0.0.1

#15217 refactor: Let DevModeHandlerManager stop dev mode handler
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointWebpackTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.1.0, target/23.3

#15215 chore: Use authorization server 1.0.0 for tests
  pom.xml
Labels: +0.0.1

#15244 test: Delete some more webpack specific tests
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoWebpackTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentWebpackIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentWebpackIT.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadWebpackIT.java
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/WebpackDevServerPortIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeWebpackIT.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointWebpackTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerStopTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/WebpackHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerWebpackTest.java
Labels: +0.1.0

#15255 chore: Update to TB 8.1.4
  pom.xml
Labels: +0.0.1, target/23.2

#15254 chore: Update to TB 6.5.1
  pom.xml
Labels: +0.0.1

#15253 test: Care less about the exact format Vite/rollup use to names files
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/23.3

#15258 test: Fix test to be compatible with Vite 4
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1, target/23.3

#15260 chore: Update to TB 8.1.4 (#15255)
  pom.xml
Labels: +0.0.1, cherry pick

#15218 chore: Upgrade springdoc test dependency to 2.0.0-RC2
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
Labels: +0.0.1

#15270 chore: Upgrade to Spring Boot 3.0
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  pom.xml
Labels: +0.0.1

#15268 chore: Upgrade to Spring Boot 2.7.6
  pom.xml
Labels: +0.0.1, target/9.0, target/23.2

#15239 fix: Get vaadin version from core
  flow-server/src/main/java/com/vaadin/flow/internal/ServerInfo.java
Labels: +0.0.1

#15219 chore: Return an exact match before checking inheritance
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Labels: +0.0.1, target/23.3

#15274 chore(deps): bump byte-buddy from 1.12.10 to 1.12.19 (#15265)
  pom.xml
Labels: +0.0.1

#15275 chore(deps): bump byte-buddy from 1.12.1 to 1.12.19 (#15265) (CP: 9.0)
  pom.xml
Labels: +0.0.1

#15278 fix: stats in development mode
  flow-server/src/main/resources/plugins/stats-plugin/package.json
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
Labels: +0.0.1

#15280 chore: Remove warning about stats init
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
Labels: +0.0.1, target/23.2, target/23.3

#15276 chore(deps): bump byte-buddy from 1.11.22 to 1.12.19 (#15265) (CP: 2.8)
  pom.xml
Labels: +0.0.1

#15277 chore: Upgrade to Spring Boot 2.7.6 (#15268) (CP: 23.2)
  flow-tests/vaadin-spring-tests/pom.xml
  pom.xml
Labels: +0.0.1

#15271 test: Use springdoc 2.0.0
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
Labels: +0.0.1

#15285 fix: Add a template of old tsconfig.json used in OSGi
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig-osgi.json
Labels: +0.0.1, target/23.3

#15287 fix: no stream serialization without uis
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/tests/server/SerializationTest.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3

#15292 fix: Empty alt in costructor should add property
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3

#15294 chore: add call thread debug logging
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
Labels: +0.0.1, target/23.2, target/23.3

#15252 feat: Added a shorthand to remove a component from its parent
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1, Contribution

#15300 fix: Empty alt in costructor should add property (#15292) (2.8)
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
Labels: +0.0.1, cherry pick

#15282 fix: remove clear condition for hierarchical data
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +0.0.1, Contribution, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#15251 chore: Upgrade vite-plugin-checker to 0.5.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/23.3

#15310 refactor: Record project folder inside node_modules instead (#15216) (CP: 23.2)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1

#15188 fix!: Use dedicated mapping for Vaadin push endpoint
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-client/src/main/java/com/vaadin/client/communication/PushConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PushConfigurationMap.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinMVCWebAppInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationRootMappedTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationUrlMappedTest.java
Labels: +1.0.0, target/23.3

#15087 chore: Import files using extension
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
Labels: +0.0.1, target/23.3

#14984 Increase initial delay to show loading indicator
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/LoadingIndicatorConfigurationMap.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3

#15316 chore: update lit to 2.3.1 (23.2)
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#15323 refactor: Rename Builder to Options and remove build() method
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0, target/23.3
