Repository vaadin/flow, pull requests merged in 2022-10, with the labels that each got.

#14715 test: fix BootstrapHandlerTest on Windows
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14717 test: Added Windows check assumption for FrontendUtilsTest.deleteNodeModules_canDeleteSymlinksAndNotFollowThem #14716
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14725 test: fix BootstrapHandlerTest on Windows (#14715) (CP 9.0)
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#14724 test: fix BootstrapHandlerTest on Windows (#14715) (CP 23.1)
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#14727 test: fix BootstrapHandlerTest on Windows (#14715) (CP 2.7)
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#14726 test: fix BootstrapHandlerTest on Windows (#14715) (CP 2.8)
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
Labels: +0.0.1

#14729 fix: attach polymer binding callback to a promise that always resolves
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/test-gwt/java/com/vaadin/client/ClientEngineTestBase.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtBasicElementBinderTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPolymerModelTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14734 chore: Improve the error message when the deployment is broken
  flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationConfiguration.java
Labels: +0.0.1, target/23.2

#14749 fix: ignore nonexistent nodes during resync
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
  flow-client/src/test/java/com/vaadin/client/flow/TreeChangeProcessorTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14748 chore: update Binder ValueChangeListener javadocs
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14745 [Snyk] Upgrade org.eclipse.jetty:jetty-servlets from 10.0.11 to 10.0.12
  pom.xml
Labels: +0.0.1

#14768 fix: ignore nonexistent nodes during resync (#14749)
  flow-client/src/main/java/com/vaadin/client/flow/StateTree.java
  flow-client/src/main/java/com/vaadin/client/flow/TreeChangeProcessor.java
  flow-client/src/test/java/com/vaadin/client/flow/TreeChangeProcessorTest.java
Labels: +0.0.1, cherry pick, target/2.7

#14769 test: update test component versions
  flow-tests/test-frontend/vite-basics/package.json
Labels: +0.0.1

#14777 fix: Redirect if refresh token is in push response also
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14786 fix: Redirect if refresh token is in push response also (#14777)
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
Labels: +0.0.1, cherry pick, target/2.7

#14742 fix: defer location and query tracking
  flow-client/src/main/java/com/vaadin/client/PopStateHandler.java
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/navigation/ui/FirstView.java
  flow-tests/test-v14-bootstrap/src/main/java/com/vaadin/flow/navigation/ui/SecondView.java
  flow-tests/test-v14-bootstrap/src/test/java/com/vaadin/flow/navigation/ui/BrowserNavigationServerRoundTripIT.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2

#14775 feat: Allow specifying vaadin.devServerPort to connect to an already running dev server
  flow-tests/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1

#14793 fix: defer location and query tracking (#14742) (CP: 2.8)
  flow-client/src/main/java/com/vaadin/client/PopStateHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/navigation/FirstView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/navigation/SecondView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/navigation/BrowserNavigationServerRoundTripIT.java
Labels: +0.0.1, cherry pick, target/2.7

#14798 chore: Update nexus-staging-maven-plugin version
  flow-tests/pom.xml
  flow-tests/vaadin-spring-tests/pom.xml
  pom.xml
Labels: +1.0.0, Flow 24.0

#14799 chore: Set version for nexus stage plugin in the root pom
  flow-tests/pom.xml
  flow-tests/vaadin-spring-tests/pom.xml
  pom.xml
Labels: +1.0.0, Flow 24.0

#14776 chore: Update TB to 14.9 corresponding version
  pom.xml
Labels: +0.0.1, target/2.7

#14804 chore: Do not record npm install time when npm install did not happen
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.0.1, target/23.1, target/23.2

#14795 Fix Javadoc rendering in AppShellConfigurator
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#14808 chore: update vaadin-parent to 2.1.0 (24.0)
  pom.xml
Labels: +1.0.0, Flow 24.0

#14817 chore: Log used tool before check
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.1, target/23.2, target/23.3

#14818 chore: Remove ServletVerifier which is not relevant for Vaadin 24
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletVerifier.java
  flow-server/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +1.0.0

#14813 chore: Upgrade Node to 16.18.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.1.0

#14832 chore: validate tool after debug log
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +1.0.0, target/23.3

#14834 chore(deps-dev): bump jaxb-impl from 4.0.0 to 4.0.1 (#14600)
  pom.xml
Labels: +1.0.0

#14830 chore: upgrade to Node 18.11.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +1.0.0, target/23.3

#14842 feat: Throw a meaningful exception if deployed into a Servlet 5 container
  flow-server/pom.xml
Labels: +0.0.1

#14831 feat: Register VaadinSecurityContextHolderStrategy as a bean (#14631)
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#14849 chore: Update license-checker to latest
  pom.xml
Labels: +0.0.1, target/23.2, target/23.3

#14841 Throw a meaningful exception if deployed into a Servlet 3 container
  flow-client/pom.xml
  flow-server/pom.xml
Labels: +0.0.1

#14741 fix: locking on FeatureFlags instead of VaadinContext (#13962)
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1, target/23.1, target/23.2, target/23.3

#14840 fix: old node installation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.2, target/23.3

#14838 fix: synchronize pwa handler on map
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Labels: +0.0.1, target/9.0, target/23.1, target/23.2, target/23.3

#14850 chore: Update versions table in readme
  README.md
Labels: +0.0.1

#14870 fix: AbstractDataProvider serialization issue (#14654)
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
Labels: +0.0.1, target/23.1, target/23.2, target/23.3

#14869 fix: synchronize pwa handler on map (#14838)
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Labels: +0.0.1, cherry pick

#14827 fix: use access and not lock
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.2, target/23.3

#14836 feat: Show version info in debug window (#12000)(CP: 2.8)
  flow-client/.eslintrc.js
  flow-client/src/main/resources/META-INF/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/main/resources/META-INF/frontend/copy-to-clipboard.js
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
  flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowConnection.java
  flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowData.java
  flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowMessage.java
  flow-server/src/main/java/com/vaadin/flow/internal/ServerInfo.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-server/src/test/java/com/vaadin/flow/internal/BrowserLiveReloadAccessTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/DebugWindowConnectionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0, cherry pick

#14886 chore: Update servlet detector to 1.0.1
  flow-server/pom.xml
Labels: +0.0.1

#14871 feat: License checker in Java instead of browser (CP: 2.8)
  flow-client/pom.xml
  flow-client/src/main/resources/META-INF/frontend/License.ts
  flow-client/src/main/resources/META-INF/frontend/VaadinDevmodeGizmo.ts
  flow-client/src/test/frontend/VaadinDevmodeGizmoTests.js
  flow-client/tsconfig.json
  flow-lit-template/pom.xml
  flow-maven-plugin/pom.xml
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowConnection.java
  flow-server/src/main/java/com/vaadin/flow/internal/DebugWindowData.java
  flow-server/src/main/java/com/vaadin/flow/internal/ProductAndMessage.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CvdlProducts.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/main/resources/plugins/stats-plugin/stats-plugin.js
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  pom.xml
Labels: +0.1.0, cherry pick

#14885 fix: use access and not lock (#14827)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
Labels: +0.0.1, cherry pick, target/2.7

#14843 fix: Allow Hilla push request without Spring CSRF
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Labels: +0.0.1

#14899 chore: update testbench version
  pom.xml
Labels: +0.0.1, target/2.7

#14895 fix: long parameter regex
  flow-server/src/main/java/com/vaadin/flow/router/ParameterDeserializer.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteParameterRegex.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.0.1, target/23.1, target/23.2, target/23.3

#14910 chore(deps): bump jackson-databind from 2.13.4 to 2.13.4.2 (#14846)
  pom.xml
Labels: +0.0.1, cherry pick, target/23.2

#14913 chore!: Remove VaadinWebSecurityConfigurerAdapter
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurityConfigurerAdapter.java
Labels: +0.0.1

#14916 chore!: Upgrade to SLF4J 2.0
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  pom.xml
Labels: +0.0.1

#14911 chore: Upgrade to Spring Boot 3 RC1
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtSecurityContextRepositoryTest.java
Labels: +0.0.1

#14918 chore: fix javadoc so snapshot compiles
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
Labels: +0.0.1

#14920 chore: Sync Jackson version with Spring Boot 3 RC1
  pom.xml
Labels: +0.0.1

#14902 feat: Move new license checker feature behind config parameter
  flow-client/src/main/resources/META-INF/frontend/License.ts
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/BootstrapHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
Labels: +1.0.0

#14919 chore!: Use authorizeHttpRequests instead of deprecated authorizeRequests
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#14922 fix: enforce the deprecated CSRF handler temporarily
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#14909 fix: run npm install if folder changes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.1, target/23.2, target/23.3

#14926 chore: validate javadoc when running unit-tests
  .github/workflows/validation.yml
Labels: +0.0.1

#14925 test: Explicitly use AntPathRequestMatcher to avoid problems
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
Labels: +0.0.1

#14932 fix: Send new csrf cookie in login response
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
Labels: +0.0.1

#14930 fix: run npm install if folder changes (#14909)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, cherry pick, target/2.7

#14931 fix: run npm install if folder changes (#14909)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
Labels: +0.0.1, cherry pick

#14938 chore: update to stable TB 6.5.0
  pom.xml
Labels: +0.0.1

#14924 fix: clean commented css before handling
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/23.1, target/23.2, target/23.3

#14944 fix: clean commented css before handling (#14924)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1, cherry pick, target/23.1

#14937 test: Enable Gradle tests with Gradle 7.5.1 and correct Spring Boot version
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1, target/23.3

#14947 chore: Upgrade to Node 18.12 LTS
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.3

#14772 chore: record last session lock/unlock time
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
Labels: +0.0.1, target/9.0, target/23.1, target/23.2, target/23.3

#14949 chore: Update testbench to 8.1.2
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, target/23.2

#14946 test: Enable Gradle tests with Gradle 7.5.1 and correct Spring Boot version (#14937) (CP: 23.3)
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  flow-plugins/flow-gradle-plugin/gradlew
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1
