Repository vaadin/flow, pull requests merged in 2022-07, with the labels that each got.

#14119 chore: Delete extra whitespace
  flow-client/src/main/frontend/License.ts
Labels: +0.0.1

#14120 chore: fix greater than sign in javadoc
  flow-data/src/main/java/com/vaadin/flow/data/binder/HasValidator.java
Labels: +0.0.1, target/23.0, target/23.1

#14123 fix: separate core and commercial components version files (#14014) (CP: 9.0)
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.1.0

#14124 fix: separate core and commercial components version files (#14014) (CP: 2.7)
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: +0.1.0, target/2.8

#14111 feat: remove validation status change listener upon unbind
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
Labels: +0.0.1, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14144 fix: always generate themes in frontend 'generated' directory subfolder
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
  flow-tests/pom.xml
  flow-tests/test-custom-frontend-directory/pom.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom-generatedTsDir.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/index.ts
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/src/css-loading-view.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/components/shared/background-color.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/components/vaadin-radio-button.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/components/vaadin-text-field.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/font/IBMPlexMono-Regular.otf
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/font/ostrich-sans-regular.ttf
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/icons/archive.png
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/img/bg.jpg
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/img/dice.jpg
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/styles.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/sub-css/sub.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/theme.json
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/unused.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/no-copy/no-copy.txt
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/parent-theme/styles.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/typescript/hello-world-view.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/typescript/hello-world-view.ts
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/servlets/ServletWithPath.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/AppShell.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/CssLoadingView.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/ThemeView.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/webapp/octopuss.jpg
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/webapp/path/test/path/monarch-butterfly.jpg
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/webapp/styles/page-stylesheet.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/webapp/styles/stylesheet.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#14149 chore: Upgrade to TestBench 8.1 alpha 10
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BodyScrollIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebComponentsIT.java
  pom.xml
Labels: +0.0.1

#14154 [Snyk] Security upgrade org.eclipse.jetty:jetty-servlets from 10.0.9 to 10.0.10
  pom.xml
Labels: +0.0.1

#14153 chore: Upgrade Node to 16.16
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.0, target/23.1

#14165 test: fix minor issues related to macos m1 tests failing
  flow-client/src/test/java/com/vaadin/client/DomApiAbstractionUsageTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComplexDialogShortcutView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/scroll/MultipleAnchorsIT.java
Labels: +0.0.1

#14168 Update to testbench 8.1.0.alpha11
  pom.xml
Labels: +0.0.1

#14185 fix: add empty export to vaadin-featureflags.ts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
Labels: +0.0.1

#14068 fix: Let DataCommunicator#flush keep track of which StateTree is supposed to execute its flushRequest
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, Contribution, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14193 fix: Let DataCommunicator#flush keep track of its StateTree (CP: 9.0)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1

#14174 test: workaround for internal selenium grid
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
  flow-tests/test-frontend/vite-pwa-production/pom.xml
  flow-tests/test-frontend/vite-pwa/pom.xml
Labels: +0.0.1

#14158 feat: allow disabling validation status change listener registration on binder
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
Labels: +0.1.0, Contribution, target/2.7, target/9.0, target/2.8, target/23.0, target/23.1

#14195 fix: Let DataCommunicator#flush keep track of its StateTree (CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/2.8

#14151 fix: Fix ServiceWorker path requests in dev mode
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
  flow-server/src/test/java/com/vaadin/flow/server/PwaRegistryTest.java
  flow-tests/test-frontend/vite-pwa-production/src/test/java/com/vaadin/viteapp/MainIT.java
Labels: +0.0.1

#14201 feat: Improving DX ValidationResult
  flow-data/src/main/java/com/vaadin/flow/data/binder/ValidationResult.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/ValidationResultTest.java
Labels: +0.1.0, Contribution

#14205 feat: allow disabling validation status change listener registration on binder (CP: 2.7)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderValidationStatusChangeListenerTest.java
Labels: +0.1.0, target/2.8

#14207 fix: Let DataCommunicator#flush keep track of its StateTree (CP: 2.8)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1

#14192 [Snyk] Upgrade lit from 2.2.6 to 2.2.7
  flow-client/package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/pnpm-lock.yaml
Labels: +0.0.1

#14182 fix: build the service worker without writing it to FS
  flow-server/src/main/resources/vite.generated.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
Labels: +0.0.1, target/23.1

#14224 chore: remove debug logs from theme loader utilities
  flow-server/src/main/resources/plugins/theme-loader/theme-loader-utils.js
Labels: +0.0.1, target/23.1

#14204 feat: provides collection based append/remove methods for Node
  flow-server/src/main/java/com/vaadin/flow/dom/Node.java
Labels: +0.1.0

#14230 fix: provide correct devMode flag to theme-generator with Vite
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.1.0, target/23.1

#14229 fix: build the service worker without writing it to FS (#14182) (CP: 23.1)
  flow-server/src/main/resources/vite.generated.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
Labels: +0.0.1, cherry pick

#14221 feat: add configuration to `TaskGenerateHilla`
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
Labels: +1.0.0

#14202 feat: provides collection based methods for HasComponents
  flow-server/src/main/java/com/vaadin/flow/component/HasComponents.java
Labels: +1.0.0
