Repository vaadin/flow, pull requests merged in 2023-02, with the labels that each got.

#15793 feat: Register @route classes for Spring native automatically
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
Labels: +0.0.1

#15796 chore: update TB to 9.0.0.alpha7
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#15800 chore: Bump vite-plugin-checker to 0.5.5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15799 fix: Fix problems in Hilla native compilation
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: +0.0.1

#15804 fix: Use correct SecurityContextRepository for stateless authentication
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
Labels: +0.0.1

#15802 feat: Throw a meaningful exception if deployed into a Servlet 5 container (#14842)(CP: 2.8)
  flow-server/pom.xml
Labels: +0.0.1, cherry pick

#15801 feat: Throw a meaningful exception if deployed into a Servlet 5 container (#14842)(CP: 9.0)
  flow-server/pom.xml
Labels: +0.0.1, cherry pick

#15805 chore: Upgrade to Testbench 9.0.0.beta1
  pom.xml
Labels: +0.0.1

#15742 feat: Allow every component to have styles
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
Labels: +0.1.0

#15807 chore: Upgrade Vite to 4.1.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#15690 chore: bump frontend dependency to 24.0.0-alpha13
  .github/workflows/validation.yml
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-tests/test-application-theme/test-reusable-as-parent-vite/src/main/java/com/vaadin/flow/uitest/ui/theme/MyPolymerField.java
  flow-tests/test-application-theme/test-theme-reusable-vite/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/typescript/hello-world-view.ts
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/MyComponent.java
  flow-tests/test-embedding/test-embedding-reusable-theme/src/main/java/com/vaadin/flow/webcomponent/MyComponent.java
  flow-tests/test-express-build/test-theme-dev-bundle/frontend/themes/my-theme/styles.css
  flow-tests/test-express-build/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/ThemableTextField.java
  flow-tests/test-themes/frontend/typescript/hello-world-view.ts
  flow-tests/test-themes/src/main/java/com/vaadin/flow/uitest/ui/theme/MyComponent.java
Labels: +0.0.1

#15814 fix(Hilla): run generator tasks after npm install
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
Labels: hilla, +0.0.1

#15764 fix: preserve push messages in cache until they are seen by client
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/LongPollingCacheFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
Labels: +0.1.0, target/9.0, target/2.8, target/23.2, target/23.3

#15767 fix: prevent concurrent disconnect and push operations
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3

#15791 fix: add push servlet mapping & fix automatic push endpoint location
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-client/src/main/java/com/vaadin/client/communication/PushConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PushConfigurationMap.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
Labels: +1.0.0

#15816 chore: Upgrade Node to install to 18.14.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#15786 fix: fixed support for Spring EnableMethodSecurity (#15059)
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/Configurator.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityUtils.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/data/Account.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/data/UserInfo.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/service/AccountService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/service/BankService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/service/UserInfoService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AnotherPublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/Broadcaster.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LoginView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MainView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/META-INF/resources/frontend/themes/spring-security-test-app/styles.css
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/META-INF/resources/icons/icon.png
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/application-contextpath.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/admin-only/secret.txt
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/all-logged-in/secret.txt
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/icons/icon.png
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/images/bank.jpg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/images/logo.jpg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/profiles/admin.svg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/profiles/user.svg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/public.txt
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/resources/image.png
  scripts/computeMatrix.js
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
Labels: +0.0.1, target/23.2, target/23.3

#15827 fix: prevent concurrent disconnect and push operations (#15767) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, cherry pick

#15830 fix: fixed support for Spring EnableMethodSecurity (CP 23.3)
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/Configurator.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityUtils.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/data/Account.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/data/UserInfo.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/service/AccountService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/service/BankService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/service/UserInfoService.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AnotherPublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/Broadcaster.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LoginView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MainView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/META-INF/resources/frontend/themes/spring-security-test-app/styles.css
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/META-INF/resources/icons/icon.png
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/application-contextpath.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/admin-only/secret.txt
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/all-logged-in/secret.txt
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/icons/icon.png
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/images/bank.jpg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/images/logo.jpg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/profiles/admin.svg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/profiles/user.svg
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/resources/static/public/public.txt
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/resources/image.png
  scripts/computeMatrix.js
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinAwareSecurityContextHolderStrategyConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
Labels: +0.0.1, cherry pick

#15844 fix: pwa charset
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.3, target/24.0

#15824 fix: Serve text/css/xml/javascript resources correctly outside the context of a page
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/JavascriptServedAsUtf8IT.java
  flow-tests/test-resources/src/main/resources/META-INF/resources/frontend/test-files/js/unicode.js
Labels: +0.0.1, target/9.0, target/2.8, target/23.3, target/24.0

#15855 chore: configure weight of pos=5 to only accommodate spring modules
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
  scripts/computeMatrix.js
Labels: +0.0.1

#15872 fix: rename stats dependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, express-build, target/24.0

#15826 fix: preserve push messages in cache until they are seen by client (#15764) (CP: 9.0)
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/LongPollingCacheFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
Labels: +0.1.0, cherry pick

#15867 fix: Add Atmosphere classes used by Hilla
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/AtmosphereHintsRegistrar.java
Labels: +0.0.1, target/24.0

#15863 fix: add push servlet mapping & fix automatic push endpoint location …
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-client/src/main/java/com/vaadin/client/communication/PushConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/component/PushConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/BootstrapHandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PushConfigurationMap.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
Labels: +1.0.0, cherry pick

#15879 fix: make application-theme-plugin type module
  flow-server/src/main/resources/plugins/application-theme-plugin/application-theme-plugin.js
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
Labels: +0.0.1, target/24.0

#15853 fix: Serve text/css/xml/javascript resources correctly outside the context of a page (#15824) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/JavascriptServedAsUtf8IT.java
  flow-tests/test-resources/src/main/resources/META-INF/resources/frontend/test-files/js/unicode.js
Labels: +0.0.1, cherry pick

#15861 fix: Serve text/css/xml/javascript resources correctly outside the context of a page (#15824) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/JavascriptServedAsUtf8IT.java
  flow-tests/test-resources/src/main/resources/META-INF/resources/test-files/js/unicode.js
Labels: +0.0.1, cherry pick

#15854 fix: Serve text/css/xml/javascript resources correctly outside the context of a page (#15824) (CP: 9.0)
  flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/JavascriptServedAsUtf8IT.java
  flow-tests/test-resources/src/main/resources/META-INF/resources/frontend/test-files/js/unicode.js
Labels: +0.0.1, cherry pick

#15882 fix: frontend hotdeploy always false in production mode
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
Labels: +0.0.1, express-build, target/24.0

#15891 fix: Make livereload on Spring work more than once
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringDevToolsPortHandler.java
Labels: +0.0.1, target/24.0

#15893 feat: bundle should take into account index.ts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, express-build, target/24.0

#15911 fix: Only show development tools code tab when Flow is used
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +1.0.0, target/24.0

#15916 fix: package generation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +1.0.0, express-build, target/24.0

#15919 fix: Do not warn about eval usage that the user cannot affect
  flow-server/src/main/resources/vite.generated.ts
Labels: +1.0.0, target/24.0

#15813 fix: Use feature detection to show the unsupported browser page
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/resources/com/vaadin/flow/server/browser-too-old.html
  flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/InfoView.java
  flow-tests/test-root-context/src/main/resources/browser-too-old.html
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CustomBrowserTooOldPageIT.java
Labels: +1.0.0, target/24.0

#15917 fix: Add reserved /VAADIN segment to the theme pattern
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-express-build/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +1.0.0, express-build, target/24.0

#15935 chore: Update TestBench to 9.0.0.beta2
  pom.xml
Labels: +0.0.1, target/24.0

#15905 chore: clarify inactive session closing log messages
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.3, target/24.0

#15939 fix: Ignore old Vaadin provided dependencies for bundle resolution
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, express-build, target/24.0

#15938 chore: Upgrade to Vite 4.1.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.0

#15936 test: Use correct Selenium version for Spring tests
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, target/24.0

#15931 chore: Upgrade default Node to 18.14.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +1.0.0, target/24.0

#15934 chore: Upgrade default installed node
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#15904 chore: Updated legacy documentation for CustomizedSystemMessages
  flow-server/src/main/java/com/vaadin/flow/server/CustomizedSystemMessages.java
  flow-server/src/main/java/com/vaadin/flow/server/SystemMessages.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.3, target/24.0

#15896 fix: ignore missing files in theme processing
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3, target/24.0

#15960 chore: add frontend dev setup to vaadin-dev-tools
  vaadin-dev-server/README.md
  vaadin-dev-server/package.json
  vaadin-dev-server/patch-application.js
  vaadin-dev-server/web-dev-server.config.mjs
Labels: +0.0.1

#15972 refactor: make dev tool tabs content updatable
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#15974 refactor: replace invalid CSS template literals in dev tool
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#15976 refactor: make dev tools component picker reusable
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/component-picker.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#15983 chore: add prettier to dev tools and reformat code
  vaadin-dev-server/README.md
  vaadin-dev-server/package.json
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/component-picker.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#15975 chore: remove options and feature flags related to Hilla
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestEndpointGeneratorTaskFactory.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/TestUtil.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateHilla.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/LookupServletContainerInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
Labels: hilla, +1.0.0, target/24.0

#15989 fix: Add Service Worker to the dev-bundle and serve it
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
  flow-tests/test-express-build/test-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java
Labels: +0.0.1, express-build, target/24.0

#15924 fix: consume parallel streams when fetching paginated data
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +1.0.0, target/23.3, target/24.0

#15996 chore: update license-checker to 1.12.0
  pom.xml
Labels: +0.0.1, target/23.2, target/23.3, target/24.0

#15977 fix: Apply custom theme styles after Lumo styles
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/test-express-build/test-embedding-express-build/frontend/themes/embedded-theme/document.css
  flow-tests/test-express-build/test-embedding-express-build/frontend/themes/embedded-theme/font/IBMPlexMono-Regular.otf
  flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-express-build/test-theme-dev-bundle/frontend/themes/my-theme/styles.css
  flow-tests/test-express-build/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
Labels: +1.0.0, express-build, target/24.0

#16012 refactor: feature flag for theme editor
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ThemeModifier.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/ThemeModifierTest.java
Labels: +0.0.1

#16013 chore: exclude frontend tests from dev tools package
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#16003 refactor: add basic theme editor panel
  vaadin-dev-server/package.json
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/component-picker.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/icons.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/registry.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#15997 chore: update TB to 9.0 rc1
  pom.xml
Labels: +0.0.1, target/24.0

#15932 chore: Upgrade default installed Node
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#15933 chore: Upgrade default installed Node
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#16018 fix: Enable code tab by default
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.0

#16014 refactor: show notice for missing theme in theme editor
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#16009 chore: Re-import sources from git for fileupload
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItem.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/RequestContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/DiskFileItem.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/DiskFileItemFactory.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltRequestContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/package-info.java
Labels: +1.0.0, target/24.0

#16021 fix: Enable code tab by default (#16018) (CP: 24.0)
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#16023 test: Remove unnecessary dependencies
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, target/24.0

#15967 fix: ignore missing files in theme processing (#15896) (CP: 2.8)
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
Labels: +0.0.1, cherry pick

#16010 fix: Update to latest file upload master
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUploadBase.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileCountLimitExceededException.java
Labels: +0.0.1, target/24.0

#15968 chore: add javadoc notes on nested property binding (#15948) (CP: 2.8)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1, cherry pick

#16039 fix: Ignore ?inline suffix for imported stylesheets
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, express-build, target/24.0

#16042 fix: Restore the Hilla exception for the code tab
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.0

#16045 fix: Restore the Hilla exception for the code tab (#16042) (CP: 24.0)
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#16048 test: remove unnecessary depedendencies (CP: 24.0)
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1

#16027 refactor: basic editing of properties in theme editor
  vaadin-dev-server/package.json
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/events.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-text-field.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
  vaadin-dev-server/web-test-runner.config.mjs
Labels: +0.0.1

#16049 chore: Upgrade to Vite 4.1.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +1.0.0, target/24.0

#15992 fix: Check for changes in project frontend files
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/views/another.ts
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/views/lit-view.ts
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/pom.xml
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/LitView.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/ChangeFrontendContentIT.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/dependencies/AnnotatedContextInlineView.java
Labels: +0.0.1, express-build, target/24.0

#16059 fix: Add missing getters to Options
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateViteDevMode.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0, target/24.0

#16063 fix: Use context class loader for class finder
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ClassFinder.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ClassFinderTest.java
Labels: +0.0.1, target/24.0

#16060 refactor: disable live reload on CSS changes in theme editor
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#16052 fix: Lock @types/node as newer versions are incompatible with the used typescript version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#16073 fix: Deleting or adding a file without importing it shouldn't cause re-bundling
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, express-build, target/24.0

#16072 refactor: keep modified component themes in theme editor
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
Labels: +0.0.1

#16064 refactor: ThemeEditor - support for setting / removing class names
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/LineNumberVisitor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ModifierException.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_clean.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messed.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messedExpected.java
Labels: +0.0.1

#16075 chore: add 24.0 branch to validate push event
  .github/workflows/validation.yml
Labels: +0.0.1, target/23.2, target/23.3, target/24.0
