Repository vaadin/flow, pull requests merged in 2023-11, with the labels that each got.

#17964 fix: Throw if not CREATED response
  flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
Labels: +0.0.1, target/24.2

#17973 test: clean frontend stuff for npm dev mode test module
  flow-tests/test-frontend/test-npm/pom.xml
Labels: +0.0.1

#17965 cp: Enable Atmosphere heartbeat (#17845) (24.1)
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  vaadin-dev-server/frontend/connection.ts
Labels: +0.0.1, cherry pick

#17966 cp: Enable Atmosphere heartbeat (#17845) (24.2)
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  vaadin-dev-server/frontend/connection.ts
Labels: +0.0.1, cherry pick

#17974 fix: prevent installing pnpm if not required
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
Labels: +0.0.1, target/24.2

#17976 chore: Upgrade @vitejs/plugin-react to 4.1.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.2

#17979 chore: Gradle plugin basic maintenance
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
Labels: +1.0.0

#17969 chore: Upgrade Spring-Boot to 3.2 RC2
  pom.xml
Labels: +0.0.1

#17983 chore: Bump to lit 3.0.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#17980 test: run production mode first for npm and pnpm test modules
  flow-tests/test-frontend/pom.xml
  flow-tests/test-frontend/test-npm/pom-production.xml
  scripts/computeMatrix.js
Labels: +0.0.1

#17986 Chore: Gradle plugin cleanup
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
Labels: +0.0.1

#17989 chore: gradle plugin test cleanup
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1

#17985 refactor: Write dev tools config as a global
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.test.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#17991 chore: Upgrade to TestBench 9.2.0.alpha1
  pom.xml
Labels: +0.1.0

#17977 feat: use devBundle from build folder
  .gitignore
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImplTest.java
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParserTest.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CompressUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CompressionException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/DevBundleUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFile.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeValidationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/DevBundleUtilsTest.java
  flow-server/src/test/java/com/vaadin/tests/util/TestUtil.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/ChangeFrontendContentIT.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
  flow-tests/test-express-build/test-dev-bundle-java-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/AddOnIT.java
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
  flow-tests/test-express-build/test-dev-bundle/pom.xml
  flow-tests/test-express-build/test-parent-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ParentThemeIT.java
  flow-tests/test-express-build/test-parent-theme-in-frontend/src/test/java/com/vaadin/flow/devbuild/ParentThemeInFrontendIT.java
  flow-tests/test-express-build/test-reusing-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ReusingThemeIT.java
  flow-tests/test-express-build/test-theme-dev-bundle/.gitignore
  flow-tests/test-express-build/test-theme-dev-bundle/src/test/java/com/vaadin/flow/devbuild/DevBundleThemeIT.java
Labels: +1.0.0

#17992 fix: Expose Properties in VaadinFlowPluginExtension
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ClasspathFilter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendOutputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinConvertPolymerTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
Labels: +0.0.1

#17996 refactoring: replace calls to deprecated methods; kdoc cleanup
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
Labels: +0.0.1

#17999 fix: path difference on windows
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeValidationUtil.java
Labels: +0.0.1

#18005 fix: Do not try to write readme if no compression
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
Labels: +0.0.1

#17994 feat: Enable running npm ci mode (CP: 23.4)
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0, cherry pick

#17971 fix: sync property change properly using debouncer
  flow-client/src/main/java/com/vaadin/client/flow/binding/Debouncer.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-client/src/main/java/com/vaadin/client/flow/nodefeature/MapProperty.java
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtPropertyElementBinderTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SynchronizedPropertyIT.java
Labels: +0.0.1

#16024 fix!: Use feature detection to show the unsupported browser page (#15813) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/UnsupportedBrowserHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/resources/com/vaadin/flow/server/browser-too-old.html
  flow-server/src/test/java/com/vaadin/flow/server/UnsupportedBrowserHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerWebpackTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/InfoView.java
  flow-tests/test-root-context/src/main/resources/browser-too-old.html
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/CustomBrowserTooOldPageIT.java
Labels: +1.0.0

#18007 fix: Make TypeScriptBootstrapModifier work when building with Maven/Gradle
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TypeScriptBootstrapModifier.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/BootstrapModifier.java
  flow-tests/test-frontend/vite-basics/src/main/resources/META-INF/services/com.vaadin.flow.server.frontend.TypeScriptBootstrapModifier
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeClassFinderTest.java
Labels: +1.0.0

#17997 feat: reuse the production bundle if no changes
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CompressUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ProdBundleUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ProdBundleUtilsTest.java
  flow-tests/test-express-build/test-prod-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
Labels: +1.0.0

#18013 chore: remove mobile dnd polyfill
  flow-dnd/src/main/java/com/vaadin/flow/component/dnd/internal/DndUtil.java
  flow-dnd/src/main/resources/META-INF/resources/frontend/dnd-polyfill-loader.js
  flow-dnd/src/main/resources/META-INF/resources/frontend/dndConnector.js
  flow-dnd/src/main/resources/META-INF/resources/frontend/vaadin-mobile-drag-drop.js
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/OpenInCurrentIdeTest.java
Labels: +0.0.1, target/24.1, target/24.2

#18019 fix: improve error message when a component is moved from one UI to another.
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
Labels: +0.0.1

#18022 fix: support accept property in StreamReceiverHandler
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, target/1.0, target/23.3, target/2.9, target/9.1, target/24.1, target/2.10, target/24.2, target/23.4

#18028 test: reset ComponentTracker.productionMode static field
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1

#17990 chore: Run tests with Bun in a separate profile
  .github/workflows/validation.yml
  flow-tests/test-frontend/pom.xml
Labels: +1.0.0

#18037 chore: update vaadin-parent to 2.2.1
  pom.xml
Labels: +0.0.1

#18039 chore: Upgrade Lit to 3.1.0
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#18038 fix: support accept property in StreamReceiverHandler (#18022) (CP: 2.9)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18036 fix: support accept property in StreamReceiverHandler (#18022) (CP: 2.10)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18030 fix: support accept property in StreamReceiverHandler (#18022) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18029 fix: support accept property in StreamReceiverHandler (#18022) (CP: 23.4)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18046 fix: update atmosphere to 3.0.3.slf4jvaadin2
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1, target/24.1, target/24.2

#17886 chore!: Upgrade to Vite 5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/plugins/rollup-plugin-postcss-lit-custom/rollup-plugin-postcss-lit.js
Labels: external dependency, +0.0.1

#18018 fix: Do not run NodeTasks in parallel
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
Labels: +0.1.0

#18045 Do not touch package.json files unless content has changed
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
Labels: +0.0.1, target/24.2

#18034 chore: add react feature flag.
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#18040 fix: support accept property in StreamReceiverHandler (#18022) (CP: 1.0)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18035 fix: support accept property in StreamReceiverHandler (#18022) (CP: 9.1)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18052 fix: update atmosphere to 2.7.3.slf4jvaadin6 (#18047) (CP:2.9)
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1, target/9.1, target/2.10

#18032 test: replace chrome mobile profile with custom settings
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
Labels: +0.0.1, target/23.3, target/9.1, target/24.1, target/24.2, target/23.4

#18059 fix: revert addClickShortcut to not reset focus by default
  flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShadowRootShortcutsWithValueChangeModeView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsWithValueChangeModeView.java
Labels: +0.0.1

#18061 fix: improve error message when a component is moved from one UI to another. (#18019) (CP: 24.1)
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementUtil.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementUtilTest.java
Labels: +0.0.1, cherry pick

#18023 fix: prevent propagating IO errors when serving PWA icons
  flow-server/src/main/java/com/vaadin/flow/server/communication/PwaHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PwaHandlerTest.java
Labels: +0.0.1

#18054 feat: Implement RangeInput component
  flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentProperty.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/RangeInputTest.java
Labels: +0.1.0

#18080 chore: Upgrade to TypeScript 5.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#18058 feat: add react router defaults
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/App.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vaadin-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +1.0.0

#18072 fix: consider routes not-public if access control is disabled
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
Labels: +0.0.1

#18085 chore: Upgrade to Vite 5.0.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18086 fix: allow access to error view if not denied by access checker
  flow-server/src/main/java/com/vaadin/flow/server/auth/DefaultNavigationCheckDecisionResolver.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/NavigationAccessControlTest.java
Labels: +0.0.1

#18084 fix: reroute to NotFoundException from default RouteAccessDeniedError
  flow-server/src/main/java/com/vaadin/flow/router/RouteAccessDeniedError.java
Labels: +1.0.0

#18087 chore: Upgrade to Vite 5.0.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18081 feat!: Implement HasPlaceholder
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/InputTextElement.java
  flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/InputTextElementIT.java
  flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/InputTextView.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Input.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/InputTest.java
  flow-server/src/main/java/com/vaadin/flow/component/HasPlaceholder.java
  flow-server/src/test/java/com/vaadin/flow/component/HasPlaceholderTest.java
Labels: +1.0.0, Contribution

#18089 feat: add border-radius style for elements
  flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
  flow-server/src/main/java/com/vaadin/flow/dom/Style.java
Labels: +1.0.0, Contribution

#18100 fix: RangeInput orientation: add support for Chrome, Edge and Safari.…
  flow-html-components/src/main/java/com/vaadin/flow/component/html/RangeInput.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/RangeInputTest.java
Labels: +0.0.1

#18103 chore: Allow hiding the dev tools button using a property
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#18095 feat: implement RangeInputElement
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/RangeInputElement.java
  flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/RangeInputElementIT.java
  flow-html-components-testbench/src/test/java/com/vaadin/flow/component/html/testbench/RangeInputView.java
Labels: +0.0.1, Contribution

#18090 chore: navigation access control javadoc improvements
  flow-server/src/main/java/com/vaadin/flow/server/auth/AccessDeniedErrorRouter.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/AccessPathChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/DefaultNavigationCheckDecisionResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/RoutePathAccessChecker.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/NavigationAccessControlConfigurer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringAccessPathChecker.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringNavigationAccessControl.java
Labels: +1.0.0

#18108 Chores: update springboot 2.7.18
  pom.xml
Labels: +0.0.1, target/23.4

#18112 chore: update spring boot to 3.1.6
  pom.xml
Labels: +0.0.1, target/24.1

#18111 chore: Upgrade to Node.js 20.10.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#18118 chore: Allow changing the dev tools don't show again message
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#18119 chore: Spring Boot 3.2.0
  pom.xml
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/SpringAccessPathCheckerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UrlMappingSpringAccessPathCheckerTest.java
Labels: +0.0.1

#18105 fix: Redirect to error view by default for errors in RPC-handling
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/ErrorHandlerUtilTest.java
Labels: +1.0.0

#18125 chore: Upgrade to TestBench 9.2.0.beta1
  pom.xml
Labels: +1.0.0

#18079 feat: Restrict debug websocket connection to loopback addresses by default
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-tests/pom.xml
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
Labels: +0.0.1, Contribution

#18131 Revert "fix: postpone commands scheduled with runWhenAttached for detached nodes (#18078)
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Labels: +0.0.1

#18110 refactor: refactor navigation access control API
  flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckDecision.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckDecisionResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/AccessCheckResult.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/DefaultAccessCheckDecisionResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessChecker.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationContext.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessCheckResultTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AnnotatedViewAccessCheckerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/NavigationAccessControlTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/RoutePathAccessCheckerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/NavigationAccessControlConfigurer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringNavigationAccessControl.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringViewAccessCheckerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/NavigationAccessControlConfigurerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/RequestUtilTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandlerTest.java
Labels: +1.0.0

#18139 chore: install also react-plugin-swc
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#18146 chore: fix WebPush FeatureFlag moreInfoLink
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1, target/24.2

#18124 feat: added a style method for the transform-origin property
  flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
  flow-server/src/main/java/com/vaadin/flow/dom/Style.java
Labels: +1.0.0, Contribution

#18128 feat: More eager cleanup for UIs using Beacon API (#16657)
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LocaleChangeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIIT.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/PreserveOnRefreshIT.java
Labels: +0.0.1, cherry pick

#18143 feat: More eager cleanup for UIs using Beacon API (#16657)
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/shared/ApplicationConstants.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LocaleChangeIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/UIsCollectedWithBeaconAPIIT.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/PreserveOnRefreshIT.java
Labels: +1.0.0, cherry pick

#18141 feat: anchor handling for react-router
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#18127 Populate UI.getCurrent() before running ErrorHandler
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1

#18151 chore: allow all hosts for devmode performance tests
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
Labels: +0.0.1

#18148 test: fix bundles folder in test clean
  .gitignore
  flow-client/README.md
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/pom.xml
  flow-tests/test-express-build/test-dev-bundle-java-add-on/pom.xml
  flow-tests/test-express-build/test-dev-bundle/pom.xml
  flow-tests/test-express-build/test-embedding-express-build/pom.xml
  flow-tests/test-express-build/test-parent-theme-express-build/pom.xml
  flow-tests/test-express-build/test-parent-theme-in-frontend/pom.xml
  flow-tests/test-express-build/test-reusing-theme-express-build/pom.xml
  flow-tests/test-express-build/test-theme-dev-bundle/pom.xml
Labels: +0.0.1

#18155 test: prevent concurrent modification exception when spring tests run in parallel
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/main/java/com/vaadin/flow/spring/flowsecurity/views/Broadcaster.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/Broadcaster.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/Broadcaster.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/Broadcaster.java
Labels: +0.0.1

#18156 test: prevent write theme resource if content is not changed
  flow-tests/test-live-reload-multimodule/ui/src/test/java/com/vaadin/flow/uitest/multimodule/ui/FrontendLiveReloadIT.java
Labels: +0.0.1

#18097 chore: bump gradle wrapper to 8.4
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  flow-plugins/flow-gradle-plugin/gradlew
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
Labels: +0.0.1

#18161 chore: upgrade gradle to 8.5
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
Labels: +0.0.1
