Repository vaadin/flow, pull requests merged in 2023-05, with the labels that each got.

#16719 chore: Delete invalid javadoc
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
Labels: +0.0.1

#16693 feat: Support lazy loading of route dependencies
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/DependencyTrigger.java
  flow-server/src/main/java/com/vaadin/flow/server/LoadDependenciesOnStartup.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/AbstractDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ChunkInfo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/EntryPointData.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithFullCPScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/DepsTests.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/frontend/lazy-component.js
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/pom-devmode.xml
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/AppConf.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/EagerViewWithLazyComponent.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/LazyView.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/test/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/LazyIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeClassFinderTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Labels: +1.0.0

#16721 chore: pinned maven enforcer plugin version
  pom.xml
Labels: +0.0.1

#16717 Fix: theme change should trigger dev bundle build in all cases (#16667) (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1

#16729 fix: Deduplicate CSS imports
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
Labels: +0.0.1

#16724 chore: Sort bundleImports for deterministic stats.json
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#16722 Rename Collab "engine" to "kit"
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#16723 feat: Make "" and "login" eager and the rest lazy by default
  flow-server/src/main/java/com/vaadin/flow/router/DefaultRoutePathProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
Labels: +0.0.1

#16709 fix: Lazy load CSS also
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
Labels: +0.0.1

#16739 fix: Make node download more stable
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Labels: +0.0.1

#16746 chore: Upgrade to Vite 4.3.5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#16745 test: Delete ignored and non-functional test
  flow-tests/pom.xml
  flow-tests/test-memory-leaks/pom.xml
  flow-tests/test-memory-leaks/src/main/java/com/vaadin/flow/memoryleaks/ui/MemoryLeakUI.java
  flow-tests/test-memory-leaks/src/test/java/com/vaadin/flow/memoryleaks/ui/RedeployLeakIT.java
Labels: +0.0.1

#16747 test: Remove productionMode parameter which has no effect
  flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-ccdm-flow-navigation/pom-production.xml
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom-generatedTsDir.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom.xml
  flow-tests/test-dev-mode/pom.xml
  flow-tests/test-eager-bootstrap/pom.xml
  flow-tests/test-frontend/test-npm/pom-production.xml
  flow-tests/test-frontend/test-npm/pom.xml
  flow-tests/test-frontend/test-pnpm/pom-production.xml
  flow-tests/test-frontend/test-pnpm/pom.xml
  flow-tests/test-frontend/vite-basics/pom.xml
  flow-tests/test-frontend/vite-context-path/pom-production.xml
  flow-tests/test-frontend/vite-embedded/pom-production.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom-production.xml
  flow-tests/test-frontend/vite-pwa-custom-offline-path/pom.xml
  flow-tests/test-frontend/vite-pwa-disabled-offline/pom-production.xml
  flow-tests/test-frontend/vite-pwa-disabled-offline/pom.xml
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-pwa-disabled-offline/pom-production.xml
  flow-tests/test-pwa-disabled-offline/pom.xml
  flow-tests/test-pwa/pom-production.xml
  flow-tests/test-pwa/pom.xml
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-scalability/pom.xml
  flow-tests/test-servlet/pom.xml
Labels: +0.0.1

#16736 refactor: Extract Maven utils to a separate class
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/MavenUtils.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProjectHelpers.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MavenUtilsTest.java
  vaadin-dev-server/src/test/resources/com/vaadin/base/devserver/maven/pom-standalone.xml
  vaadin-dev-server/src/test/resources/com/vaadin/base/devserver/maven/pom-with-parent.xml
Labels: +0.0.1

#16753 chore: Fix javadoc
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
  flow-server/src/main/java/com/vaadin/flow/server/LoadDependenciesOnStartup.java
Labels: +0.0.1

#16728 feat: add license check for production bundle
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#16758 fix: Restore JRebel support
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReloadAccess.java
Labels: +0.1.0, target/24.0

#16644 feat: Added single and double click event listeners registration methods
  flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ImageClickView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ImageClickIT.java
Labels: +1.0.0, Contribution

#16732 feat: Allow listening to additional jar-resources folders
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FileIOUtilsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/pom.xml
  flow-tests/test-live-reload-multimodule/library/pom.xml
  flow-tests/test-live-reload-multimodule/library/src/main/resources/META-INF/frontend/in-frontend.js
  flow-tests/test-live-reload-multimodule/library/src/main/resources/META-INF/resources/frontend/in-resources-frontend.js
  flow-tests/test-live-reload-multimodule/pom.xml
  flow-tests/test-live-reload-multimodule/ui/pom.xml
  flow-tests/test-live-reload-multimodule/ui/src/main/java/com/vaadin/flow/uitest/multimodule/ui/FrontendLiveReloadView.java
  flow-tests/test-live-reload-multimodule/ui/src/main/java/com/vaadin/flow/uitest/multimodule/ui/ProjectFolderInfo.java
  flow-tests/test-live-reload-multimodule/ui/src/test/java/com/vaadin/flow/uitest/multimodule/ui/FrontendLiveReloadIT.java
  scripts/computeMatrix.js
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ThemeLiveUpdater.java
Labels: +0.0.1

#16757 feat: add parameter to force prod build
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
  flow-tests/test-express-build/test-prod-bundle/pom.xml
Labels: +0.0.1

#16660 fix: postpone serverSyncId computation after changes are applied
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
Labels: +0.0.1

#16766 fix: not require stats.json output when generateBundle is disabled
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1, Contribution

#16768 fix: Require production bundle for LoadDependenciesOnStartup
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
Labels: +0.0.1

#16777 chore: Upgrade to Lit 2.7.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#16774 Revert "feat!: add DataProvider API for refreshing without clearing selection (#16650)"
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataChangeEvent.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataProviderTest.java
Labels: +1.0.0

#16769 fix: set Lookup attribute to servlet context from OSGi servlet context
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/OSGiVaadinServletTest.java
Labels: +0.0.1

#16786 fix: Run the IndexHtmlRequestListener after the whole page is complete
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, target/24.0

#16781 feat: Include bundle size visualization for production build
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#16782 feat: Store and use package-lock for bundle
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
Labels: +0.0.1

#16790 feat: task to clean generated frontend files
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/TodoIT.java
  flow-tests/test-frontend/test-npm/src/test/java/com/vaadin/flow/mixedtest/ui/NpmUsedIT.java
  flow-tests/test-frontend/test-pnpm/src/test/java/com/vaadin/flow/mixedtest/ui/PnpmUsedIT.java
Labels: +0.1.0

#16797 fix: Import theme for exported wc from correct path
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
Labels: +0.0.1

#16795 chore: Tweak the feature flag message to give more info
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
Labels: +0.0.1

#16794 fix: Store and reuse index.html modifications for dev bundles
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/tests/util/TestUtil.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/webapp/imported-by-vite-plugin.css
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/ViteImportedCSSIT.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/vite.config.ts
Labels: +1.0.0

#16796 fix: compatibility with CookieCsrfTokenRepository in Spring Security
  flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java
Labels: +1.0.0

#16799 test: trim expected style string in CssLoadingIT
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
Labels: +0.0.1

#16776 Fix homebrew try-with-resources to behave like it is supposed to.
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
Labels: +0.0.1, Contribution

#16803 fix: suggest single goal for scaffolding Hilla apps
  flow-server/src/main/resources/com/vaadin/flow/router/NoRoutesError_hilla.html
Labels: +0.0.1

#16802 chore: Upgrade to Vite 4.3.7
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#16765 VaadinService: Avoid silently clearing the thread interrupted state
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.0.1, Contribution

#15885 Disable sending updates to client for effectively non-visible nodes
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
Labels: +0.0.1, target/1.0, target/2.8, target/23.3, target/24.0, target/2.9, target/9.1, target/24.1

#16807 fix: propagate exception raised during stream write (#16776) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamResourceHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamResourceHandlerTest.java
Labels: +0.0.1, cherry pick

#16819 Disable sending updates to client for effectively non-visible nodes (CP: 2.8)
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
Labels: +0.1.0, cherry pick

#16818 Disable sending updates to client for effectively non-visible nodes (CP: 2.9)
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
Labels: +0.1.0, cherry pick

#16822 chore: Upgrade Vite to 4.3.8
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#16826 chore: Upgrade to Spring Boot 3.1.0
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-helpers/pom.xml
  pom.xml
Labels: +0.0.1, target/24.1

#16828 chore: Upgrade Vite to 4.3.8 (#16822) (CP: 24.1)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +1.0.0

#16829 chore: Upgrade to Spring Boot 3.1.0 (#16826) (CP: 24.1)
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-helpers/pom.xml
  pom.xml
Labels: +1.0.0

#16831 fix: retain node_modules folder
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
Labels: +0.0.1, target/24.1

#16836 fix: remove detach listener when javascript execution completes
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1

#16850 fix: remove detach listener when javascript execution completes (#16836) (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1, cherry pick

#16851 fix: remove detach listener when javascript execution completes (#16836) (CP: 9.1)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1, cherry pick

#16852 fix: remove detach listener when javascript execution completes (#16836) (CP: 2.9)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1, cherry pick

#16853 fix: remove detach listener when javascript execution completes (#16836) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1, cherry pick

#16854 test: do not delete custom vite.config.ts on clean
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/pom.xml
Labels: +0.0.1

#16847 feat: Improve error messages in Text methods
  flow-server/src/main/java/com/vaadin/flow/component/Text.java
  flow-server/src/test/java/com/vaadin/flow/component/TextTest.java
Labels: +0.0.1, Contribution

#16871 chore: bump spring boot to 3.0.7
  pom.xml
Labels: +0.0.1

#16834 chore: add owner to JavaScriptInvocation class.
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/component/JavaScriptInvocationTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.1.0

#16875 chore: disable sending updates to client for effectively non-visible nodes, and some additional cleanup, changes to apply CP-s (#15885) (#16855) and (#16836) (CP: 1.0)
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.1.0

#16876 chore: Upgrade to Vite 4.3.9
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.1

#16889 chore: Upgrade to Vite 4.1.5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#16884 fix: Change from ? extends Component to ? for VS Code
  flow-server/src/main/java/com/vaadin/flow/server/LoadDependenciesOnStartup.java
Labels: +0.0.1, target/24.1

#16893 fix: HtmlComponentSmokeTest.testAllHtmlComponents() casting dynamically problem
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Labels: +0.1.0

#16890 chore: Upgrade to Vite 3.2.7
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#16901 fix: npm install task should use ClassFinder
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +1.0.0, target/24.0, target/24.1

#16882 chore!: Add vaadin. prefix to recently added properties
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
Labels: +0.0.1, target/24.1

#16912 test: restore user.home system property after test (#14273) (CP: 9.1)
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/ProjectHelpersTest.java
Labels: +0.0.1

#16917 fix: removed babel/plugin-proposal-object-rest-spread
  flow-server/src/main/resources/webpack.generated.js
Labels: +0.0.1

#16915 fix: Use push/splice to avoid Safari 16.4 issue
  flow-server/src/main/resources/META-INF/frontend/theme-util.js
Labels: +0.0.1, target/24.1

#16914 feat: clean app devBundle with clean-frontend
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
Labels: +0.0.1, target/24.1

#16918 chore: Upgrade workbox to 6.6.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.1

#16921 chore: upgrade jackson.version to 2.15.2
  pom.xml
Labels: +0.0.1, target/24.0, target/24.1

#16910 fix: Accept css if not building bundle
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
Labels: +0.0.1, target/24.1

#16932 fix: JS syntax error in login form CSRF provider script
  flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java
Labels: hilla, +0.0.1, target/24.1

#16931 chore: upgrade jackson.version to 2.15.2 (CP: 24.1)
  pom.xml
Labels: +0.0.1
