Repository vaadin/flow, pull requests merged in 2023-09, with the labels that each got.

#17504 fix: Update UI if custom errorHandler
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ErrorHandlingView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ErrorHandlingIT.java
Labels: +0.0.1, target/23.3, target/24.0, target/24.1

#17534 chore : use latest springboot 3.0.10 in flow 24.0
  pom.xml
Labels: +0.0.1

#17535 chore: update springboot to 3.1.3 in flow 24.1
  pom.xml
Labels: +0.0.1

#17536 fix: CssBundler should check all groups
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/CssBundlerTest.java
Labels: +0.0.1, target/24.1

#17385 chore: Add Experimental feature flag for FormFiller addon
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: awaits another ticket, +0.0.1

#17529 feat: Added methods to prevent default and stopping propagation
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
  flow-server/src/main/java/com/vaadin/flow/component/DomEvent.java
  flow-server/src/main/java/com/vaadin/flow/dom/DomListenerRegistration.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DomEventStopPropagationAndPreventDefaultView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DomEventStopPropagationAndPreventDefaultIT.java
Labels: +1.0.0, Contribution

#17542 fix: Check for null when handling exception
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
Labels: +0.0.1, target/23.3, target/24.0, target/24.1

#17530 fix: Binder throws NPE and eats a relevant exception
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1, Contribution

#17539 fix: shouldVisit should match package exactly
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Labels: +0.0.1, target/24.0, target/24.1

#17548 fix: Use released commons-fileupload2
  flow-commons-upload/bnd.bnd
  flow-commons-upload/pom.xml
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItem.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemFactory.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemHeaders.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemHeadersSupport.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemIterator.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileItemStream.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUpload.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUploadBase.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/FileUploadException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/InvalidFileNameException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/MultipartStream.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/ParameterParser.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/ProgressListener.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/RequestContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/UploadContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/DiskFileItem.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/DiskFileItemFactory.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/disk/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/impl/FileItemIteratorImpl.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/impl/FileItemStreamImpl.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/impl/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltFileCleaner.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltFileUpload.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/JakSrvltRequestContext.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/jaksrvlt/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileCountLimitExceededException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileSizeLimitExceededException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/FileUploadIOException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/IOFileUploadException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/InvalidContentTypeException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/SizeException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/SizeLimitExceededException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/pub/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/Closeable.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/FileItemHeadersImpl.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/LimitedInputStream.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/Streams.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/Base64Decoder.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/MimeUtility.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/ParseException.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/QuotedPrintableDecoder.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/RFC2231Utility.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/mime/package-info.java
  flow-commons-upload/src/main/java/com/vaadin/external/apache/commons/fileupload2/util/package-info.java
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/internal/ResponseWriterTest.java
  pom.xml
Labels: +1.0.0, target/24.1

#17552 chore: Upgrade default Node to 20.6.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#17555 fix: Update gradle to support jdk20
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  flow-plugins/flow-gradle-plugin/gradlew
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1

#17553 Merge 2.9 to 2.10
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-tests/test-no-root-context/pom.xml
  flow-tests/test-no-theme/pom.xml
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/TemplateInTemplateIT.java
  pom.xml
Labels: +0.0.1

#17559 chore: Collect usage statistics for Spring-Boot
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringInstantiator.java
Labels: +0.0.1

#17558 test: Add missing tests for invisible nodes
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
Labels: +0.0.1, target/1.0, target/23.3, target/24.0, target/2.9, target/9.1, target/24.1, target/2.10

#17565 fix: Use earlier atmospehere version
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1

#17561 chore: Update TestBench to 9.1 pre-release
  flow-test-util/pom.xml
  pom.xml
Labels: +0.0.1

#17572 fix: support downgrading dependencies based on versions.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
Labels: hilla, +0.0.1, target/24.1

#17579 chore: Upgrade to Node 20.6.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#17514 test: add test to measure reload time of plain Spring boot app
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/pom.xml
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/Application.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/HelloWorldController.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/ReadyStatusController.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/static/benchmark.js
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/templates/page.html
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  scripts/computeMatrix.js
Labels: +1.0.0

#17577 fix: Not sort chunk lines in place
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
Labels: +0.0.1, target/24.1

#17576 fix: forward to should update url
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.0.1, target/23.3, target/24.1

#17585 chore: update vaadin-parent for upcoming prereleases
  pom.xml
Labels: +0.0.1

#17587 Fix: check for null resolvedPath
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
Labels: +0.0.1

#17541 fix!: Use servlet context path as the default logout url
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1, cherry pick, Contribution

#17580 chore: Remove sysout message
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java
Labels: +1.0.0

#17560 fix: Allow platform dependencies to be linked
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1

#17606 fix: set kotlin language version
  flow-plugins/flow-gradle-plugin/build.gradle
Labels: +0.0.1

#17603 fix: reroute doens't change url.
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
Labels: +0.0.1, target/23.3, target/24.1

#17605 test: adjust spring.devtools.restart properties for reload time tests
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
Labels: +1.0.0

#17512 test: add test to measure reload time of large application with addons
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/pom.xml
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/Application.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/HelloWorldController.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/ReadyStatusController.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/static/benchmark.js
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/main/resources/templates/page.html
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/README.MD
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/CodeGeneratorMojo.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/addons-route-java.mustache
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
  scripts/computeMatrix.js
Labels: +0.0.1

#17613 chore: update atmosphere version
  flow-server/bnd.bnd
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1

#17611 Improve the theme-editor test to check the rules in the created CSS file
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/AbstractThemeEditorIT.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsCheckboxPropertyEditorElement.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeClassNameEditorElement.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeColorPropertyEditorElement.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeRangePropertyEditorElement.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeTextInputElement.java
Labels: +0.0.1, Theme Editor

#17620 test: make PWA test compatible with Java 11 an 17
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1

#17591 perf: improve route registration performance
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
Labels: +0.0.1

#17622 chore: remove not needed deploy.plugin version
  pom.xml
Labels: +0.0.1

#17623 chore: use pre-compiled regex when possible
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1

#17616 fix: Allow dev tools window to grow
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.1

#17618 feat: Add deactivate event for dev tools tabs
  flow-tests/test-dev-mode/frontend/devtools-plugin.ts
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/DevToolsPluginIT.java
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.1

#17604 perf: optimize SpringLookup lookup time by caching
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java
Labels: +0.0.1

#17636 test: fix open url to use correct servlet
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/AbstractBaseIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeWebpackIT.java
Labels: +0.0.1

#17638 chore: bump commons-compress to resolve vulnerability (CP 23.3)
  flow-plugins/flow-maven-plugin/pom.xml
  flow-server/pom.xml
Labels: +0.0.1

#17612 Generate at build time the metadata for theme editor tests
  .gitignore
  flow-tests/test-theme-editor/metadata/vaadin-button.txt
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
  vaadin-dev-server/export-metadata-script.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/ComponentsMetadata.java
  vaadin-dev-server/vite.config.js
Labels: +0.0.1, Theme Editor

#17640 test: Add new Spring boot reload time test module (#17464) (CP: 24.1)
  flow-tests/pom.xml
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/README.MD
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/CodeGeneratorMojo.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/CssImportContext.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/JavaClassContext.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/JavaRouteContext.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/JavaSpringServiceContext.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/java/com/vaadin/flow/spring/test/JsModuleContext.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/META-INF/MANIFEST.MF
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/css-import.mustache
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/js-module.mustache
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/route-java.mustache
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/generator/src/main/resources/service-java.mustache
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/library/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/library/src/main/resources/META-INF/frontend/in-frontend.js
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/library/src/main/resources/META-INF/resources/frontend/in-resources-frontend.js
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/theme/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/theme/src/main/resources/META-INF/resources/themes/mytheme/styles.css
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/frontend/benchmark.js
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/AppShell.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/Application.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/ApplicationServiceInitListener.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/MainLayout.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsApplicationReloadView.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/store/CatalogLayout.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/store/ProductView.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/frontend/benchmark.js
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/Application.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsHorizontalLayoutReloadView.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsNativeButtonReloadView.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  scripts/computeMatrix.js
Labels: +0.0.1

#17649 test: fixed test module parent version number
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/pom.xml
Labels: +0.0.1

#17646 chore: Update Node.js to latest 20.7.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#17647 fix: router-link postpone navigation
  flow-client/src/main/frontend/Flow.ts
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PostponeUpdateView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeUpdateIT.java
Labels: +0.0.1, target/24.1

#17660 chore: update vaadin-parent for flow 2.10 [skip ci]
  pom.xml
Labels: +0.0.1

#17673 Feat/add tests for vaadin components
  flow-tests/test-theme-editor/pom.xml
  flow-tests/test-theme-editor/src/main/java/com/vaadin/flow/uitest/ui/ThemeEditorView.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/AbstractThemeEditorIT.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
Labels: +0.0.1, Theme Editor

#17644 Caching: Cache all com.vaadin.flow class instances
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1

#17668 fix: synchronize cache maps in SpringLookupInitializer
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java
Labels: +0.0.1

#17676 fix: bump spring-boot version to resolve vulnerability
  pom.xml
Labels: +0.0.1

#17677 chore: change synchronizedMap to ConcurrentHashMap
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringLookupInitializer.java
Labels: +0.0.1

#17679 test: Ignore failed test for Theme Editor
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
Labels: +0.0.1

#17672 chore: cache JS imported paths during chunk generation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
Labels: +0.0.1, target/24.1

#17659 fix: forward/reroute when query parameters changed
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +0.0.1, target/23.3, target/24.1

#17680 fix: upgrade spring-boot to 3.1.4
  flow-tests/vaadin-spring-tests/test-spring-war/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-war/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  pom.xml
Labels: +0.0.1, target/24.1

#17686 Fixes the flaky theme editor tests
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/AbstractThemeEditorIT.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
Labels: +0.0.1, Theme Editor

#17670 test: add optional assert with reload time threshold
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
Labels: +0.0.1

#17667 refactor: Use overrides also for pnpm
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/resources/pnpmfile.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-tests/test-frontend/test-pnpm/pnpm-lock.yaml
  flow-tests/test-frontend/test-pnpm/pom-production.xml
Labels: +0.0.1

#17645 fix: prevent deadlock when accessing FeatureFlags
  flow-dnd/src/test/java/com/vaadin/flow/component/dnd/AbstractDnDUnitTest.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/scopes/AbstractScopeTest.java
Labels: +0.0.1

#17693 chore: Update TestBench to 9.1.0.beta1
  pom.xml
Labels: +0.0.1

#17706 fix: Use build timestamp for Push script request
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Version.java
  flow-server/src/main/resources/com/vaadin/flow/server/version.properties
Labels: +0.0.1, target/1.0, target/23.3, target/2.9, target/9.1, target/24.1, target/2.10

#17661 fix: Do not override user npm dependency version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1

#17695 fix: detach should be sent for node
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternalUpdater.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Labels: +0.0.1, target/24.2

#17502 feat: Adds a VaadinRequestInterceptor abstraction
  flow-server/src/main/java/com/vaadin/flow/server/ServiceInitEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinRequestInterceptor.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/MockServletServiceSessionSetup.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/MyVaadinServiceInitListener.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringVaadinServletServiceTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/TestServletConfiguration.java
Labels: +0.1.0, Contribution

#17701 feat: Cache all classes from JARs
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1

#17716 fix: Use build timestamp for Push script request (#17706) (CP: 2.10)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Version.java
  flow-server/src/main/resources/com/vaadin/flow/server/version.properties
Labels: +0.0.1, cherry pick, target/2.9

#17717 fix: Use build timestamp for Push script request (#17706) (CP: 1.0)
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/Version.java
  flow-server/src/main/resources/com/vaadin/flow/server/version.properties
Labels: +0.1.0, cherry pick

#17712 In theme-editor, adds a test for vaadin-accordion component
  flow-tests/test-theme-editor/pom.xml
  flow-tests/test-theme-editor/src/main/java/com/vaadin/flow/uitest/ui/ThemeEditorView.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsComponentPickerElement.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/CssRule.java
Labels: +0.0.1, Theme Editor

#17687 feat: Allow specifying `devDependencies` with `@NpmPackage`.
  flow-server/src/main/java/com/vaadin/flow/component/dependency/NpmPackage.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
Labels: +0.1.0, Contribution

#17732 fix: Disable the Vite public directory to not interfere with a folder named 'public'
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#17733 chore: Update TestBench to 9.1.0.beta2
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, target/24.2

#17730 fix: Be less verbose when Vite is not running
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +1.0.0, target/24.2
