Repository vaadin/flow, pull requests merged in 2023-07, with the labels that each got.

#17160 fix: use dark color scheme for dev tools
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.1

#17161 fix: Report exception if filewatcher fails to start
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
Labels: +0.0.1, target/24.1

#17146 feat: dispatch popstate event on server-side navigation
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
Labels: +0.0.1

#17155 fix: prevent writing service worker on filesystem in dev mode
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/23.3, target/24.0, target/24.1

#17157 fix: set restart monitor before checking for dev server connection
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/RestartMonitorTest.java
Labels: +0.0.1

#17158 fix: prevent PWA registry lookup when VaadinServlet is not initialized
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
Labels: +0.0.1, target/24.1

#17169 chore: cleaned up guava and jakarta.websocket dependencies to handle the version in one place.
  flow-test-util/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  flow-tests/test-npm-only-features/test-npm-performance-regression/pom.xml
  pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#17174 fix: prevent writing service worker on filesystem in dev mode (#17155) (CP: 24.0)
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, cherry pick

#17175 fix: prevent writing service worker on filesystem in dev mode (#17155) (CP: 23.3)
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, cherry pick

#17179 fix: add missing hint for native build
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
Labels: +0.0.1

#17136 chore: replace deprecated Spring Security APIs usage
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#17181 chore: remove redundant spring.version (V23.3)
  pom.xml
Labels: +0.0.1

#17188 chore: Bump @vitejs/plugin-react to 4.0.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#17187 chore: Bump rollup-plugin-visualizer to 5.9.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#17183 chore: Bump lit to 2.7.6
  flow-client/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, target/24.1

#17184 chore: Bump typescript to 5.1.6
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#17185 chore: Remove unnecessary mkdirp dependency
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#17186 chore: Bump Vite to 4.4.0
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#17190 chore: Bump lit to 2.7.6 (#17183) (CP: 24.1)
  flow-client/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#17195 chore: Bump glob to 9.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/theme-loader/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#17192 chore: Upgrade vite plugin checker to 0.6.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
Labels: +0.0.1

#17194 chore: Recreate package json files
  flow-client/package-lock.json
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#17202 chore: Bump Vite to 4.4.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#17199 fix: Do not force chokidar version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/resources/pnpmfile.js
Labels: +0.0.1

#17203 chore: Delete unnecessary complexity
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServiceClassLoaderUtil.java
Labels: +1.0.0

#17204 fix: Do not include dev dependencies when locking versions using package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +1.0.0

#17209 test: fix webpush integration test
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-tests/test-webpush/src/main/java/com/vaadin/flow/webpush/WebPushView.java
  flow-tests/test-webpush/src/test/java/com/vaadin/flow/webpush/WebPushIT.java
  flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
  flow-webpush/src/main/resources/META-INF/frontend/FlowWebPush.js
Labels: +0.0.1

#17216 feat: fail fast when plugin is used with an unsupported version of Gradle
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
Labels: +0.0.1

#17218 fix: prevent NPE in ShortcutRegistration.toString
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
Labels: +0.0.1, target/23.3, target/24.0, target/2.9, target/9.1, target/24.1

#17229 chore: downgrade minimum supported gradle version to 7.6
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
Labels: +0.0.1

#17130 fix: prevent deadlock when push is requested during disconnect
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, target/24.1

#17238 fix: Fix regression when sync id check is disabled
  flow-server/src/main/java/com/vaadin/flow/server/communication/LongPollingCacheFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/LongPollingCacheFilterTest.java
Labels: +0.0.1, Contribution, target/23.3, target/24.0, target/2.9, target/9.1, target/24.1

#17246 fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, cherry pick

#17248 fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, cherry pick

#17250 fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 2.9)
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, cherry pick

#17249 fix: prevent deadlock when push is requested during disconnect (#17130) (CP: 9.1)
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
Labels: +0.0.1, cherry pick

#17259 feat: Allow modifying QueryParameters
  flow-server/src/main/java/com/vaadin/flow/router/QueryParameters.java
  flow-server/src/test/java/com/vaadin/flow/router/QueryParametersTest.java
Labels: +0.0.1, Contribution

#17263 chore: explictly use ant path matchers in VaadinWebSecurity
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#17266 chore(deps): bump spring.boot.version from 3.0.8 to 3.0.9
  pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#17265 chore(deps): bump spring.boot.version to 2.7.14
  pom.xml
Labels: +0.0.1

#17261 chore: log classloading errors in reflections class finder
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java
Labels: +0.0.1, target/23.3, target/24.0, target/9.1, target/24.1

#17270 chore: prevent usage statistics failure when collecting info
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
Labels: +0.0.1

#17280 fix: pre-compile visitable classes regex pattern
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1, target/24.0, target/24.1

#17217 added meta-data file for vaadin-date-picker
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-heading.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-panel.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-date-picker.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-date-time-picker.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-details-summary.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-list-box.ts
Labels: +1.0.0, Theme Editor

#17231 fix: do not register requests while flush in progress
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, Contribution

#17282 fix: pre-compile visitable classes regex pattern (#17280) (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1, cherry pick

#17291 fix: update jandex-maven-plugin for JDK 21
  flow-jandex/pom.xml
Labels: +0.0.1

#17296 test: ignore properties from mixin interfaces in component tests
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
Labels: +0.0.1

#17306 Add meta data for message input
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-message-input.ts
Labels: +0.0.1, Theme Editor

#17300 fix: fixed issue with using child selector, accordion metadata updates
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-heading.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion-panel.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-accordion.ts
  vaadin-dev-server/frontend/theme-editor/model.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
Labels: +0.0.1, Theme Editor

#17301 Add meta data for tab and tabsheet
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-tab.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-tabs.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-tabsheet.ts
Labels: +0.0.1, Theme Editor

#17316 Add meta data for message list
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-message-list.ts
Labels: +0.0.1, Theme Editor

#17297 test: disable deserialization test on OSGi
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/SerializeShortcutIT.java
Labels: +0.0.1, target/23.3, target/24.0, target/24.1

#17315 test: add tests classifier to test-jar unpack configuration
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
Labels: +0.0.1

#17320 feat: Theme Editor Multi-Select Combo Box metadata
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-multi-select-combo-box.ts
Labels: +0.0.1, Theme Editor

#17294 Feat/theme editor vaadin-icon and vaadin-rich-text-editor
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-icon.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-rich-text-editor.ts
Labels: +0.0.1, Theme Editor
