Repository vaadin/flow, pull requests merged in 2023-12, with the labels that each got.

#18169 feat!: reject AppShell classes which extend Component
  flow-server/src/main/java/com/vaadin/flow/component/page/AppShellConfigurator.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa-custom-offline-path/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-frontend/vite-pwa-disabled-offline/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa-disabled-offline/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa-production/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-frontend/vite-pwa/src/main/java/com/vaadin/viteapp/AppShell.java
  flow-tests/test-frontend/vite-pwa/src/main/java/com/vaadin/viteapp/MainView.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AppShell.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/FrontendLiveReloadView.java
  flow-tests/test-pwa-disabled-offline/src/main/java/com/vaadin/flow/pwatest/AppShell.java
  flow-tests/test-pwa-disabled-offline/src/main/java/com/vaadin/flow/pwatest/MainView.java
  flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/AppShell.java
  flow-tests/test-pwa/src/main/java/com/vaadin/flow/pwatest/ui/PwaTestView.java
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1, Contribution

#18129 feature: Implement multiple strategies for the `VaadinSession.checkHasLog()` call
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/LockCheckStrategy.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
Labels: +0.1.0, Contribution

#18176 refactor: don't throw when VaadinWeSecurity.getViewAccessChecker is called
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +1.0.0, target/24.3

#18175 chore: improve session lock strategy
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/SessionLockCheckStrategy.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/MockDeploymentConfiguration.java
Labels: +1.0.0

#18179 fix: Remove old bundle in clean-frontend goal or task
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
Labels: +1.0.0, target/24.3

#18184 refactoring: make SessionLockCheckStrategy.LOG log stack trace as well
  flow-server/src/main/java/com/vaadin/flow/server/SessionLockCheckStrategy.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinSessionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/MockLogger.java
Labels: +1.0.0

#18170 chore: atmosphere-2.4.24.vaadin3
  flow-push/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
Labels: +0.0.1

#18187 chore: use latest vaadin-parent in flow 9.2
  pom.xml
Labels: +0.0.1, target/1.0, target/2.9, target/9.1, target/2.10

#18164 fix: pre-emtive navigation
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.3

#18208 chore: Upgrade to TestBench 9.2.0.rc1
  pom.xml
Labels: +1.0.0, target/24.3

#18205 Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 2.9)"
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1

#18202 Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 23.3)"
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1

#18201 Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 23.4)"
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1

#18203 Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 9.1)"
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, target/9.2

#18206 Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 1.0)"
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1

#18211 chore: Upgrade Vite to 5.0.5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +1.0.0, target/24.3

#18212 chore: Upgrade Vite to 4.5.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18204 Revert "fix: support accept property in StreamReceiverHandler (#18022) (CP: 2.10)"
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
Labels: +0.0.1, cherry pick

#18226 fix: warning in TaskRunDevBundleBuild when README exists (#18210)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
Labels: +1.0.0, Contribution

#18241 fix: Generate files to Frontend
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/App.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.ts
Labels: +0.0.1, target/24.3

#18238 test: use custom thread pool for RestartMonitor test
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/RestartMonitorTest.java
Labels: +0.0.1

#18172 fix: postpone commands scheduled with runWhenAttached for detached nodes
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateNodeTest.java
Labels: +0.0.1, target/23.3, target/24.1, target/24.2, target/23.4, target/24.3

#18254 test: wait for dev server start future completion
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/AbstractDevServerRunnerTest.java
Labels: +0.0.1

#18248 fix: consider theme variants from JAR in bundleImports
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
Labels: +0.0.1, target/24.1, target/24.2, target/24.3

#18255 chore!: Remove unused method
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.0.1

#18256 refactor: Move logic out of dev tools connection class
  vaadin-dev-server/frontend/License.ts
  vaadin-dev-server/frontend/connection.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#18236 docs: fix broken contributing link
  CONTRIBUTING.md
Labels: +1.0.0, Contribution

#18263 refactor: Split out live reload connection
  vaadin-dev-server/frontend/connection.ts
  vaadin-dev-server/frontend/live-reload-connection.ts
  vaadin-dev-server/frontend/theme-editor/api.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
  vaadin-dev-server/frontend/websocket-connection.ts
Labels: +0.0.1

#18265 fix: Use Atmosphere for debug window connection
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
  vaadin-dev-server/frontend/websocket-connection.ts
Labels: +0.0.1

#18274 chore: Upgrade TestBench to 9.2.0
  pom.xml
Labels: +0.0.1, target/24.3

#18273 chore: update @vaadin/common-frontend
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: hilla, +0.0.1, target/24.3

#18276 chore: upgrade TB to 9.2.0 (24.3)
  pom.xml
Labels: +0.0.1

#18277 chore: update @vaadin/common-frontend (#18273)(CP: 24.3)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, cherry pick

#18290 test: Use https://example.net
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
Labels: +0.0.1

#18291 chore: Add a link to docs for react router feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1, target/24.3

#18289 chore: replace deprecated Vite config options
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, Contribution, target/24.3

#18305 test: Use https://example.net (#18290) (CP: 1.0)
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
Labels: +0.0.1, cherry pick

#18268 fix: Support fragmented messages in debug window
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/FragmentedMessageHolder.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/FragmentedMessageTest.java
  vaadin-dev-server/frontend/websocket-connection.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +1.0.0, target/24.3

#18310 chore: Update package files
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +1.0.0

#18311 test: Ignore all the bundles
  .gitignore
Labels: +1.0.0

#18312 test: Ignore leftover lock files
  .gitignore
Labels: +0.0.1

#18307 chore: Be more tolerant to dev tools conf not being available
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.3

#18313 chore: Bump dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#18308 chore: Upgrade @koa/cors
  vaadin-dev-server/package.json
Labels: +0.0.1, target/24.3

#18315 chore: Upgrade org.eclipse versions
  flow-client/pom.xml
Labels: +0.0.1

#18317 feat: support DataProviderWrapper better in AbstractDataView
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
Labels: +1.0.0

#18320 chore: Vite 5.0.10
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.3

#18296 fix: delay web-component bootstrap during dev-bundle creation
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractTestBenchTest.java
  flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
  flow-tests/test-multi-war/deployment/src/test/java/com/vaadin/flow/multiwar/deployment/TwoAppsIT.java
Labels: +1.0.0, target/24.3

#18328 chore: bump testbench to 8.2.5
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  flow-tests/test-ccdm-flow-navigation/src/test/java/com/vaadin/flow/navigate/NavigateBetweenViewsIT.java
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/pom.xml
  pom.xml
Labels: +0.0.1, target/23.3

#18306 feat: add getItemIndex to DataView
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractLazyDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ItemIndexProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/LazyDataView.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractLazyDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/AbstractListDataViewTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HasHierarchicalDataProviderTest.java
Labels: +1.0.0

#18336 test: prevent test flakyness by waiting for element
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
Labels: +0.0.1

#18340 chore: move getItemIndex to AbstractDataView
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractDataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractListDataView.java
Labels: +0.0.1

#18341 chore: bump Testbench to 9.2.1
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#18343 chore: bump Testbench to 9.2.1 (#18341) (CP: 24.3)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, cherry pick

#18285 fix: Single request navigation
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
  flow-tests/pom.xml
  flow-tests/test-react-router/pom.xml
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/StateView.java
  flow-tests/test-react-router/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-react-router/src/test/java/com/vaadin/flow/StateIT.java
Labels: +1.0.0

#18344 upgrade spring boot to 3.1.7
  pom.xml
Labels: +0.0.1

#18337 feat: rename `dev.hilla` to `com.vaadin.hilla`
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestEndpointGeneratorTaskFactory.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/TestUtil.java
  flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
  flow-server/src/test/java/com/vaadin/flow/server/PlatformTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-dev-server/src/test/resources/java/MyEndpoint.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, Contribution

#18321 test: add tests for navigating with react-router
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-tests/pom.xml
  flow-tests/test-react-router/pom-production.xml
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/AnchorView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/PostponeView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/RouterView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/ServerView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/StateView.java
  flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
Labels: +0.0.1

#18335 docs: update ClickNotifier addClickShortcut JavaDoc
  flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
Labels: +0.0.1, target/24.3

#18366 revert: Revert "chore(deps): bump jackson.version from 2.16.0 to 2.16.1 (#18360)"
  pom.xml
Labels: +0.0.1

#18354 fix: update stats.json for WebComponentExporter resources
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#18348 fix: handle inner classes in component tracker
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java
Labels: +0.0.1, target/24.2, target/24.3

#18355 feat: allow disable component tracker
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
  flow-server/src/test/java/com/vaadin/flow/DisableComponentTrackerTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1

#18363 fix: ignore plugins registration when dev-tools are disabled
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, target/24.2, target/24.3

#18371 test: re-enable gradle MPR test
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
Labels: +0.0.1

#18372 fix: update stats.json for Frontend resources
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/js/test.js
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/test.ts
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/unknownfile.js
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleJsModuleView.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleJsModuleIT.java
Labels: +0.0.1
