Repository vaadin/flow, pull requests merged in 2023-10, with the labels that each got.

#17744 chore: Upgrade Node.js to v20.8.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.2

#17749 fix: ignore servlet registrations without server-class definition
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/ServletDeployerTest.java
Labels: +0.0.1, target/24.1, target/24.2

#17746 test: Log CDP version mismatch messages from Selenium only once
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Labels: +0.0.1, target/24.2

#17740 Theme editor: adds a test for vaadin-dialog element
  flow-tests/test-theme-editor/pom.xml
  flow-tests/test-theme-editor/src/main/java/com/vaadin/flow/uitest/ui/ThemeEditorView.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/ThemeEditorIT.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsComponentPickerElement.java
  flow-tests/test-theme-editor/src/test/java/com/vaadin/flow/uitest/ui/testbench/DevToolsThemeEditorElement.java
Labels: +0.0.1, Theme Editor

#17763 chore: Bump TypeScript to 5.2.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#17765 fix: improve LitTemplateParser to find correct content
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/BundleLitParser.java
  flow-lit-template/src/test/java/com/vaadin/flow/component/littemplate/BundleLitParserTest.java
Labels: +0.0.1, target/24.1, target/24.2

#17767 chore: bump Vite to 4.4.10
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.2

#17781 chore: Upgrade to TestBench 9.1.0.rc1
  pom.xml
Labels: +0.0.1, target/24.2

#17783 fix: added class can be with /
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, target/24.2

#17772 fix: Add reachable classes to child route
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Labels: +0.0.1, target/24.1, target/24.2

#17739 fix: update role checkers to work in same way
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/RolePrefixedAdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/AuthenticationUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringViewAccessChecker.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinRolePrefixHolder.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +0.0.1

#17786 chore: add 24.2 branch to validation.yml
  .github/workflows/validation.yml
Labels: +0.0.1, target/24.2

#17784 chore: update jackson to 2.15.2
  pom.xml
Labels: +0.0.1

#17774 Do not passivate child keys with active&expanded parents
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
Labels: +0.0.1

#17800 Revert "chore: update jackson to 2.15.2 (#17784)"
  pom.xml
Labels: +0.0.1

#17802 test: fix horizontal-layout npm package version
  flow-tests/test-express-build/test-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java
Labels: +0.0.1, target/24.1, target/24.2

#17745 feature: provide an API to make router ignore an anchor
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentProperty.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
Labels: +0.0.1, Contribution

#17791 feat: Show error view on action exception
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/ErrorHandlerUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/ErrorHandlerUtilTest.java
Labels: +1.0.0

#17817 feat: add RouteParameters to AfterNavigationEvent
  flow-server/src/main/java/com/vaadin/flow/router/AfterNavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
Labels: +1.0.0

#17820 fix: jsx files are not taken into front-end build from add-ons
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/resources/jar-with-frontend-resources.jar
  flow-server/src/test/resources/jar-with-modern-frontend.jar
Labels: +0.0.1, Contribution

#17805 Log JS exceptions in production mode
  flow-client/src/main/java/com/vaadin/client/Console.java
  flow-tests/test-misc/frontend/consoleLoggingProxy.js
  flow-tests/test-misc/frontend/exception-logging.js
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ExceptionLoggingView.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/ExceptionLoggingIT.java
Labels: +1.0.0

#17812 chore: Upgrade to Lit 3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#17833 test: Add tests for dev mode client-side logging; Clarify prod mode test
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/frontend/BrowserLoggingView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/frontend/BrowserLoggingIT.java
  flow-tests/test-misc/frontend/consoleLoggingProxy.js
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/ExceptionLoggingIT.java
Labels: +0.0.1

#17835 Fix the support for Java 17 (Theme editor)
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/editor/AddComponentTest.java
  vaadin-dev-server/src/test/resources/com/vaadin/base/devserver/editor/inputs/EmptyViewWithSwitch.java
Labels: +0.0.1, Theme Editor

#17796 fix: push event allows redirects for expired session
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushAtmosphereHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/CustomServiceInitListener.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LogoutView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MainView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/TimeoutView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
Labels: +0.0.1

#17837 fix: readding component that on detach removes components
  flow-server/src/main/java/com/vaadin/flow/dom/Node.java
  flow-server/src/main/java/com/vaadin/flow/dom/impl/AbstractNodeStateProvider.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1, target/23.3, target/24.1, target/24.2

#17823 feat: Default I18N provider
  flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
  flow-server/src/main/java/com/vaadin/flow/i18n/DefaultI18NProvider.java
  flow-server/src/main/java/com/vaadin/flow/i18n/I18NUtil.java
  flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
  flow-server/src/test/java/com/vaadin/flow/i18n/I18NUtilTest.java
  flow-tests/test-misc/pom.xml
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/TranslationView.java
  flow-tests/test-misc/src/main/resources/vaadin-i18n/translations.properties
  flow-tests/test-misc/src/main/resources/vaadin-i18n/translations_de.properties
  flow-tests/test-misc/src/main/resources/vaadin-i18n/translations_fi_FI.properties
  flow-tests/test-misc/src/main/resources/vaadin-i18n/translations_fr_FR.properties
  flow-tests/test-misc/src/main/resources/vaadin-i18n/translations_ja_JP.properties
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/TranslationIT.java
Labels: +0.1.0

#17857 test: fix test to not be run threaded
  flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
  flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java
Labels: +0.0.1

#17858 feat: add getActiveViewLocation and getActiveRouterTargetsChain to UI
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
Labels: +0.0.1

#17867 chore: fix typo when appending new line
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#17861 feat: Use binding object to check for Binder#hasChanges
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.1.0, Contribution

#17871 chore: update testbench to 9.0.8
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#17866 feat: add Div constructor that accept text content
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Div.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/DivTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AbstractEventDataView.java
Labels: +1.0.0

#17863 fix: RouteAlias hides Route value
  flow-server/src/main/java/com/vaadin/flow/router/internal/ConfiguredRoutes.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/ConfiguredRoutesTest.java
Labels: +0.0.1

#17878 chore: Upgrade Node.js to 20.8.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/main

#17883 feat: Add ConditionalOnMissingBean for ServletRegistration
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringBootAutoConfigurationConditionalTest.java
Labels: +0.0.1

#17845 Enable Atmosphere heartbeat
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushRequestHandler.java
  vaadin-dev-server/frontend/connection.ts
Labels: +0.0.1

#17892 chore: Fix Maven deprecation warning
  flow-client/pom.xml
  flow-data/pom.xml
  flow-dnd/pom.xml
  flow-html-components-testbench/pom.xml
  flow-html-components/pom.xml
  flow-lit-template/pom.xml
  flow-polymer-template/pom.xml
  flow-polymer2lit/pom.xml
  flow-push/pom.xml
  flow-server/pom.xml
  flow-test-generic/pom.xml
  flow-test-util/pom.xml
  flow-webpush/pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#17887 chore: Upgrade Spring-boot to 2.7.17
  pom.xml
Labels: +0.0.1

#17891 chore: Bump npm dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#17893 test: Use correct styles import
  flow-tests/test-ccdm/frontend/css-importing-test.ts
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/typescript/hello-world-view.ts
  flow-tests/test-themes/frontend/typescript/hello-world-view.ts
Labels: +0.0.1

#17899 build: Install the default node version
  .github/workflows/validation.yml
Labels: +0.0.1

#17901 fix: exit disconnect if disconnection already happened
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
Labels: +0.0.1, target/23.3, target/2.9, target/9.1, target/24.1, target/2.10, target/24.2

#17904 chore: Upgrade default Node to 20.9.0 (LTS)
  .github/workflows/validation.yml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.2

#17888 feat: add handleDisconnect method to plugin
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsInterface.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsMessageHandler.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Labels: +0.0.1, target/24.2

#17915 chore: Upgrade default Node to 20.9.0 (LTS) (#17904) (CP: 24.2)
  .github/workflows/validation.yml
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#17879 feat: Add Component/Element to ErrorEvent
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-server/src/main/java/com/vaadin/flow/server/ErrorEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ComponentErrorView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ComponentErrorIT.java
Labels: +0.0.1

#17889 fix: Show Hilla version when Hilla is available
  vaadin-dev-server/frontend/vaadin-dev-tools-info.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ServerInfo.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/ServerInfoTest.java
Labels: +0.0.1, target/24.2

#17922 build: Install bun for validation build
  .github/workflows/validation.yml
Labels: +0.0.1

#17919 Remove .pnpmfile.cjs on clean-frontend
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
Labels: +0.0.1

#17920 fix: page calculation when not equally divisible
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/23.3, target/24.1, target/24.2

#17927 chore: bump testbench to 7.1.1
  pom.xml
Labels: +0.0.1

#17930 fix: page calculation when not equally divisible (#17920)
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, cherry pick

#17882 feat: add more properties with the typed API in Style
  flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
  flow-server/src/main/java/com/vaadin/flow/dom/Style.java
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
  flow-tests/test-live-reload/src/main/java/com/vaadin/flow/uitest/ui/AbstractLiveReloadView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BasicComponentView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/BasicElementView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DnDAttachDetachView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
Labels: +1.0.0

#17912 refactor: Delete duplicate version comparison method
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendVersion.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +1.0.0

#17943 fix!: replace outdated webpush dependency
  flow-webpush/pom.xml
  flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
Labels: +0.0.1, target/24.2

#17950 test: Do not include vcf-nav which has TS issues
  flow-tests/test-express-build/test-prod-bundle/src/main/java/com/vaadin/prodbundle/FakeAppConf.java
Labels: +0.0.1, target/24.2

#17936 fix: send markAsUsed only when Theme Editor is opened first time
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, Theme Editor, target/24.2

#17953 test: use Flow donwloaded node for npm tests
  flow-tests/test-frontend/test-npm/pom-production.xml
  flow-tests/test-frontend/test-npm/pom.xml
Labels: +0.0.1

#17948 fix: load chunks for component parents
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +0.0.1, target/24.1, target/24.2

#17952 fix: fix web push compilation error
  flow-tests/test-webpush/src/main/java/com/vaadin/flow/webpush/WebPushView.java
Labels: +0.0.1, target/24.2

#17949 feat: Allow plugging in a modifier for vaadin.ts
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TypeScriptBootstrapModifier.java
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/BootstrapModifier.java
  flow-tests/test-frontend/vite-basics/src/main/resources/META-INF/services/com.vaadin.flow.server.frontend.TypeScriptBootstrapModifier
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
Labels: +0.1.0

#17959 fix: throw WebPushException for sendNotification
  flow-webpush/src/main/java/com/vaadin/flow/server/webpush/WebPush.java
Labels: +0.1.0, target/24.2

#17958 chore: upgrade jetty version
  pom.xml
Labels: +0.0.1, target/2.10
