Repository vaadin/flow, pull requests merged in 2023-03, with the labels that each got.

#16076 feat: Search for missed entries in theme.json
  flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-tests/test-express-build/test-parent-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ParentThemeIT.java
  flow-tests/test-express-build/test-reusing-theme-express-build/src/test/java/com/vaadin/flow/devbuild/ReusingThemeIT.java
Labels: +0.0.1, express-build, target/24.0

#16080 chore: add 24.0 branch to validate push event [CP 24.0]
  .github/workflows/validation.yml
Labels: +0.0.1

#16077 refactor: editable host properties in theme editor
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/events.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-text-field.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/tests/utils.ts
Labels: +0.0.1

#16081 feat: add aria-labelledby API to HasAriaLabel
  flow-server/src/main/java/com/vaadin/flow/component/HasAriaLabel.java
  flow-server/src/main/java/com/vaadin/flow/dom/ElementConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/HasAriaLabelTest.java
Labels: +1.0.0

#16078 feat: Add README to the dev bundle directory
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
Labels: +1.0.0, target/24.0

#16082 refactor: simplify accessing CSS properties in theme detector
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/detector.ts
Labels: +0.0.1

#16092 refactor: save theme editor changes immediately
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#16025 test: Backport test fix for npm 9
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1, target/9.0, target/2.8, target/23.2

#15986 feat: Enable running npm ci mode (#15579)
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#16085 fix: use setAttribute in setAriaLabel method
  flow-server/src/main/java/com/vaadin/flow/component/HasAriaLabel.java
Labels: +0.0.1, target/23.2, target/23.3

#16087 chore: update TB to 9.0.0
  pom.xml
Labels: +0.0.1, target/24.0

#16093 test: Run with web-test-runner instead of intern
  flow-client/package-lock.json
  flow-client/package.json
  flow-client/pom.xml
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/tsconfig.json
  flow-client/src/test/npm/intern.json
  flow-client/web-test-runner.config.mjs
  flow-client/webpack.tests.config.js
Labels: +0.0.1, target/23.3, target/24.0

#16099 refactor: added support for themeEditorComponentMetadata command
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ModifierException.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorException.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/BaseRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/BaseResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ClassNamesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ComponentMetadataRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ComponentMetadataResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ErrorResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/RulesRequest.java
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
Labels: +0.0.1

#16103 feat: Add app vs default dev-bundle statistics
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
Labels: +0.0.1, target/24.0

#16088 fix: Parent theme should not trigger a re-bundle
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, target/24.0

#16117 test: Run with web-test-runner instead of intern (#16093) (CP: 23.3)
  flow-client/package-lock.json
  flow-client/package.json
  flow-client/pom.xml
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/tsconfig.json
  flow-client/src/test/npm/intern.json
  flow-client/web-test-runner.config.mjs
  flow-client/webpack.tests.config.js
Labels: +0.0.1

#16070 chore: Log downloaded node archive size
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Labels: +0.0.1, target/24.0

#15982 chore: Update file upload to latest
  flow-server/pom.xml
Labels: +0.0.1, target/1.0, target/9.0, target/2.8, target/23.2

#16123 refactor: implement theme editor API client
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vaadin-dev-tools.ts
Labels: +0.0.1

#16136 chore: Update commons file upload to 1.5 (#15982) (CP: 2.8)
  flow-server/pom.xml
Labels: +0.0.1

#16138 chore: Update commons file upload to 1.5 (#15982) (CP: 1.0)
  flow-server/pom.xml
Labels: +0.0.1

#16129 test: Avoid using Jetty API that is going away
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
Labels: +0.0.1, target/23.3, target/24.0

#16127 chore: Upgrade to Spring Boot 3.0.4
  pom.xml
Labels: +0.0.1, target/24.0

#16016 chore: Upgrade to Spring Boot 2.7.9
  pom.xml
Labels: +0.0.1

#16146 chore: Update commons file upload to 1.5 (#15982) (CP: 2.9)
  flow-server/pom.xml
Labels: +1.0.0

#16139 fix: Exclude Vite specific import parameters for project's file imports (CP: 24.0)
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/styles/my-styles.css
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
Labels: +0.0.1

#16140 fix: Skip checking @vaadin/flow-frontend package (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1

#16142 fix: Not throw for not yet copied CSS when checking for re-bundling (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssAnnotationVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssData.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/MyComponent.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/resources/META-INF/resources/frontend/addons-styles/add-on-styles.css
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
Labels: +0.0.1

#16147 test: Increase build timeout to 30min
  .github/workflows/validation.yml
Labels: +0.0.1, target/9.0, target/2.8, target/23.2, target/23.3, target/24.0

#16148 refactor: initialize component theme in theme editor
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadPreviewRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadPreviewResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/tests/utils.ts
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
Labels: +0.0.1, theme-editor

#16113 fix: Remove words about adding bundle dependency
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1, target/24.0

#16029 refactor: skip the node_modules folder completely
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
Labels: +0.0.1, target/24.0

#16162 feat: Add upload limits (#16091) (CP: 2.8)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
Labels: +0.1.0

#16163 feat: Add upload limits (#16091) (CP: 2.9)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
Labels: +1.0.0

#16104 chore: update workflow for cancelled steps [skip ci]
  .github/workflows/validation.yml
Labels: +0.0.1, target/9.0, target/23.2, target/23.3, target/24.0

#16145 test: Avoid using Jetty API that is going away (#16129) (CP: 23.3)
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/src/test/java/com/vaadin/viteapp/BasicComponentIT.java
Labels: +0.0.1

#16154 fix: Fixes for Spring native compile
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: +0.0.1, target/24.0

#16169 feat: Add upload limits (#16091) (CP: 24.0)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
Labels: +0.0.1, target/main

#16172 test: Build using Maven 3.8.7
  .github/workflows/validation.yml
Labels: +0.0.1, target/9.0, target/23.2, target/23.3, target/24.0

#16175 feat: Add upload limits (#16091) (CP: 23.2)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
Labels: +0.1.0

#16126 fix: Not throw for not yet copied CSS when checking for re-bundling
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssAnnotationVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/CssData.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/MyComponent.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/resources/META-INF/resources/frontend/addons-styles/add-on-styles.css
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
Labels: +0.0.1

#16176 feat: Add upload limits (#16091) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
Labels: +0.1.0

#16177 test: Run with playwright that installs chromium on demand
  flow-client/package-lock.json
  flow-client/package.json
Labels: +0.0.1, target/9.0, target/23.2, target/23.3, target/24.0

#16181 test: Build using Maven 3.8.7 (#16172) (CP: 9.0)
  .github/workflows/validation.yml
Labels: +0.0.1

#16128 test: Use built-in Selenium Manager instead of WebDriverManager
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ViteDevModeIT.java
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/ContextPathIT.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ExternalPackageIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-test-assets/src/test/java/com/vaadin/viteapp/TemplateIT.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/CompressedResourceIT.java
  flow-tests/test-pwa/pom-production.xml
  flow-tests/test-pwa/pom.xml
  pom.xml
Labels: +0.0.1, target/9.0, target/23.2, target/23.3, target/24.0

#16118 fix: Skip checking @vaadin/flow-frontend package
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
Labels: +0.0.1, target/24.0

#15965 fix: ignore missing files in theme processing (#15896) (CP:23.3)
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
Labels: +0.1.0, cherry pick, target/9.0, target/23.2

#16120 test: Run with web-test-runner instead of intern (#16093) (CP: 9.0)
  flow-client/package-lock.json
  flow-client/package.json
  flow-client/pom.xml
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-client/src/test/frontend/tsconfig.json
  flow-client/src/test/npm/intern.json
  flow-client/web-test-runner.config.mjs
  flow-client/webpack.tests.config.js
Labels: +0.0.1

#16137 chore: Update commons file upload to 1.5 (#15982) (CP: 9.0)
  flow-server/pom.xml
Labels: +0.0.1

#16198 test: Run with playwright that installs browsers on demand (CP:9.0)
  flow-client/package-lock.json
  flow-client/package.json
Labels: +0.1.0

#16183 refactor: theme editor undo
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorCommand.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/ClassNamesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/ComponentMetadataHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/HistoryHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LoadPreviewHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LoadRulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/RulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/BaseRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/BaseResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ClassNamesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ComponentMetadataRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ComponentMetadataResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ErrorResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/HistoryRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadPreviewRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadPreviewResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/RulesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/CssRule.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/HasSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/HasThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/LineNumberVisitor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/MessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/MessageHandlerCommand.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/ThemeEditorException.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/ThemeEditorHistory.java
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
Labels: +0.0.1, theme-editor

#16199 refactor: initialize theme preview lazily
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/preview.ts
Labels: +0.0.1, theme-editor

#15966 fix: consume parallel streams when fetching paginated data (#15924) (CP: 9.0)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorAsyncTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, cherry pick

#16189 test: Use built-in Selenium Manager instead of WebDriverManager (#16128) (CP: 23.2)
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ViteDevModeIT.java
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/ContextPathIT.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-test-assets/src/test/java/com/vaadin/viteapp/TemplateIT.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/CompressedResourceIT.java
  flow-tests/test-pwa/pom-production.xml
  flow-tests/test-pwa/pom.xml
  pom.xml
Labels: +0.0.1

#16190 test: Use built-in Selenium Manager instead of WebDriverManager (#16128) (CP: 23.3)
  flow-test-util/pom.xml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDeviceTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeDriverLocator.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ViteDevModeIT.java
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-context-path/src/test/java/com/vaadin/viteapp/ContextPathIT.java
  flow-tests/test-frontend/vite-production-custom-frontend/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/BundlesIT.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-test-assets/src/test/java/com/vaadin/viteapp/TemplateIT.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/CompressedResourceIT.java
  flow-tests/test-pwa/pom-production.xml
  flow-tests/test-pwa/pom.xml
  pom.xml
Labels: +0.0.1

#16200 test: Do not install chromedriver
  .github/workflows/validation.yml
Labels: +0.0.1, target/9.0, target/23.2, target/23.3, target/24.0

#16158 refactor: add range property editor for theme editor
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/shared.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/icons.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/presets.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
Labels: +0.0.1, Theme Editor

#16202 chore: Use TestBench 8.2 to get latest Selenium
  pom.xml
Labels: +0.0.1

#16206 test: Do not install chromedriver in build (#16200) (CP: 9.0)
  .github/workflows/validation.yml
Labels: +0.0.1

#16153 chore: Align Flow test dev bundle with the default dev bundle in platform
  flow-tests/test-express-build/pom.xml
  flow-tests/test-express-build/test-dev-bundle/frontend/themes/vaadin-dev-bundle/theme.json
  flow-tests/test-express-build/test-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java
  flow-tests/test-express-build/test-theme-default-dev-bundle/.gitignore
  flow-tests/test-express-build/test-theme-default-dev-bundle/frontend/index.html
  flow-tests/test-express-build/test-theme-default-dev-bundle/frontend/themes/my-theme/styles.css
  flow-tests/test-express-build/test-theme-default-dev-bundle/pom.xml
  flow-tests/test-express-build/test-theme-default-dev-bundle/src/main/java/com/vaadin/flow/defaultbundle/AppShell.java
  flow-tests/test-express-build/test-theme-default-dev-bundle/src/main/java/com/vaadin/flow/defaultbundle/DefaultDevBundleThemeView.java
  flow-tests/test-express-build/test-theme-default-dev-bundle/src/test/java/com/vaadin/flow/defaultbundle/DefaultDevBundleThemeIT.java
  scripts/computeMatrix.js
Labels: +0.0.1, target/main

#16125 fix: Exclude Vite specific import parameters for project's file imports
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/frontend/styles/my-styles.css
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/main/java/com/vaadin/flow/frontend/DevBundleCssImportView.java
  flow-tests/test-express-build/test-dev-bundle-frontend-add-on/src/test/java/com/vaadin/flow/frontend/DevBundleCssImportIT.java
Labels: +0.0.1

#16211 refactor: integrate theme editor history with frontend
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/api.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/history.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/history.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/icons.ts
Labels: +0.0.1

#16217 chore: Update to TestBench 9.0.1
  pom.xml
Labels: +0.0.1, target/24.0

#16219 refactor: show modified properties in theme editor
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/shared.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/model.ts
Labels: +0.0.1, Theme Editor

#16226 chore: use group for pull_request event [skip ci]
  .github/workflows/validation.yml
Labels: +0.0.1

#16221 fix: Add missing provided scope
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1, target/24.0

#16224 refactor: reduce boilerplate for property editors
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/base-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/base-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/shared.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/text-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/events.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
Labels: +0.0.1, Theme Editor

#16086 fix: option key does not work in addClickShortCut() method
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortCutRegistrationFilterTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutEventTest.java
Labels: +0.0.1, target/23.3, target/24.0

#16242 refactor: implement color property editor in theme editor
  vaadin-dev-server/package.json
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/base-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-picker.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-picker.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-property-editor.test.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/color-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/editors/range-property-editor.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/presets.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/components/vaadin-button.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/metadata/model.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/theme-editor/property-list.ts
  vaadin-dev-server/src/main/resources/META-INF/frontend/vaadin-dev-tools/vendor/@vaadin/overlay/src/vaadin-overlay-position-mixin.js
Labels: +0.0.1, Theme Editor

#16243 fix: Do not import Lumo twice for the document
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1, target/24.0

#16207 feat: support ES-module applications
  flow-server/src/main/resources/plugins/theme-loader/theme-loader-utils.js
  flow-server/src/main/resources/vite.generated.ts
Labels: hilla, +0.0.1, target/24.0

#16225 refactor: Add mode enum to make code easier to read
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/Mode.java
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/PropertyDeploymentConfigurationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0, target/24.0

#16124 feat: Adds helper methods for commonly used CSS properties
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
  flow-server/src/main/java/com/vaadin/flow/dom/Style.java
  flow-server/src/main/java/com/vaadin/flow/router/InternalServerError.java
  flow-server/src/test/java/com/vaadin/flow/component/HasTextTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +1.0.0, Contribution

#16261 refactor: remove circular dependencies in dev tools
  vaadin-dev-server/frontend/component-picker.ts
  vaadin-dev-server/frontend/connection.ts
  vaadin-dev-server/frontend/styles.ts
  vaadin-dev-server/frontend/theme-editor/api.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, Theme Editor

#16252 Added a missing navigate method
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
Labels: +0.0.1, Contribution

#16260 refactor: Support for component instance styling
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorCommand.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/ComponentMetadataHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LoadRulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/RulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/BaseRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/CssRule.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_clean.java
Labels: +0.0.1, Theme Editor

#16262 chore: remove the enforceFieldValidation feature flag (#16248) (CP: 24.0)
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0

#16223 fix: Use correct scope for ee api's
  flow-data/pom.xml
  flow-html-components/pom.xml
  flow-lit-template/pom.xml
  flow-polymer-template/pom.xml
  flow-server/pom.xml
  flow-tests/test-frontend/vite-embedded-webcomponent-resync/pom.xml
  pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1, Contribution, target/24.0

#16268 refactor: theme scope selection
  vaadin-dev-server/frontend/theme-editor/api.test.ts
  vaadin-dev-server/frontend/theme-editor/api.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/color-picker.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/color-picker.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/text-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/text-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/property-list.ts
  vaadin-dev-server/frontend/theme-editor/components/scope-selector.ts
  vaadin-dev-server/frontend/theme-editor/detector.ts
  vaadin-dev-server/frontend/theme-editor/editor.test.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/theme-editor/model.test.ts
  vaadin-dev-server/frontend/theme-editor/model.ts
  vaadin-dev-server/frontend/theme-editor/styles.ts
  vaadin-dev-server/package.json
Labels: +0.0.1, Theme Editor

#16273 refactor: fix base theme detection in theme editor
  vaadin-dev-server/frontend/theme-editor/editor.test.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
Labels: +0.0.1, Theme Editor

#16274 refactor: added classname to set and load rules responses
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LoadRulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/RulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/RulesResponse.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
Labels: +0.0.1, Theme Editor

#16275 refactor: Theme Editor: additional metadata for components
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-avatar.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-number-field.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-progress-bar.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-area.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-field.ts
Labels: +0.0.1, Theme Editor

#16270 refactor: highlight selected component in theme editor
  vaadin-dev-server/frontend/component-picker.ts
  vaadin-dev-server/frontend/theme-editor/editor.test.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
Labels: +0.0.1, Theme Editor

#16276 chore: optimize getModifierKey method, to handle more implementations of Key interface:
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
Labels: +0.0.1

#16280 refactor: Theme Editor updates after demo
  vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-checkbox.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
Labels: +0.0.1, Theme Editor

#16289 refactor: fix range editor sizing issues
  vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.ts
Labels: +0.0.1, Theme Editor

#16285 refactor: preview generated class name in browser
  vaadin-dev-server/frontend/theme-editor/api.ts
  vaadin-dev-server/frontend/theme-editor/editor.test.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
Labels: +0.0.1, Theme Editor

#16290 refactor: use overlay for component picker hover styles
  vaadin-dev-server/frontend/component-picker.ts
Labels: +0.0.1, Theme Editor

#16299 chore: Upgrade to TestBench 8.2.2
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, target/23.2

#16271 chore: Use Node 18.15.0 by default
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#16272 chore: Upgrade to Vite 4.2.0
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#16294 test: Update test Lumo to reflect latest version
  flow-tests/test-lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
  flow-tests/test-lumo/src/main/resources/META-INF/resources/frontend/lumo-includes.ts
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
Labels: +0.0.1

#16297 chore: Run dev bundle build in development mode
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/template/EmptyListsIT.java
Labels: +0.0.1, target/24.0

#16310 chore: Upgrade license-checker to 1.12.2
  pom.xml
Labels: +0.0.1, target/2.8, target/23.2, target/23.3, target/24.0, target/2.9

#16318 chore: fix concurrency cancellation
  .github/workflows/validation.yml
Labels: +0.0.1

#16306 chore!: Remove compatibility mode from API
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendWebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriter.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentGeneratorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentModulesWriterTest.java
Labels: +1.0.0

#16326 chore: Load Lumo utility and badge using the Lumo utils
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1

#16327 chore: also cancel builds for main branches when newer pushes
  .github/workflows/validation.yml
Labels: +0.0.1

#16330 fix: Always set development mode when in development mode
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1, target/24.0

#16266 fix: Try determining the project folder from the classpath
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
Labels: +0.0.1, target/23.3, target/24.0

#16334 chore: also cancel builds for main branches when newer pushes (#16327) (CP: 23.3)
  .github/workflows/validation.yml
Labels: +0.0.1

#16337 chore: Throw an exception when a download fails
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Labels: +0.0.1, target/23.3, target/24.0

#16336 fix: Try determining the project folder from the classpath (#16266) (CP: 23.3)
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1

#16333 fix: Always set theme variant
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
Labels: +0.0.1, target/24.0

#16308 refactor: Extract theme utils from the generated theme
  flow-server/src/main/resources/META-INF/frontend/theme-util.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1

#16342 test: Remove invalid part of test
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/main/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/MultipleNpmPackageAnnotationsView.java
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/main/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleView.java
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/main/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NpmPackageLayout.java
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/MultipleNpmPackageAnnotationsIT.java
  flow-tests/test-express-build/test-dev-bundle-no-plugin/src/test/java/com/vaadin/flow/testnpmonlyfeatures/nobuildmojo/NoAppBundleIT.java
Labels: +0.0.1, target/24.0

#16328 refactor: drop String operations in favor of javaparser API, polishing
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messed.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messedExpected.java
Labels: +0.0.1, Theme Editor

#16332 chore: also cancel builds for main branches when newer pushes (#16327) (CP: 24.0)
  .github/workflows/validation.yml
Labels: +0.0.1

#16346 fix: align javaparser version with the one used by Spreadsheet
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
Labels: +0.0.1

#16344 fix: Do not build Brotli files for the dev bundle
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/24.0

#16349 chore: update @vaadin/router to 1.7.5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/test-npm/package.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1, target/24.0

#16351 Revert lumo changes from 24.0
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
Labels: +0.0.1

#16352 chore: Remove dev mode detector version force
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/24.0

#16353 chore: Upgrade Atmosphere to 3.0.3
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  pom.xml
Labels: +0.0.1, target/24.0

#16296 fix: Make applications esm modules instead of cjs
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#16309 chore: Remove unnecessary dependency
  flow-polymer-template/pom.xml
  flow-server/pom.xml
  flow-tests/test-application-theme/test-theme-component-live-reload/pom.xml
  flow-tests/test-application-theme/test-theme-live-reload/pom.xml
  flow-tests/test-express-build/test-parent-theme-express-build/pom.xml
  flow-tests/test-express-build/test-parent-theme-in-frontend/pom.xml
  flow-tests/test-express-build/test-reusing-theme-express-build/pom.xml
  flow-tests/test-express-build/test-theme-dev-bundle/pom.xml
  flow-tests/test-live-reload/pom.xml
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-root-context/pom.xml
  vaadin-dev-server/pom.xml
  vaadin-spring/pom.xml
Labels: +0.0.1

#16358 chore: bump spring to 6.0.7
  pom.xml
Labels: +0.0.1, target/24.0

#16364 refactor: hide selection highlight when closing theme editor
  vaadin-dev-server/frontend/theme-editor/editor.test.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, Theme Editor

#16367 chore: added more covering tests to ComponentTest.java for covering getLocale() method
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +0.0.1

#16160 refactor: Reuse already fetched I18NProvider in Component.getTranslation
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
Labels: performance, +0.0.1, Contribution

#16368 chore: remove unused version properties
  pom.xml
Labels: +0.0.1, target/24.0

#16361 chore: optimize (and fix) generateEventModifierFilter() method, to handle more implementations of Key interface and fix browser differences. (#16276)(#16086)(CP: 2.9)
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/main/java/com/vaadin/flow/component/Shortcuts.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortCutRegistrationFilterTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutEventTest.java
Labels: +1.0.0

#16365 refactor: theme editor api updates
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorCommand.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/ClassNamesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/ComponentMetadataHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LoadRulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LocalClassNameHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/RulesHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ClassNamesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/ComponentMetadataResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/LoadRulesResponse.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/messages/SetClassNameRequest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/CssRule.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/LocalClassNameVisitor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/LocalClassNamesVisitor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/StatementLineNumberVisitor.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandlerTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
  vaadin-dev-server/src/test/resources/java/org/vaadin/example/TestView_messedExpected.java
Labels: +1.0.0, Theme Editor

#16375 fix: Allow access to /favicon even when the vaadin mapping is /something
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/TestBenchHelpers.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
Labels: +1.0.0, target/24.0

#16376 chore: Upgrade to Spring Boot 3.0.5
  flow-tests/servlet-containers/tomcat10/pom.xml
  pom.xml
Labels: +0.0.1, target/24.0

#16377 chore: Upgrade to Spring Boot 2.7.10
  flow-tests/servlet-containers/tomcat9/pom.xml
  pom.xml
Labels: +0.0.1

#16372 refactor: use selectors in theme editor component metadata
  vaadin-dev-server/frontend/theme-editor/api.test.ts
  vaadin-dev-server/frontend/theme-editor/api.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/color-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/range-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/text-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/property-list.ts
  vaadin-dev-server/frontend/theme-editor/detector.test.ts
  vaadin-dev-server/frontend/theme-editor/detector.ts
  vaadin-dev-server/frontend/theme-editor/editor.test.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-avatar.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-button.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-checkbox.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-number-field.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-progress-bar.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-area.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-text-field.ts
  vaadin-dev-server/frontend/theme-editor/metadata/model.ts
  vaadin-dev-server/frontend/theme-editor/metadata/registry.test.ts
  vaadin-dev-server/frontend/theme-editor/model.test.ts
  vaadin-dev-server/frontend/theme-editor/model.ts
  vaadin-dev-server/frontend/theme-editor/tests/utils.ts
Labels: +0.0.1, Theme Editor

#16382 test: Use the same slf4j version everywhere
  flow-tests/test-express-build/frontend-add-on/pom.xml
  flow-tests/test-express-build/java-add-on/pom.xml
  flow-tests/test-express-build/test-dev-bundle/pom.xml
Labels: +0.0.1, target/24.0

#16380 chore: update formatter url: master -> main
  pom.xml
Labels: +1.0.0, target/23.2, target/23.3, target/24.0

#16391 chore: update license-checker to 1.12.3
  pom.xml
Labels: +0.0.1, target/24.0

#16384 refactor: add menubar metadata to theme editor
  vaadin-dev-server/frontend/theme-editor/components/editors/base-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/checkbox-property-editor.test.ts
  vaadin-dev-server/frontend/theme-editor/components/editors/checkbox-property-editor.ts
  vaadin-dev-server/frontend/theme-editor/components/property-list.ts
  vaadin-dev-server/frontend/theme-editor/detector.test.ts
  vaadin-dev-server/frontend/theme-editor/detector.ts
  vaadin-dev-server/frontend/theme-editor/editor.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/presets.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-menu-bar.ts
  vaadin-dev-server/frontend/theme-editor/metadata/model.ts
  vaadin-dev-server/frontend/theme-editor/model.test.ts
  vaadin-dev-server/frontend/theme-editor/model.ts
  vaadin-dev-server/frontend/theme-editor/tests/utils.ts
Labels: +0.0.1, Theme Editor

#16394 refactor: css rules classname replace
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeEditorMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/ThemeModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/handlers/LocalClassNameHandler.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/ThemeModifierTest.java
Labels: +0.0.1, Theme Editor

#15865 test: Use --headless=new as ChromeOptions recommends for Chrome 109+
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTest.java
Labels: +0.0.1, target/24.0

#16399 fix: Decode project folder when using classpath
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
Labels: +0.0.1, target/23.3, target/24.0

#16412 fix: Decode project folder when using classpath (#16399) (CP: 23.3)
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1

#16292 chore: Generate JS instead of TS to avoid import strageness
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1

#16378 refactor: fix empty line after removing component
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
Labels: +0.0.1, Theme Editor

#16400 refactor: add select metadata to theme editor
  vaadin-dev-server/frontend/theme-editor/detector.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/vaadin-select.ts
Labels: +0.0.1, Theme Editor

#16247 fix: Import all document styles using style tags
  flow-client/src/main/java/com/vaadin/client/ResourceLoader.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/resources/META-INF/frontend/theme-util.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuildTest.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/CssLoadingIT.java
Labels: +0.0.1

#16414 refactor: allow theming non-Vaadin components
  vaadin-dev-server/frontend/theme-editor/metadata/components/defaults.ts
  vaadin-dev-server/frontend/theme-editor/metadata/components/generic.ts
  vaadin-dev-server/frontend/theme-editor/metadata/registry.test.ts
  vaadin-dev-server/frontend/theme-editor/metadata/registry.ts
Labels: +0.0.1, Theme Editor

#16418 chore: Write theme file only if it has changed
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-handle.js
Labels: +0.0.1

#16409 test: Check end result instead of implementation details
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/side-src/main/frontend/themes/app-theme/styles.css
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-frontend/vite-basics/frontend/themes/vite-basics/styles.css
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/ThemeIT.java
  flow-tests/test-themes/frontend/themes/app-theme/styles.css
  flow-tests/test-themes/src/test/java/com/vaadin/flow/uitest/ui/theme/ThemeIT.java
Labels: +0.0.1

#16422 refactor: remove empty lines on classname update
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
Labels: +0.0.1, Theme Editor

#16437 chore: update branch info in readme [skip ci]
  README.md
Labels: +0.0.1

#16436 refactor: add support for addClassName inside constructor block
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/editor/Editor.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifier.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/themeeditor/utils/LocalClassNameVisitor.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/AbstractThemeEditorTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/themeeditor/JavaSourceModifierTest.java
Labels: +0.0.1, Theme Editor

#16440 chore: Upgrade to TestBench 9.0.2
  pom.xml
Labels: +0.0.1, target/24.0

#16439 test: Test that an embedded theme does not leak into the document
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#16444 chore: Upgrade to TestBench 9.0.2 (#16440) (CP: 24.0)
  pom.xml
Labels: +0.0.1

#16446 refactor: show theme editor only in Flow apps
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, Theme Editor

#16445 refactor: import constructable stylesheets polyfill from dev tools
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
  vaadin-dev-server/vite.config.js
Labels: +0.0.1, Theme Editor
