Repository vaadin/flow, pull requests merged in 2024-09, with the labels that each got.

#19846 chore: add premiumFeatures.enable token to build info
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
Labels: +0.0.1

#19856 fix: prevent NPE when creating init parameters
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.0.1, target/24.3, target/23.5, target/24.4

#19860 chore: remove Copilot I18n feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0

#19840 chore: upgrade commons-compress to 1.26.1
  flow-server/pom.xml
Labels: +0.0.1

#19867 chore: Javaparser 3.26.2
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#19869 test: pin selenium devtools version compatible with chrome 128 (24.3)
  flow-tests/pom.xml
Labels: +0.0.1

#19859 fix: prevent NPE when creating init parameters (#19856) (CP: 23.5)
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/PreserveOnRefreshIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
Labels: +0.0.1, cherry pick

#19853 chore: upgrade springboot to 3.2.9
  pom.xml
Labels: +0.0.1

#19884 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19873 fix: Validate layout values
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
Labels: +1.0.0

#19885 fix: safely handle nested removal of menu routes
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Labels: +0.0.1, Contribution

#19878 fix: No react module for Vaadin Router
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullScannerPwaTest.java
Labels: +0.0.1

#19861 chore: upgrade testbench to 9.3.4
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#19875 fix: prevent Flow navigation for Hilla route
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +0.0.1, target/24.4

#19886 test: assert after browser resize event listener completes (2.11)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
Labels: +0.0.1

#19889 fix: use instantiator to lookup DAUCustomizer implementation
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.0.1

#19893 test: fix servlet containers test modules (2.11)
  flow-tests/servlet-containers/felix-jetty/pom.xml
  flow-tests/servlet-containers/pom.xml
  flow-tests/servlet-containers/tomcat85/pom.xml
  flow-tests/servlet-containers/tomcat9/pom.xml
  flow-tests/test-root-context/pom.xml
Labels: +0.0.1

#19897 chore: Upgrade LC to 1.12.14
  pom.xml
Labels: +0.0.1, target/24.3, target/23.5, target/2.11

#19898 fix: client navigation for server layout
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultRouteResolver.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/router/DefaultRouteResolverTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
Labels: +0.0.1

#19901 chore: Upgrade LC to 1.12.14 (#19897) (CP: 2.11)
  pom.xml
Labels: +0.0.1, cherry pick

#19900 chore: Upgrade LC to 1.12.14 (#19897) (CP: 23.5)
  pom.xml
Labels: +0.0.1, cherry pick

#19899 chore: Upgrade LC to 1.12.14 (#19897) (CP: 24.3)
  pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1, cherry pick

#19902 feat: Make proxy reading method public
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ProxyFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.0.1

#19903 feat: Add download progress listener to FileDownloader
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DownloadException.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/FileDownloader.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloaderTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#19894 feat: Add option to not modify readonly files during copy, add logging of time
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyLocalFrontendFiles.java
Labels: +1.0.0, target/24.4

#19915 chore: Upgrade React Router
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#19916 chore: improve error message for duplicated PWA annotation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
Labels: +0.0.1, target/24.3, target/23.5, target/24.4

#19928 chore: improve error message for duplicated PWA annotation (#19916) (CP: 23.5)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
Labels: +0.0.1, cherry pick

#19921 fix: wait for output reading to complete before parsing version
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
Labels: +0.0.1, target/24.3, target/24.4

#19917 chore: TypeScript 5.6.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#19937 chore: prevent jandex artifact to import transitive dependencies
  flow-jandex/pom.xml
Labels: +0.0.1, target/24.4

#19935 fix: Propagate Premium Features flag value to configuration
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
Labels: +0.0.1

#19932 chore: Vite 5.4.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19942 chore: exclude transitive JNA dependency from org.eclipse.core.resources (2.11)
  flow-client/pom.xml
Labels: +0.0.1

#19933 feat: generate layout.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeClassFinderTest.java
Labels: +0.0.1

#19945 fix: Evaluate target not active
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#19947 Revert "feat: Support top-level await"
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
  flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/toplevelawait-main.js
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/toplevelawait-other.js
Labels: +0.0.1

#19949 fix: Reset the Premium Features flag before license checking
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Labels: +0.0.1

#19943 chore: exclude transitive JNA dependency from org.eclipse.core.resources (23.5)
  flow-client/pom.xml
Labels: +0.0.1

#19952 feat: add collectMenuItemsList() to MenuRegistry
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Labels: +0.0.1

#19558 chore: remove splash messages from dev tools
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#19957 chore: Upgrade LC to 1.13.0.beta1
  pom.xml
Labels: +0.0.1

#19962 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19963 chore: Bump Vite
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19964 chore: Bump Vite
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19940 chore: bump eclipse platform dependencies to the latest versions
  flow-client/pom.xml
Labels: +0.0.1, target/24.3, target/24.4

#19959 fix: forward with optional callback
  flow-server/src/main/java/com/vaadin/flow/router/BeforeEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardTargetView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardTargetWithParametersView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardingToParametersView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/ForwardingView.java
  flow-tests/test-react-router/src/test/java/com/vaadin/flow/ForwardTargetIT.java
Labels: +0.0.1, target/24.4

#19976 chore: bump eclipse platform dependencies to the latest versions (#19940) (CP: 24.3)
  flow-client/pom.xml
Labels: +0.0.1, cherry pick

#19977 fix: fail fast if view defines same path for route and route alias
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/AbstractRouteRegistryInitializerTest.java
Labels: +0.0.1, target/24.3, target/23.5, target/24.4

#19979 fix: ensure session is registered with Hotswapper
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Labels: +0.1.0

#19996 fix: Do not throw if re-setting the login view
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
Labels: +0.1.0, target/24.4, target/24.5

#19993 chore: upgrade springboot to 3.2.10 (24.4)
  pom.xml
Labels: +0.0.1

#19997 chore: Upgrade to LC 1.13.0.beta2
  pom.xml
Labels: +0.0.1, target/24.5

#20009 refactor: Make DebugWindowConnection send public and name it broadcast
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +0.0.1, target/24.5

#19984 fix: close overlay drawer on click
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.4, target/24.5

#20019 test: increase sleep time to allow GC to perform cleanup
  flow-server/src/test/java/com/vaadin/flow/ComponentTrackerTest.java
Labels: +0.0.1, target/24.3, target/24.4, target/24.5

#20018 chore: Node 22.9.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#20007 chore: More detailed logging for ignored handling
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
Labels: +0.0.1, target/24.3, target/23.5, target/24.4, target/24.5

#20024 fix: Validate Control Center feature when used
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/controlcenter/starter/actuate/endpoint/VaadinActuatorEndpoint.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Labels: +0.0.1, target/24.5

#20028 chore: More detailed logging for ignored handling (#20007)
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
Labels: +0.0.1, cherry pick

#20030 chore: More detailed logging for ignored handling (#20007)
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
Labels: +0.0.1, cherry pick

#20034 chore: update validation versions
  .github/workflows/validation.yml
Labels: +0.0.1, target/24.5

#20014 chore: HMR for vaadin-react.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vaadin-react.tsx
Labels: +0.0.1, target/24.5

#20036 chore: show warning when LC is missing in a DAU build
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBuild.java
Labels: +0.0.1, target/24.5

#20040 fix: hide root output element
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.4, target/24.5

#20045 chore: Bump frontend deps
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.5

#20046 chore: Bump more frontend deps
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.5

#20050 test: prevent DauStorage calls in unit tests
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceDauTest.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUUtilsTest.java
Labels: +0.0.1, target/24.5

#20047 fix: update title after navigation
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PageIT.java
Labels: +0.0.1, target/24.4, target/24.5

#20076 fix: Layout should be collected as entyrpoint
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Labels: +0.0.1, target/24.5

#20054 chore: Add possibility to register shutdown commands for development mode
  flow-server/src/main/java/com/vaadin/flow/internal/DevModeHandlerManager.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeHandlerStopTest.java
Labels: +0.1.0, target/24.5

#20075 fix: Store layout packages
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, target/24.5

#20073 feat: ComponentTracker file location of Kotlin files
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentTracker.java
  flow-server/src/test/java/com/vaadin/flow/ComponentTrackerLocationTest.java
Labels: +0.1.0, target/24.5

#20078 chore: upgrade to TB 9.3.5
  pom.xml
Labels: +0.0.1, target/24.4, target/24.5

#20059 fix: add nodeVersion in gradle plugin settings
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
Labels: +1.0.0, Contribution, target/24.3, target/24.4, target/24.5

#20095 chore: upgrade springboot to 3.2.10 (24.3)
  pom.xml
Labels: +0.0.1

#20008 [test PR]chore: test Spring boot 3.4
  pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/JwtStatelessAuthenticationTest.java
Labels: +1.0.0
