Repository vaadin/flow, pull requests merged in 2024-08, with the labels that each got.

#19737 test: fix pwa production nightly test
  flow-tests/test-pwa/pom-production.xml
Labels: +0.0.1, target/24.4

#19742 fix: Unify client route to match server route format
  flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
Labels: +0.0.1, target/24.4

#19740 fix: apply CssImport to exported webcomponent
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/resources/META-INF/frontend/theme-util.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/frontend/css-import-component.css
  flow-tests/test-embedding/test-embedding-application-theme/src/main/frontend/themes/embedded-theme/theme.json
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/CssImportComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/24.3, target/23.5, target/24.4

#19746 fix: apply CssImport to exported webcomponent (#19740) (CP: 24.3)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/resources/META-INF/frontend/theme-util.js
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
  flow-tests/test-embedding/test-embedding-application-theme/frontend/css-import-component.css
  flow-tests/test-embedding/test-embedding-application-theme/frontend/themes/embedded-theme/theme.json
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/CssImportComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/java/com/vaadin/flow/webcomponent/ThemedComponent.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1

#19749 fix: always generate routes.tsx
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
Labels: +0.0.1, target/24.4

#19751 fix: rename lock file
  .gitignore
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Labels: +0.0.1, target/24.4

#19747 feat: Add CompletableFuture WebStorage API
  flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
  flow-server/src/main/java/com/vaadin/flow/component/page/WebStorage.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/WebStorageView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/WebStorageIT.java
Labels: +0.1.0, Contribution

#19736 feat: push and replace without navigation callback
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
Labels: +0.0.1, target/24.4

#19770 chore: Node 20.16.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#19771 feat: add support for Daily Active User feature
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/MessageDigestUtil.java
  flow-server/src/main/java/com/vaadin/flow/internal/StringUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUCustomizer.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptor.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/DauEnforcementException.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/EnforcementNotificationMessages.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/FlowDauIntegration.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/UserIdentityContext.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/UserIdentitySupplier.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceDauTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptorTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  pom.xml
Labels: +0.1.0

#19763 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#19761 chore: Bump Lit to 3.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#19767 fix: Fix hierarchical keys passivation
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorTest.java
Labels: +0.0.1

#19782 chore: add utility method for DAU tracking
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUUtilsTest.java
Labels: +1.0.0

#19781 fix: use URLClassLoader with ResourceProvider in Maven plugins
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/ResourceProviderImpl.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Labels: hilla, +0.0.1, target/24.4

#19787 Fix for dropping support for bower mode
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/common/FrontendDataProvider.java
Labels: +0.0.1

#19766 feat: Strongly cache Copilot files
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
Labels: +0.0.1

#19784 fix: HierarchicalDataCommunicator doesn't support estimates
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
Labels: +0.0.1

#19796 fix: preserve record prop order, sort for beans
  flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BeanPropertySetTest.java
Labels: +0.0.1

#19803 fix: Downgrade to glob 10.4.5 which is Node 18 compatible
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#19806 feat: Binder record support
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java
Labels: +0.0.1

#19793 chore: upgrade open to 8.5.0.2
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#19815 chore: Upgrade to license checker 1.13.0.alpha2
  pom.xml
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#19810 fix: use URLClassLoader with ResourceProvider in Maven plugins (#19781)
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/LookupImpl.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/utils/ResourceProviderImpl.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Labels: +0.0.1, cherry pick

#19814 chore: Upgrade to Node.js 20.17.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#19488 feat:Improve Binder change detection
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.1.0, Contribution

#19791 fix: use Thread context ClassLoader for loading I18n ResourceBundle
  flow-server/src/main/java/com/vaadin/flow/di/DefaultInstantiator.java
  flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/DefaultInstantiatorMenuAccessControlTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/i18n/DefaultI18NProviderFactory.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/i18n/DefaultI18NProviderFactorySuite.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/i18n/DefaultI18NProviderFactoryTest.java
Labels: hilla, +0.1.0, target/24.4

#19797 feat: Automatic Flow layout
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactRouterOutlet.java
  flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/Layout.java
  flow-server/src/main/java/com/vaadin/flow/router/Route.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteAlias.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/DefaultRouteResolver.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/RouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/SessionRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/AvailableViewInfo.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
  flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
  flow-server/src/test/java/com/vaadin/flow/router/DefaultRouteResolverTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/server/ErrorHandlerUtilTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +1.0.0

#19819 chore: upgrade spring boot to 3.2.9
  pom.xml
Labels: +0.0.1

#19820 chore: Upgrade to license checker 1.13.0.alpha3
  pom.xml
Labels: +0.1.0

#19816 fix: block new users immediately when enforcement=ON
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptor.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/FlowDauIntegration.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptorTest.java
Labels: +1.0.0

#19824 fix: Make outlet tsx generated
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactRouterOutlet.java
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactRouterOutletElement.template
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
Labels: +0.0.1

#19775 Create Fieldset - Legend Java API
  flow-html-components/src/main/java/com/vaadin/flow/component/html/FieldSet.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/FieldSetTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
Labels: +0.1.0

#19826 fix: Add react classes in optimized mode
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1

#19812 chore: Bump frontend dependencies (24.4)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#19811 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19833 fix: Use 8080 as the default launch port for opening the browser
  vaadin-spring/src/main/java/com/vaadin/flow/spring/DevModeBrowserLauncher.java
Labels: +0.0.1, target/24.4

#19835 Revert "fix: Make outlet tsx generated (#19824)"
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactRouterOutlet.java
  flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1

#19837 chore: remove Copilot Flow feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +1.0.0

#19849 fix: Validate Layout annotation
  flow-server/src/main/java/com/vaadin/flow/server/startup/RouteRegistryInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1

#19848 chore: upgrade TB to 9.3.4
  pom.xml
Labels: +0.0.1

#19841 chore: Upgrade LC to 1.13.0.alpha4
  pom.xml
Labels: +0.0.1

#19845 fix: React file not added when reactEnabled false
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
Labels: +0.0.1

#19852 Options should correct the reactEnable flag
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1
