Repository vaadin/flow, pull requests merged in 2024-12, with the labels that each got.

#20590 chore: Vite 6.0.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.6

#20447 chore: Update the JRebel class for backend type detection
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Labels: +0.0.1, target/24.5, target/24.6

#20592 chore: LicenseChecker 1.13.3
  pom.xml
Labels: +0.0.1

#20601 fix: enforce plugin-required dependencies and log incompatibilities
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/invoker.properties
  flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/src/main/java/com/vaadin/test/ProjectFlowExtension.java
  flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/verify.bsh
  flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/invoker.properties
  flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/src/main/java/com/vaadin/test/ProjectFlowExtension.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20611 fix: Remove timeout for browser websocket connection for Vite
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketEndpoint.java
Labels: +0.0.1, target/24.5, target/24.6

#20617 chore: Node 22.12.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.6

#20618 chore: Node 20.18.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#20537 chore: React Router v7
  flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-flow.tsx
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-basics/src/main/frontend/routes.tsx
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
  flow-tests/test-react-router/src/main/frontend/NavigateView.tsx
  flow-tests/test-react-router/src/main/frontend/routes.tsx
Labels: +0.0.1

#20620 chore: Bump frontend deps
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.5, target/24.6

#20634 chore: use latest bun version
  .github/workflows/validation.yml
Labels: +0.0.1, target/24.6

#20622 fix: service destroy listener exceptions
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20641 fix: Add React Router future flags for flow auto-generated routes file
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-flow.tsx
Labels: +0.0.1, target/24.5

#20645 fix: wrap UI closing to catch exceptions
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20632 chore: fix dependencies incompatibilities log message
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20659 chore: update component version to 24.5.8 (#20655)
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#20660 chore: Log the correct id
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
Labels: +0.0.1, target/24.5, target/24.6

#20642 test: fix flaky spring security tests
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
Labels: +0.0.1

#20667 chore: TestBench 9.3.7
  pom.xml
Labels: +0.0.1

#20673 fix: appended path on fast navigate
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.5, target/24.6

#20666 fix: fix redirect URL for PUSH with websocket transport
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/main/java/com/vaadin/flow/spring/flowsecuritywebsocket/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/main/java/com/vaadin/flow/spring/flowsecuritywebsocket/PushWebsocketConfigurer.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
  scripts/computeMatrix.js
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20669 chore!: Change supported Node from 18 to 20
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.0.1

#20657 fix: browser parsing
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-server/src/test/java/com/vaadin/flow/server/WebBrowserTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
  flow-server/src/test/resources/common-desktop-useragents.json
  flow-server/src/test/resources/mobile-useragents.json
Labels: +1.0.0, target/24.6

#20687 fix: ensure requestEnd clears Vaadin thread locals
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Labels: +0.0.1, target/23.5, target/24.4, target/2.11, target/24.5, target/24.6

#20692 fix: ensure requestEnd clears Vaadin thread locals (#20687) (CP: 23.5)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
Labels: +0.0.1, cherry pick

#20656 fix: catch exceptions from detach calls
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/component/DetachNotifier.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
Labels: +1.0.0, target/24.4, target/24.5, target/24.6

#20694 chore: Add a new maven module for Full-Stack Signals common lib
  flow-bom/pom.xml
  flow/pom.xml
  pom.xml
  signals/bnd.bnd
  signals/pom.xml
  signals/src/main/java/com/vaadin/signals/dummy
  signals/src/test/java/com/vaadin/signals/dummy
Labels: +0.0.1

#20702 chore: do not log incompatibility if project dependencies are not resolved (CP: 24.4)
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
Labels: +0.0.1, cherry pick

#20679 fix: fix role checking when using websocket push
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SecurityUtil.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20688 fix: handle logout from a background thread
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/MainView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20703 chore: do not log incompatibility if project dependencies are not resolved (CP: 24.5)
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
Labels: +0.0.1, cherry pick

#20704 test: set Jetty stop timeout (2.11)
  flow-tests/pom.xml
Labels: +0.0.1

#20710 fix: fix role checking when using websocket push (#20679) (CP: 24.5)
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SecurityUtil.java
Labels: +0.0.1, cherry pick

#20711 fix: fix role checking when using websocket push (#20679) (CP: 24.4)
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringNavigationAccessControl.java
Labels: +0.0.1, cherry pick

#20709 fix: fix role checking when using websocket push (#20679) (CP: 24.6)
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-websocket/src/test/java/com/vaadin/flow/spring/flowsecuritywebsocket/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SecurityUtil.java
Labels: +0.0.1, cherry pick

#20718 fix: Disable workbox developer logs by default
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/sw.ts
Labels: +0.0.1, target/24.6

#20719 chore: pin javassist version in flow plugin base
  flow-plugins/flow-plugin-base/pom.xml
  pom.xml
  vaadin-spring/pom.xml
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20735 Fix for duplicate maven-jar entries in POM.XML
  flow-tests/test-express-build/frontend-add-on/pom.xml
  flow-tests/test-express-build/java-add-on/pom.xml
Labels: +0.0.1

#20729 fix: re-build production bundle if index.html changes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-tests/test-express-build/test-parent-theme-in-frontend-prod/src/main/frontend/index.html
  flow-tests/test-express-build/test-parent-theme-prod/src/main/frontend/index.html
  flow-tests/test-express-build/test-prod-bundle-no-plugin/src/main/frontend/index.html
  flow-tests/test-express-build/test-theme-legacy-components-css-prod/src/main/frontend/index.html
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20744 chore: fix test typos
  flow-client/src/test-gwt/java/com/vaadin/client/GwtSuite.java
  flow-client/src/test-gwt/java/com/vaadin/client/communication/GwtAtmospherePushConnectionTest.java
Labels: +0.0.1

#20746 chore: makes HttpClient instance available for garbage collection
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
Labels: +0.0.1, target/24.6

#20612 fix: do not mistakenly run 2 npm installs
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
Labels: +0.0.1

#20684 fix: trigger refresh on hotswap only for redefined classes
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Labels: +0.0.1, target/24.5, target/24.6

#20753 chore: Vite 6.0.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#20757 chore: Upgrade to Glob 11
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#20758 chore: upgrade springboot to 3.4.1
  pom.xml
Labels: +0.0.1, target/24.6

#20761 test: disable shm usage for reload time test
  flow-tests/vaadin-spring-tests/test-plain-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/test/java/org/vaadin/example/SpringDevToolsReloadViewIT.java
Labels: +0.0.1, target/24.4, target/24.5, target/24.6

#20765 chore: Updated link at Copilot experimental feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#20769 feat: add feature flag for Card
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#20773 chore: sonar fixes
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#20778 chore: Remove unused declarations in flow-server and flow-data
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java
  flow-server/src/main/java/com/vaadin/flow/dom/ChildElementConsumer.java
  flow-server/src/main/java/com/vaadin/flow/dom/Node.java
  flow-server/src/main/java/com/vaadin/flow/internal/menu/MenuRegistry.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
  flow-server/src/main/java/com/vaadin/flow/server/AppShellRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/PushHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyTemplateFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ServletDeployer.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
Labels: +0.0.1

#20790 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.6

#20795 chore: use custom thread pool for vaadin-dev-server tasks
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1
