Repository vaadin/flow, pull requests merged in 2024-05, with the labels that each got.

#19288 test: fix webpush test notification check
  flow-tests/test-webpush/src/test/java/com/vaadin/flow/webpush/WebPushIT.java
Labels: +0.0.1, target/24.3

#19290 test: wait before checking size (#19243) (CP: 24.3)
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/BrowserWindowResizeIT.java
Labels: +0.0.1, cherry pick

#19274 fix: prevent embedded styles to leak main document
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTestComponents.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateTestUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScannerTest.java
  flow-tests/test-embedding/test-embedding-application-theme/src/main/webapp/index.html
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/24.3

#19292 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#19196 fix: make property change listener trigger on removeProperty
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
  flow-server/src/test/java/com/vaadin/flow/component/PropertyDescriptorsTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
Labels: +0.0.1, Contribution, target/24.3

#19293 fix: prevent embedded styles to leak main document (#19274) (CP: 24.3)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
Labels: +0.0.1, cherry pick

#19287 fix: include filesystem dependencies in gradle plugin class finder
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/resources/addon.jar
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
Labels: +0.0.1, target/24.3, target/24.4

#19300 fix: prevent exception getting DevModeHandlerManager on application shutdown
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeStartupListener.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/DevModeHandlerStopTest.java
Labels: +0.0.1, target/24.3, target/24.4

#19310 Revert "fix: make property change listener trigger on removeProperty (#19196)"
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
  flow-server/src/test/java/com/vaadin/flow/component/PropertyDescriptorsTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMapTest.java
Labels: +0.0.1, target/24.4

#19312 feat: Add HasLabelAsText interface to NativeButtonElement
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeButtonElement.java
Labels: enhancement, +0.0.1

#19325 chore: Bump Vite to 5.2.11
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#19318 docs: update Javadoc in Menu annotation
  flow-server/src/main/java/com/vaadin/flow/router/Menu.java
Labels: +0.0.1, target/24.4

#19340 fix: Fix failure when Vite sends many messages in sequence
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
Labels: +0.0.1, target/24.4

#19323 fix: reload flow after hmr reload in dev mode
  flow-client/src/main/frontend/FlowBootstrap.js
Labels: +0.0.1, target/24.4

#19345 fix: add warnings for unsupported feature flags
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Labels: +0.0.1

#19346 chore: Upgrade Node.js to 20.13.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.4

#19350 chore: Reintroduce message debug logging
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
Labels: +0.0.1, target/24.4

#19309 fix!: rename createWebComponent method
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.4

#19332 fix: change type of Menu order to double
  flow-server/src/main/java/com/vaadin/flow/router/Menu.java
  flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/AdminView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/PrivateView.java
Labels: +1.0.0, target/24.4

#19358 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1, target/24.4

#19329 fix: set page title to documentTitleSignal
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1, target/24.4

#19362 chore: Bump frontend dependencies (#19358) (CP: 24.4)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#19342 fix: provide specific package-lock.json for hybrid applications
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
Labels: +0.0.1, target/24.4

#19372 chore(deps): bump component.version from 24.3.11 to 24.3.12 (#19364)
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1

#19373 chore(deps): bump org.mockito:mockito-core from 5.7.0 to 5.12.0 (#19367)
  pom.xml
Labels: +0.0.1

#19355 feat: Get menu views api
  flow-server/src/main/java/com/vaadin/flow/router/MenuData.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/ParameterInfo.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteFormat.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteSegment.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/AvailableViewInfo.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/RouteParamType.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +1.0.0

#19360 fix: clear preseved chain cache for inactive UI
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
  flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
Labels: +0.0.1, target/23.3, target/23.4, target/24.3, target/23.5, target/24.4

#19331 feat: API for reloading current route target
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/NavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RefreshCurrentPreserveOnRefreshRouteView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteLayout.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCurrentPreserveOnRefreshRouteIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RefreshCurrentRouteIT.java
Labels: +1.0.0

#19380 chore: add feature flag for Copilot I18n plugin
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#19382 fix: clear preseved chain cache for inactive UI (#19360) (CP: 24.3)
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
  flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
Labels: +0.0.1, cherry pick

#19385 fix: clear preseved chain cache for inactive UI (#19360) (CP: 23.5)
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-misc/pom.xml
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
  flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
Labels: +0.0.1, cherry pick

#19383 fix: clear preseved chain cache for inactive UI (#19360) (CP: 23.4)
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-misc/pom.xml
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
  flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
Labels: +0.0.1, cherry pick

#19384 fix: clear preseved chain cache for inactive UI (#19360) (CP: 23.3)
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-misc/pom.xml
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ActiveUIsView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/PreserveOnRefreshView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/UITrackerListener.java
  flow-tests/test-misc/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PreserveOnRefreshCloseUIsIT.java
Labels: +0.1.0, cherry pick

#19295 chore: Upgrade web-components version in tests
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
Labels: +0.0.1

#19236 chore: dont install chrome in container, let selenium install it instead
  .github/workflows/validation.yml
Labels: +0.0.1, target/24.3, target/24.4

#19391 chore: add feature flag for Full-stack Signals
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#19393 chore: add feature flag for Copilot I18n plugin (#19380)
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#19322 fix: add explicit dependency to JDK classes in vaadin-dev-server
  vaadin-dev-server/pom.xml
Labels: +0.0.1, target/24.3, target/24.4

#19401 fix: do not set lastHandledNavigation on refresh
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +0.0.1

#19409 fix: avoid blocking thread on ViteWebsocketConnection creation
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketProxy.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1

#19413 fix: add reflection hints for VaadinRolePrefixHolder
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: +0.0.1, target/24.3, target/24.4

#19400 feat: Add MAU tracking for routing
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
Labels: +0.0.1, target/24.4

#19389 feat: Filter client routes by authentication and role
  flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/ClientRoutesProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/test/java/com/vaadin/flow/component/InvalidUrlTest.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouteNotFoundErrorTest.java
  flow-server/src/test/java/com/vaadin/flow/router/RouterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/HillaRoutesRegisteredIT.java
Labels: +1.0.0

#19420 chore: update testbench to beta2
  pom.xml
Labels: +0.0.1, target/24.4

#19421 chore: upgrade TB to 9.3.0.beta2 (24.4)
  pom.xml
Labels: +0.0.1

#19406 fix: support route parameters in menu
  flow-server/src/main/java/com/vaadin/flow/router/RouteBaseData.java
  flow-server/src/main/java/com/vaadin/flow/router/RouteParameterData.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractRouteRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
Labels: +1.0.0

#19432 Revert "chore(deps): bump io.smallrye:jandex-maven-plugin from 3.1.8 to 3.2.0 (#19407)"
  flow-jandex/pom.xml
Labels: +0.0.1

#19438 chore: upgrade TB to 9.3.0.rc1
  pom.xml
Labels: +0.0.1, target/main

#19439 Revert "chore(deps): bump jakarta.validation:jakarta.validation-api from 3.0.2 to 3.1.0 (#19426)
  pom.xml
Labels: +0.0.1

#19443 chore: upgrade TB to 9.3.0.rc1
  pom.xml
Labels: +0.0.1

#19430 chore: Upgrade to Spring-Boot 3.3.0
  pom.xml
Labels: +0.0.1

#19444 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/24.4

#19452 fix: prevent prepare-frontend to remove Hilla generated files
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
Labels: +0.0.1, target/24.4

#19455 fix: add missing hints to fix native compilation
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinBeanFactoryInitializationAotProcessor.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: +0.0.1, target/24.3, target/24.4

#19453 chore: Bump frontend dependencies (#19444)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, cherry pick

#19464 fix: use maven project classpath to detect Hilla presence
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
Labels: +0.0.1, target/24.4

#19461 feat: add alternative translate methods to I18NProvider
  flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/LocaleUtil.java
  flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
  flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/TranslationView.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/TranslationIT.java
Labels: +1.0.0

#19460 fix: add missing reflection hints for flow-components
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: +1.0.0, target/24.3, target/24.4
