Repository vaadin/flow, pull requests merged in 2024-06, with the labels that each got.

#19487 feat: add ValueContext.getBinder()
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/RequiredFieldConfiguratorUtil.java
  flow-data/src/main/java/com/vaadin/flow/data/binder/ValueContext.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/ValueContextTest.java
Labels: +0.1.0

#19493 fix: Use react useBlocker hook for navigation
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationTriggerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeUpdateIT.java
Labels: +0.0.1

#19478 chore: Upgrade Node.js to 20.14.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +1.0.0

#19469 feat: Create converters for numeric values from NumberField
  flow-data/src/main/java/com/vaadin/flow/data/converter/BigDecimalToDoubleConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/BigDecimalToFloatConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/BigDecimalToIntegerConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/BigDecimalToLongConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/DefaultConverterFactory.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/DoubleToBigDecimalConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/FloatToBigDecimalConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/FloatToDoubleConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/IntegerToBigDecimalConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/IntegerToDoubleConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/IntegerToLongConverter.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/LongToBigDecimalConverter.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/BigDecimalToDoubleConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/BigDecimalToFloatConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/BigDecimalToIntegerConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/BigDecimalToLongConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/DefaultConverterFactoryTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/DoubleToBigDecimalConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/FloatToBigDecimalConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/FloatToDoubleConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/IntegerToBigDecimalConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/IntegerToDoubleConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/IntegerToLongConverterTest.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/LongToBigDecimalConverterTest.java
Labels: +0.1.0

#19434 feat: Flow components as children for ReactAdapterComponent
  flow-client/src/main/java/com/vaadin/client/ElementUtil.java
  flow-client/src/main/java/com/vaadin/client/ReactUtils.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactAdapterComponent.java
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
  flow-server/src/main/java/com/vaadin/flow/dom/impl/BasicElementStateProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeProperties.java
  flow-tests/test-react-adapter/src/main/frontend/ReactLayout.tsx
  flow-tests/test-react-adapter/src/main/java/com/vaadin/flow/FlowInReactComponentView.java
  flow-tests/test-react-adapter/src/main/java/com/vaadin/flow/ReactLayout.java
  flow-tests/test-react-adapter/src/test/java/com/vaadin/flow/FlowInReactComponentIT.java
Labels: +0.0.1

#19422 fix: force page reload on re-sync with MPR
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
Labels: +0.0.1, target/24.3, target/24.4

#18553 feat: add raw html table and related components
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableBodyElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableCaptionElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableCellElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableFooterElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableHeaderCellElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableHeaderElement.java
  flow-html-components-testbench/src/main/java/com/vaadin/flow/component/html/testbench/NativeTableRowElement.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTable.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableBody.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableCaption.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableCell.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableFooter.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableHeader.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableHeaderCell.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableRow.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeTableRowContainer.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableBodyTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableCaptionTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableCellTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableFooterTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableHeaderCellTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableHeaderTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableRowContainerTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableRowTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableTest.java
  flow-server/src/main/java/com/vaadin/flow/component/Tag.java
Labels: +0.1.0, Contribution

#19505 fix: do not use popstate event
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes-flow.tsx
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/HistoryView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PopStateHandlerView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PostponeUpdateIT.java
Labels: +0.0.1

#19520 fix: Add usage stats for react adapter
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
Labels: +0.0.1

#19515 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.4

#19521 chore: Feature flag for smaller new Copilot features
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1, target/24.4

#19523 chore: Feature flag for smaller new Copilot features (#19521) (CP: 24.4)
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#19533 fix: add vaadin-navigated event
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
  flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
Labels: +0.0.1, target/24.4

#19537 Fix: send vaadin-navigated event
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
Labels: +0.0.1, target/24.4

#19538 Fix: send vaadin-navigated event (#19537)
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
Labels: +0.0.1, cherry pick

#19532 chore: Upgrade to Node.js 20.14.0 (CP: 24.3)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, cherry pick

#19529 chore: Upgrade Node.js to 18.20.3
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.3, target/23.4

#19539 fix: preserve navigated.current value
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/NavigationView.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/ServerView.java
  flow-tests/test-react-router/src/test/java/com/vaadin/flow/NavigationIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
Labels: +0.0.1, target/24.4

#19544 fix: Bun is bun on Windows
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.4

#19552 chore: Remove Java live reload warning
  vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
Labels: +0.0.1, target/24.4

#19489 Fix assertion error after removing a class name
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/NodeList.java
Labels: +0.0.1, Contribution

#19559 chore: upgrade to TB 9.3.0
  pom.xml
Labels: +0.0.1, target/24.4

#19431 chore: improve route registry update logics
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteTarget.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
Labels: +0.0.1

#19571 fix: require the minimum interface needed
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
Labels: +1.0.0

#19575 Change Discord -> Forum
  README.md
Labels: +0.0.1

#19545 docs: Update javadoc for Binder's binding builder methods
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1

#19577 chore: Bump Vite to 5.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.4

#19585 fix: Never warn about copilot messages
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +0.0.1, target/24.4

#19587 chore: Format
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/main/java/com/vaadin/flow/data/converter/FloatToDoubleConverter.java
  flow-data/src/test/java/com/vaadin/flow/data/converter/FloatToDoubleConverterTest.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/page/History.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/MenuRegistry.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryMenuAccessTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/HistoryView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PopStateHandlerView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +0.0.1

#19584 chore(deps): bump component.version from 24.3.13 to 24.4.2 (#19581)
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#19564 fix: improve restart with copilot
  flow-server/src/main/resources/vite.generated.ts
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadListener.java
Labels: +0.0.1, target/24.4

#19608 chore: upgrade to TB 9.3.1
  pom.xml
Labels: +0.0.1, target/24.4

#19609 chore: upgrade to TB 9.3.1 (#19608) (CP: 24.4)
  pom.xml
Labels: +0.0.1, cherry pick

#19614 fix: detect project folder for gradle kotlin projects
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/test/java/com/vaadin/flow/server/AbstractConfigurationTest.java
Labels: +0.0.1, target/24.4

#19612 chore(deps): bump component.version from 24.4.2 to 24.4.3 (#19599)
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#19600 chore: exclude commons-io to fix dependencyConvergence issue
  flow-server/pom.xml
Labels: +0.0.1, target/24.4

#19561 feat: Upgrade to TypeScript 5.5
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#19622 fix: Preserve usage stats for hot deploy mode as well
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/24.4

#19603 feat: add a common API to integrate with hotswap tools
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/main/java/com/vaadin/flow/hotswap/VaadinHotswapper.java
  flow-server/src/main/java/com/vaadin/flow/internal/ReflectionCacheHotswapper.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteRegistryHotswapper.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/main/resources/META-INF/services/com.vaadin.flow.hotswap.VaadinHotswapper
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteRegistryHotswapperTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#19624 feat!: add license check for 2.11
  flow-client/bnd.bnd
  flow-data/bnd.bnd
  flow-dnd/bnd.bnd
  flow-html-components/bnd.bnd
  flow-lit-template/bnd.bnd
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-osgi/bnd.bnd
  flow-push/bnd.bnd
  flow-server/bnd.bnd
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServlet.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletTest.java
  flow-tests/test-root-context/bnd.bnd
  flow-theme-integrations/lumo/bnd.bnd
  flow-theme-integrations/material/bnd.bnd
Labels: +1.0.0

#19632 docs: Update javadoc for ValueContext constructors
  flow-data/src/main/java/com/vaadin/flow/data/binder/ValueContext.java
Labels: +0.0.1

#19641 chore: fix commons-io dependency convergence issue (24.4)
  flow-server/pom.xml
Labels: +0.0.1

#19631 fix: handle clicks outside container
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.4

#19643 chore: fix dependency convergence issue on commons-io
  flow-server/pom.xml
Labels: +0.0.1

#19639 fix: Use @preact/signals-react-transform
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/plugins/react-function-location-plugin/react-function-location-plugin.js
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1
