Repository vaadin/flow, pull requests merged in 2024-02, with the labels that each got.

#18570 fix: Ensure navigation events are delivered when both exported web components and a normal UI is used
  flow-client/src/main/frontend/Flow.ts
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandlerTest.java
  flow-tests/test-ccdm/frontend/index.js
  flow-tests/test-ccdm/src/test/java/com/vaadin/flow/ccdmtest/IndexHtmlRequestHandlerIT.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/RouterLinkView.java
Labels: +1.0.0

#18582 chore: upgrade checker plugin
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/23.4, target/24.3

#18587 chore: Bump lit to 3.1.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, target/24.3

#18586 chore: upgrade vite-plugin-checker to 0.6.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
Labels: +0.0.1

#18588 chore: Bump react deps to latest
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#18598 test: wait for dev server
  flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/eagerbootstrap/ParameterIT.java
  flow-tests/test-eager-bootstrap/src/test/java/com/vaadin/flow/servlet/BasicViewsIT.java
Labels: +0.0.1

#18549 Adds skipDefaultValidator API
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.1.0

#18595 chore: Regenerate test package json files
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#18601 Feat: add loadComponentScript method
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#18600 chore: update testbench to 9.2.2
  pom.xml
Labels: +0.0.1

#18604 feat: create and load WebComponent
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#18603 Remove caching of AppShellConfigurator classes to fix injection
  flow-tests/test-redeployment-no-cache/src/main/java/com/vaadin/flow/uitest/ui/DevModeNoClassCacheView.java
  flow-tests/test-redeployment-no-cache/src/test/java/com/vaadin/flow/uitest/ui/DevModeNoClassCacheIT.java
  flow-tests/test-redeployment/src/main/java/com/vaadin/flow/uitest/ui/DevModeClassCacheView.java
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/Application.java
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/java/com/vaadin/flow/spring/test/DummyService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, target/24.2, target/24.3

#18590 feat: Section and IFrame implements HasAriaLabel
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Section.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/IFrameTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/SectionTest.java
Labels: +0.1.0, Contribution

#18599 feat: Make ProjectHelpers.getUserKey publicly accessible to be used in Copilot
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/ProjectHelpers.java
Labels: +1.0.0

#18615 fix: Add a lang attribute to the html tag of the browser-too-old.htnl
  flow-server/src/main/resources/com/vaadin/flow/server/browser-too-old.html
Labels: +0.0.1, target/24.3

#18621 chore: upgrade license-checker 1.12.6 (9.2)
  pom.xml
Labels: +0.0.1

#18609 feat: apply auto-detection of Hilla application
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
  flow-server/src/main/java/com/vaadin/flow/server/AbstractConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/router/RouteNotFoundErrorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/AbstractDevModeTest.java
Labels: +1.0.0

#18623 Fix regression NPE in binder
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1

#18597 feat: Use React/Lit auto-detection to add Hilla components
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/frontend/dependencies/hilla/components/lit/package.json
  flow-server/src/test/resources/com/vaadin/flow/server/frontend/dependencies/hilla/components/react/package.json
Labels: +0.0.1

#18630 fix: Catch exceptions when package.json template doesn't exist
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/resources/com/vaadin/flow/server/frontend/dependencies/hilla/components/no-deps/package.json
Labels: +0.0.1

#18631 chore: update vite-plugin-checker to 0.6.4 (24.2)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18643 fix: Spring Boot's deprecation warning
  vaadin-spring/src/main/java/com/vaadin/flow/spring/annotation/SpringComponent.java
Labels: +0.0.1, Contribution, target/24.3

#18647 chore: update license-checker to 1.12.7
  pom.xml
Labels: +0.0.1, target/23.3, target/2.10, target/24.2, target/23.4, target/24.3, target/9.2

#18653 chore: upgrade license-checker to 1.12.7 (9.2)
  pom.xml
Labels: +0.0.1

#18635 chore: change hotdeploy property to null by default
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
Labels: +0.0.1

#18657 fix!: rename default validator api
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +1.0.0

#18654 chore: Bump react dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#18661 fix: delay initial poller call
  flow-server/src/main/resources/com/vaadin/flow/server/webcomponent/webcomponent-script-template.js
Labels: +0.0.1

#18655 chore: Bump Vite to 5.1.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +1.0.0, target/24.3

#18662 fix: move @types/x to devDependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#18646 chore: Use type Import in types.d.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
Labels: +0.0.1

#18658 fix: Use class finder to load package.json templates
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeValidationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksExecutionTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPluginsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockOptions.java
Labels: +1.0.0

#18659 chore: update flow-maven-plugin goals for unified platform
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/ConvertPolymerMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FrontendDanceMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
Labels: +1.0.0

#18671 chore: upgrade testbench to 8.2.6 (23.3)
  pom.xml
Labels: +0.0.1, target/23.4

#18670 chore: upgrade testbench to 9.1.1 (24.2)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#18665 refactor!: rename enable.react.router to react.enable
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/JavaScriptNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/StateView.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#18636 feat: Add method to write only the changed properties to the bean
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
  flow-data/src/test/java/com/vaadin/flow/tests/data/bean/Person.java
Labels: +0.0.1, Contribution

#18673 fix: Do not overwrite theme set in index.html
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1

#18668 fix: Log debug connection issues as debug
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +0.0.1

#18667 fixes: upgrade vite version to 3.2.8 (23.3)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/23.4

#18550 fix: change SBOM maven goals lifecycle phase
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateMavenBOMMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
Labels: +0.0.1, Contribution

#18525 feat: add React component adapter
  flow-server/src/main/java/com/vaadin/flow/component/react/ReactAdapterComponent.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonDecodingException.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonEncodingException.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.tsx
  flow-server/src/test/java/com/vaadin/flow/component/react/ReactAdapterComponentTest.java
  flow-tests/pom.xml
  flow-tests/test-react-adapter/frontend/ReactInput.tsx
  flow-tests/test-react-adapter/pom-production.xml
  flow-tests/test-react-adapter/pom.xml
  flow-tests/test-react-adapter/src/main/java/com/vaadin/flow/ReactAdapterView.java
  flow-tests/test-react-adapter/src/main/java/com/vaadin/flow/ReactInput.java
  flow-tests/test-react-adapter/src/test/java/com/vaadin/flow/ReactAdapterIT.java
Labels: +0.1.0

#18685 test: Recreate package-lock
  flow-tests/test-frontend/test-npm/package-lock.json
Labels: +0.0.1

#18677 fix: do not run generator without hilla
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/hilla/EndpointController.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Labels: +0.0.1

#18687 chore: Fix typo in default value
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/JavaLiveReloadIT.java
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#18688 chore: improve message for customized types.d.ts update
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
Labels: +0.0.1

#18683 chore: upgrade minimum supported Gradle version to 8.4
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
Labels: +0.0.1

#18686 chore!: bump jackson.version from 2.16.0 to 2.16.1
  pom.xml
Labels: +0.0.1

#18705 test: Remove versions up to 8.3 as they fail before check
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
Labels: +0.0.1

#18706 chore: Update License file text for Commercial modules
  flow-polymer-template/LICENSE
  flow-polymer-template/LICENSE.txt
Labels: +0.0.1

#18701 fix: Possibly missing packages should not show error
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#18703 fix: Rename react.router.enable left-overs to react.enable
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1

#18708 chore: Upgrade to Node 20.11.1 security release
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.3

#18709 chore: Upgrade to Node 20.11.1 security release (24.2)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#18710 feat: Move ReactComponentAdapter to flow-react
  flow-bom/pom.xml
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-react/pom.xml
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactAdapterComponent.java
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.tsx
  flow-react/src/test/java/com/vaadin/flow/component/react/ReactAdapterComponentTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
  flow-tests/test-react-adapter/pom-production.xml
  flow-tests/test-react-adapter/pom.xml
  flow/pom.xml
  pom.xml
Labels: +1.0.0

#18698 feat: Wrap the JS snippet in async function
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java
Labels: +0.0.1, Contribution

#18712 chore: Make WebComponentExporter eligible check logging more visible for problem solving
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentExporterUtils.java
Labels: +0.0.1

#18716 chore: update webdrivermanager to 5.6.3
  pom.xml
Labels: +0.0.1

#18715 chore: Upgrade to latest Node.js 18
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/23.3

#18700 feat: Add methods for checking roles and authorities
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
Labels: +0.0.1, Contribution

#18713 chore: Upgrade to Node 20.11.1 security release (#18708) (CP: 24.3)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#18718 chore: rebuild bundle if React is disabled
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
Labels: +0.0.1

#18717 feat: Only add react-components with flow-react
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#18728 feat!: no more App.tsx
  .gitignore
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/App.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.tsx
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Labels: +0.0.1

#18731 chore: upgrade dokka version
  flow-plugins/flow-gradle-plugin/build.gradle
Labels: +0.0.1

#18714 fix: postpone serverSyncId computation after changes are applied (#16…
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
Labels: +0.0.1

#18739 fix: upgrade license-checker to 1.12.8
  pom.xml
Labels: +0.0.1, target/23.3, target/2.10, target/24.2, target/23.4, target/24.3, target/9.2

#18746 fix: upgrade license-checker to 1.12.8 (9.2)
  pom.xml
Labels: +0.0.1

#18725 chore: update GHA action to get rid Node 16 warning
  .github/workflows/validation.yml
Labels: +0.0.1

#18740 chore: fix unwanted imports
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendVersionTest.java
Labels: +0.0.1

#18738 chore: Upgrade to npm 10.2.4 (24.2)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#18726 chore: log message when requested range does not match fetched items
  flow-data/src/main/java/com/vaadin/flow/data/provider/CallbackDataProvider.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/ConfigurableFilterDataProviderWrapper.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataProviderWrapper.java
Labels: +0.0.1

#18757 chore: fix validation workflow permission
  .github/workflows/validation.yml
Labels: +0.0.1

#18754 fix: fix cache resource validation on application reload
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1

#18760 fix: run setBean validation for changed bindings only (#18735)
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
Labels: +0.0.1, target/24.2, target/24.3

#18761 chore: test new upload/download test result artifacts.
  .github/workflows/validation.yml
Labels: +0.0.1

#18690 NPM SBOM generator fixes
  .gitignore
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/resources/package-lock.json
  flow-plugins/flow-maven-plugin/src/test/resources/package.json
Labels: +0.0.1

#18759 fix: use Vite @vitejs/plugin-react also in production
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#18765 feat: Lookup for any Hilla views for auto-detection
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
Labels: +0.0.1

#18770 test: Add/fix tests for binding cross-validation
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/24.2, target/24.3

#18771 chore: Bump dependencies to latest
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18772 feat: Support top-level await
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-frontend/vite-basics/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-basics/src/test/java/com/vaadin/viteapp/BasicsIT.java
  flow-tests/test-frontend/vite-production/src/main/java/com/vaadin/viteapp/views/empty/MainView.java
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/toplevelawait-main.js
  flow-tests/test-frontend/vite-test-assets/src/main/resources/META-INF/frontend/toplevelawait-other.js
Labels: +0.0.1

#18766 fix: Add optional .js extension for Flow import
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
Labels: +0.0.1

#18776 chore: bump Testbench to 9.2.3
  pom.xml
Labels: +0.0.1

#18779 chore: upgrade testbench to 9.2.3 (24.3)
  pom.xml
Labels: +0.0.1

#18778 feat: Added single and double click event listeners registration methods
  flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ImageClickView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ImageClickIT.java
Labels: +1.0.0

#18756 feat: update gradle plugin clean tasks
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/resources/hilla-endpoint-stub.jar
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanOptions.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
Labels: +1.0.0

#18786 chore: upgrade spring.boot to 3.1.9
  pom.xml
Labels: +0.0.1

#18707 fix: include only react-components in package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Labels: +0.0.1

#18788 fix: silently update types.d.ts in Hilla projects
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/types.d.ts.hilla
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitionsTest.java
Labels: +0.0.1

#18795 fix: Use closures to store listeners and fallback to window
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#18802 test: check field validity in addition to errormsg
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderConverterValidatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#18799 chore: improve AuthenticationContext javadoc
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
Labels: +0.0.1

#18749 feat: Call copilot init feature when starting from an empty app
  flow-server/src/main/java/com/vaadin/flow/router/AbstractRouteNotFoundError.java
  flow-server/src/main/resources/com/vaadin/flow/router/NoRoutesError_dev.html
  flow-server/src/main/resources/com/vaadin/flow/router/NoRoutesError_hilla.html
Labels: +0.0.1

#18807 fix: Read Hilla version from correct file
  flow-server/src/main/java/com/vaadin/flow/server/Platform.java
  flow-server/src/test/java/com/vaadin/flow/server/PlatformTest.java
Labels: +0.0.1

#18804 chore: upgrade spring framework to 5.3.32 (23.4)
  pom.xml
  vaadin-spring/pom.xml
Labels: +0.0.1

#18801 fix: fire location-changed on popstateevent
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#18809 feat: support exclusions property in versions.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ExclusionFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Labels: +0.1.0

#18823 fix: also scan changed files for routes
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadEvent.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +1.0.0, target/24.2, target/24.3

#18829 test: add bundle validation test
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
Labels: +0.0.1

#18833 fix: unbind previous binding for the same field
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/24.2, target/24.3

#18841 fix: fix cache resource validation on reload (cp: 24.3)
  flow-tests/test-redeployment/pom.xml
  flow-tests/test-redeployment/src/test/java/com/vaadin/flow/uitest/ui/DevModeClassCacheIT.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, cherry pick

#18840 fix: remove routes.tsx when React is disabled
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FileIOUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsDefinitions.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Labels: +0.0.1
