Repository vaadin/flow, pull requests merged in 2024-07, with the labels that each got.

#19655 chore: Update the license tag in flow 2.11
  pom.xml
Labels: +0.0.1

#19646 chore: Vite 5.3.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.4

#19557 chore: Remove dev tools notification code
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-live-reload/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshLiveReloadIT.java
  vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#19660 fix: Make index.tsx HMR compatible
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index-react.tsx
Labels: +0.0.1, target/24.4

#19662 chore: upgrade to TB 9.3.2
  pom.xml
Labels: +0.0.1, target/24.4

#19663 chore: upgrade to TB 9.3.2 (24.4)
  pom.xml
Labels: +0.0.1

#19636 chore(deps): bump component.version from 24.4.3 to 24.4.4 (#19634)
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#19659 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#19667 chore: Node 20.15.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.4

#19666 fix: Pass route data through window.Vaadin.routesConfig instead of an import
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vaadin-react.tsx
Labels: +0.0.1, target/24.4

#19674 test: fix pwa nightly test
  flow-tests/test-pwa/pom.xml
Labels: +0.0.1

#19669 feat: add application identifier to build info
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
Labels: +0.0.1

#19676 fix: Check license for polymer in dev mode only
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/PolymerTemplate.java
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
Labels: +0.0.1, target/24.3, target/24.4

#19681 chore: fix GH workflow pnpm issue (24.3)
  .github/workflows/validation.yml
Labels: +0.0.1

#19684 upgrade spring boot to 3.2.7 (24.3)
  pom.xml
Labels: +0.0.1

#19683 refactor: Avoid duplicate invocations of Component:getUI
  flow-data/src/main/java/com/vaadin/flow/data/binder/ValueContext.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/AbstractComponentDataGenerator.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentUtil.java
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
Labels: +0.0.1, Contribution

#19696 test: remove static mock for Locale class
  flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
  flow-server/src/test/java/com/vaadin/flow/i18n/TranslationFileRequestHandlerTest.java
Labels: +0.0.1

#19706 fix: ignore abstract AppShellConfigurators
  flow-server/src/main/java/com/vaadin/flow/component/page/Inline.java
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
Labels: +0.0.1, target/24.3, target/23.5, target/24.4

#19716 chore: updgrade pnpm in validation workflow
  .github/workflows/validation.yml
Labels: +0.0.1

#19713 cp: ignore abstract AppShellConfigurators
  flow-server/src/main/java/com/vaadin/flow/component/page/Inline.java
  flow-server/src/main/java/com/vaadin/flow/server/PWA.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinAppShellInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/VaadinAppShellInitializerTest.java
  flow-tests/pom.xml
Labels: +0.0.1, cherry pick

#19718 fix: update browser URL on preserve on refresh navigation
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNavigationView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshNavigationIT.java
Labels: +0.0.1, target/24.3, target/24.4

#19721 chore: log class causing failure in frontend dependency scan
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
Labels: +0.0.1, target/24.3, target/24.4

#19650 feat: refresh browser using dev-tools connection
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
  vaadin-dev-server/src/main/frontend/live-reload-connection.ts
  vaadin-dev-server/src/main/frontend/vaadin-dev-tools.ts
  vaadin-dev-server/src/main/frontend/websocket-connection.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +1.0.0

#19732 chore: Delete unnecessary complexity (#17203) (CP: 23.5)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServiceClassLoaderUtil.java
Labels: +1.0.0, cherry pick

#19733 chore: Delete unnecessary complexity (#17203) (CP: 2.11)
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServiceClassLoaderUtil.java
Labels: +1.0.0, cherry pick

#19730 fix: do not block navigation to current url
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/NavigationEventsView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/NavigationEventsIT.java
Labels: +0.0.1, target/24.4
