Repository vaadin/flow, pull requests merged in 2024-01, with the labels that each got.

#18394 chore: Easier copy-paste for no import message
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/routes.tsx
Labels: +0.0.1, target/24.3

#18406 fix: Report errors when running commands to launch the IDE to open a file
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/OpenInCurrentIdeTest.java
Labels: +0.0.1, target/24.3

#18408 fix: permit access to custom PWA icons and favicon (#18385) (CP: 24.2)
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurity/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurity/Configurator.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurity/HomeView.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurity/LoginView.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/resources/META-INF/resources/custom/icons/path/fav.ico
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/resources/META-INF/resources/custom/icons/path/hey.png
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-webicons-urlmapping/src/test/java/com/vaadin/flow/spring/flowsecurity/CustomWebIconsIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/java/com/vaadin/flow/spring/flowsecurity/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/java/com/vaadin/flow/spring/flowsecurity/Configurator.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/java/com/vaadin/flow/spring/flowsecurity/HomeView.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/java/com/vaadin/flow/spring/flowsecurity/LoginView.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/resources/META-INF/resources/custom/icons/path/fav.ico
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/resources/META-INF/resources/custom/icons/path/hey.png
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-webicons/src/test/java/com/vaadin/flow/spring/flowsecurity/CustomWebIconsIT.java
  scripts/computeMatrix.js
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/WebIconsRequestMatcher.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/WebIconsRequestMatcherTest.java
Labels: +0.0.1, cherry pick

#18412 feat: Pass theme definition to bootstrap modifiers
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TypeScriptBootstrapModifier.java
Labels: +1.0.0, target/24.3

#18417 fix: limit the requested items to a given threshold
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +0.0.1, target/1.0, target/23.3, target/2.10, target/24.2, target/23.4, target/24.3, target/9.2

#18419 chore: Upgrade license-checker to 1.12.4
  pom.xml
Labels: +0.0.1, target/23.3, target/2.10, target/24.2, target/23.4, target/24.3, target/9.2

#18425 fix: limit the requested items to a given threshold (#18417)
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
Labels: +0.0.1, cherry pick

#18435 Add documentation link to proxy info messages
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
Labels: +0.0.1

#18440 chore: update license-checker to 1.12.4 (CP: 9.2)
  pom.xml
Labels: +0.0.1

#18405 fix: replace 'blacklist' and 'whitelist' with 'blocked' and 'allowed'
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-reload-time/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-white-list/src/main/resources/application.properties
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, target/23.3, target/24.2, target/23.4, target/24.3

#18402 Show link to Docs when devmode host not allowed
  vaadin-dev-server/frontend/vaadin-dev-tools.ts
Labels: +0.0.1

#18429 chore: Upgrade to Node.js 20.11.0 and npm 10.2.4
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#18456 fix: replace 'blacklist' and 'whitelist' with 'blocked' and 'allowed' (#18405) (CP: 23.4)
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-white-list/src/main/resources/application.properties
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, cherry pick

#18457 fix: replace 'blacklist' and 'whitelist' with 'blocked' and 'allowed' (#18405) (CP: 23.3)
  flow-lit-template/src/main/java/com/vaadin/flow/component/littemplate/internal/LitTemplateParserImpl.java
  flow-polymer-template/src/main/java/com/vaadin/flow/component/polymertemplate/NpmTemplateParser.java
  flow-tests/vaadin-spring-tests/test-mvc-without-endpoints/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-white-list/src/main/resources/application.properties
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, cherry pick

#18447 fix: prevent dev-tools connection to downgrade to streaming transport
  vaadin-dev-server/frontend/websocket-connection.ts
Labels: +0.0.1, target/24.3

#18462 Deprecate HtmlImport and Compatibility Mode
  flow-server/src/main/java/com/vaadin/flow/component/dependency/HtmlImport.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultDeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
Labels: +0.1.0

#18464 chore: provide default session lock strategy
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
Labels: +1.0.0

#18478 chore: fix formatting
  flow-server/src/main/java/com/vaadin/flow/component/dependency/HtmlImport.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java
Labels: +0.1.0

#18476 chore: Bump react dependencies to latest
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#18477 test: add https URLS to license test whitelist
  build-tools/src/test/java/com/vaadin/LicenseCheckTest.java
Labels: +0.1.0

#18467 fix: refresh dev-tools token on server restart
  flow-server/src/main/java/com/vaadin/flow/server/DevToolsToken.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/DevToolsTokenTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Labels: +1.0.0, target/24.3

#18475 chore: Bump Vite and rollup-plugin-visualizer
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18483 chore: Bump Vite and rollup-plugin-visualizer (CP: 24.3)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18480 test: add missing licenses to whitelist
  build-tools/src/test/java/com/vaadin/LicenseCheckTest.java
Labels: +0.1.0

#18488 chore: Upgrade to Vite 3.2.8
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18487 chore: Upgrade to Vite 5.0.12
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.3

#18496 chore: upgrade to Vite 4.5.2 (24.2)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18499 chore: Recreate package files
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#18497 chore: upgrade to vite 2.9.17 (9.2)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#18500 chore: Upgrade to vite 5.0.12 (24.3)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#18501 chore: update spring.boot to 3.1.8 (24.2)
  pom.xml
Labels: +0.0.1

#18387 feat!: Make react-router default
  .gitignore
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/function/DeploymentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateIndexTs.java
  flow-server/src/main/resources/com/vaadin/flow/server/BootstrapHandler.js
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/tests/util/MockDeploymentConfiguration.java
  flow-tests/test-ccdm-flow-navigation/pom-production.xml
  flow-tests/test-ccdm-flow-navigation/pom.xml
  flow-tests/test-ccdm/pom-production.xml
  flow-tests/test-ccdm/pom.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom-generatedTsDir.xml
  flow-tests/test-custom-frontend-directory/test-themes-custom-frontend-directory/pom.xml
  flow-tests/test-frontend/vite-pwa-production/pom.xml
  flow-tests/test-frontend/vite-pwa/pom.xml
  flow-tests/test-react-router/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/scroll/PushStateScrollView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/HistoryIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PopStateHandlerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/RouterLinkIT.java
  flow-tests/test-themes/pom-devbundle.xml
  flow-tests/test-themes/pom-production.xml
  flow-tests/test-themes/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +1.0.0

#18484 fix: Abort resource handling if dev server resource handling fails
  flow-server/src/main/java/com/vaadin/flow/server/StaticFileServer.java
Labels: +0.0.1, target/24.3

#18471 fix: fix static resource retrieval with Jetty 12
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinServletService.java
Labels: +0.0.1, target/24.3

#18437 chore: Bump commons versions
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  pom.xml
Labels: +0.0.1

#18463 fix: remove Lazy annotation from Flow security beans
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringSecurityAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringSecurityAutoConfigurationTest.java
Labels: +0.0.1, target/24.3

#18455 fix: Remove fallback middleware also after Vite restart
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/24.3

#18469 feat: Include react plugin by default so dev build gets source information
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vite.config-react-swc.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vite.config-react.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#18489 fix: propagate all request parameter to location in eagerServerLoad mode
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
Labels: +0.0.1, target/23.3, target/24.2, target/23.4, target/24.3, target/9.2

#18513 chore: remove the build tools module
  build-tools/pom.xml
  build-tools/src/test/java/com/vaadin/LicenseCheckTest.java
  pom.xml
Labels: +0.0.1

#18502 test: test executable jar with Jetty
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-jar/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-boot-jar/src/main/java/com/vaadin/flow/spring/test/TestServletInitializer.java
  flow-tests/vaadin-spring-tests/test-spring-boot-jar/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-common/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-common/src/main/java/com/vaadin/flow/spring/test/ShutdownHook.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/SmokeTestIT.java
  scripts/computeMatrix.js
Labels: +0.0.1

#18392 feat: SBOM generation
  .gitignore
  flow-plugins/flow-maven-plugin/pom.xml
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateMavenBOMMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/InvocationRequestBuilder.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/GenerateMavenBOMMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/InvocationRequestBuilderTest.java
  flow-plugins/flow-maven-plugin/src/test/resources/package-lock.json
  flow-plugins/flow-maven-plugin/src/test/resources/package.json
  pom.xml
Labels: +0.0.1, Contribution

#18527 chore: exclude commons dependency to obey enforcer-plugin
  flow-server/pom.xml
Labels: +0.0.1

#18542 fix: Pass a mutable copy of routes array into React function
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#18535 Validation fixes
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1

#18532 feat: make it possible to controll clean-frontend
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/CleanFrontendMojo.java
Labels: +0.0.1

#18546 fix: no serverSideRoutes check if no Routes
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Labels: +0.0.1

#18486 Allow moving node to another tree after removeFromTree call
  flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/StateTreeTest.java
Labels: +0.0.1, target/24.2, target/24.3

#18368 fix: consider local npm packages in bundle validation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
Labels: +0.0.1, target/24.3

#18552 Close streams fetched from data-providers
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/DataView.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicationController.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapper.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalCommunicatorDataTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchyMapperWithDataTest.java
Labels: +0.0.1, Contribution

#18559 feat: add react components to package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
Labels: +0.0.1

#18569 fix: Uncaught SyntaxError: Unexpected identifier 'RefreshRuntime'
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
Labels: +0.0.1
