Repository vaadin/flow, pull requests merged in 2025-10, with the labels that each got.

#22386 test: Update package file to resolve GitHub warnings
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/vite-context-path/package.json
Labels: +0.0.1

#22378 feat: Add bean serialization support
  flow-polymer-template/src/test/java/com/vaadin/flow/component/polymertemplate/PolymerTemplateTest.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/component/page/ExtendedClientDetails.java
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractServerHandlers.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ClientCallableHandlers.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PolymerServerEventHandlers.java
  flow-server/src/main/java/com/vaadin/flow/shared/JsonConstants.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/HistoryTest.java
  flow-server/src/test/java/com/vaadin/flow/component/page/PageTest.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementJacksonTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java
Labels: +1.0.0

#22388 test: Remove created bundle to avoid using old code
  flow-tests/test-root-context/pom.xml
Labels: +0.0.1, target/24.8, target/24.9

#22381 feat: Add bean deserialization support for executeJs return values
  flow-server/src/main/java/com/vaadin/flow/component/page/Page.java
  flow-server/src/main/java/com/vaadin/flow/component/page/PendingJavaScriptResult.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonCodec.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java
Labels: +0.0.1

#22387 chore: Claude instructions generated using /init
  CLAUDE.md
Labels: +0.0.1

#22361 feat: Modular feature flag system using Service Provider Interface
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/experimental/CoreFeatureFlagProvider.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlagProvider.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/experimental/FlowComponentsFeatureFlagProvider.java
  flow-server/src/main/java/com/vaadin/experimental/HillaFeatureFlagProvider.java
  flow-server/src/main/resources/META-INF/services/com.vaadin.experimental.FeatureFlagProvider
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
  flow-server/src/test/java/com/vaadin/experimental/TestFeatureFlagProvider.java
  flow-server/src/test/resources/META-INF/services/com.vaadin.experimental.FeatureFlagProvider
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
Labels: +1.0.0

#22397 chore: Bump frontend dependencies to latest versions
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#22398 fix: make sure request principal is available (#22368) (CP: 24.9)
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/main/java/com/vaadin/hilla/EndpointController.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/RequestUtil.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/SpringAccessPathChecker.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UserPrincipalRequestMatcherSpringAccessPathCheckerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurerTest.java
Labels: +0.0.1, cherry pick

#22403 fix: Null for primitive should not fail decode
  flow-polymer-template/src/test/java/com/vaadin/flow/server/communication/rpc/PolymerPublishedServerEventHandlerRpcHandlerTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentEventBusTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
Labels: +0.0.1

#22401 fix: check legacy frontend folder from prepare step
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
Labels: +0.0.1

#22240 feat: add ComponentEffect.bindChildren
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEffect.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java
Labels: +0.0.1

#22360 chore: bump java versions of commons-lang3 commons-io and byte-buddy in 24.8
  pom.xml
Labels: +0.0.1

#22382 test: Add tests for collection serialization
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ExecJavaScriptView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ExecJavaScriptIT.java
Labels: +0.1.0

#22056 fix: ElementRequestHandler requests are no longer blocked by Spring Security (#22055)
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
Labels: +0.0.1

#22363 fix: I18NProvider.translate return same as Component.translate
  flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
  flow-server/src/test/java/com/vaadin/flow/i18n/DefaultInstantiatorI18NTest.java
  flow-server/src/test/java/com/vaadin/flow/server/I18NProviderTest.java
Labels: +0.0.1

#22418 test: use lighter thread pool for testing
  flow-lit-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-polymer-template/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/AtmospherePushConnectionTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1

#22436 chore: update ASM to 9.9 to work with Java 26
  pom.xml
Labels: +0.0.1

#22435 fix: Update old override (#22429)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
Labels: +0.0.1, cherry pick, target/24.8

#22448 chore: migrate from formatter plugin to spotless
  .github/workflows/formatter.yml
  CLAUDE.md
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
  flow-client/src/main/java/com/vaadin/client/PolymerUtils.java
  flow-client/src/main/java/com/vaadin/client/communication/AtmospherePushConnection.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/ServerEventObject.java
  flow-client/src/main/java/com/vaadin/client/flow/binding/SimpleElementBindingStrategy.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementPropertyMap.java
  pom.xml
Labels: +0.0.1

#22450 chore: Ensure Java files end with newline
  flow-data/src/test/java/com/vaadin/flow/data/converter/DefaultConverterFactoryTest.java
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/FrontendScannerConfigTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/ReflectorTest.java
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/ParameterInfo.java
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/component/EventWithBeanData.java
  flow-server/src/test/java/com/vaadin/flow/component/page/StylesheetRemovalTest.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/AccessCheckResultTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/ClientCallableBeanSupportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/dau/DAUVaadinRequestInterceptorTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/DevBundleUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/GeneratedFilesSupportTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ProdBundleUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateSettingsFileTest.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/ExceptionLoggingView.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/ExceptionLoggingIT.java
  flow-tests/test-react-router/src/main/java/com/vaadin/flow/StateView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StyleRemovalView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StyleRemovalIT.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/routescope/ParentChildNoOwnerIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/MenuItem.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/main/java/com/vaadin/flow/spring/flowsecurity/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-standalone-routepathaccesschecker/src/test/java/com/vaadin/flow/spring/flowsecurity/MenuItem.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/LogoutView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/main/java/com/vaadin/flow/spring/flowsecurity/views/TimeoutView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/MenuItem.java
  pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadCache.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadEvent.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/ReloadListener.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandler.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurer.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/stateless/VaadinStatelessSecurityConfigurer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/i18n/DefaultI18NProviderFactoryTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/NavigationAccessControlConfigurerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/SpringAccessPathCheckerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UrlMappingSpringAccessPathCheckerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/UserPrincipalRequestMatcherSpringAccessPathCheckerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSavedRequestAwareAuthenticationSuccessHandlerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/stateless/SerializedJwtSplitCookieRepositoryTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/TestServletConfiguration.java
Labels: +0.1.0

#22444 fix: Always permit Aura and Lumo requests
  flow-server/src/main/java/com/vaadin/flow/server/HandlerHelper.java
  flow-server/src/test/java/com/vaadin/flow/server/HandlerHelperTest.java
  flow-tests/pom.xml
  flow-tests/test-lumo-theme/pom.xml
  flow-tests/test-lumo-theme/src/main/resources/META-INF/resources/@vaadin/vaadin-lumo-styles/fake-lumo.css
  flow-tests/vaadin-spring-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/src/main/java/com/vaadin/flow/spring/flowthemessecuritycontextpath/Application.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/src/main/java/com/vaadin/flow/spring/flowthemessecuritycontextpath/Configurator.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/src/main/java/com/vaadin/flow/spring/flowthemessecuritycontextpath/PublicView.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/src/main/java/com/vaadin/flow/spring/flowthemessecuritycontextpath/SecurityConfig.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-security-flow-themes-contextpath/src/test/java/com/vaadin/flow/spring/flowthemessecuritycontextpath/AppViewIT.java
  scripts/computeMatrix.js
Labels: +0.0.1
