Repository vaadin/flow, pull requests merged in 2025-04, with the labels that each got.

#21207 chore: update spring-boot to 3.4.4 (#21168)(CP:24.7)
  pom.xml
  vaadin-spring/src/test/java/com/vaadin/flow/spring/instantiator/SpringInstantiatorTest.java
Labels: +0.0.1, cherry pick

#21214 test: menu registry test in production mode
  flow-server/src/test/java/com/vaadin/flow/server/menu/MenuRegistryTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1

#21189 feat: Enable preserving partial view chain
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/PreserveOnRefresh.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/MainLayout.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/MainView.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/RootLayout.java
  flow-tests/test-misc/src/main/java/com/vaadin/flow/misc/ui/partial/SecondView.java
  flow-tests/test-misc/src/test/java/com/vaadin/flow/misc/ui/PartialMatchRefreshIT.java
  flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/MainLayout.java
  flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/MainView.java
  flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/RootLayout.java
  flow-tests/vaadin-spring-tests/test-spring-boot/src/main/java/com/vaadin/flow/spring/test/partial/SecondView.java
  flow-tests/vaadin-spring-tests/test-spring-boot/src/test/java/com/vaadin/flow/spring/test/partial/PartialMatchRefreshIT.java
Labels: +0.1.0

#21218 test: wait for condition instead of fixed delay
  pom.xml
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1

#21224 fix: add native hint for feature flags file
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: +0.0.1, target/24.6, target/24.7

#21216 fix: prevent resending message when request is in progress
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-client/src/main/java/com/vaadin/client/communication/ReconnectionAttemptEvent.java
  flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/SlowResponseView.java
  flow-tests/test-client-queue/src/test/java/com/vaadin/flow/misc/ui/SlowResponseIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/faulttolerance/NetworkInterruptionIT.java
Labels: +0.0.1, target/24.7

#21219 fix: extra delay on full page reload
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/ServerRpcHandlerTest.java
Labels: +0.0.1

#21222 chore: update test modules weights
  .github/workflows/validation.yml
  scripts/computeMatrix.js
Labels: +0.0.1

#21231 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.7

#21239 feat: add feature flag for Master Detail Layout
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1, target/24.7

#21238 chore: Bump frontend dependencies (#21231)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, cherry pick

#21250 fix: reduce concurrent PWA icons generation tasks
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
Labels: +0.0.1

#21249 revert: chore(deps): bump io.smallrye:jandex-maven-plugin from 3.2.7 to 3.3.0 (#21247)
  flow-jandex/pom.xml
Labels: +0.0.1

#21263 feat: backport of PWA icon image lazy generation (23.5)
  flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
Labels: +0.0.1

#21262 feat: backport of PWA icon image lazy generation (2.11)
  flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
Labels: +0.0.1

#21252 chore: add toString method to PushMessage
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
Labels: +0.0.1

#21269 chore: Use Ubuntu 24.04
  .github/workflows/validation.yml
Labels: +0.0.1

#21236 refactor(server): add getNpmPackageExecutable tool
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/AbstractDevServerRunner.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ViteHandler.java
Labels: +0.0.1

#21257 chore: Replace old trac issue number with link to correct ticket
  flow-client/src/main/java/com/vaadin/client/communication/DefaultConnectionStateHandler.java
Labels: +0.0.1, Contribution

#21274 fix: force page reload only for redefined classes
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Labels: +0.0.1

#21251 feat: scan Maven "provided" scoped dependencies
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Reflector.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/ReflectorTest.java
Labels: +0.0.1

#21276 fix(flow-server): enable top-level await for dependencies
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateVite.java
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateViteTest.java
Labels: hilla, +0.0.1

#21279 feat: backport of PWA icons generation at build time (2.11)
  flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaIcon.java
  flow-server/src/main/java/com/vaadin/flow/server/PwaRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIcons.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DevModeInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGeneratePWAIconsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeClassFinderTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#21281 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21277 fix: prevent serialization to leak CurrentInstances
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java
Labels: +0.0.1, target/24.6, target/24.7

#21285 chore: upgrade javaparser-core to 3.26.4
  pom.xml
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1

#21295 test: wait for condition instead of fixed delay (#21218) (CP: 24.6)
  pom.xml
  vaadin-dev-server/pom.xml
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1, cherry pick

#21296 chore: bump vite to 6.2.6 (24.7)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21304 Exclude trees without changes from the result collector
  signals/src/main/java/com/vaadin/signals/impl/StagedTransaction.java
  signals/src/test/java/com/vaadin/signals/impl/StagedTransactionTest.java
Labels: +0.0.1

#21228 feat: add ElementRequestHandler
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-server/src/main/java/com/vaadin/flow/server/ElementRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/StreamResourceRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/StreamResourceRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
Labels: +0.1.0

#21306 chore: TestBench 9.4.0.alpha1
  pom.xml
Labels: +0.0.1

#21307 chore: TestBench 9.3.11
  pom.xml
Labels: +0.0.1, target/24.6

#21301 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21312 chore: Vite 6.3.2
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21318 chore: add 23.6 branch to GHA branch collection
  .github/workflows/validation.yml
Labels: +1.0.0

#21321 chore: exclude commons-io from com.vaadin:open dependency
  vaadin-dev-server/pom.xml
Labels: +0.0.1

#21314 fix: prevent resynchronization loop
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/internal/StateTree.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/AppConfig.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/ResyncLoopView.java
  flow-tests/test-client-queue/src/test/java/com/vaadin/flow/misc/ui/ResyncLoopIT.java
Labels: +0.0.1, target/24.7

#21327 chore: Update Node.js and pnpm in the GH workflow
  .github/workflows/validation.yml
Labels: +0.0.1

#21322 chore!: Upgrade default Node.js to 22 and supported to 20 (2.12)
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.1.0

#21332 chore: update component version to 24.7.2 (#21297)
  flow-tests/test-frontend/vite-production/src/test/java/com/vaadin/viteapp/ProductionBasicsIT.java
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#21320 chore!: Upgrade default Node.js to 22 and supported to 20 (23.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/FrontendStubs.java
Labels: +0.0.1

#21333 fix: detect parameter type from parameterized interface
  flow-server/src/main/java/com/vaadin/flow/router/ParameterDeserializer.java
  flow-server/src/test/java/com/vaadin/flow/router/ParameterDeserializerTest.java
Labels: +0.0.1

#21330 fix(flow-server): enable top-level await for service worker
  flow-server/src/main/resources/vite.generated.ts
Labels: hilla, +0.0.1

#21336 chore: Node 22.15.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#21096 feat: update plugin id in order to publish flow-gradle-plugin separately
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/AbstractGradleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/TestUtils.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/ClasspathFilter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/FlowPlugin.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/FrontendTools.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendOutputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinConvertPolymerTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
  flow-plugins/flow-gradle-plugin/src/test/kotlin/com/vaadin/gradle/ClasspathFilterTest.kt
  flow-plugins/flow-gradle-plugin/src/test/kotlin/com/vaadin/gradle/GlobMatcherTest.kt
  flow-plugins/flow-gradle-plugin/src/test/kotlin/com/vaadin/gradle/ModuleIdentifierPredicateTest.kt
Labels: +0.0.1

#21308 Delegate to the outer transaction after starting a commit
  signals/src/main/java/com/vaadin/signals/impl/StagedTransaction.java
  signals/src/test/java/com/vaadin/signals/impl/ComputedSignalTest.java
  signals/src/test/java/com/vaadin/signals/impl/StagedTransactionTest.java
Labels: +0.0.1

#21246 feat: add DownloadHandler
  flow-server/src/main/java/com/vaadin/flow/server/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DownloadRequest.java
  flow-server/src/main/java/com/vaadin/flow/server/StreamResourceRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DownloadHandlerView.java
  flow-tests/test-root-context/src/main/resources/com/vaadin/flow/uitest/ui/class-file.json
  flow-tests/test-root-context/src/main/resources/download.json
  flow-tests/test-root-context/src/main/webapp/WEB-INF/servlet.json
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DownloadHandlerIT.java
Labels: +0.1.0

#21311 feat(router): add custom detail object to client views
  flow-server/src/main/java/com/vaadin/flow/internal/menu/MenuRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/menu/AvailableViewInfo.java
  flow-server/src/test/java/com/vaadin/flow/router/DefaultRouteResolverTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/JarContentsManagerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/menu/AvailableViewInfoTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/springnative/VaadinHintsRegistrar.java
Labels: hilla, +0.1.0

#21340 fix: make DownloadRequest a record
  flow-server/src/main/java/com/vaadin/flow/server/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/DownloadRequest.java
Labels: +1.0.0

#21346 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#21339 chore: update the GHA workflow
  .github/workflows/validation.yml
Labels: +0.0.1

#21350 chore: extract global variable in workflow
  .github/workflows/validation.yml
Labels: +0.0.1

#21342 fix: Do not starve the common ForkJoinPool with blocking listener tasks
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
Labels: +0.0.1, target/24.7

#21338 feat: add download handler to html components
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlObjectTest.java
Labels: +1.0.0

#21347 chore: Bump frontend dependencies (24.7)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#21360 feat: Upgrade webpack to version 5 (23.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingVite.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateWebpack.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/webpack/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/tsconfig.json
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-copy.js
  flow-server/src/main/resources/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js
  flow-server/src/main/resources/plugins/theme-loader/theme-loader.js
  flow-server/src/main/resources/webpack.config.js
  flow-server/src/main/resources/webpack.generated.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfigTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskNotifyWebpackConfExistenceWhileUsingViteTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateWebpackTest.java
Labels: +0.0.1

#21365 fix: prevent file watcher threads from slowing down JVM shutdown
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevModeHandlerManagerImpl.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/NamedDaemonThreadFactory.java
Labels: +0.0.1, target/24.6, target/24.7

#21372 fix: prevent file watcher threads from slowing down JVM shutdown (#21365) (CP: 24.6)
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/FileWatcher.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/NamedDaemonThreadFactory.java
Labels: +0.0.1, cherry pick
