Repository vaadin/flow, pull requests merged in 2025-02, with the labels that each got.

#20933 feat: Add setSrc(AbstractStreamResource)
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/IFrameView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/IFrameIT.java
Labels: +0.0.1, Contribution

#20567 feat: execute Hilla tasks whenever Hilla is available
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Labels: +0.0.1

#20943 fix: add viewport-fix=cover to index.html as well
  flow-server/src/main/resources/com/vaadin/flow/server/default-offline-page.html
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
Labels: +0.0.1, target/24.6

#20947 fix: postpone frontend bootstrap file generation
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
Labels: +0.0.1

#20949 chore: Improve performance by using HashSet
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1, Contribution, target/24.5, target/24.6

#20952 chore: make GHA work again on 23.5 branch
  .github/workflows/validation.yml
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  flow-tests/pom.xml
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
  pom.xml
Labels: +0.0.1

#20951 test: run npm production tests before development mode (23.5)
  flow-tests/test-frontend/pom.xml
Labels: +0.0.1

#20970 chore: upgrade license-checker to 1.13.4 (#20964)(CP: 24.5)
  pom.xml
Labels: +0.0.1, cherry pick

#20971 chore: upgrade license-checker to 1.13.4 (#20964)(CP: 23.5)
  pom.xml
Labels: +0.0.1, cherry pick

#20972 chore: upgrade license-checker to 1.13.4 (#20964)(CP: 2.11)
  pom.xml
Labels: +0.0.1, cherry pick

#20948 feat: Add jackson utils and codec
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonCodec.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonCodecTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.0.1

#20979 chore: Node 22.14.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#20978 chore: improve class scanning filter
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
Labels: +0.0.1, target/24.5, target/24.6

#20987 chore: Vite 6.1.0
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#20973 feat: update fronted to use Jackson
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CssBundler.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ExclusionFilter.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendPluginsUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/GenerateMainImports.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGeneratePackageJson.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateTsConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPlugins.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskPrepareProdBundle.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdatePackages.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/ThemeValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonConverter.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/VersionsJsonFilter.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractNodeUpdatePackagesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/CssBundlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesNpmVersionLockingTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPluginsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunNpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdatePackagesNpmTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ThemeValidationUtilTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonConverterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/VersionsJsonFilterTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ThemeLiveUpdater.java
Labels: +1.0.0

#20993 fix: Format package.json
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
Labels: +0.0.1

#20876 feat: Add signal commands
  signals/pom.xml
  signals/src/main/java/com/vaadin/signals/Id.java
  signals/src/main/java/com/vaadin/signals/ListSignal.java
  signals/src/main/java/com/vaadin/signals/Node.java
  signals/src/main/java/com/vaadin/signals/SignalCommand.java
  signals/src/main/java/com/vaadin/signals/dummy
  signals/src/main/java/com/vaadin/signals/impl/CommandResult.java
  signals/src/main/java/com/vaadin/signals/impl/MutableTreeRevision.java
  signals/src/main/java/com/vaadin/signals/impl/Snapshot.java
  signals/src/main/java/com/vaadin/signals/impl/TreeRevision.java
  signals/src/test/java/com/vaadin/signals/IdTest.java
  signals/src/test/java/com/vaadin/signals/dummy
  signals/src/test/java/com/vaadin/signals/impl/CommandResultTest.java
  signals/src/test/java/com/vaadin/signals/impl/MutableTreeRevisionTest.java
  signals/src/test/java/com/vaadin/signals/impl/SnapshotTest.java
  signals/src/test/java/com/vaadin/signals/impl/TreeRevisionTest.java
Labels: +0.0.1

#20984 !Revert "feat: Add interfaces for CRUD services (#20743)"
  vaadin-spring/pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CrudService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/FormService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/GetService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/AndFilter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/Filter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/OrFilter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/package-info.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/JpaFilterConverter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/package-info.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/package-info.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/TestApplication.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/filter/FilterTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryServiceJpaTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryServiceTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/NestedObject.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/SecondLevelNestedObject.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestCrudRepositoryService.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestEnum.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestObject.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestRepository.java
Labels: +1.0.0

#21002 chore: Provide info about server hidden elements in dev mode
  flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java
Labels: +0.0.1

#21005 fix: Output file JSON without a leading space before colon
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java
Labels: +0.0.1

#21011 chore: Vite 6.1.1
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21015 chore: Bump React 19 types
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
Labels: +0.0.1

#21020 chore: bump frontend dependencies (24.5)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21019 chore: upgrade springboot to 3.3.9 (24.5)
  pom.xml
Labels: +0.0.1

#21018 chore: Upgrade to Node.js 18.20.7
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#21034 chore: upgrade testbench 9.3.10 (24.5)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#21035 chore: upgrade testbench 9.3.10 (24.6)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#21028 chore: Log used IDE
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/OpenInCurrentIde.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
Labels: +0.0.1, target/24.5, target/24.6

#21009 feat: improved endpoint detection
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/TestEndpointGeneratorTaskFactory.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/hilla/EndpointRequestUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/BundleValidationUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/EndpointGeneratorTaskFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeTasksHillaTest.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DevModeEndpointTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/TestEndpointGeneratorTaskFactory.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeClassFinderTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringBootAutoConfiguration.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/VaadinServletContextInitializerTest.java
Labels: +0.1.0

#21043 Revert "chore: update spring-boot to 3.4.3 (#21023) (#21027)"
  pom.xml
Labels: +1.0.0, target/24.6

#21044 chore: Vite 6.2.0
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21022 feat: add support for Gradle configuration cache
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/FrontendTools.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendOutputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinCleanTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinConvertPolymerTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPlugin.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinPrepareFrontendTask.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinUtils.kt
Labels: +0.0.1

#21063 chore: remove unused feature flags files
  flow-tests/test-express-build/test-dev-bundle/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-root-context/src/main/resources/vaadin-featureflags.properties
  flow-tests/test-webpush/src/main/resources/vaadin-featureflags.properties
Labels: +0.0.1
