Repository vaadin/flow, pull requests merged in 2025-06, with the labels that each got.

#21571 test: fix test assertion
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#21538 fix: UI available from event in upoad handling.
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
Labels: +0.0.1, target/24.8

#21536 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
Labels: +0.0.1, target/24.8

#21590 fix!: Use long for content length in DownloadResponse
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
Labels: +1.0.0, target/24.8

#21570 fix: Update beanstore ui if changed
  vaadin-spring/src/main/java/com/vaadin/flow/spring/scopes/VaadinRouteScope.java
Labels: +0.0.1, target/24.7, target/24.8

#21591 chore: upgrade testbench to 9.4.0.rc1
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/DownloadHandlerIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/StreamResourceIT.java
  pom.xml
Labels: +1.0.0, target/24.8

#21615 fix: prevent route collision check before dev server is started
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/RouteUtilTest.java
Labels: +0.0.1, target/24.8

#21610 chore!: Declare IOException in download/upload callbacks
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileUploadCallback.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadCallback.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadCallback.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TemporaryFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
Labels: +1.0.0, target/24.8

#21624 feat: add method for `download`
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +0.0.1, target/24.8

#21631 chore: skip test modules when publishing (2.12)
  pom.xml
Labels: +0.0.1

#21634 chore: upgrade tb to 8.3.0 (23.6)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/PreserveOnRefreshIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/StreamResourceIT.java
  flow-tests/vaadin-spring-tests/test-spring-common/src/test/java/com/vaadin/flow/spring/test/StreamResourceIT.java
  pom.xml
Labels: +0.0.1

#21655 chore: downgrade vite-plugin-checker to support node 20 (23.6)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21653 fix: Allow observing other nodes from an observer
  signals/src/main/java/com/vaadin/signals/impl/SignalTree.java
  signals/src/test/java/com/vaadin/signals/impl/EffectTest.java
  signals/src/test/java/com/vaadin/signals/impl/SynchronousSignalTreeTest.java
Labels: +0.0.1, target/24.8

#21663 revert: Revert "feat: Make current user available without an AuthenticationContext instance (#21503)"
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
Labels: +1.0.0, target/24.8

#21698 chore: TestBench 9.4.0
  pom.xml
Labels: +0.0.1

#21697 doc: Add locale to the example in javadoc
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEffect.java
Labels: +0.0.1, target/24.8

#21686 fix: Use handlers registered using ResourceHandlerRegistry
  flow-tests/vaadin-spring-tests/test-spring-boot-contextpath/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-jar/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-only-prepare/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-reverseproxy/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot-scan/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-boot/src/main/resources/application.properties
  flow-tests/vaadin-spring-tests/test-spring-war/src/main/resources/application.properties
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletConfiguration.java
Labels: +1.0.0

#21709 chore: use constructor.newinstance
  flow-data/src/test/java/com/vaadin/flow/data/binder/Jsr303Test.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/NotEmptyTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ComponentTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/InputTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/NativeTableTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/RangeInputTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/JsonSerializer.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FullDependenciesScanner.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/ThemeWrapper.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/ClassLoaderAwareServletContainerInitializer.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-tests/test-frontend/test-bun/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
  flow-tests/test-frontend/test-npm/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
  flow-tests/test-frontend/test-pnpm/src/main/java/com/vaadin/flow/mixedtest/ui/MissingDependenciesView.java
  flow-tests/test-frontend/vite-test-assets/src/main/java/com/vaadin/viteapp/views/template/TemplateView.java
  flow-tests/test-npm-only-features/test-npm-bytecode-scanning/src/main/java/com/vaadin/flow/testnpmonlyfeatures/bytecodescanning/ByteCodeScanningView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/ui/SerializationTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/ui/ToStringTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerClassLoaderTest.java
Labels: +0.0.1

#21716 chore: replace commons-fileupload2-jakarta with commons-fileupload2-jakarta-servlet6 (#21711) (CP:24.7)
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Labels: +1.0.0

#21717 chore: replace commons-fileupload2-jakarta with commons-fileupload2-jakarta-servlet6 (#21711) (CP:24.6)
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamReceiverHandlerTest.java
Labels: +1.0.0

#21725 fix: Update Query getPageSize to check for offset
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/DataCommunicatorTest.java
Labels: +0.0.1, target/24.6, target/24.7, target/24.8

#21737 chore: upgrade springboot to 3.4.7 (24.7)
  pom.xml
Labels: +0.0.1

#21736 chore: upgrade springboot to 3.5.3 (24.8)
  pom.xml
Labels: +0.0.1

#21742 chore: Node 22.16.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.7

#21766 chore: Node 22.17.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.7, target/24.8

#21773 test: trigger application reload after client side benchmark is started
  flow-tests/vaadin-spring-tests/test-spring-boot-multimodule-reload-time/ui/src/main/java/com/vaadin/flow/spring/test/SpringDevToolsReloadUtils.java
Labels: +0.0.1, target/24.7, target/24.8, target/24.9

#21739 fix: Avoid NPE when tracking usage for removed nodes
  signals/src/main/java/com/vaadin/signals/Signal.java
  signals/src/main/java/com/vaadin/signals/impl/UsageTracker.java
  signals/src/test/java/com/vaadin/signals/ValueSignalTest.java
Labels: +0.0.1, target/24.8, target/24.9

#21738 Disallow update operation in readonly transactions
  signals/src/main/java/com/vaadin/signals/ValueSignal.java
  signals/src/test/java/com/vaadin/signals/ValueSignalTest.java
Labels: +0.0.1, target/24.8, target/24.9

#21793 fix: Distinguish between missing node and node with null value
  signals/src/main/java/com/vaadin/signals/Signal.java
  signals/src/test/java/com/vaadin/signals/impl/EffectTest.java
Labels: +0.0.1, target/24.8, target/24.9
