Repository vaadin/flow, pull requests merged in 2025-01, with the labels that each got.

#20791 chore: Bump react router
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#20787 chore: log all flow-build-info.json locations
  flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
Labels: +0.0.1

#20785 fix: parse bot user agents
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
Labels: +0.0.1, target/24.6

#20798 chore: Bump preact signals
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#20786 chore: apply sonarqube suggestions
  flow-client/src/test-gwt/java/com/vaadin/client/flow/GwtEventHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JsonUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendUtilsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
  flow-server/src/test/java/com/vaadin/flow/shared/BrowserDetailsTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
Labels: +0.0.1

#20777 chore: refactor navigation state renderer
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
Labels: +0.0.1

#20771 fix: ReactRouterOutlet interferes with layout
  flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
Labels: +0.0.1

#20804 chore: Use custom react transform in development mode
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateReactFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/jsx-dev-transform/index.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/jsx-dev-transform/jsx-dev-runtime.ts
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/jsx-dev-transform/jsx-runtime.ts
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateReactFilesTest.java
Labels: +0.0.1

#20812 chore: Node 22.13.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#20817 chore: TypeScript 5.7.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, target/24.6

#20823 chore: TypeScript 5.7.3 (#20817) (CP: 24.6)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1, cherry pick

#20821 fix: validate downloaded node
  flow-server/src/main/java/com/vaadin/flow/internal/MessageDigestUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/NodeInstaller.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/ProxyConfig.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/VerificationException.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendToolsTest.java
Labels: +0.1.0

#20820 feat: add support for OAuth2 logout configuration
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/VaadinWebSecurity.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
Labels: +0.0.1

#20743 feat: Add interfaces for CRUD services
  vaadin-spring/pom.xml
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CrudService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/FormService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/GetService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/AndFilter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/Filter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/OrFilter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/PropertyStringFilter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/filter/package-info.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/JpaFilterConverter.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/ListRepositoryService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/PropertyStringFilterSpecification.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/jpa/package-info.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/package-info.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/SpringClassesSerializableTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/TestApplication.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/filter/FilterTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryServiceJpaTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/CrudRepositoryServiceTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/NestedObject.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/SecondLevelNestedObject.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestCrudRepositoryService.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestEnum.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestObject.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/data/jpa/TestRepository.java
Labels: +0.1.0

#20749 feat: queue message payloads
  flow-client/src/main/java/com/vaadin/client/communication/MessageHandler.java
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-client/src/main/java/com/vaadin/client/communication/RequestResponseTracker.java
  flow-client/src/test/frontend/FlowTests.ts
  flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java
  flow-tests/pom.xml
  flow-tests/test-client-queue/pom.xml
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomService.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomServlet.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/CustomUidlRequestHandler.java
  flow-tests/test-client-queue/src/main/java/com/vaadin/flow/misc/ui/TestNoResponseView.java
  flow-tests/test-client-queue/src/test/java/com/vaadin/flow/misc/ui/NoResponseIT.java
Labels: +0.0.1

#20840 fix: Store the exception and not an array with the exception for uncaught promise exceptions
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1, target/24.6

#20851 chore: update component version to 24.6.2 (#20839)
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#20852 chore: Update browser details parse log output
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
Labels: +0.0.1

#20847 fix: make route config errors more prominent
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteSegment.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/RouteUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/DefaultErrorHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/VaadinServletContextStartupInitializer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/AbstractRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/ConfigureRoutesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/SessionRouteRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/RouteRegistryInitializerTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java
Labels: +0.0.1

#20856 chore: Bump more flow-client deps
  flow-client/package-lock.json
  flow-client/package.json
Labels: +0.0.1

#20855 fix: fix setReadonly when using binder with records
  flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
  flow-data/src/test/java/com/vaadin/flow/data/binder/BinderTest.java
Labels: +0.0.1, target/24.5, target/24.6

#20770 fix(flow-react): avoid Flow-React portal outlet removal conflicts
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1, target/24.6

#20860 fix(server): use Math.random instead of nanoid
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#20862 fix(flow-react): avoid Flow-React portal outlet removal conflicts (#20770) (CP: 24.6)
  flow-react/src/main/resources/com/vaadin/flow/server/frontend/ReactAdapter.template
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
Labels: +0.0.1

#20867 chore: Add convenience list and count without Filter
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
Labels: +0.1.0

#20866 chore: Bump more flow-client deps
  flow-client/package-lock.json
  flow-client/package.json
Labels: +0.0.1

#20863 chore: update Readme about branch schema
  README.md
Labels: +0.0.1

#20874 feat: DisabledUpdateMode for ShortcutRegistration
  flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java
  flow-server/src/test/java/com/vaadin/flow/component/ShortcutRegistrationTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ShortcutsView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ShortcutsIT.java
Labels: +0.0.1

#20877 Revert "fix: Store the exception and not an array with the exception for uncaught promise exceptions"
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
Labels: +0.0.1, target/24.6

#20879 Revert "chore: Add convenience list and count without Filter"
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/CountService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/data/ListService.java
Labels: +1.0.0

#20845 feat: add accessibleDisabledButtons feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#20848 fix: trigger refresh from client on hotswap with PUSH
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Labels: +0.0.1

#20900 fix: support bun 1.2 lock file
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateImports.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/FileTestUtil.java
  flow-tests/test-frontend/test-bun/src/test/java/com/vaadin/flow/mixedtest/ui/BunUsedIT.java
Labels: +0.0.1

#20888 chore: Node 22.13.1
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1, target/24.6

#20889 chore: Node 20.18.2
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#20890 chore: Node 18.20.6
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#20904 test: fix redirect after logout test
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AppViewIT.java
Labels: +0.0.1, target/24.5, target/24.6

#20884 chore: Fix flow-server tests to work on Windows
  flow-server/src/test/java/com/vaadin/flow/server/StaticFileServerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DevModeInitializerTest.java
Labels: +0.0.1, Contribution

#20901 chore: upgrade springboot to 3.3.8 (24.5)
  pom.xml
Labels: +0.0.1

#20894 refactor: use Vite official API for building sw.js
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1

#20799 chore: Vite 6.0.11
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.6

#20914 test: fix URLStreamHandlerFactory reset for Java 17 (2.11)
  pom.xml
Labels: +0.0.1

#20909 fix: build service worker without writing it to FS
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, target/24.5, target/24.6

#20916 refactor: use Vite official API for building sw.js (#20894) (CP: 24.5)
  flow-server/src/main/resources/vite.generated.ts
  flow-tests/test-pwa/src/test/java/com/vaadin/flow/pwatest/ui/PwaTestIT.java
Labels: +0.0.1, cherry pick

#20918 fix: build service worker without writing it to FS (#20909) (CP: 24.5)
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1, cherry pick

#20921 fix: fix UI refresh event name
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
Labels: +0.0.1, target/24.5, target/24.6

#20920 chore: Vite 6.0.11 (#20799) (CP: 24.5)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, cherry pick

#20935 chore: Bump react router
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#20936 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#20937 chore: Bump react 19 types
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
Labels: +0.0.1

#20930 feat: add feature flag for layout improvements
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.0.1

#20929 feat: mark full size components with data attribute
  flow-server/src/main/java/com/vaadin/flow/component/HasSize.java
  flow-server/src/main/java/com/vaadin/flow/server/Constants.java
  flow-server/src/test/java/com/vaadin/flow/component/HasSizeTest.java
Labels: +0.0.1
