Repository vaadin/flow, pull requests merged in 2025-05, with the labels that each got.

#21381 chore: upgrade vaadin-parent to 2.2.2
  pom.xml
Labels: +0.0.1, target/24.7

#21374 fix: check for module.forHMROnly before assignment
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vaadin-react.tsx
Labels: hilla, +0.0.1, target/24.7

#21382 chore: vite 6.3.4
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.7

#21393 fix: elementrequesthandler node state handling
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
Labels: +0.0.1

#21399 chore: use github variable for concurrency group
  .github/workflows/validation.yml
Labels: +1.0.0

#21398 fix: Preserve handler type when chaining listener methods
  flow-server/src/main/java/com/vaadin/flow/server/TransferProgressListener.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
Labels: +1.0.0

#21395 chore: TestBench 8.3.0.alpha1
  pom.xml
Labels: +0.0.1

#21400 feat: add factory method for UploadHandler
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TemporaryFileFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TemporaryFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadMetadata.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
Labels: +0.1.0

#21409 test: Add tests for TransferProgressListener in upload case
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/UploadTransferProgressTest.java
Labels: +1.0.0

#21408 refactor!: Renamings in new handlers API
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlComponentSmokeTest.java
  flow-server/src/main/java/com/vaadin/flow/server/StreamResourceRegistry.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ElementRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferContext.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/StreamResourceRegistryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DownloadHandlerView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/StreamResourceView.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/TransferProgressListenerView.java
Labels: +1.0.0

#21419 chore: fix javadoc links after refactor
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
Labels: +0.0.1

#21418 chore: deprecate StreamResource api
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
  flow-server/src/main/java/com/vaadin/flow/server/StreamReceiver.java
  flow-server/src/main/java/com/vaadin/flow/server/StreamResource.java
  flow-server/src/main/java/com/vaadin/flow/server/StreamVariable.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
Labels: +0.1.0

#21407 chore: update test package jsons.
  flow-tests/test-frontend/test-npm/package-lock.json
  flow-tests/test-frontend/vite-basics/package.json
  flow-tests/test-frontend/vite-context-path/package.json
  flow-tests/test-frontend/vite-production/package.json
Labels: +0.0.1

#21428 chore: upgrade to TB 9.3.12 (24.7)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1, target/24.6

#21429 chore: upgrade to TB 9.3.12 (24.6)
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#21427 fix: Check DisabledUpdateMode and isVisible in element request validation
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
Labels: +0.0.1

#21425 Update read revision before applying changes
  signals/src/main/java/com/vaadin/signals/impl/Transaction.java
  signals/src/test/java/com/vaadin/signals/impl/TransactionTest.java
Labels: +0.0.1

#21430 chore: Bump node
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#21431 chore: Bump node (24.7)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#21432 chore: Bump node (24.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#21433 chore: Bump node (23.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +0.0.1

#21424 feat: Make an Executor available through VaadinService
  flow-server/src/main/java/com/vaadin/flow/server/ServiceInitEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java
  vaadin-spring/src/main/java/com/vaadin/flow/spring/annotation/VaadinTaskExecutor.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringVaadinServiceExecutorTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/service/TestServletConfiguration.java
Labels: +0.1.0

#21435 test: disable selenium-devtools workaround (24.6)
  flow-tests/pom.xml
Labels: +0.0.1

#21437 fix: Do not lock the session while transferring content
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
Labels: +1.0.0, upload and download

#21444 chore: expand only one variable in Concurrency Group
  .github/workflows/validation.yml
Labels: +0.0.1

#21443 fix: Make addTransferProgressListener protected
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
Labels: +1.0.0

#21445 feat!: add setContentLengthLong to VaadinResponse
  flow-server/src/main/java/com/vaadin/flow/server/VaadinResponse.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
Labels: +1.0.0

#21447 fix: Update JavaDoc to be more descriptive
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
Labels: +0.0.1

#21442 chore: upgrade vaadin-parent to 3.0.0
  pom.xml
Labels: +0.0.1, target/1.0, target/23.5, target/2.11, target/24.6, target/24.7, target/23.6, target/2.12

#21440 fix: read PageTitle annotation from application-defined class
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/JavaScriptBootstrapUITest.java
Labels: +0.0.1

#21454 chore: upgrade vaadin-parent to 3.0.0 (2.12)
  pom.xml
Labels: +0.0.1

#21455 chore: upgrade vaadin-parent to 3.0.0 (2.11)
  pom.xml
Labels: +0.0.1

#21446 chore: upgrade to TB 9.4.0.alpha2
  flow-test-util/src/main/java/com/vaadin/flow/testutil/DevToolsWrapper.java
  pom.xml
Labels: +0.0.1

#21453 chore: upgrade vaadin-parent to 3.0.0 (23.5)
  pom.xml
Labels: +0.0.1

#21439 fix: Add IOException to handlers signature
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ElementRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
Labels: +0.1.0

#21452 chore: upgrade vaadin-parent to 3.0.0 (23.6)
  pom.xml
Labels: +0.0.1

#21438 fix!: Add setter helpers to DownloadEvent and new method for inline
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ClassDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/FileDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandlerTest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/DownloadHandlerView.java
Labels: +1.0.0

#21462 fix: rename allowInert for ElementRequestHandler
  flow-server/src/main/java/com/vaadin/flow/server/communication/StreamRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ElementRequestHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/StreamRequestHandlerTest.java
Labels: +1.0.0

#21459 fix: Remove faulty method
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadMetadata.java
Labels: +1.0.0

#21458 fix: call successhandler from access block
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UploadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/UploadTransferProgressTest.java
Labels: +1.0.0

#21456 fix: Inline download in data html elements
  flow-html-components/src/main/java/com/vaadin/flow/component/html/HtmlObject.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/IFrame.java
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Image.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/HtmlObjectTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/IFrameTest.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/ImageTest.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
Labels: +1.0.0

#21461 fix: Improve javadoc and handle unknown content length as -1
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferContext.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java
Labels: +0.0.1

#21463 fix: Do not set Content-Disposition for null file name
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadResponse.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/DownloadEventTest.java
Labels: +0.0.1

#21465 feat: Add overloads with TransferContext
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
Labels: +0.0.1

#21471 chore: Allow sending any object to dev tools
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsInterface.java
Labels: +0.0.1

#21476 fix: Handle downloads where the server does not provide content-length
  flow-server/src/main/java/com/vaadin/flow/server/frontend/installer/DefaultFileDownloader.java
Labels: +0.0.1

#21488 fix: remove name/fileName from inputStreamDownload
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/InputStreamDownloadHandlerTest.java
Labels: +1.0.0

#21469 chore: Bump frontend dependencies (patch+minor versions)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/webpack/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#21467 chore: Update byte-buddy version
  pom.xml
Labels: +0.0.1

#21502 chore: upgrade springboot to 3.4.6 (24.7)
  pom.xml
Labels: +0.0.1, target/24.6

#21494 doc: Add more javadoc to handlers
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
Labels: +0.0.1

#21457 feat: Add a shortcut to get DeploymentConfiguration from UIInternals
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/test/java/com/vaadin/flow/component/internal/UIInternalsTest.java
Labels: +0.0.1, Contribution

#21503 feat: Make current user available without an AuthenticationContext instance
  vaadin-spring/src/main/java/com/vaadin/flow/spring/security/AuthenticationContext.java
Labels: +0.0.1

#21478 feat: create transfer util
  flow-server/src/main/java/com/vaadin/flow/server/streams/AbstractFileUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ClassDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/FileDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InputStreamDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/ServletResourceDownloadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressListener.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/streams/AbstractDownloadHandlerTest.java
Labels: +1.0.0

#21470 doc: Add note about need to use setKey in Grid for getting sortOrders in Query object
  flow-data/src/main/java/com/vaadin/flow/data/provider/Query.java
Labels: +1.0.0

#21468 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.8

#21512 fix: set download attribute for Anchor DownloadHandlers
  flow-html-components/src/main/java/com/vaadin/flow/component/html/Anchor.java
  flow-html-components/src/test/java/com/vaadin/flow/component/html/AnchorTest.java
Labels: +1.0.0, target/24.8

#21490 feat: initialize signals environment
  flow-server/pom.xml
  flow-server/src/main/java/com/vaadin/experimental/DisabledFeatureException.java
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/test/java/com/vaadin/flow/hotswap/HotswapperTest.java
  flow-server/src/test/java/com/vaadin/flow/server/MockVaadinServletService.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceSignalsInitializationTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/VaadinServletServiceTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/PushHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
  flow-test-generic/src/main/java/com/vaadin/flow/testutil/ClassesSerializableTest.java
  signals/src/main/java/com/vaadin/signals/SignalEnvironment.java
Labels: +1.0.0, target/24.8

#21501 chore: Spring Boot 3.5.0
  pom.xml
Labels: +0.0.1, target/24.8

#21520 chore: Node 24.1.0
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
Labels: +1.0.0

#21522 fix: do not generate list for empty string
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/startup/DevModeInitializer.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTest.java
Labels: +1.0.0, target/24.6, target/24.7, target/24.8

#21521 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.7, target/24.8

#21525 chore: add missing webpack cli flag (2.12)
  flow-server/src/main/java/com/vaadin/flow/server/DevModeHandler.java
Labels: +0.0.1

#21539 chore: Clean up streams
  flow-server/src/main/java/com/vaadin/flow/server/streams/DownloadEvent.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/InMemoryUploadHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/TransferProgressAwareHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/streams/UploadEvent.java
Labels: +0.0.1, target/24.8

#21545 chore: prevent sync id to be updated on queued messages
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
Labels: +0.0.1, target/24.7, target/24.8

#21549 chore: TestBench 9.4.0.beta1
  pom.xml
Labels: +0.0.1, target/24.8

#21402 feat: add subscription mechanism to receive all processed events
  signals/src/main/java/com/vaadin/signals/Signal.java
  signals/src/main/java/com/vaadin/signals/SignalUtils.java
  signals/src/main/java/com/vaadin/signals/impl/AsynchronousSignalTree.java
  signals/src/main/java/com/vaadin/signals/impl/SignalTree.java
  signals/src/main/java/com/vaadin/signals/impl/SynchronousSignalTree.java
  signals/src/test/java/com/vaadin/signals/SignalUtilsTest.java
  signals/src/test/java/com/vaadin/signals/impl/AsynchronousSignalTreeTest.java
  signals/src/test/java/com/vaadin/signals/impl/SynchronousSignalTreeTest.java
Labels: +1.0.0, target/24.8

#21565 fix: Make Vite messages from browser to server work
  flow-tests/test-dev-mode/src/main/frontend/vite-communication.ts
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/ViteCommunicationView.java
  flow-tests/test-dev-mode/src/test/java/com/vaadin/flow/uitest/ui/ViteCommunicationIT.java
  flow-tests/test-dev-mode/vite.config.ts
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnection.java
Labels: +0.0.1, target/24.8

#21568 fix(flow-server): write i18n.json only in production build mode
  flow-server/src/main/resources/vite.generated.ts
Labels: +0.0.1

#21559 chore: downgrade byte-buddy to 1.12.23 (23.6)
  pom.xml
Labels: +0.0.1

#21556 chore(i18n): remove references to Hilla I18n Feature Flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: hilla, +1.0.0, target/24.8
