Repository vaadin/flow, pull requests merged in 2025-03, with the labels that each got.

#21065 chore: remove elemental dep from maven plugin
  flow-plugins/flow-maven-plugin/pom.xml
Labels: +0.0.1

#21069 chore: TypeScript 5.8
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
Labels: +0.0.1

#21062 feat: plugins to use jackson
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscMultiModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/MiscSingleModuleTest.kt
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/TestUtils.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/BuildFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/CleanFrontendMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojoTest.java
  flow-plugins/flow-maven-plugin/src/test/java/com/vaadin/flow/plugin/maven/PrepareFrontendMojoTest.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/CleanFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
Labels: +0.0.1

#21053 feat: Change internal json handling to jackson
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/InlineTargets.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandlerViteTest.java
Labels: +1.0.0

#21059 feat: use jackson for setting up configuration
  flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/AbstractConfigurationFactory.java
  flow-server/src/main/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactory.java
  flow-server/src/test/java/com/vaadin/flow/server/DeploymentConfigurationFactoryTest.java
  flow-server/src/test/java/com/vaadin/flow/server/startup/DefaultApplicationConfigurationFactoryTest.java
Labels: +1.0.0

#21075 chore: bump frontend dependency (24.5)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
Labels: +0.0.1

#21067 feat: add ignore version check to plugin params
  flow-plugins/flow-dev-bundle-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildDevBundleMojo.java
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/GradlePluginAdapter.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/PrepareFrontendInputProperties.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/FlowModeAbstractMojo.java
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/GenerateNpmBOMMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/ConvertPolymerCommand.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/PluginAdapterBase.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendToolsSettings.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunDevBundleBuild.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java
Labels: +0.0.1

#21066 fix: compute client-side feature flag values at runtime
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
Labels: +0.0.1, target/24.7

#21081 fix: compute client-side feature flag values at runtime (#21066) (CP: 24.7)
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlags.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrap.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/WebComponentProviderTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateFeatureFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateWebComponentBootstrapTest.java
Labels: +0.0.1, cherry pick

#21056 feat: Jackson used in dev-server
  flow-server/src/main/java/com/vaadin/flow/hotswap/Hotswapper.java
  flow-server/src/main/java/com/vaadin/flow/internal/BrowserLiveReload.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/DevToolsPlugin.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsInterface.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DevToolsMessageHandler.java
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/stats/DevModeUsageStatistics.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionTest.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/startup/DevModeInitializerTestBase.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/stats/DevModeUsageStatisticsTest.java
Labels: +1.0.0

#21030 chore: Update example feature flag description
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
  flow-server/src/test/java/com/vaadin/experimental/FeatureFlagsTest.java
Labels: +0.0.1

#21064 feat: Internals to jackson
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponent.java
  flow-server/src/main/java/com/vaadin/flow/i18n/TranslationFileRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/internal/UsageStatisticsExporter.java
  flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementAttributeMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/springcsrf/SpringCsrfTokenUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/CvdlProducts.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/JacksonUtilsTest.java
Labels: +1.0.0

#21079 test: prevent Atmosphere IllegalStateException in Spring Tests
  vaadin-spring/src/test/java/com/vaadin/flow/spring/instantiator/SpringInstantiatorTest.java
Labels: +0.0.1

#21084 chore: Preserve method signature to avoid compile errors
  flow-react/src/main/resources/META-INF/resources/frontend/ReactRouterOutletElement.tsx
Labels: +0.0.1, target/24.7

#21078 test: attempt to make Vite websocket tests more reliable
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1, target/24.7

#21083 fix: fix equality check in NavigationAccessControl
  flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java
  flow-server/src/test/java/com/vaadin/flow/server/auth/NavigationAccessControlTest.java
Labels: +0.0.1, target/24.5, target/24.6, target/24.7

#21093 test: increase timeouts for ViteWebsocketConnection tests
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/viteproxy/ViteWebsocketConnectionTest.java
Labels: +0.0.1

#21103 fix: prevent duplicated messages in client queue
  flow-client/src/main/java/com/vaadin/client/communication/MessageSender.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/AbstractBrowserConsoleTest.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/ChromeBrowserTestWithProxy.java
  flow-test-util/src/main/java/com/vaadin/flow/testutil/net/SimpleProxy.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/faulttolerance/BeforeOutputStreamActionFilter.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/faulttolerance/NetworkInterruptionView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/faulttolerance/NetworkInterruptionIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/PushChromeBrowserTestWithProxy.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/ReconnectTest.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/push/SendMultibyteCharactersTest.java
Labels: +0.0.1, target/24.7

#21080 fix: constant pool to jackson
  flow-polymer-template/src/test/java/com/vaadin/flow/templatemodel/TemplateModelTest.java
  flow-server/src/main/java/com/vaadin/flow/internal/ConstantPool.java
  flow-server/src/main/java/com/vaadin/flow/internal/ConstantPoolKey.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/main/java/com/vaadin/flow/internal/change/NodeChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/PolymerEventListenerMap.java
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/AtmospherePushConnection.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/MetadataWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-server/src/test/java/com/vaadin/flow/component/DomEventTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/ConstantPoolTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/change/ListChangeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/change/MapPutChangeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/change/MapRemoveChangeTest.java
  flow-server/src/test/java/com/vaadin/flow/internal/nodefeature/PolymerServerEventHandlersTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/MetadataWriterTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlRequestHandlerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/UidlWriterTest.java
Labels: +1.0.0

#21109 fix: use add if not replacing
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java
Labels: +0.0.1

#21100 feat: Router parts to jackson
  flow-server/src/main/java/com/vaadin/flow/component/EventData.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/ErrorNavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/NavigationEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +0.1.0

#21107 feat: use single scanner for plugin class scan
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/plugin/base/BuildFrontendUtil.java
  flow-plugins/flow-plugin-base/src/test/java/com/vaadin/flow/plugin/base/BuildFrontendUtilTest.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/Options.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesScanner.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/ComponentFlagsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithByteCodeScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdateImportsWithFullCPScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithByteCodeScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdatePackagesWithFullCPCodeScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithByteCodeScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateImportsWithFullCPScannerTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/UpdateThemedImportsTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/FrontendScannerPwaTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerDependenciesTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/scanner/ScannerThemeTest.java
Labels: +0.1.0

#21101 feat: WebComponent more Jackson
  flow-server/src/main/java/com/vaadin/flow/component/WebComponentExporter.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentConfiguration.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentBinding.java
  flow-server/src/main/java/com/vaadin/flow/server/webcomponent/WebComponentGenerator.java
  flow-server/src/test/java/com/vaadin/flow/component/webcomponent/WebComponentTest.java
  flow-server/src/test/java/com/vaadin/flow/server/webcomponent/WebComponentBindingTest.java
Labels: +0.1.0

#21108 feat: add defaultAutoResponsiveFormLayout feature flag
  flow-server/src/main/java/com/vaadin/experimental/FeatureFlags.java
Labels: +0.1.0

#21099 fix: watch active project resources
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/ExternalDependencyWatcher.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
Labels: +0.0.1, target/24.5, target/24.6, target/24.7

#21025 fix: set page height to 100% instead of 100vh
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/index.html
Labels: +0.0.1, target/24.7

#21124 fix: ensure exported WebComponent adds absolute links to document.css
  flow-server/src/main/java/com/vaadin/flow/server/BootstrapHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentBootstrapHandler.java
  flow-tests/test-express-build/test-embedding-express-build/src/main/frontend/themes/embedded-theme/theme.json
  flow-tests/test-express-build/test-embedding-express-build/src/main/frontend/themes/parent-theme/styles.css
  flow-tests/test-express-build/test-embedding-express-build/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
Labels: +0.0.1, target/24.5, target/24.6, target/24.7

#21013 feat: Add trees and transactions to signals module
  signals/src/main/java/com/vaadin/signals/impl/AsynchronousSignalTree.java
  signals/src/main/java/com/vaadin/signals/impl/CommandsAndHandlers.java
  signals/src/main/java/com/vaadin/signals/impl/SignalTree.java
  signals/src/main/java/com/vaadin/signals/impl/StagedTransaction.java
  signals/src/main/java/com/vaadin/signals/impl/SynchronousSignalTree.java
  signals/src/main/java/com/vaadin/signals/impl/Transaction.java
  signals/src/main/java/com/vaadin/signals/operations/SignalOperation.java
  signals/src/main/java/com/vaadin/signals/operations/TransactionOperation.java
  signals/src/test/java/com/vaadin/signals/TestUtil.java
  signals/src/test/java/com/vaadin/signals/impl/AsynchronousSignalTreeTest.java
  signals/src/test/java/com/vaadin/signals/impl/CommandsAndHandlersTest.java
  signals/src/test/java/com/vaadin/signals/impl/StagedTransactionTest.java
  signals/src/test/java/com/vaadin/signals/impl/SynchronousSignalTreeTest.java
  signals/src/test/java/com/vaadin/signals/impl/TransactionTest.java
Labels: +0.0.1

#21126 chore: add 24.7 to GHA branches
  .github/workflows/validation.yml
Labels: +0.0.1

#21119 fix: add allowInert support for synchronized properties
  flow-html-components/src/main/java/com/vaadin/flow/component/html/NativeDetails.java
  flow-server/src/main/java/com/vaadin/flow/component/Component.java
  flow-server/src/main/java/com/vaadin/flow/component/Synchronize.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/ComponentMetaData.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/ElementListenerMap.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/MapSyncRpcHandler.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/AllowInertSynchronizedPropertyView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AllowInertSynchronizedPropertyIT.java
Labels: +0.1.0, target/24.5, target/24.6, target/24.7

#21133 test: refactor FileWatcherTest to clean up resources
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/FileWatcherTest.java
Labels: target/24.7

#21111 feat: ReactAdapter and element to support jackson
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactAdapterComponent.java
  flow-react/src/main/java/com/vaadin/flow/component/react/ReactRouterOutlet.java
  flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEventBus.java
  flow-server/src/main/java/com/vaadin/flow/component/ScrollOptions.java
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/webcomponent/WebComponentUI.java
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/main/java/com/vaadin/flow/internal/JacksonUtils.java
  flow-server/src/main/java/com/vaadin/flow/internal/JavaScriptSemantics.java
  flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
  flow-server/src/main/java/com/vaadin/flow/internal/nodefeature/AbstractPropertyMap.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/DefaultRpcDecoder.java
  flow-server/src/test/java/com/vaadin/flow/component/AbstractSinglePropertyFieldTest.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementJacksonTest.java
  flow-server/src/test/java/com/vaadin/flow/server/communication/rpc/PublishedServerEventHandlerRpcHandlerTest.java
Labels: +1.0.0

#21136 chore: fix 404 link in readme
  README.md
Labels: +0.0.1

#21145 chore: update component version to 24.6.7 (#21140)
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
  flow-tests/vaadin-spring-tests/pom.xml
Labels: +0.0.1, cherry pick

#20990 fix: add global click handler for navigation
  flow-plugins/flow-maven-plugin/src/it/flow-addon/src/main/fake-resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/Flow.tsx
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/vaadin-react.tsx
Labels: +0.0.1

#21116 chore: Explicitly set resources encoding in Maven resources plugin
  pom.xml
Labels: +0.0.1, Contribution

#21155 fix: Clean file-routes if hilla not in use
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
Labels: +1.0.0, target/24.7

#21161 fix: Clean file-routes if hilla not in use (#21155)
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinBuildFrontendTask.kt
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/BuildFrontendMojo.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeTasks.java
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCleanFrontendFilesTest.java
Labels: +1.0.0, cherry pick

#21175 fix: Renavigation to same url (#21170)
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +0.0.1, cherry pick

#21176 fix: Renavigation to same url (#21170)
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
  flow-server/src/main/java/com/vaadin/flow/router/BeforeLeaveEvent.java
  flow-server/src/main/java/com/vaadin/flow/router/Router.java
  flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java
  flow-server/src/test/java/com/vaadin/flow/router/internal/NavigationStateRendererTest.java
Labels: +0.0.1, cherry pick

#21177 chore: Vite 6.2.3
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1, target/24.7

#21174 fix: prevent hot-reload failure caused by prepare-frontend task
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
Labels: +0.0.1, target/24.6, target/24.7

#21190 chore: Deprecate Fragment
  flow-plugins/flow-maven-plugin/src/main/java/com/vaadin/flow/plugin/maven/Fragment.java
Labels: +0.0.1

#21184 fix: prevent hot-reload failure caused by prepare-frontend task (#21174)(CP:24.7)
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
Labels: +0.0.1, cherry pick

#21185 fix: prevent hot-reload failure caused by prepare-frontend task (#21174)(CP:24.6)
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/VaadinSmokeTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/VaadinFlowPluginExtension.kt
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRemoveOldFrontendGeneratedFilesTest.java
Labels: +0.0.1, cherry pick

#21199 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#21193 fix: align npm package order between full and annotation scanners
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java
Labels: +0.0.1, Contribution
