Repository vaadin/flow, pull requests merged in 2025-09, with the labels that each got.

#22048 fix: Fixed high CPU usage due to pending JS commands (#22024) (#22035)(CP:23.6)
  flow-server/src/main/java/com/vaadin/flow/component/internal/UIInternals.java
Labels: +0.0.1, cherry pick

#22135 chore: Update testbench version to 9.5.0-beta1
  pom.xml
Labels: +0.0.1

#22138 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +1.0.0

#22136 refactor: override buildQuery in HierarchicalDataCommunicator
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorBasicTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorFlatHierarchyTest.java
Labels: +0.0.1

#22144 fix: Mapping of ArrayNode
  flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
Labels: +0.0.1

#22147 chore: add flow module to flow-bom
  flow-bom/pom.xml
Labels: +0.0.1

#22156 fix: Skip pre-trial validation when clicking on Log in or Sign up
  vaadin-dev-server/src/main/java/com/vaadin/base/devserver/DebugWindowConnection.java
  vaadin-dev-server/src/test/java/com/vaadin/base/devserver/DebugWindowConnectionLicenseCheckTest.java
Labels: +0.0.1, target/24.9

#22145 Add clarifying comments to async signal confirmation
  signals/src/main/java/com/vaadin/signals/impl/AsynchronousSignalTree.java
Labels: +0.0.1

#22158 chore: Update a link to license page
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/commercial-banner.js
Labels: +0.0.1, target/24.9

#22174 fix: Log available component styles
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImport.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskUpdateThemeImportTest.java
Labels: +0.0.1

#22090 feat!: Drop lumo imports from theme plugin
  flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendDependencies.java
  flow-server/src/main/resources/plugins/application-theme-plugin/package.json
  flow-server/src/main/resources/plugins/application-theme-plugin/theme-generator.js
  flow-server/src/test/java/com/vaadin/flow/server/frontend/BundleValidationTest.java
  flow-tests/test-application-theme/test-theme-reusable-vite/src/main/frontend/ts-component.ts
  flow-tests/test-embedding/test-embedding-application-theme/src/test/java/com/vaadin/flow/webcomponent/ApplicationThemeComponentIT.java
  flow-tests/test-embedding/test-embedding-generic/pom.xml
  flow-tests/test-embedding/test-embedding-production-mode/pom.xml
  flow-tests/test-lumo/src/main/java/com/vaadin/flow/theme/lumo/Lumo.java
  flow-tests/test-misc/pom.xml
  flow-tests/test-resources/src/main/java/com/vaadin/flow/uitest/ui/dependencies/TestVersion.java
Labels: +1.0.0

#22183 chore: Bump frontend dependencies
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#22188 chore: Update Vaadin license-checker version to 2.0.0-rc1
  pom.xml
Labels: +0.0.1, target/24.9

#22187 fix: Fix faulty javadoc for acceptNullValues
  flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java
Labels: +0.0.1, target/24.7, target/24.8, target/24.9

#22081 chore: upgrade springboot to 4.0.0-M2
  pom.xml
  signals/pom.xml
  signals/src/test/java/com/vaadin/signals/IdTest.java
  signals/src/test/java/com/vaadin/signals/SignalCommandTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/AuthenticationContextTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinSecurityConfigurerTest.java
  vaadin-spring/src/test/java/com/vaadin/flow/spring/security/VaadinWebSecurityTest.java
Labels: +0.0.1

#22196 fix: optimize Element API for small datasets
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
Labels: +0.0.1, target/24.7, target/24.8, target/24.9

#22198 fix: preserve './' prefix in import path normalization (#22173)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/AbstractUpdateImportsTest.java
Labels: +0.0.1

#22250 Move map from AbstractSignal to Signal
  signals/src/main/java/com/vaadin/signals/AbstractSignal.java
  signals/src/main/java/com/vaadin/signals/Signal.java
  signals/src/test/java/com/vaadin/signals/impl/ComputedSignalTest.java
Labels: +0.0.1

#22254 fix: Array type should be serializable
  flow-server/src/main/java/com/vaadin/flow/dom/Element.java
  flow-server/src/test/java/com/vaadin/flow/dom/ElementTest.java
Labels: +0.0.1, target/24.7, target/24.8, target/24.9

#22253 Commercial Banner Update: Styles & Accessibility
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/commercial-banner.js
Labels: +0.0.1, target/24.9

#22230 Remove ComponentEffect.format
  flow-server/src/main/java/com/vaadin/flow/component/ComponentEffect.java
  flow-server/src/test/java/com/vaadin/flow/component/ComponentEffectTest.java
Labels: +1.0.0

#22191 fix: Do not run any Maven goals automatically in Eclipse / VS Code
  flow-plugins/flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Labels: +0.0.1

#22265 fix: handle ArrayNode in MapPutChange to fix ReactAdapterComponent.setState() (#22251)
  flow-server/src/main/java/com/vaadin/flow/internal/change/MapPutChange.java
  flow-server/src/test/java/com/vaadin/flow/internal/change/MapPutChangeTest.java
Labels: +0.0.1, target/24.9

#22276 fix: copy all frontend resources from JAR files (#22264) (CP: 23.6)
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFiles.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/FrontendResourcesAreCopiedAfterCleaningTest.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskCopyFrontendFilesTest.java
  flow-server/src/test/resources/jar-with-frontend-resources.jar
  flow-server/src/test/resources/jar-with-modern-frontend.jar
Labels: +0.0.1, cherry pick

#22289 chore: Upgrade default npm packages versions
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#22292 chore: Bump frontend dependencies (24.8)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1

#22295 feat: add ModalityMode enum
  flow-server/src/main/java/com/vaadin/flow/component/ModalityMode.java
Labels: +0.1.0

#22269 chore: Change Enterprise to Team features on splash screens
  vaadin-dev-server/src/main/frontend/pre-trial-splash-screen.ts
Labels: +0.0.1, target/24.9

#22291 chore: Bump frontend dependencies (24.9)
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react19/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
  flow-tests/test-themes/pom-devbundle.xml
Labels: +0.0.1

#22297 Update README.md: remove 24.7
  README.md
Labels: +0.0.1

#22301 refactor: extract vaadin bundles plugin into internal package
  flow-server/src/main/resources/plugins/plugins.json
  flow-server/src/main/resources/plugins/vite-plugin-vaadin-bundles/index.ts
  flow-server/src/main/resources/plugins/vite-plugin-vaadin-bundles/package.json
  flow-server/src/main/resources/vite.generated.ts
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskInstallFrontendBuildPluginsTest.java
Labels: +0.0.1

#22336 test: Clean up data communicator tests
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorBasicTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataGenerationTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataRefreshTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorKeyGenerationTest.java
Labels: +0.0.1

#22321 fix: remove pinned async dev dependency from default package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/default/package.json
  flow-server/src/test/java/com/vaadin/flow/server/frontend/NodeUpdaterTest.java
Labels: +0.0.1, target/24.9

#22339 chore: Delete temporary component
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/component/login/LoginI18n.java
  flow-tests/vaadin-spring-tests/test-spring-helpers/src/main/java/com/vaadin/flow/component/login/LoginOverlay.java
Labels: +0.0.1

#22329 fix: ensure to add feature-flags import at the start of bundle
  flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrap.java
  flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskGenerateBootstrapTest.java
Labels: +0.0.1, target/24.8, target/24.9

#22322 refactor: Iterate only affected sub-caches when collapsing items
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/Cache.java
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
Labels: +0.0.1

#22302 feat: add setChildComponentModal(ModalityMode) to UI
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/test/java/com/vaadin/flow/component/UITest.java
  flow-tests/test-root-context/src/main/java/com/vaadin/flow/uitest/ui/ModalDialogView.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/AllowInertSynchronizedPropertyIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/InertComponentIT.java
  flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/ModalDialogIT.java
Labels: +0.0.1

#22337 test: wait before pressing login button (23.6)
  flow-tests/vaadin-spring-tests/test-spring-security-flow-methodsecurity/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/AbstractIT.java
  flow-tests/vaadin-spring-tests/test-spring-security-flow/src/test/java/com/vaadin/flow/spring/flowsecurity/UIAccessContextIT.java
Labels: +0.0.1

#22328 fix: Clean up client keys only after viewport update is confirmed
  flow-data/src/main/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicator.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/AbstractHierarchicalDataCommunicatorTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorBasicTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorDataGenerationTest.java
  flow-data/src/test/java/com/vaadin/flow/data/provider/hierarchy/HierarchicalDataCommunicatorKeyGenerationTest.java
Labels: +0.0.1

#22342 TASK-1 I18NProvider: add default getDefaultLocale method
  flow-server/src/main/java/com/vaadin/flow/component/UI.java
  flow-server/src/main/java/com/vaadin/flow/i18n/I18NProvider.java
  flow-server/src/main/java/com/vaadin/flow/internal/LocaleUtil.java
  flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java
Labels: +0.1.0, Contribution

#22348 chore: update minimum Gradle version to 8.14
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.jar
  flow-plugins/flow-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
  flow-plugins/flow-gradle-plugin/gradlew
  flow-plugins/flow-gradle-plugin/gradlew.bat
  flow-plugins/flow-gradle-plugin/src/functionalTest/kotlin/com/vaadin/gradle/GradleVersionSupportTest.kt
  flow-plugins/flow-gradle-plugin/src/main/kotlin/com/vaadin/gradle/FlowPlugin.kt
Labels: +1.0.0

#22283 chore: Deprecate WebBrowser and BrowserDetails
  flow-client/src/main/java/com/vaadin/client/BrowserInfo.java
  flow-server/src/main/java/com/vaadin/flow/server/WebBrowser.java
  flow-server/src/main/java/com/vaadin/flow/server/communication/UidlWriter.java
  flow-server/src/main/java/com/vaadin/flow/shared/BrowserDetails.java
  flow-tests/test-dev-mode/src/main/java/com/vaadin/flow/uitest/ui/InfoView.java
Labels: +1.0.0

#22359 chore: bump java versions of commons-lang3 commons-io and byte-buddy in 24.9
  pom.xml
Labels: +0.0.1

#22362 chore: Bump frontend dependencies to latest versions
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/react-router/package.json
  flow-server/src/main/resources/com/vaadin/flow/server/frontend/dependencies/vite/package.json
Labels: +0.0.1

#22370 fix: instead of throwing, warn if legace frontend folder is used
  flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java
  flow-server/src/test/java/com/vaadin/flow/server/DefaultDeploymentConfigurationTest.java
Labels: +0.0.1

#22357 chore!: set Java 21 as baseline
  .github/workflows/validation.yml
  README.md
  eclipse/VaadinJavaConventions.xml
  flow-client/bnd.bnd
  flow-data/bnd.bnd
  flow-dnd/bnd.bnd
  flow-html-components/bnd.bnd
  flow-lit-template/bnd.bnd
  flow-plugins/flow-gradle-plugin/README.md
  flow-plugins/flow-gradle-plugin/build.gradle
  flow-plugins/flow-maven-plugin/src/it/appshellconfiguration-external-annotations/pom.xml
  flow-plugins/flow-maven-plugin/src/it/classfinder-lookup/pom.xml
  flow-plugins/flow-maven-plugin/src/it/commercial-banner-build/pom.xml
  flow-plugins/flow-maven-plugin/src/it/deps-with-classifier-dups-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/flow-addon/pom.xml
  flow-plugins/flow-maven-plugin/src/it/frontend-scanner-tuning-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/ignore-maven-deps-from-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/offending-dependency-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/plugin-pinned-deps-project/pom.xml
  flow-plugins/flow-maven-plugin/src/it/resources-from-project/pom.xml
  flow-plugins/flow-plugin-base/bnd.bnd
  flow-plugins/pom.xml
  flow-polymer-template/bnd.bnd
  flow-push/bnd.bnd
  flow-server/bnd.bnd
  flow-tests/test-express-build/test-flow-maven-plugin/pom.xml
  flow-tests/test-root-context/bnd.bnd
  flow-webpush/bnd.bnd
  pom.xml
  signals/bnd.bnd
Labels: +0.0.1
